== To The Reader.

The following account of one who was beloved in his day for his work`'s sake,
and for the savour of his meek and gentle spirit,
has been compiled chiefly from his manuscript diaries,
and from letters to his intimate friends; though some matter taken from other sources,
and tending to elucidate particular parts of the narrative,
has been occasionally interspersed.
In condensing his manuscripts,
a care has been exercised to avoid any change of
language involving a difference of sentiment;
and the variations found necessary, have been chiefly omissions for the sake of brevity,
or for avoiding those errors of the pen which often occur in hurried writing,
without revision.

John Pemberton left no continued account of his life or religious engagements,
his memorandums relating principally to particular journeys;
and from the length of time which has elapsed
since the period of his youth and active life,
those from whom minute information on these subjects might have been obtained,
have been removed from among us.
This may account for an appearance of abruptness in some parts of the memoir,
particularly with reference to the early part of his life.

The striking features of his character were Christian simplicity,
meekness and diffidence, united with an ardent love for his fellow creatures,
and desire for their present and everlasting welfare.
An abiding sense of the Divine presence seemed to cover his spirit;
and though his Journal may not be so replete as some others,
with incidents calculated to strike the mind by their novelty;
yet the reader may find himself amply repaid for the perusal,
in tracing the footsteps of one much weaned from the spirit and maxims of the world,
anxiously endeavouring to perform his day`'s work in the day time,
and looking for acceptance, not to any merits of his own, but in living faith,
to the mercy of God in Christ Jesus our Lord,
with the heartfelt acknowledgment that he was but an unprofitable servant,
having done no more than was his duty to do.

[.signed-section-signature]
William Hodgson, Jr.
