== Chapter I.

[.chapter-synopsis]
* Early life and first journey in Europe, in company with John Churchman.

In the summer of the year 1682,
about a week after the arrival of William Penn in the province of Pennsylvania,
the ancestors of John Pemberton landed at Choptank, in Maryland.
The party consisted of Ralph Pemberton, of Radcliffe-bridge, Lancashire, England,
an aged man; of his son Phineas, and Phebe, his wife, from Bolton in the moors,
both in the prime of life, with their two small children,
and a considerable number of other Friends.
Pennsylvania was the place of their intended residence,
but the site of Philadelphia was yet a wilderness.
Phineas Pemberton purchased three hundred acres of land some miles up the river Delaware,
not far from the present town of Bristol, and settled there early in the next year.
On this tract he resided about sixteen years,
and then removed a few miles further from the river,
to what was afterwards known by the name of the Pemberton farm.
He died on the first day of the year 1702, aged fifty-two years.
He appears to have been a faithful and useful member of the religious Society of Friends,
both he and his father having been among its early members in the north of England;
and both having gone through repeated sufferings
for the sake of its righteous testimonies,
previous to leaving their native land.

His son Israel, the father of the subject of this memoir,
was born on the 20th of the twelfth month, 1684,
and about the twenty-fifth year of his age married Rachel Read.
He was a useful member of civil and religious society,
and was highly esteemed for his hospitality and upright conduct through life.
Of ten children, only three sons, Israel, James and John, survived him,
who inherited a considerable temporal estate,
and enjoyed what is of far greater importance, the advantage of his pious example,
and of a deep parental solicitude for their education
in the nurture and admonition of the Lord.`"

John, the youngest of the three, was born in Philadelphia,
on the 27th day of the eleventh month, 1727,
and was brought up to the pursuit of commercial business.
Of his younger life very little account has come down to the present day.
He appears to have been a young man of amiable and tender disposition,
and a mind measurably brought under the sanctifying operations of the Spirit of Truth.
His constitution was naturally delicate, which induced him, on coming to man's estate,
to undertake a voyage to Europe.
He had also on this occasion some views of mercantile business, which however,
do not appear to have much engrossed his attention.

In undertaking this journey,
it is evident that his mind was seriously impressed with the dangers
and temptations to which he would be exposed in a foreign land,
far from the salutary restraining influence of parental solicitude.
But at the same time that he was mindful of his own frailty,
he remembered on whom strength is laid, and left home with sincere desires,
that he might be favoured to keep constantly on the watch,
and to look to that never-failing source of wisdom and safety,
which is the only sure dependence, either in youth or old age.
These desires did not forsake him after the dangers of the deep were passed.
In a letter to his brother Israel, written while in London, he says,
"`I have hitherto avoided such company that I thought could be of no advantage to me,
and hope my conduct may be such while from home,
that I may not merit less the esteem of my friends than when I left you.
Wickedness does greatly abound, and temptations of various kinds present;
yet there is a Hand, that if rightly applied to, will give strength to overcome them.`"

It was his privilege to have for companions on the voyage,
that experienced minister of the gospel, John Churchman, and his brother-in-law,
William Brown,
who were crossing the ocean on a religious visit to Friends of Great Britain, Ireland,
and part of the European continent.
They sailed from Chester on the 4th of fourth month, 1750, and landed at Dover,
in England, on the 6th of the fifth month, after a good passage; during which,
John Churchman says, they were careful to keep meetings in the cabin twice a week;
in which they "`felt the presence of the great Lord and Master, and therein were comforted.`"

John Pemberton, on their arrival in England,
found an engagement of mind to accompany his friend John Churchman,
during a part of his journey.
The latter says, "`John Pemberton concluded to go with me a few days,
and his company was kindly accepted by me, he being a sober, well inclined young man.`"

"`With reference to this undertaking,`" he says in a
letter written about that time to his parents;
"`I could not be easy to leave our friend John Churchman, as he was very low in his mind,
and had no companion to travel with him; and being desirous of my company,
I have concluded to stay a while longer with him.`"

From other letters written to his parents soon after his arrival in London,
it appears that his mind was even then undergoing that
process of gradual change and purification,
which was preparatory to his being made use of as an
instrument of good to others and to the church.
He says that he felt the Divine hand nearer to him since he left them,
than at any previous period of his life; "`for which,`" he adds,
"`I am bound to render thanksgiving to the Author of all good, who is worthy.`"

As he continued with John Churchman, he became more and more bound to the service.
Writing to his brother Israel, from Bristol, on the 30th of seventh month, 1750,
after some expressions of sympathy with John Churchman,
under the exercises which attended him, he remarks:

"`How much longer I shall stay with our said Friend, I do not at present know;
but have no satisfaction when I think of leaving him,
though I cannot account for the reason.`"

In another letter, dated London, eleventh month 12th, addressed to his parents, he says,
"`Your affectionate advice and counsel was edifying, as well as very necessary;
and I hope ever to have a just regard to that principle of light and grace,
which alone is able to direct us aright.
Though poverty and weakness have chiefly been my portion,
yet I have been at times favoured with the income and influences of Divine love,
which has filled my heart and raised my hope and faith, when almost ready to fail;
that I have secretly been made to praise the worthy name of the Lord.
You will find that I had been some weeks with our dear friend John Churchman,
whom I accompanied into Cornwall, not being at liberty with ease of mind, to leave him,
being held, though I could not tell for what or why.
We visited pretty thoroughly, Wiltshire, Somersetshire, Devonshire and Cornwall;
and though it was a poor low time with us, yet I have no cause to repent,
but hope that I have reaped some benefit, both in my health and otherwise; and might,
I believe, have received more, had I been as faithful as I know I ought to have been.
The meetings in these counties are in general small, and lukewarmness is prevalent;
yet in many places there is a hopeful seed springing among the younger sort.
My companion's service was altogether with those who make profession with us,
choosing meetings as free from mixture as possible, and in general he has had them so.
His service has been close, having had chiefly to speak to the states of the people;
and he has been favoured with a clear understanding in every meeting.`"

It will be observed, that in this letter he speaks of their having been into Cornwall.
It was at a meeting held at Penzance, in that county,
that he was first strengthened to open his mouth in public testimony,
as a minister of the gospel.
His natural diffidence,
and the humility of a mind imbued with a sense of its own weakness and unworthiness,
prevented him from mentioning this circumstance in his
confidential letters to his parents at that time;
but his companion, John Churchman, notices it in the following terms: "`At this meeting,
my companion, John Pemberton, spoke a few words in way of testimony, tender and broken,
being the first time;
and I thought it had a good degree of the savour of truth attending.`"

Having thus put his hand to the plough,
in childlike obedience to the requisitions of his Divine Master,
it does not appear that he was frequent in his early public testimonies;
and his mind was often bowed under a deep feeling of unworthiness,
and not infrequently of short coming and unfaithfulness to the manifestations of duty.
It is interesting to trace a little the feelings which accompanied him about this period,
as we may gather them from scattered portions of his letters.
It will serve also, in some degree, to show the course of their travels,
and the exercises for the body's sake, which they had to pass through.

In a letter to his parents, dated Yarmouth, first month 2nd, 1751, he says;
"`I still continue with our dear Friend, John Churchman, not having liberty to leave him;
though I am such a poor creature that I often
think I add to the weight of his sufferings,
of which he has had a large share, having waded through deep baptisms and sore conflicts,
on account of the great declension and lukewarmness of the professors of truth,
who have a name to live, and yet are dead.
This sad disorder is prevalent among many in most places;
yet there is preserved a little remnant in nearly all the meetings,
with whom he has to sympathize.`"

In a subsequent letter, dated London, third month 27th, he remarks;
"`Though I love the truth, and the enjoyment of my Master's presence,
yet I have not given up to be so fully resigned to his will,
as I am sensible I ought to be; for which he has, in his mercy,
been pleased to chastise me many ways;
and for several weeks has withdrawn the light of his countenance,
so that I have had to pass through a barren wilderness;
yet I am sensible that He who is all-powerful,
is able to make even the barren wilderness a fruitful field.
My transgressions have been so many,
and the strivings and visitations of the Lord's Spirit so frequent,
and he has so long waited to be gracious to my soul,
that I at times fear my day is almost, if not quite, over;
and that I am unworthy any more to be favoured.
Indeed, such gross darkness and stupidity seem to surround me,
that I scarcely dare to look up, or cry out for mercy.
But, my dear parents, I have, in much reverence and humility just to say,
that for a few days past,
I have had a faint hope and belief that the Lord will visit again;
and if it should please him, in his infinite love and mercy, thus to do, I hope,
through his power, to be more faithful.
And I hope that you, my dear parents, in your near accesses to him in prayer,
will not be unmindful of me.`"

They now travelled into the north of England and some parts of Scotland.
At Bridlington, in Yorkshire, he wrote a letter to his parents, dated fifth month 23rd,
1751, from which the following extract is taken, containing the first information,
from himself, of his being engaged in the ministry.

"`I have ever been sensible, since I knew anything almost,
that we were not created barely to serve ourselves;
and have many times been desirous that I might not be an unthankful receiver of the
many favours and blessings which Providence has been pleased to bestow on us.
Yet, since I came into England, I have flinched like a cowardly soldier,
and not stood my ground;
but by hearkening to the insinuations and discouragements of the enemy,
I have been hindered in my progress, been led into confusion,
and into such a vast wilderness, that I am at times fearful I shall fall therein.
The dragon and wild beasts seem to surround, and such darkness to overspread me,
that it appears almost impossible I should ever see and enjoy the promised land.
Yet I have in humility to acknowledge, that the Lord, in the riches of his love,
has been pleased sometimes, in the deepest distress, to afford manna to my poor soul,
by which I have been somewhat refreshed.
And I much desire to be preserved in patience,
until it shall please the Lord to redeem me therefrom; for I believe it has been,
and still is, necessary I should undergo suffering,
that my will may be brought into true resignation and holy subjection to the Divine will.
For we must undergo much, to become truly fools.

"`I find you have heard,
that it has pleased the Lord to cause my mouth to be opened a few times in the ministry;
being obliged to do so after having undergone some days' severe discipline,
in order to get a little ease.
But I transgressed so often,
that He permitted the enemy to lead me into the state I am now in;
and I have not said anything for several months.

"`My dear companion has been very affectionate and kind to me,
and has not been lacking in wholesome advice and counsel,
and has frequently given me encouragement;
otherwise I believe I should have sunk long since.`"

A letter to his brother Israel, dated from Kendal, tenth month 7th,
develops the state of his mind under these exercises still more distinctly.
The following is an extract:

"`It is with much gratitude, not only to you, my dear brother,
but to our great and kind Master,
that I have to acknowledge the receipt of your
several affectionate and sympathizing epistles,
which all came to hand in due course, and afford me much consolation;
being sensible the counsel given me, sprang not out of the earth,
but that you were directed therein by our gracious Benefactor;
to whom I desire to be kept faithful, in humble thankfulness,
not only for the encouragement he is pleased to
favour me with from my near and dear friends,
hut also for his immediate support, and tender dealings with me.
For I can in truth say.
He has not been lacking to give me peace and joy,
when I have been faithful in discharging what he has required;
although to the natural man it might appear trifling and mean.
But alas!
I have frequently forfeited this repose and near union with my Master,
by allowing reasoning to take place;
while the grand adversary of our happiness is always on his watch,
to insinuate some plausible excuse to deter us from our duty.
This has been my weakness, for which I have had to suffer deeply;
being often put into the furnace to be further refined and hardened.
Yet I fear I shall never turn out an edge that will stand, fit for use and service.
For whenever I neglect my duty by allowing reasonings to overpower,
the enemy well knows my weak side,
and fails not to affright me with terrible apprehensions,
and so to sink me as into the pit, where nothing but darkness and horror appear.
And for my disobedience the Lord is pleased to withdraw his presence,
and I am left to be tossed as a ship on the ocean.
Yet when I have been most deeply beset, he has been pleased to interpose,
and shut the jaws of the devourer,
and revive a little hope that I am not quite given over.
Then the twilight has again appeared, and the sun in some measure also;
at which my soul has had to rejoice,
and in thankfulness to praise the name of my Redeemer,
who deals tenderly with us poor creatures.
I wish I could say that these sufferings had taught me wisdom;
for alas! it has not been only once or twice, that I have thus failed, but very often;
and I remain frequently in this low spot, sometimes for weeks, yes months.
My very dear companion has carried himself exceeding affectionately towards me,
and is very capable of giving advice and counsel; which he fails not to do.`"

After travelling for several months in Scotland and the north of England,
they took passage at Whitehaven and crossed the channel to Dublin.
The next day they attended the meeting in Sycamore-alley;
respecting which John Pemberton makes the following remark:
"`There appeared too much curiosity in some, to know who and what we were;
of which my dear companion was sensible,
and directed them how they might best know such who are sent amongst them; which was,
by getting to the root of Divine life, the true touch-stone, which can savour spirits;
and in that state, the children of one Father are known to each other.`"

While they remained in Dublin,
his mind was afresh brought into discouragement on his own account;
and he had also to partake of renewed baptism as for the dead,
under a sense of the state of the church.
He says he was brought into "`a very low spot;`" but in due time he was
favoured with a consoling evidence of the continued favour of the Almighty,
as appears from the following extract from his journal, dated 17th of sixth month:
"`I had some consolation by the presence of Him, whom I often grieve,
and through weakness deprive myself of the favour of his blessed presence,
and the smiles of his countenance.
For this holy visitation my spirit was much tendered in thankfulness,
and I renewed covenant with my blessed Redeemer.`"

In a letter to his brother James, of the same date, he remarks;

"`Let such whose eyes the Lord in mercy has been pleased to open,
to see in some measure his beauty, and the great comeliness of his blessed truth,
dwell in humility and in a sense of his favours,
that so they may be a furtherance and not a hindrance,
to the reformation and great work which he is determined to bring to pass.
I continue a weakling,
yet at times am in degree enabled to breathe for the preservation of myself and friends.
There is much lack of qualified members to act in the discipline of the church,
which God in his power and wisdom, concerned our worthy forefathers to set up;
and which we know has been as a hedge to enclose and preserve our Society,
where it has been strictly kept up,
while a manifest declension appears where it is neglected.
It is with sorrow of soul I sometimes view our Society in some places,
where they have not kept a strict watch in this respect;
and in others where they make a show of something of the kind,
yet act in the affairs of the church with the carnal will and reasonings of man,
not being willing to bow in mind, so that they might receive a qualification from Him,
who only can influence rightly to act for his glory.
Many of this kind usurp authority and rule in the church,
to the burden and grief of the true hearted.

"`As we have been here but a short time, I have seen little about me,
having kept house mostly since we landed;
for it sinks my spirit to walk along the streets,
to hear and behold the profanity of the inhabitants.`"

In his journal, under date of first-day, sixth month 21st, is the following:
"`Many of the professors of truth in this day, attend meetings for form,
and because it is looked upon as disreputable to forsake going to places of worship;
many content themselves with going once a week,
and by reason of these our meetings are covered with heaviness, dryness and gloom,
and the faithful few are bowed under a weight of exercise and sorrow.`"

From Dublin they passed northward, having meetings at Dundalk, Newry, Moyallen, Lurgan,
Lisburn, Belfast, etc.
At Ballinderry, on the 5th of seventh month, John Pemberton remarks,
that a spirit of drowsiness had come over many of those present at the meeting,
who were closely spoken to, but to very little purpose.
He adds, "`My companion had a very searching time,
in which he opened the state of the church,
showing the cause why such degeneracy appeared;
and had to speak very closely to some who pretended to
be of the foremost rank and at the head of affairs,
but were corrupt in practice and unsound members; and even ministers,
who had begun in the spirit,
being called and qualified of God for this honourable station; yet,
not keeping to the root of life in themselves, their ministry was become dead,
though they retained a form of words,
and could reason and speak of things they had learned in the beginning.
By joining with the world and the spirit thereof, they had eclipsed the light,
and their spirits were not so seasoned with good as in times past.
Such, whether elders or ministers,
were desired to look back and consider from what they had fallen,
and humble themselves before the Lord, that they might be again quickened.

It is hard to persuade some to believe the truth of themselves, and to see where they are.
But we had to rejoice, in that there was a number there, both young and old,
whose spirits were seasoned with the truth, and whose dwelling was low.
Consolation was administered to such, and prayers were put up,
that their faith might not fail; as Christ said to Peter,
when satan desired to have him and the rest of the disciples,
that he might sift them as wheat; which is the case with the faithful now.
They are tried and proved,
and often meet with buffetings and slights from such who call themselves brethren,
and are at the helm of affairs,
and act therein by the wisdom and carnal apprehension of man;
under whose government the church will never thrive,
nor the affairs thereof be conducted aright.
It was declared that the days would come, when such should be laid aside, or taken away,
and those raised up who would depend on the Lord for wisdom and counsel,
and live uprightly: then would the church flourish and the truth shine.`"

Passing from there, they travelled to Antrim, Ballinacre, Grange and Coleraine,
and afterwards towards Toberhead; near which place they held a meeting,
as they had done at the other places of their tarriance.
"`Here,`" says John Pemberton, "`My companion was greatly opened and enlarged,
and towards the conclusion, had to prophecy of a day which was approaching,
that would try the foundations of all;
and woe would be unto such who were not on the right foundation.
It was told them that religion would not flourish, it was to be feared,
until a trying time came upon this nation,
which would purge the earth from the gross professors of Christianity,
as well priests and ministers, as hearers, who live in gluttony, pride and other evils,
and thereby have corrupted their ways.`"

After this they visited Dungannon, Charlemont, and other places in the county Tyrone;
where they found the meetings of Friends in a very declining condition,
from the predominance of a worldly spirit,
by which the faithful were sorely burdened and discouraged.
Close labour was administered to those;
and a little strength and encouragement extended to the oppressed suffering remnant.

From Dungannon, John Pemberton wrote to his parents to the following effect:
"`We have travelled hard all last week,
meetings lying at a pretty great distance from each other,
and had one every day except yesterday.
The travail of the faithful in our Society at this day, is with pain and sorrow.
How long the Lord in mercy may lengthen out the day of visitation,
and forbear to shake his rod over the land, is not for mortals to determine;
but wickedness, pride, folly and vanity greatly abound; for which the land mourns.
Oh, that such whom the Lord has in some measure favoured with his love,
and who have tasted of the good word of life and the powers of the world to come,
may stand faithful and upright, under the direction of their holy Captain;
that they may be found clear in the day of trial.
I much desire to be of the number of these; but infirmities so surround,
and faith is so weak, that I am fearful at times, I shall fall a victim to the enemy,
who is powerful in his attacks.
Yet I am sensible the Lord's power is above his power,
and that he will enable such who stand faithful to his command,
to resist the adversary.`"

In a letter written at Lurgan, a week afterwards,
he speaks thus of the desolations of the church in those parts:
"`It is lamentable to behold how many there are who appeared as bright lights,
and might have continued ornaments in our Zion, who,
by letting their minds out by degrees after the perishing treasure of this world,
have eclipsed the light in themselves; and from this, other evils ensuing,
some have of late become a reproach to the profession.
Yet I believe there are a few preserved,
who I pray may still be kept from the unrighteous leaven.`"

At Ballyhagan he makes the following memorandum:
"`First-day being esteemed by some an idle day,
the house was much crowded with Friends and others.
Much time was spent in silence;
after which my companion appeared in the demonstration and power of the gospel,
beginning with the words spoken by the Lord through the mouth of a servant:
'`Oh! that my people were wise, that they understood this;
that they would consider their latter end!`' Many were
tendered through the power that accompanied his service,
and God was glorified, who over and above all,
is worthy of dominion and praise now and forever.
The meeting concluded well, and Friends proceeded to the business;
in which my companion had a short but very close testimony,
inviting them to bestir themselves, to revive and put in practice the discipline,
that had been much neglected; first, by applying to the great Physician,
to have themselves thoroughly cleansed from the dregs of self and the world;
that so a holy zeal may again be raised,
and they prepared to receive counsel and qualification to act to the honour of God,
not in their own wills, nor to be seen of men, but in humility and reverence,
for the welfare of Zion and the glory of God.
It was told them, that the Lord seemed still to hover over them,
and was willing again to revisit and quicken into a holy sense and life,
if they would embrace and seek him in sincerity of heart.
But if not, they would be set aside,
and a purer and more noble people would be raised in that province,
who would seek His honour, more than the grandeur and praise of the world.`"

Taking, after this, a southerly course, they travelled through the county of Westmeath,
having many meetings, until they reached Moat,
where John Churchman was detained nearly three weeks by illness.
John Pemberton thus mentions it in a letter to his parents:
"`We have been detained here above two weeks by my dear companion's indisposition.
He has been brought very low, to appearance almost to the grave.
Yet, through the mercy and providence of God, he is again raised, and has,
for a few days past, recovered to admiration;
for which mercy and favour let God be glorified and praised; unto whom,
and unto his dear Son, honour and glory are due, both now and forever.`"

They now resumed their journey;
but John Pemberton appears to have been again
tried with a sense of poverty and desertion.
He was, as it were, in his infancy as a minister of the gospel,
and had many baptisms to pass through on his own account, under a sense of his inability,
in his own strength, to advance the kingdom of the Redeemer.
Many close provings were his portion, and discouraging fears,
lest any misstep of so inexperienced a servant
might mar the work to which he had put his hand.

It is also apparent that the state of the churches,
and various circumstances of the people among whom their lot was cast,
rested constantly upon his mind with oppressive weight,
and increased the burden of trial and exercise.
In his memorandums and letters,
he speaks of the low state to which about this time he was reduced,
notwithstanding the fatherly care exercised and comfort attempted to be administered,
by his experienced companion.
These baptisms,
which more or less must attend all true ministers of the glorious gospel of Christ,
may be considered as an evidence that he was not
going about this weighty work in his own will,
but under the constraining power of divine love
and the holy anointing of the Spirit of Truth.

In a letter to his parents dated at Moat, eighth month 15th, 1752, he says:
"`I desire to be thankful for the many mercies
and favours the Lord is pleased to grant us;
and this,
I am satisfied cannot be done but through obedience to
his manifestations and a careful observance of his law.
Oh! that this then may be the practice of all who profess his blessed name.
Then would greenness appear on our branches,
and lively and acceptable fruits would be produced,
to the glory of God and the edification and comfort of ourselves and one another.
My mind, though in weakness and much poverty,
is at times engaged that this may be my concern and care.
But through fears, and sometimes self, that great enemy to our advancement in godliness,
getting possession, I reason away, what I fear, yes, by what I feel afterwards,
I am sure is my duty.
And were it not that we have a most merciful God,
who is indeed long suffering and full of compassion,
my soul had been as the plains of Sodom, and as desolate as the streets of Gomorrah.
But blessed, and in reverence, ever praised be his holy name,
I yet witness at times his mercy extended, that would restore.
Oh, that I may be favoured with faith to believe and trust in his power!
For he alone can create true faith,
and give ability and holy resolution to occupy faithfully the gifts entrusted to us.`"

They had now got as far south as the county Tipperary,
where they attended meetings at Cashell, Clonmel, and some other places;
and then proceeded into the county of Cork,
having close labour at several meetings in the city of Cork, and visiting Youghall,
Bandon, Mallow and Charleville.
From there they went to Limerick and attended the quarterly,
or province meeting for Munster.

Under date of first-day, ninth month 24th, John Pemberton says:
"`I was concerned in the fore part of the meeting to supplicate the Almighty,
in a few words, that he would be pleased to grant us ability to worship him acceptably,
and that he would so overshadow with his power, that the disorderly,
light and airy spirits might be kept under.
My companion had afterwards a searching testimony.
The young men who were accounted witty, were exhorted to learn that heavenly wisdom,
which would stand them in stead in a pinching time.
It was plainly told them,
that several of them were favoured with good natural qualifications,
and had acquired the world's wisdom,
so that they could argue and pretend to find out the causes of things;
yet that this would profit them little;
wherefore they were exhorted to get understanding.
The elders too were aroused, some warned and some encouraged,
and the meeting ended pretty well.
In the afternoon meeting I sunk again into the old spot,
out of which I had been somewhat recovered,
by not having faith to obey a small motion to duty; and I suffered deeply therefor,
as I have many times done.
O! faith, that precious gift, how weak is it with me, and how does cowardice prevail!

My companion had a searching opportunity to stir up Friends to their duty;
but how dull of hearing are the professors; how blind do they make themselves,
and what an itching is there after words!
Yet there are a few preserved tender, and a visitation to many of the young.
But self-denial is a narrow path to flesh, and few care to walk therein.
Oh, that I might be favoured with faithfulness to persevere in it!
In the evening was the meeting for ministers and elders,
in which my companion advised some to search deeply,
and see if something had not dimmed the beauty with which the truth arrays her children;
and if it was found that life and zeal were in measure lost, to apply unto Him who can,
and is willing to restore.
He showed Friends, in the wisdom of Truth,
the door by which undue liberty and corruption have crept into the church,
and laid waste the beauty of the truth in many in this nation; namely,
by elders and heads of families conniving at weaknesses in their children,
so that by degrees, one evil after another prevailed.

"`Second-day; this morning a meeting for worship was held,
in which my companion had a clear, good time,
though very close to the dead and carnal professors, the libertines and the careless;
yet he had consolation for the sensible,
and encouragement to such who were young in years, that were tender and desirous of good.
I had a few sentences to express in a weak manner and in fear;
but by letting in reasoning afterwards, I suffered much,
being sorely buffeted both by self and the devil,
for lack of abiding in calmness and retiring to the right centre.`"

At Limerick they remained some days and attended several meetings;
in which John Churchman was led into very close labour
with a spirit of worldly wisdom and self-security,
and had to show the deplorable condition of those who
entertained deistical and freethinking notions.

John Pemberton says in a letter from this place,
that they found more substantial Friends in that province than in the north; but adds,
that they had to sympathise with them, under a sense of the prevailing degeneracy;
"`for,`" says he,
"`the beauty of Zion seems to be laid waste, and Jerusalem become almost a desolation.`"
And he gives this as a great cause of the degeneracy, namely:
"`The elders having too much winked at what are by many called small things;
and thereby greater evils have got head in their families and in the church;
and they have lost their authority by not dwelling in the virtue and power of truth.`"

After having meetings at several other places,
they attended the quarterly meeting for the province of Leinster, at Mount Mellick.
Referring to the meeting for worship held there on first-day, John Pemberton says:
"`There was a greater appearance of Friends than I had seen before at one place.
Some yet retain their zeal and tenderness, both among the aged and the youth,
though many are lukewarm and carnal professors, whose delight is centred in this world;
some have made unto themselves gods of silver and gold;
and some of the youth worship themselves, decking and adorning and doting on themselves,
yet are careless of seeking after the adornment of a meek and quiet spirit,
which only can give true beauty and comeliness.`"

At Ballynakill they had an opportunity with Friends, in which he remarks;
"`Little was said to them, their expectations being outward.
They were plainly told thereof,
and advised not to neglect their own duty and set their eyes on man,
but to retire unto Him who alone can afford true satisfaction;
and then they would be better prepared to receive help through instruments.`"

They proceeded to Carlow, Athy and Ballitore,
and had a religious opportunity with the scholars at Abraham Shackleton's school;
from there to Newton, Kilconner and Waterford.
At this place they attended three meetings,
which were times of close labour and searching as with lighted candles.
A warning was sounded to those who were dangerously
building without the true line and plummet,
even the anointing of the holy Spirit.
Friends were cautioned also against a conformity to the customs,
fashions and manners of the world, and a delight in its riches and friendships.
The instance of the siege of Ai, was set before them,
when the children of Israel could not prosper against their enemies,
until they had first cleared their own camp of "`the accursed thing.`"
There was comfort, nevertheless, administered to the true mourners,
and encouragement for some of the youth.

After having meetings at Ross, Wexford, and some other places, they came to Cooladine,
and attended the monthly meeting on the 29th of the tenth month.
"`The fore part,`" says John Pemberton, "`was heavy and dull,
the minds of many not being rightly exercised;
but truth came over us towards the conclusion, and it ended in a pretty good frame.
The hearts of the sincere were comforted,
and the lukewarm and negligent stirred up and warned.
My companion had an open, good time, and spoke of the end of man's being created,
how Adam fell, and of Christ Jesus, by whom the restoration and atonement came.`"

After this and some other meetings, they proceeded to Wicklow, and from there to Dublin,
and were at the six weeks' meeting for the province of Leinster,
and the half-year's meeting for the nation of Ireland.
John Pemberton mentions, that in the select meeting his companion had very close labour,
"`recommending humility and self-denial, submission to the cross,
and following the example of our holy Head and High Priest, who,
though he was himself God, yet deigned to take on him flesh,
and became like unto us in all things, sin only excepted.
Friends were warned of a lying spirit that was gone forth, soothing some in their sins,
and persuading them that their condition was better than it really is.
The state of the ministry was tenderly, though very closely touched,
and also the place of elders;
and the great lack of anointed elders in this nation was lamented,
with a warning to Friends in that responsible station, to beware of the world,
which had corrupted many and rendered them insensible to good,
and incapable of discerning the savour of what was delivered in the ministry.
In the general half-yearly meeting also,
John Churchman was largely engaged in solemn exhortation to
forsake the spirit of the world and worldly wisdom,
and seek an establishment in the blessed truth,
without looking back for the flesh-pots of Egypt, or the delights of the city of Sodom;
declaring that a day was coming,
wherein the Lord would scourge the inhabitants of this land for their sins,
and well would it then be for those who had a place of defence, a sure hiding place,
a hole in the Rock to cover them; and that the wicked would have no such refuge,
having no right to expect defence in a calamitous day.`"
At this meeting, John Pemberton says,
"`Friends signed certificates for my companion and self, signifying their unity with me;
which in a degree bowed my spirit, esteeming myself unworthy thereof.`"

On the 28th of eleventh month, they attended the monthly meeting at Meath street,
in Dublin; "`in which,`" says John Pemberton,
"`my companion had an instructive and close time, and chiefly spoke of this text:
'`If we walk in the light, as He is in the light, we have fellowship one with another,
and the blood of Jesus Christ, his Son,
cleanses us from all sin;`' pointing out that without witnessing this,
there was no true communion or fellowship.
There was a nomination of some Friends to visit the families
of such who departed most widely from the limits of truth in
their dress and the furniture of their houses,
etc.; and we joined Friends in this service.

"`First-day, twelfth month 3rd;
my companion had a close opportunity and spoke to such as were uneasy with silence,
and were too apt to blame the ministers,
concluding it mere humour in them to sit the chief part of the time in silence,
and then towards the conclusion, to get up and speak a few words.
They were shown the nature of silence,
and how necessary it is to prepare people's minds to receive what may be delivered;
which, in an unprepared, unsettled state, might only divert the ear,
and not reach the spiritual senses.
Such as would reason and say in their minds, '`We are told of judgments and a trying day;
but behold, no such day appears;`' and so are ready to vaunt above it,
were told that the Lord in his mercy and long
suffering is pleased to lengthen tranquillity,
to try if people will receive warning and repent; if not, his judgments will overtake,
and he will shake his rod, and sweep the wicked as with a besom of destruction.
And if it should not happen in their day,
yet such who continued in their sins and rebellion,
and would neither be entreated nor warned,
it was in the Lord's power to cut the thread of their lives,
and appoint them their portion agreeably to their doings.`"

A week after this John Pemberton makes the following memorandum;
"`In the afternoon my companion had a good opportunity in opening in a clear manner,
and proving by many sacred texts, that Christ, by his spirit,
appeared in the hearts of people before he came in the flesh;
adducing the apostle's declaration, that the spiritual Rock,
of which the children of Israel drank in their journey through the wilderness,
was Christ; as well as other Scripture passages;
thereby confuting the notion of such that say there was no salvation
to those who lived before the coming of Christ in the flesh.`"

The following interesting remarks being part of a letter written at Dublin,
to his brother Israel, will serve to show his feelings and exercises about this time.

"`I have often to desire, that you may, with myself,
be preserved in the path of regeneration and sanctification;
which can only be by dwelling under the true
yoke and abiding steadfast in the holy cross;
so that we may witness the world and the affections and lusts thereof crucified,
and our desires thereafter more and more slain;
that we may be clothed with the pure and holy adorning, and our desires,
as we advance in age, may be to lay up treasures in heaven,
where neither moth nor rust does corrupt; and that we may not esteem this world our home,
but seek a city, whose builder and maker the Lord is.
Oh! that this was the engagement of every mind.

But it is matter of sorrow and lamentation, to behold how great a part of mankind,
and even of those who profess themselves children of the light,
are pursuing vanity and many hurtful things,
sacrificing the love and favour of the Lord to their lusts,
as though they were supported by their own power,
and were to continue forever in these poor frail tabernacles of clay.

"`I am so sensible of my own imperfections and weaknesses,
that I think myself unfit to communicate advice or strength to others;
though I have experienced the sentiment of the wise Solomon fulfilled many times, namely,
'`There is one who withholds more than is right,
but it leads to poverty.`' Yet I believe it is possible, and think I have seen it,
to give that to others which is designed as food for ourselves;
which has made me sometimes more backward than has been profitable.
But I desire to attain to a state of stability, wherein I may see my duty clearly,
and be willing to practice obedience.

"`My soul is at times engaged with breathing desires for the
preservation of the youth of this age in general;
and I have often to remember the beautiful plants which
the Lord has given you in particular,
with fervent desires, that as he was pleased to visit our souls when very young,
so he may effectually reach unto them by the visitations of the Holy Spirit,
and influence their minds with a sense of his love and regard,
that they may heartily join with the early offers thereof.`"

A few days after the date of this letter we find the following memorandum in his journal:

"`Sixth-day; at meeting Friends were exhorted to be more inward,
and to seek to get into the valley; for the faith of some would be tried,
and the church also would suffer a trial;
and it seemed as though the Lord would dry up the currents on the mountains,
and would restrain the clouds, and would scorch these high places,
and they should be barren;
therefore there was need for all to sink low and get into the valley of true humility,
that they might have something to refresh them,
when the Lord is pleased to cause a famine of the word to come.
It was also testified, that he would likewise prove in an outward manner,
though it was not to be declared in the will of man, nor the time to be limited;
for '`a thousand years with the.
Lord are as one day,
and one day as a thousand years.`' Yet if it did not happen in their time,
it might in that of their offspring;
for the earth would be purged from the present
load of unrighteousness beneath which it groans,
and he would have a pure people, that should exalt his name,
by preferring his honour to every thing else; whether he brought it about by sword,
famine, or pestilence.`"

The deeds of insurrectionary violence and rapine under which Ireland mourned,
during the latter part of that century,
the misery which has of late years involved a large
portion of its inhabitants in absolute famine,
and the history of what has occurred in our own
branch of the Christian church in that land,
within the same space of time, naturally and irresistibly lead to the conclusion,
on reading the above paragraph,
that the Lord still continues to favour his faithful
servants with a true sense of the state of the church,
and even at times, with a prophetic glimpse into the counsels of his holy will.
It is a well known fact, that some years subsequent to this date,
the Society of Friends in Ireland was torn by
the dividing spirit of a dark Socinian heresy;
and since then, with regard to "`the ministry of the word,`" it may almost be said,
that the Lord has "`restrained the clouds,`" that they send forth no water.

They were detained many weeks in Dublin, and were brought into much exercise and labour,
in visiting the families of those who were deficient in their
testimony against the fashions and indulgences of the world,
"`the lust of the flesh, the lust of the eyes, and the pride of life.`"
In speaking of his companion's service in one of the meetings for worship,
John Pemberton says:
"`He was led to expose the ignorance of those
who concluded there was no worship performed,
or profit experienced in meeting together, unless some minister preached,
and who were ready to admire at and censure us for sitting in silence.
This was not confined, he said, to those of other societies,
but included some that profess with us,
who never were baptized by the one Eternal Spirit,
which creates anew and translates from darkness to light;
but are contented to remain in the outward court.
Such were declared not to be of the true church, of which there is but one,
the foundation and corner stone of which is Jesus Christ,
whom the wise builders despise and reject.
Though there are many different sects in the world,
and all believe they are of the true church; yet none are true members,
but such as are redeemed from the world and the corruptions thereof,
and their minds purged and purified by the washing of regeneration.
It was believed there were some such in all societies;
but those who were delighted in the pursuit of worldly treasure,
and lived in the pleasures and the pollutions of the world,
whatever their profession might be, were of the church of antichrist.
It was not flesh and blood that revealed the Son of God unto Peter.
We find that the people, some of whom it is probable were learned and accounted wise,
were divided in opinion respecting the Lord Jesus, and ignorant of his true character.
But when he queried of the disciples, who they thought that he, the Son of man was,
Peter as mouth for the rest answered, '`You are the Christ,
the Son of the living God.`' To which Christ replied,
'`Flesh and blood has not revealed this unto you, but my Father which is in heaven.
And I say also unto you, that you are Peter, and on this Rock will I build my church,
and the gates of hell shall not prevail against it.`' So all at this
day must he founded and built on the same eternal foundation,
Christ Jesus, revealed in the heart.`"

Having now been at all the meetings of Friends in Ireland,
and spent much time in visiting families and attending the meetings in Dublin,
they re-crossed the channel and landed near Whitehaven, on the 25th of the first month,
1753; after which they attended many meetings in the north of England.
At Cockermouth, John Pemberton observes: "`The vanity of such was exposed,
who valued themselves for being in society with a people that is respected,
who could commend their principles and esteem them the most consistent with Christianity;
yet were shallow, and lived not in the life and power of what they professed.
It was declared that confession,
or assent in judgment to articles or precepts ever so good,
without being practisers and careful observers to live up to the profession,
will not stand us in stead, or be acceptable to God; and elders, ministers, yes,
all were exhorted to wait low in their minds, and not presume to act in their own wills,
but to let the will of the Lord be their rule;
and if he communicate advice to be delivered either in public or private, to a brother,
a sister, or a child in religion, then to do it,
as it came from Him who is the resurrection and the life.`"

First-day, second month 4th; at Pardshaw Hall, "`The meeting was very large.
The nature and advantage of true silence and retirement of mind were pointed out,
to which our forefathers and elders in the beginning were called,
and whereby they increased in divine knowledge, and became acquainted with Him,
whom they had in vain sought after among many professions, hearing much,
and looking for him where he was not to be found.
It is lamentable,
that so many of the successors of these worthies have
fallen into the same way that they were gathered from;
being outward in their views and expectations,
and therefore remain destitute of life and salvation.`"

Sixth-day, 16th; at Salterforth, "`Several not professing with us came to the meeting.
They were exhorted to a preparation for their latter end;
and as none but the pure and holy can enter the kingdom of God,
they were entreated in love to seek that power which would cleanse;
none being true Christians, but such as are alive unto God,
and eat the flesh of Christ and drink his blood; such who die to sin,
as he for our sakes laid down his life and suffered the
ignominious death of the cross for our sins;
that by laying down the life of self,
we might witness restoration and salvation from the evil and wrathful nature,
and know the blood of sprinkling, which speaks better things than that of Abel,
thoroughly to purge the heart; it being the heart the Lord beholds,
and it is that which must be purified and justified in his sight.`"

They travelled for about a month in various parts of Yorkshire, and held many meetings.
At Sheffield, on the 11th of third month, John Pemberton makes the following remarks:
"`Friends were exhorted to seek and know the Lord for themselves,
and to depend and wait on Him; which, it is to be lamented,
is much lacking in many places, both among preachers and other members;
an itching ear being in the latter to hear something to divert and please,
and in the former a desire to speak, that the people might not be scattered;
which is for lack of self being thoroughly mortified and slain,
and from indulging a foolish pity.
Oh, may I,
if it should please the Lord to qualify me to
preach the gospel of peace and glad tidings,
be preserved from going forth without the true
motion and speaking from former experience,
without a renewed qualification, and witnessing Him who is the true guide, to put forth;
that God maybe glorified, his people edified,
and he that ministers be refreshed and have the answer of peace.
The afternoon meeting was pretty large, and the state of it spoken to;
there being several who have turned to the world, in a pursuit after its treasures,
fashions and customs.
An easeful lukewarm disposition of mind covers others;
so that the few who remain in good degree sincere,
are bowed low and sit in their meetings in a sense of great poverty and death.`"

Passing through parts of Derbyshire and Nottinghamshire, they returned into Yorkshire,
and attended two meetings at Rawcliffe, which, John Pemberton says, "`were distressing.
The few who seemed to have some life, were exhorted to keep close to the Lord,
that thereby they might be preserved in a divine sense and sight,
to judge and distinguish between right and wrong;
and to be cautious how they joined with every sound, or danced after every pipe,
lest they should be drawn into error; but to try the spirits of such as speak among them.
This seemed very close speaking, but it was done in wisdom and meekness.`"

At York quarterly meeting they met with their valued countryman William Brown,
after a separation of many months.
John Pemberton describes this quarterly meeting, as "`not a time of great rejoicing;
yet it was an instructive good meeting,
and a remarkable calm attended the sittings thereof.
There was a great appearance of Friends,
among whom were a large number of hopeful young people,
whose hearts at times mourn for Zion, and long to see her appear in her ancient beauty.
Our friend William Brown, proposed the establishment of a women's yearly meeting,
as in Pennsylvania; and after consideration and consulting the women Friends,
it was agreed to suggest it to the yearly meeting of London.`"

After attending meetings at several other places in Yorkshire,
they crossed the river Humber,
and travelled pretty generally over Nottinghamshire and Leicestershire.
At Oatby, John Pemberton remarks, that from the appearance of the members,
they were "`in hopes to be favoured with some divine refreshment;
but there was much sloth and looking outward to the instruments.
We are so prone to love ease, that a necessary striving is much lacking in many places,
which makes it hard for poor travellers,
who are sent to and fro to sympathize with their brethren and sisters.
There is too much dependance on them,
and Friends were exhorted to seek substance for themselves.`"

Passing afterwards through Coventry and Warwick,
and holding meetings in these and several other places, they came to Birmingham,
and attended the monthly meeting there;
at which the necessity for a firm and faithful maintenance of our Christian discipline,
in the fear of the Lord and for the honour of his name,
was closely pressed upon the members, both male and female.
From there they travelled through Worcestershire; and at Evesham, a town in that county,
John Pemberton remarks; "`the people were exhorted to fear the Lord,
and many disorders among them were pointed out,
particularly running out in marriage with those not professing truth,
and the evil consequences attending it.

We afterwards understood, that there were few in that meeting who had been married,
but had acted in that manner;
and we had not then so much room to marvel at the barrenness that was felt among them,
which is a manifest proof that the Lord's displeasure is against such doings.
He at this day, as well as formerly,
requires that such as more particularly call themselves his children,
by professing to be led and guided by his Spirit,
should not give their daughters to the children of the world,
nor take its daughters for wives to their sons.`"
Here also a faithful maintenance of the discipline was closely recommended.

Afterwards having many meetings in Warwickshire, Northamptonshire and Oxfordshire,
they "`went to Adderbury, and attended the monthly meeting;
in which the testimony of truth ran very close in love,
to arouse them that are at ease in Zion and trust in the mountain of profession,
yet have lost the life and dew of their youth.
After parting with several valuable Friends, who were made near to us by the truth,
we passed on to Bicester.

"`Third-day; had a meeting here, to which also came some few of the neighbours;
and the cross of Christ was recommended as necessary to
make them disciples of Christ Jesus and children of God.
The advantages of true silence were pointed out, which is a wonder to the world,
and too little known by some who profess themselves spiritual worshippers.
After some refreshment, we proceeded to Aylesbury, in Buckinghamshire.

"`Fourth,-day; there were but eight women and our own company of four men,
at this meeting.
We had to sympathize in spirit with the few,
and encouragement was handed forth to the sincere in heart,
to keep steady in their love to God,
and to show it by a zealous concern to assemble themselves in the middle of the week,
as well as on first-days, to worship Him who is not limited to numbers in his favours,
but dispenses his blessings now, as in former times,
to two or three that meet in his name, and are humbled in spirit before him.`"

Proceeding through Uxbridge, Kingston, etc.,
they arrived in London on the 7th of sixth month,
and the next day were at a large meeting at Grace-church street.
John Pemberton says: "`the expectation of many was outward,
who were desirous of being fed with words.
But the Lord saw fit to disappoint them in great measure,
and they were exhorted to look to the Lord and to depend on him.`"

They attended the yearly meeting in London;
at which the establishment of a yearly meeting of ministers and elders,
to precede the yearly meeting at large, was considered,
as well as the proposition of York quarterly meeting for the
establishment of a yearly meeting of women Friends.
Both these subjects were, after solid deliberation,
referred to the decision of a subsequent yearly meeting.
"`The business of this meeting,`" John Pemberton remarks,
"`was conducted in the spirit of love, meekness and condescension, in a good degree,
though some opposite spirits were for running counter to the current of truth.
The good Hand seemed to be near,
and to countenance the foregoing propositions in a remarkable manner.
The meeting was very large,
and a zeal for the cause of truth was felt to flow in the bosoms of many of the youth,
as well as the aged, who retain the sap and living virtue of truth.`"

Speaking of his own exercises and baptisms at this time,
John Pemberton says in a letter addressed to his parents, dated sixth month 13th,
from London; "`I hope I am in some degree sensible of the continued mercy of the Lord,
though strippings seem to be my lot; and a secret mourning, in humility and reverence,
for myself and my fellow-mortals, attends at times,
with desires for my more steady abiding under,
and true submission to the cross and walking in the narrow way;
which to the unmortified nature is hard.
For lack, I fear, of being more inward and attentive,
I am not so skilful in distinguishing the voice of the true, from the false prophet;
and so, through diffidence and fear, often miss of discharging my duty punctually,
and thus leanness and feebleness still attend me; and of late my situation has been such,
that I have been ready to cry out,
how long will it be before my feet are firmly established on the immovable foundation?`"

Soon after the yearly meeting they left London and travelled through parts of Essex,
Suffolk, etc.
At Colchester they attended the quarterly meeting of Essex;
"`in which,`" John Pemberton remarks,
"`Friends were exhorted to be cautious how they meddled
with the affairs of the church in their own spirits;
and were shown where they ought to look for a qualification to act for the Lord,
in the way that would be pleasing to him,
and for the edification of his church and people;
the transacting of these affairs not being, as some vainly imagine, political and formal,
but first introduced in the wisdom and power of Truth, and if rightly conducted,
must be continued and upheld by the same Divine and heavenly power.`"

The affectionate feelings which clothed his mind
in the remembrance of his relations at home,
and the motives which induced him to continue for a while longer in the field of labour,
to which he had felt himself bound now for about three years,
may be judged of by the following expressions,
in a letter written to his parents from Woodbridge, sixth month 30th, 1753:
"`It gives me great uneasiness to find that my
dear father is so weakly and declining in health;
yet I am in some degree comforted, with an evidence,
that through the mercy and favour of the Lord,
you have been preserved through the course of your pilgrimage, in his fear,
and by dwelling in it, have witnessed life and favour; not living in a hypocritical,
pharisaical show, a cleansing of the outside barely,
but have lived in and possessed the vital part of religion.
And oh! says my soul, may the Lord in the riches of his love and condescending goodness,
be pleased to favour with the renewings of life, strengthen your faith,
and fix your hope and confidence in him,
that you may be enabled to keep sight of the Pilot,
till you be conducted and anchored in safety in the harbour of rest,
where the righteous live forever.
I fully intended to leave my dear companion at London; but when I looked towards home,
the cords seemed not to be loosened.
So with the advice of my friends, and in pursuance of the way that seemed most easy,
I set out from London, and am come thus far with my dear companion; who, I expect,
after the conclusion of this and the Norwich yearly meeting,
will shortly embark for Holland.
He is not certain of any person to accompany him, unless I go.
Notwithstanding I long greatly to see home and my dear parents,
and cannot perceive what advantage my stay is to anyone here,
yet I am resigned to the will of the Lord, and to be directed in his counsel,
and desire to be preserved from saying, '`What are You doing?`'

They attended accordingly, the annual religious gatherings called yearly meetings,
at Woodbridge and Norwich; at which latter place,
John Pemberton makes the following memorandum in his journal:

"`First-day, seventh month 8th; this morning went to the meeting at Norwich,
which was large and a solid meeting, though too much outward dependance.

"`Second-day; this morning was the meeting for ministers and elders.
It was an exercising time; a cloud of darkness seemed to hang over,
which caused the hearts of the sincere to examine and query after the cause.
It seemed as though the Lord was displeased with some,
because their hearts were turned from him to idolatry,
and yet they pretended to rule and govern in his church.

"`First-day, 22nd; were at the meetings at Norwich, much in silence,
which to many is unpleasant;
but there is a hopeful seed and young plantation here that labour for their own food,
and do grow, and will be preserved in greenness, if they abide steadfast;
though the foundations of others may be shaken, who depend on receiving food outwardly,
and have neglected the gift in themselves.
For the Lord is jealous of his honour,
and will be sought unto by the whole house of Israel.

"`Third-day, attended the week-day meeting;
in which preachers and hearers were recommended to silence,
and such who were at times commissioned to preach the gospel,
exhorted not to speak before they witnessed what the apostle alludes to, when he says,
'`Woe is unto me if I preach not the gospel;`' lest they should
communicate to others what was designed for themselves.`"

Soon after this they proceeded to Yarmouth and embarked on the 25th of seventh month,
for Rotterdam, in Holland, where they arrived on the 29th, after a rough passage;
and went to Amsterdam and had a meeting with Friends in that city.
John Pemberton says, "`here are a few tender spirited Friends, who live near the truth;
but the spirit of the world prevails, which ever was,
and ever will be at enmity with the Father,
and causes the upright in heart to bear heavier burdens.

"`First-day, eighth month 5th; the meetings were attended by many others beside Friends;
to whom the kingdom of Christ within was preached,
and the people directed to him as the only sure leader and conductor.
There were some tender people at these meetings, especially among the youth,
who were exhorted to seek the Lord in their youthful days, and he would be found of them.

"`6th; The hearts of many in this land, as well as in other places,
when they hear the doctrine of truth declared, assent thereto;
but the stumbling blocks in our Society cause them to halt, being led to conclude,
when they see the conduct of some who profess themselves children of the light,
but are stained with the spots of the world, and continue in the unregenerate nature,
which is not subject to the cross of Christ; that there is nothing in religion,
or that these are not the people with whom they should join.
There are many who have broken off from their bondage to the priests,
and are in a seeking condition, often sorely distressed to know how to act,
or with whom to join; some crying, Lo here, and others, Lo there.
It is pleasant to behold the sober countenances of some,
as we pass through the towns and streets, who seem to be of tender spirits.
The fields are ripening unto harvest; but my dear companion, as in his previous travels,
is led to our own Society, if possible, to regulate things there.
The love of our heavenly Father is still extended to us as a people;
and he is desirous that those whom he has particularly
distinguished from all the families of the earth,
should be inheritors of the holy and promised land.

"`7th; Poverty and weakness surround me;
yet the Lord in his mercy is at times pleased to favour with a degree of light,
and with a humble spirit,
and to raise fresh desires for an established heart and
a mind more disposed to believe and obey.`"

After a few days spent at Amsterdam, they proceeded to Twisk,
about twenty-four miles distant,
and visited the families of those professing with Friends at that place,
and a village in the neighbourhood, called Abbey-kirk.
They also had some close labour with them in their meetings,
and then took wagon and went to Hoorn.
Here they held a meeting with the sober inhabitants to a good degree of satisfaction;
and returned to Amsterdam.

On the 22nd of the eighth month was held a meeting, called a yearly meeting;
"`which,`" says John Pemberton,
"`consisted chiefly of the Friends belonging to Amsterdam,
and a few of the town's people.
The sincere were encouraged to faithfulness,
and to discharge themselves honestly one toward another,
not letting in the reasonings of the creature, which bring weakness and death.
My companion had to tell them, that though things looked dull among them at present,
he was well satisfied the arm of the Lord was stretched forth,
and he would gather a people in that city that should be zealous for his name and cause.
Therefore they were encouraged to trust in the Lord and often to seek his face,
and be upright in their day, that they may be as lights to the world;
and by their humble walking, be instrumental to gather people to the name of the Lord.

"`First-day, 26th; the meeting was more full than at any time since we have been here,
and my dear companion had a large and acceptable opportunity,
tending to stir up the people to labour to be prepared for death.`"

Being now clear of Holland,
they embarked at Rotterdam in the same vessel which had brought them over,
and landed at Yarmouth, in England, on the 2nd of ninth month.
The next day they went to Norwich and attended the monthly meeting in that city.
Speaking of this visit to Holland, in a letter written to his parents from Norwich,
John Pemberton says; "`We visited the few Friends there very particularly,
and were three first-days at Amsterdam, and had some pretty good meetings among them,
Truth favouring with a degree of authority.
Respecting our Society, things are very low,
owing in great measure to the neglect of discipline, which when rightly maintained,
is of great benefit.
May those who are favoured to see the advantage and necessity of such order,
keep near the Truth, that their sight may be preserved clear, and their judgment sound;
for true discerning is with the upright only.
Such having the cause of Truth at heart, are not drawn aside through favour or affection,
but with Christian boldness are concerned to do justice and judgment.
Where this is the case, the Lord is pleased to favour them in their sitting before him;
but where the hedge is allowed to be trampled down, a blast attends,
and the true seed is in sorrow and mourning.
There are in Holland a few professors who witness the life and savour of Truth,
and are concerned daily to seek after it;
but it was painful to us to find ourselves deprived of
the satisfaction of freely conversing with them,
without having recourse to an interpreter.`"

John Pemberton feeling himself now released from further service with John Churchman,
after solid deliberation they concluded it right to separate.
He thus mentions the separation, which was at Edmondsbury,
on the 21st of ninth month, 1753.
"`This morning I accompanied my very dear companion a few miles out of Bury,
when we parted in much love and tenderness,
having travelled together about three years in tender affection towards each other.
But this seemed the time to separate, he having been ever since we landed from Holland,
much straitened, being shut up, till yesterday, when his way opened for Wales,
and myself inclined towards London.`"

John Churchman in his journal,
expresses on this occasion the same feelings of affection for his faithful companion.
"`My mind,`" says he, "`being drawn towards Wales, my companion, John Pemberton,
who had been with me three years, having travelled together in much love and unity,
inclining to go towards London, we parted in the same love.`"

The remainder of this journey may be briefly narrated
in the following extracts from John Pemberton's journal.

"`Fourth-day, ninth month 26th; attended the meeting at Colchester,
which was small and low, words not being so much lacking as life and power,
and a living up to the truth professed.

"`Fifth-day, I went to Chelmsford, accompanied by John Kendal.

"`First-day, I attended both the meetings.
That in the morning, small and dull for the most part;
but the Lord favoured in some degree towards the latter part.
The afternoon meeting was pretty large, yet attended with pain;
there being many whose minds are indifferent and cool about religion,
and are as a door upon its hinges, going and coming, and yet remaining in the same spot;
on account of whom there is a mournful seed.

"`First-day, tenth month 21st; attended both the meetings at Walden,
where are several valuable Friends: these have heavy burdens;
which I much desire that the Lord may remove in his time,
by arousing and stirring up the careless and lukewarm to seek him for themselves,
and to witness the Word to purge and purify the heart;
that thereby the Lord might delight to come down and
visit his people with his enlivening presence,
in their approaches before him.
In the evening had a pretty satisfactory opportunity in the family;
where there are several hopeful plants,
who I desire may be preserved from the snares of the tempter.

"`Third-day, took leave of my kind friends, and accompanied by William Impey,
went to Bardfield,
where in the evening we had an opportunity with some of the few Friends of that place.

"`First-day, tenth month 28th; attended the quarterly meeting for worship at Stebbing,
which was large, but truth low.

"`Fourth-day, had a meeting with the few professors at Coptford,
where much blindness and darkness reigns,
and a great declension in not keeping to the testimony against paying tithes, etc.
Had discourse with Friends on the subject, and afterwards proceeded to Colne,
and on fifth-day had a meeting with the few Friends there.

"`Sixth-day, was at the meeting at Coggeshall, and Friends having notice,
pretty many attended.
The lukewarm and careless professors were closely spoken to;
these have spread through the Society and in the world; and Oh,
that there may be an awakening,
and a true thirst raised in the people after the pure Fountain of life;
that truth may prevail in their hearts,
and the Lord delight to overshadow the assemblies of
his people with his life-giving presence.
Next morning set forward to Chelmsford, and then to London,
where I arrived in the evening.`"

He remained in London and its vicinity,
attending meetings and preparing for his departure homeward,
until the 15th of the ensuing second month.

A vessel at length offering for Philadelphia, he left London on the day above mentioned,
in company with Daniel Weston, and at Gravesend went on board the ship Carolina,
Stephen Mesnard, master.
They had a favourable, though not a very rapid passage,
and entered the Delaware bay on the 10th of fourth month.
On approaching his native shores,
John Pemberton received the afflicting intelligence of the decease of his father,
which he mentions in the following terms:
"`By the pilot I had the sorrowful and greatly afflicting tidings of
the decease of my dearly beloved and much honoured father,
who departed on the 19th day of the first month,
being seized as he was attending a funeral, with a dizziness,
to which he had been for some years much subject.
He was taken into Samuel Mickle's, near the grave-yard, and there departed.
He was an exemplary man in life and conduct, devoted to the fear and service of God.
He lived beloved, and died much lamented.
May his descendants be religiously concerned to follow his pious steps,
and their latter end be crowned with peace, as I believe his was.
I retired into my state room, and had some sorrowful moments;
yet I had before been apprehensive that he was departed, being,
about the time he went off, much impressed with such a belief,
when at my friend Daniel Weston's, in London;
and I told Mary Weston that I believed my father was gone.

"`I reached Philadelphia on seventh-day, the 13th of fourth month, 1754,
and met my honoured worthy mother.
It was a meeting of joy and of deep sorrow.
She was supported with Christian fortitude and resignation under her heavy exercise.
I felt a sorrowful spirit, but a solid mind.
My beloved friends appeared rejoiced at my safe return after so long an absence;
and I hope I am thankful for the preservation experienced over the great ocean,
and the evident sense of the continued mercy of Almighty God towards me,
a poor unworthy person, who have often neglected the performance of known duty.
I had experienced the Lord to be long suffering and abundant in compassion,
seeing my weakness and dastardly disposition; giving way so much to which,
has caused many days and nights of anguish and distress.`"

He was now restored in peace to his family, and a new scene opened before him.
He had been careful, on undertaking so important a journey,
to take with him a certificate from his friends at home; and having, since his departure,
notwithstanding his sense of many frailties and short comings,
experienced his feet to be shod with the preparation of the gospel of peace,
and his tongue enabled to declare of the mercy of God in Christ Jesus our Lord,
he presented to his brethren, at their monthly meeting held in the fifth month following,
testimonials of the unity of Friends in Great Britain and Ireland, with his services.

For some years after his return home from Europe, John Pemberton resided with his mother,
and was diligently occupied in mercantile business.
It appears, however, that he was careful to avoid entanglement in the affairs of trade,
or drinking in the spirit of the world,
which would have disabled him from faithfully pursuing that
path of religious service to which he believed himself called.
He was also mindful to cherish a deep interest
in the welfare of his fellow men of all classes,
and a peculiar sympathy for those two oppressed races, the natives,
or descendants of Africa, and the aboriginal inhabitants of his own country.

About this time he was instrumental, with his two brothers and several other Friends,
in the formation of an association for the benefit of the Indians,
and the preservation of amicable relations between them
and the white inhabitants of Pennsylvania.
This "`Friendly Association,`" as it was termed,
took great pains to induce the governors of the province to
adopt such measures as would be likely to soothe the irritated
feelings of these oppressed sons of the forest;
and was useful also in persuading the Indians themselves to
accede to the reasonable propositions made to them.
John Pemberton, on several occasions,
had some of the chiefs as guests in his hospitable abode;
and the three brothers appear to have possessed great influence with this people.

About the year 1757, he was united with Daniel Stanton and Benjamin Hooton,
in promoting a treaty of peace and amity amongst the frontier Indians, at Easton,
in Pennsylvania.
Some of the Indians in the neighbourhood of Fort Allen,
having discovered a backwardness about attending this treaty,
it was deemed necessary for the above mentioned Friends to visit them,
in order to endeavour to persuade them to join the rest in council at Easton.
They accordingly conveyed to them an invitation
from those Indians who had already assembled,
and also from the government of Pennsylvania.
Daniel Stanton thus speaks of it in his journal:

"`It was thought some of them had been very mischievous in the murders and bloodshed,
and taking of captives on the frontiers of our province.
And a great concern having fallen on the minds of a number of worthy Friends,
principally in Philadelphia, who freely contributed their money and time,
for promoting the restoration of peace with the natives; I have apprehended, and believe,
they were instrumental in the Lord's hand,
to appease the revengeful nature of so barbarous and cruel an enemy;
the hearts of the Indians retaining a great love
for the memory of our first worthy proprietary,
William Penn.
Remarkable it was, that through the protection of the Almighty,
which was as a mighty rock in a weary land,
few called by our name were ill used during all this calamity.

"`Three Indian men accompanied us as far as Fort Allen, Moses Tatamy and two others.
We travelled much in the night and through a great rain, stormy and cold weather,
to reach that place; to which we came the next morning.
The captain received us very civilly,
and I thought did what he could to be of service to us,
and behaved very kindly and friendly to the Indians, which they seemed to take well.
At first sight the Indians appeared dreadful to behold,
as to anger and revenge in their countenances,
with their painted warlike looks and weapons, and were very shy.
Yet after some friendly conversation, and their receiving a few small presents,
which we carried with us for some of their chiefs,
they appeared in quite a different disposition before we parted.
But they could not be prevailed with to come to the treaty,
because of the word and engagement they had made among themselves, to depute Tedyuscung,
their chief man, to transact the business with the government on their behalf.
In confirmation of their continuing in this mind,
they sent a string of wampum by Moses Tatamy.
After a further time of free conversation, they appeared still more pleased,
and as I thought, out of love to us, sent two of their young men to accompany us back;
we parted with them in love.
Our endeavours appeared to be well taken by them, and I hope were of service;
although none of them but the two young men, came with us to Easton.
We ventured our lives and went through hardships to perform this errand;
but through the mercy and kindness of the Lord we were preserved;
for which my soul had cause to be thankful to his great and good name.`"

About this time also, John Pemberton united with his friend Daniel Stanton,
in a religious visit to the families of Friends and
those making profession with us in Philadelphia,
the Northern Liberties, and the vicinity of the city across the Schuylkill.
This service, in the course of which they visited more than five hundred families,
engaged them at various times, as they found freedom to proceed,
for upwards of two years.
It was kindly received, and believed to be,
through the goodness of the Almighty accompanying them,
a time "`of tender visitation to many souls.`"
During a part of this period, in the spring of the year 1759,
he accompanied William Reckitt, a minister from England,
to some meetings in Pennsylvania and New-Jersey; and about three years after this,
on the 17th of fifth month, 1762,
he left home on a journey to Rhode Island and some other parts of New-England,
visiting the island of Nantucket, in company with Robert Proud,
H+++.+++ Harris and E. Wilkinson.
He was out on this occasion upwards of two months,
and on his return made the following memorandum:

"`I have occasion to be thankful for the fresh
extendings of Divine notice in this journey,
and particularly so in the latter part of it; though many deep baptisms attended.`"

For several years he remained principally at home, being diligently occupied,
not only in his temporal business, but also in aiding the cause of the oppressed,
and promoting, by works of benevolence and Christian love,
the welfare of his fellow-creatures, without distinction of tongue or colour.
He also occasionally visited neighbouring meetings in the country,
as impressions of duty, or gospel freedom and love to the brethren prompted.

On the 24th of the second month, 1765, he was deprived of his mother by death,
about the seventy-fourth year of her age.
She was the daughter of Charles Read,
one of the early settlers of Pennsylvania under the grant to William Penn;
and is described by the monthly meeting of Philadelphia,
in their memorial respecting her, as a "`mother in Israel,
having a pious concern for the prosperity of the cause of Truth.
She usefully filled the station of an overseer and elder,
being carefully concerned to rule her own family well,
and that her offspring might have a portion of that treasure which fails not.
She was a true sympathiser with those under affliction of body or mind,
demonstrating her sensibility herein by her frequent visits to such,
which were weighty and comforting, her conduct being solid and instructive.
Few,`" they add,
"`have been more zealously concerned and
diligent in the attendance of religious meetings,
seldom allowing the inclemency of weather to prevent her;
and continuing the like concern when very feeble.`"

On the 8th day of the fifth month, 1766, he was married to Hannah,
the daughter of Isaac and Sarah Zane.

About this time a company of stage players came to Philadelphia,
with a view to erect a theatre for the exhibition of
their pernicious and sinful diversions.
Friends were affected with much concern on this account,
and feeling it incumbent upon them to bear their testimony against it,
and do what lay in their power,
to prevent the establishment in the city of a thing fraught with so much evil,
they sent a remonstrance to the governor, John Penn, who was then at Shrewsbury,
in New Jersey; requesting him to interpose his authority to prevent the same.
John Pemberton, Mordecai Yarnall, Joshua Emlen and Daniel Stanton,
were appointed to present the petition.
They found, however, to their disappointment,
that the governor had already given a promise to the players, of permission to proceed.
Friends continued sorrowfully affected with this
dangerous innovation upon the morals of their city,
and deeply concerned for the preservation of the youth from the snare thus laid for them;
and this concern resulted in the spreading of a printed paper among their members,
of which the following is a copy:

[.embedded-content-document.epistle]
--

[.blurb]
=== Advice and caution from the monthly meeting of Friends in Philadelphia, the 23rd day of the ninth month, 1768.

[.salutation]
To our friends and brethren, in religious profession with us:

Dear Friends,
A deep exercise and fervent concern being impressed on our minds for
the preservation and welfare of the members of our religious Society,
and especially of the youth under our care,
we affectionately exhort and advise all who make profession of being led and
guided by the dictates of the divine principle of light and truth,
to commemorate with reverence and thankfulness, the manifold mercies and blessings which,
by the bounty of the Lord our God, are continued to us; and by integrity,
sobriety and circumspection of life and conduct,
to manifest that we are sincerely desirous of walking answerable to so great favours.

We are engaged the more immediately to excite these considerations at this time,
from an apprehension that the minds of the unwatchful will be in danger of being
captivated by the ensnaring diversions of the horse races and stage plays,
which are intended to be again exhibited in and near this city.
We earnestly entreat and beseech,
you would seriously consider the danger and destructive tendency of
countenancing or encouraging these profane amusements,
by attending, or being spectators of them, as they evidently tend to introduce idleness,
licentiousness and intemperance,
and are directly opposite to the precepts and example of our Lord Jesus Christ,
and to the testimony and practice of his disciples and followers in every age.

We therefore fervently desire that all Friends,
to whom the important care of youth is entrusted, would, by admonition and persuasion,
endeavour to convince them of the hurtful consequences
of being deluded by these ensnaring temptations;
and where this labour fails of success, that they would discharge their duty faithfully,
by proper restraints.

And dearly beloved youth,--Considering how many are drawn aside into vanity and folly,
from the holy visitation of Divine love,
which you have at times been sensibly affected with,
we entreat and beseech you to avoid these temptations;
permit the sincere and ardent desires of your elder
brethren for your present and eternal welfare,
to have place in your minds.

Let a due consideration of the uncertainty of the time allotted you,
excite you to devote it to the honour of God.
Attend to the restraints of Divine grace,
and thus you will be preserved from the evils of the world,
become serviceable in your several stations, and obtain true peace here,
and a well grounded hope of everlasting happiness hereafter.

[.signed-section-closing]
Signed in and on behalf of our said meeting, by

[.signed-section-signature]
John Pemberton, Clerk at this time.

--

On the 30th of fifth month, 1769, he left; home with the unity of his friends,
on a religious visit to Rhode Island and Nantucket;
during the course of which he attended a great number of meetings at various places,
and had religious opportunities in many families.
The following memoranda are taken from a diary which he kept of this journey,
and may serve to elucidate in some degree,
the exercise which attended him on that occasion.

"`Sixth month 2nd; Proceeded to Bethpage,
and met with our friend Rachel Wilson and her companion.
After taking some refreshment we went to the meeting, which was large,
there being a marriage; then proceeded to Sequetague in company with many Friends,
where we had a large and good meeting, and many departed with thankfulness.

"`4th; Had a favoured meeting in the court house at Setawket,
several being reached by the testimony of truth;
and then proceeded with intent to have a meeting about three miles further,
where was a meeting place of a people who had separated from the Presbyterians, and who,
we expected, might be more free from bigotry.
But we found the elders were very shy, and not free to permit a meeting there,
though their minister was absent.
Many however gathered, and finding our minds engaged,
we held a meeting at some distance from the house, under the trees.
A number of young people staid, and some of their elders;
and the testimony of truth was in a solid and free manner declared,
which had place with many.
About two miles further, we came to a meeting house of the Presbyterians,
and after halting a short space on horseback, went a little forward;
but not finding entire liberty, we alighted,
and went back to the meeting house and continued without until their service was over;
when we stepped in, and our friend Rachel Wilson, craved liberty to speak a few words.
The minister consented, and continued in his pulpit;
but after she had gone on for some time,
and was declaring her call to the ministry in a clear manner, he interrupted her,
and said to this effect; '`that if she asserted her being called to the ministry,
as it was not agreeable to the word of God, he should oppose her.`'
She paused awhile, and I requested he would have patience.
She asked him whether he would oppose the truth, and repeated the same words.
He said, if he heard anything contrary to '`the word,`' it was his duty to oppose it.
She said, if she declared anything contrary to the Scriptures,
she was willing to hear rebuke; adding, that she did not desire to offend;
it was love to God and to their souls, that she had at heart, and so went on;
and the minister came out of his pulpit and went off.
A sober young man spoke softly to him, as he afterwards told us,
and desired that she might go on, for he had a mind to hear her.
The people staid and heard with serious attention, many of them being affected,
and she had a good opportunity, the truth being declared with power and authority.

6th; At New London application was made to the sheriff,
who readily granted the court house, and assisted in placing seats.
Many people gathered, and it was early perceived that it would not accommodate them all.
One Colonel Saltonstall, stood up and proposed our going to the meeting house just by,
for the better accommodation of the people.
They moved to it in an orderly manner,
and the testimony of truth was freely declared by our friend Rachel Wilson.
Some ranting people, called by some, No day Baptists, by others, Quakers,
were at the meeting; and one woman, near the close,
said that if we were the children of God,
there were some of the children of God in prison, and one very sick,
and she would have us go and visit them.
As these poor deluded people were called by many, Quakers,
I was concerned to declare our disunity with them and their practices,
expressing that we were known to be an orderly people, and did not countenance,
nor had we unity with such conduct as these people manifested.

After the meeting we had conversation with the young man who officiated as parson,
a sober courteous man, who had appeared sensibly affected with the truth;
and we condemned their manner of treating these deluded people,
who are severely persecuted.
After dinner we went to the prison.
Parson Graves, of Providence, the young Presbyterian, and several others attended;
so that the prison was crowded.
Our friend Rachel Wilson, was enabled to speak suitably to these poor creatures,
some of whom were calm, but others looked very wild.
They all appeared, with respect to their persons, cleanly, well looking people,
but very positive in their sentiments.
The women seemed the most fiery; they used the plain language,
and were full of Scripture, but argument has little weight with them.
The evil of persecution was exposed, and endeavours used to calm them;
which I desire may be blessed with success.
We afterwards spent a little time with Parson Graves, who appeared a thoughtful,
sensible man, and condemned the conduct of the Presbyterians to these ranters.

"`Sixth month 13th; This morning we visited the prisoners at Newport; a stinking jail,
where it is a shame that human beings should be kept.
The sheriff, the governor's son and others, besides some Friends, were present;
the meeting was favoured and the prisoners thankful for the visit.

"`19th; Went to Aponygansett, where the meeting was exceedingly crowded,
and though not so lively as some others, yet Truth in some measure favoured,
and the gospel was preached.

"`20th; Embarked on board the Dartmouth packet with a number of Friends for Nantucket.
We stopped at Elizabeth island,
and some of us went ashore and waited for a
proper time of tide to pass through Wood's hole,
a dangerous passage.
We set sail again about four o'clock, got safely through,
and arrived about sunset at Holme's hole, a good harbour in Martha's vineyard.
We went ashore, and collecting some of the inhabitants,
had a meeting at our friend Daniel Coffin's,
being the only family of Friends on that island.
In the morning we went on board again and landed at Nantucket about eleven o'clock.

"`22nd; I met twice with a committee of Friends,
appointed by the yearly meeting at Rhode Island,
respecting a division that has long unhappily subsisted among Friends on this island.

"`23rd; This morning began the yearly meeting on Nantucket,
and in the afternoon I again met the above committee
and some of the parties in the difference here;
and the Lord favoured us, so that there was a willingness wrought in all present,
except one who desired to think more upon it, to leave the matter to arbitration;
and a paper was drawn up accordingly.
This step affected my mind with thankfulness.
Next day, in the afternoon, I again met some of the parties,
and a few more signed the paper; but some principally concerned not being there,
it was resulted to visit them privately.

"`27th; After the conclusion of the meeting for business yesterday,
I acquainted our friend Rachel Wilson, with the contention which had subsisted,
of which she was unacquainted, except that there was some uneasiness.
I told her I apprehended we should need some of her assistance;
which she was free to give; and early this morning we set out,
and being joined by the committee, we first visited;
a divine covering and sweetness almost immediately attended, and after some time spent,
he signed the paper, and we went to '`s, the former Friend accompanying us.
We spent some time in solemn silence, and suitable advice being communicated,
we proceeded to the business; and though at first there was an unwillingness,
yet truth prevailed, and this family came into the agreement.
After which we collected again into silence,
and the opportunity was seasoned with divine virtue, our friend Rachel Wilson,
being concerned in fervent prayer.
We then concluded to give notice to the parties,
to meet this evening to conclude on referees; when they met,
and after a pause proceeded to a nomination.
We then gathered into silence, and our friend, Rachel Wilson, was concerned in prayer,
and the meeting concluded in peace and thankfulness.

"`29th; This morning we took a farewell of many tender Friends, who seemed afresh visited.
Some that are young, and several advanced in life are alive in the Truth,
and many of the middle aged steady and hopeful;
and my mind was thankful that amidst such distraction, a remnant should be preserved.
We embarked about seven o'clock,
and landed at Wood's hole about five o'clock in the evening.

"`Seventh month 2nd; Although very poorly, I set out for Yarmouth.
The people who attended this meeting seemed generally very poor,
and many came who were bare-legged and bare-footed; truth prevailed,
and it was an instructive edifying meeting.

"`8th; Crossed Merrimack river to Amesbury, had a meeting there,
and then proceeded to Hampton.
On second-day was the quarterly meeting for business,
and after that a meeting for worship, which was large and laborious,
by reason of a greater dependance on words than labour to feel for the life;
too many under the profession of the truth being faulty herein.

"`14th; Embarked on board a boat in company with several Friends,
and had a passage of about four hours to Mariconeague, or Hartshill,
having passed many small islands.
The meeting that evening was but a dull time;
afterwards those that profess with Friends were selected, and some advice communicated.
They are in a poor situation, and the meeting I apprehend not properly supported,
though some appeared hopeful.

"`15th; Took boat again for Perumscot, which we reached in about six hours and a half,
and next day were at two large meetings in their new meeting house.
My mind has been much stripped, and great poverty of spirit experienced;
yet my mouth was opened in each meeting.

"`On fifth-day morning we mounted our horses and went to Lynn;
and here my mind continuing very heavy respecting Mariconeague,
I halted and remained at Zaccheus Collins's, and the women Friends proceeded for Boston.
After resting awhile, I wrote an epistle to Friends at Mariconeague;
in the afternoon I took horse towards Cambridge, intending to overtake the women Friends;
but not finding true quiet, I returned;
and on seventh-day morning I set out again eastward,
determining that if it was the requiring of Truth that I should go back,
I would strive to perform it.

"`On third-day Samuel Collins brought his chaise, intending to accompany me.
Very dull was I for lack of divine enjoyment, yet fearful of turning back.
We proceeded to Berwick, and on fourth-day arrived at Perumscot.
On fifth-day I had conversation with some Friends
respecting the situation of Friends at Mariconeague,
and I found them of the same sentiment with
myself respecting the danger of their declining.
The next day I set out with Friends in a boat, and after a passage of about five hours,
landed on the neck and visited four families that evening.

"`Seventh-day, I rose early, visited three families and attended their monthly meeting.
Things here are indeed very low, and unless the Lord interpose,
the beloved youth are likely to be scattered and lost to Society.
I endeavoured with all the ability afforded to discharge myself,
and if possible to stir up to faithfulness.
After this we again embarked, and returned to the harbour we had left.

"`On first-day I attended two meetings at Perumscot, which were dull, hard meetings,
yet I was faithful to perform what I apprehended my duty,
and had afterwards an opportunity of making some serious remarks to several Friends.
On the 6th of eighth month, I got to Newport, and after a few days' stay,
embarked for New-York, and so home.`"

On the 6th of the tenth month, 1774,
he again left home on a visit to some parts of New-England,
in company with our friend Mary Leaver.

They visited the meetings generally of Rhode Island, Nantucket,
and some parts of Massachusetts,
and were accompanied on a portion of the journey by Moses Brown, of Providence,
then a young man.
Respecting this Friend,
afterwards so highly esteemed as a qualified and faithful elder in the church,
John Pemberton makes the following remark in his diary of this journey:

"`Moses Brown, with his wife's mother, her daughter and Audrey Green,
a nurse in his family, are lately convinced of the truth,
and happily brought into conformity to it; so that they are weighty, solid,
plain and circumspect.
And though he is great in the world,
and has been much engaged in the concerns thereof in various respects, yet is he humble,
meek and lowly, and by diligent attention, has,
for so short a space that he has professed the truth,
made great advancement on the right foundation;
where I wish he and the rest may be mercifully preserved.
I could not but remark the gravity and plainness of his family and servants;
their words being few and savoury;
so that I had much satisfaction in this religious family.`"

He made a third visit to New-England in the sixth month, 1776,
attending the yearly meeting on Rhode Island,
in company with his friend Samuel Emlen, jr.
It was a time of great commotion,
the revolutionary agitation making it difficult travelling from one place to another;
yet they were preserved from much annoyance by the contending parties,
and had to encourage their friends to a firm adherence to their peaceable principles.
"`Through the various sittings of the yearly meeting,`" he says,
"`the love and mercy of the Lord was manifested, to the tendering of many hearts;
and I could not but admire at his gracious condescension.
It seemed as though the Lord was preparing his people for some great trial,
and that the shaking of his rod had a humbling, profitable effect upon many minds.`"
During a part of his homeward journey, John Pemberton had the company of William Rickman,
then of New-York, and afterwards a devoted minister of the gospel,
zealously exercised in support of the ancient principles of truth in his native country,
Great Britain, where he died in the year 1839, in the ninety-fourth year of his age,
full of days and full of peace.

Late in the autumn of this year, 1776,
and at a time of much commotion and some danger to travellers,
from the contending armies which were spread over great part of the country,
John Pemberton visited the Eastern shore of Maryland,
attending the quarterly meeting at Cecil, and the particular meetings belonging thereto.
Towards the close of this visit,
he found himself not at liberty without proceeding to Accomac county, in Virginia,
to visit a family residing in a remote situation, sixty miles from any other Friends.
He accordingly paid this little debt of gospel love;
had two seasonable religious opportunities with the family,
in one of which a number of coloured people were present,
and left them with hearts tendered by the power of Truth.

He remarks in his memorandum of this visit,
that "`they were glad to see the face of a Friend,
and to receive the crumbs which the full-fed would have despised.`"
Before reaching home he received intelligence of Friends in Philadelphia
being subjected to much trial and loss by the violence of a mob,
on account of their refusal to illuminate their houses,
as a mark of joy for a victory gained in Virginia.

[.offset]
About this time he recommenced the keeping of memorandums, as follows:

=== Diary during part of the Revolutionary war.

"`The ways of the Lord are unsearchable to frail mortals.
His judgments are in the earth, and remarkably so in this once peaceful land; his wisdom,
power and majesty, are greatly manifested in confounding the wisdom of the wise,
and showing the weakness and insufficiency of human contrivance, policy and prudence.
And yet, in abundant condescension and mercy,
he is showing himself gracious to a despised remnant, amidst the agitation,
confusion and distraction that prevail; with which multitudes are tossed,
and in terror and amazement, so that they are like men at their wits' end,
having no stay, but fleeing one way and removing another;
whose situation is much to be lamented.
Yet though disappointed, they are not humbled, but persist in their gainsaying,
as men given up to a reprobate mind.

"`Amidst all these commotions, the Lord in mercy has vouchsafed to say to a remnant,
as to the boisterous waves formerly,
'`Peace, be still!`'
He has permitted our religious meetings to be held in much quietude,
and favoured the minds of such who have endeavoured to
keep out of the flaming fiery spirit,
with an admirable calm.
Although destruction has been threatened to Friends, yet the Lord has hitherto preserved,
and few have unsettled themselves, or removed from the city; to Him be the praise.
The covering of Divine love attends, to unite well concerned Friends,
in considering many weighty matters,
which almost daily call for their attention and consideration;
and the gracious dealing of the Lord,
is abundantly worthy of being commemorated and preserved for future time.

"`It is indeed deeply affecting to see the destruction
of mankind by the unnatural war now raging,
wherein multitudes have been slain, and more have died through sickness and want.
The flower of the country, young lads, and those just arrived at a state of manhood;
many of them sons of reputable farmers in Maryland and Virginia, and other provinces;
being brought to the city in large numbers, pine away with sickness,
and many are buried in a day.
Besides this, the last fall was very dry,
and the green wheat in many places suffered so much,
that some husbandmen sowed their fields over again.
The late harvest was greatly blasted, so that in some places in this province,
there was not more than a fourth part of a crop.
In Maryland, Virginia, and the southern colonies, the grain was injured by a worm,
and much was given to the swine.
In some parts of North Carolina, besides this destroying worm,
a murrain prevailed among the cattle, so that many died;
and yet the people are not humbled.

"`Another occurrence I have thought memorable,
as it shows the necessity and advantage of humbly seeking wisdom superior to our own,
to direct in times of difficulty and trial, and also of acting in conformity thereto.
It was the case of Friends in New-York, most of whom,
under a prospect of trial and danger in that city,
sought a retreat on Long island and at Westchester, Hackensack, Newark, Elizabeth-town,
Rahway, etc.; places which afterwards were invested,
and put under greater trials than even the city itself.
A few who kept steady to their principles and to the guidance of Truth,
not being free to leave the city, remained during all the troubles,
and were upheld and preserved.
In the time of a great fire there, after the city was occupied by the king's troops,
wherein nearly a fourth part was burnt, the dwellings of Friends were preserved.
One family who could not be free to leave the city, lived near where the fire raged;
it was on each side of their dwelling, yet their house was preserved unhurt,
which was justly esteemed a providence of the Lord.
The Friend of that house, a descendant of the worthy Isaac Penington,
told me during last summer, that she could find no peace in thinking of removing;
and I believe she and some others profited under the dispensation.
In this province many have removed to Bucks county,
apprehending they should be more safe than in the city;
but the American army being ranged along the river from Bristol, as high as Tohiccon,
ravage and destroy almost all before them; wasting in many instances,
as much as they otherwise consume; so that little remains of fodder,
or food to some families.

"`The last summer, on the second-day of the week,
our meeting house in High street was forced open, and a large number of soldiers put in.
It appeared to be from a disposition in some to show their authority,
more than from real necessity,
for there were plenty of empty store houses near the river,
and other places much more convenient;
and it did not appear satisfactory to the officers and soldiers themselves.
Friends met on fourth-day,
to consider whether it was proper to alter the place of our meeting on fifth-day;
and great unanimity appeared, that it should be held there next day as usual.
A few Friends waited on some of the principal officers, who received them civilly,
and after being informed that the next day was the usual time
of our meeting for Divine worship at that house,
and that it was our desire to hold it there,
with other information respecting the nature of true worship,
and our differing from most others in the manner of performing it,
they proposed that way should be made for it.
We had the house somewhat cleansed,
and it was very satisfactory to find that a zeal appeared both in male and female,
young and aged, to attend the meeting, which was favoured.
On first-day the soldiers did not get away until Friends were gathering,
yet it was evident they gave as little interruption as they could.
The meeting was held to a good degree of satisfaction,
and those who had been instrumental to the house being thus occupied,
seemed ashamed of their conduct.

"`Twelfth month 19th; The monthly meeting for sufferings this day, was larger than usual,
though no particular notice was sent to the members;
but truth operating on the minds of Friends, they were brought together;
and apprehending that under the present exercise and trials,
it would be profitable to issue an epistle to encourage Friends in stability,
a committee was appointed, and the next day an epistle was approved,
and directed to be printed and speedily dispersed; being as follows:

[.embedded-content-document.epistle]
--

[.letter-heading]
To our Friends and brethren in religious profession, in these and the adjacent provinces.

[.salutation]
Dearly beloved Friends and brethren,

Our minds being renewedly impressed with a fervent religious
concern for your spiritual welfare and preservation in the
love and fellowship of the gospel of our Lord Jesus Christ,
the Prince of peace;
by the constrainings of his love we are engaged
to salute you in this time of deep exercise,
affliction and difficulty;
earnestly desiring that we may by steady circumspection and care,
in every part of our conduct and conversation,
evidence that under the close trials which are and may be permitted to attend us,
our faith and reliance are fixed on Him alone for protection and deliverance,
remembering his gracious promise to his faithful followers;
'`Lo, I am with you alway, even unto the end of the world.`'
And, '`As it became Him for whom are all things,
and by whom are all things, in bringing many sons unto glory,
to make the Captain of their salvation perfect
through sufferings;`' let us not be dismayed,
if we are now led in the same path.

As we keep in the Lord's power and peaceable truth, which is over all,
and therein seek the good of all, neither outward sufferings, persecutions,
nor anything that is below,
will hinder or break our heavenly fellowship in the light and Spirit of Christ.`"
--George Fox's Epistle, 1685.

Thus we may with Christian firmness and fortitude,
withstand and refuse to submit to the arbitrary injunctions and ordinances of men,
who assume to themselves the power of compelling others,
either in person or by other assistance, to join in carrying on war,
and of prescribing modes of determining concerning our religious principles,
by imposing tests not warranted by the precepts of Christ,
or the laws of the happy constitution,
under which we and others long enjoyed tranquillity and peace.

We therefore, in the aboundings of that love,
which wishes the spiritual and temporal prosperity of all men, exhort,
admonish and caution all who make religious profession with us,
and especially our beloved youth, to stand fast in that liberty, wherewith,
through the manifold sufferings of our predecessors, we have been favoured,
and steadily to bear our testimony against every attempt to deprive us of it.

And, dear Friends,
you who have known the truth and the powerful operations thereof on your minds,
adhere faithfully thereto, and by your good example and stability,
labour to strengthen the weak, confirm the wavering,
and warn and caution the unwary against being beguiled by the
snares of the adversaries of truth and righteousness.
Let not the fear of suffering, either in person or property,
prevail on any to join with or promote any work or preparation for war.

Our profession and principles are founded on that spirit which is contrary to,
and will in time put an end to all wars, and bring in everlasting righteousness;
and by our constantly abiding under the direction and instruction of that spirit,
we may be endued with the '`wisdom from above, which is first pure, then peaceable,
gentle, and easy to be entreated, full of mercy and good fruits, without partiality,
and without hypocrisy.`' That this may be our happy experience,
is our fervent desire and prayer.

Signed in and on behalf of the meeting for sufferings, held in Philadelphia,
for Pennsylvania and New-Jersey, the 20th day of the twelfth month, 1776.

[.signed-section-signature]
John Pemberton, Clerk.

--

"`On the 22nd and 23rd,
some skirmishes happened between portions of the
European and American armies not far from Burlington;
and during this week two Friends were taken up
and cast into prison for refusing to bear arms,
or work at the entrenchments making near the city.
Upon this, some Friends were verbally named at the meeting for sufferings on the 26th,
and the next morning had an opportunity with General Putnam,
and laid before him the grounds of our religious principles,
and why we could not join in warlike measures, nor consent to pay,
or perform any services, in lieu thereof.
A discharge was obtained for one of the Friends,
and the other had been released the day before
on the application of one not professing with us.

"`First month 4th, 1777; This week has been a bloody one.
On the 2nd instant, a battle was fought at Trenton, in which many were slain,
and lay unburied for several days.
The inhabitants had generally deserted their dwellings, and the town was much wrecked.
On the 3rd was a battle, said to be still more bloody, with numbers slain on both sides,
among others, Anthony Morris, son of the present Anthony.
On the 1st instant, our friend Thomas Watson, of Buckingham, a peaceable, quiet,
sensible man, was haled from his home by a number of armed men,
who came towards bed time, terrified the family,
and carried him before one called Lord Sterling, who sent him to Newtown;
where he was confined in irons, and his coat taken away.
And though through the lenity of some who watched him, it was returned,
yet heavy irons were kept on him for forty-eight hours,
and he was detained there three nights without a bed.
The general congress having recommended to those called the Council of safety,
to enforce the passing of their money, they have created heavy penalties for refusing it;
so that fresh sufferings seem likely to ensue.
This week great numbers of soldiers have died; the pestilential disorder increasing,
and the sick being greatly neglected, not having proper nourishment or nursing.

"`25th; Great numbers of soldiers have been buried during the past two weeks,
and many others came to the city from Virginia, Maryland, etc.,
looking like respectable farmers; and the reflection was sorrowful,
how many wives were likely to become widows, and children fatherless.
Our friends Mark Miller and Thomas Redman, of New-Jersey,
were imprisoned this week at Gloucester,
for reading in their meetings the epistle issued by the meeting for sufferings;
and several Friends at Mount Holly and Evesham, were taken up for refusing to bear arms, etc.

"`By the newspapers, it appears that the king proclaimed a fast in England,
that the people should lament on account of their sins,
and implore the Divine mercy and assistance on their arms, in this contest with America;
and on the other hand, in part of New-York, Connecticut, New-Jersey and Pennsylvania,
fasts and days of humiliation have been proclaimed,
to desire success for the arms of America.
The sense of such contrary and contradictory proceedings is very affecting.
That there is necessity to fast from all wrong things,
and to humble ourselves because of the great impiety and wickedness that abound,
are indeed to be acknowledged, and that we implore the Lord to have mercy on this land,
and to pity the people; but to abstain from labour one day,
and even on that day to sport and commit evil of various kinds,
and smite and despitefully use such as dare not join in this hypocrisy,
cannot reasonably be supposed to be the fast acceptable or available with God.
And how can it be supposed that we, as a religious Society,
could comply with such injunctions?
For thereby our Friends in England and Friends here,
might implore the same Divine Being for contrary and contradictory things.
Lamentable confusion and defection from the Spirit of Christ!

"`Our friends Mark Miller and Thomas Redman, were discharged,
after being confined eight weeks in Gloucester jail;
and Mark attended the meeting for sufferings,
and gave a comfortable account of the Divine support they had experienced.
They refused paying any fine or fees, and maintained their testimony with uprightness.

"`Fourth month 13th, being first-day of the week, and also on second-day,
inquisitors went about to know what provisions people had in their houses;
and by fresh resolutions from the Board of war, a large committee was named,
to take all provisions, bar-iron, etc.,
except what they shall deem a reasonable allowance for each family;
so that it appears probable much calamity will ensue.

"`27th;
News was brought that the English troops had destroyed a great quantity of
provisions laid up by the Americans at a place called Danbury,
in Connecticut.
Greatly indeed is it to be lamented that such
destruction and havoc should be made of what we may,
before long, be much in need of.

"`Feeling the gentle drawings of Truth on my mind,
I mentioned at the monthly meeting on sixth-day,
my prospect of attending the yearly meeting in Virginia, etc.;
and after deliberate consideration, several expressing their approbation and sympathy,
a minute was made for me.
Putting my affairs in order, and taking a solemn leave of my dear wife and many Friends,
I set out on the 6th of fifth month, 1777,
and at Wilmington overtook my beloved friend Samuel Emlen, jr., and his companion,
who were under a like concern.
We had a favourable passage across the bay, from Rockhall to Annapolis,
and on the 11th attended the meeting at West river, which was small,
and for the most part a suffering time, though more favoured towards the conclusion.

"`Fifth month 15th;
Attended the quarterly meeting held by adjournment at White Oak swamp,
which was favoured.
The business was conducted well, a growing concern appearing for the prosperity of truth.

"`17th; The yearly meeting was opened at Curies,
and finished on the 20th. It was attended by more solid Friends than I expected;
great unanimity appeared, and the business was conducted well.

"`Fifth-day, 22nd; Apprehending my mind drawn still further southward,
I proceeded to Petersburg, accompanied by S. Fisher and R. Pleasants,
and on the 29th reached our friend Thomas Newby's, at the head of Perquimon's river,
in North Carolina.

"`Sixth-day, went to the quarterly meeting of ministers and elders,
held at the Old-neck meeting house; which was a solid good meeting.
Next morning a committee of the yearly meeting for North Carolina,
met to consider a matter which was greatly distressing and afflictive.
Many Friends, from humane and honourable motives, had set their negroes at liberty,
and the assembly, so called, for this province, had made a law in the present month,
to take up and sell all that should be set free.
Immediately on the law being published, parties of men went about,
and taking up these poor creatures, carried them to Hartford jail;
which not only alarmed them, but greatly affected their former masters.
Friends appeared unanimous,
and a committee was selected to have the case particularly under notice,
and to act therein as wisdom should direct.
After this the meeting for worship came on, which was large, and many appearances therein.
But I found it my place to leach them silence by example;
there being a disposition to hear, and also with many to speak,
so that I thought both hearers and preachers had
occasion more deeply to learn and love silence.
Near the close of the meeting I was free to make some
observations to excite to such a disposition,
and to an awful retired waiting upon God, in every rank.

"`Second-day evening, again entered Virginia,
and on seventh-day went to the monthly meeting at White Oak swamp.
The first meeting was laborious and exercising;
the minds of many not duly attending to the important end of meeting,
being outward and indolent, though there were a number of concerned Friends.

"`Sixth month 8th; Went to the meeting at Wainoak,
to which came many not professing with Friends,
and a larger number of black people than I had
seen at any one meeting since leaving home.
They sat solidly,
and I was glad to find encouragement was given them to attend the meeting.

"`14th; I got safely home in the evening,
through the mercy and gracious dealings of the Lord, where I found my dear wife,
better in health than when I left her, and my friends generally well,
for which I have cause to be truly thankful.
I returned with an easy quiet mind,
which I attribute to the condescending goodness of the Lord,
preserving me in stability and resignation; for which I bless his name,
to whom the praise of his works belong.

"`Seventh month 19th; Our friend Joseph Moore, is in confinement at Trenton,
for refusing the test; and Isaac Horner for refusing the continental currency.
They are preserved in resignation and peace.
Richard Smith has also been confined a considerable time in Burlington jail.

"`On the 2nd day of ninth month, 1777, about two o'clock, P. M.,
three persons came to my house,
and informed me they had orders from the Supreme
Executive Council to take me as a prisoner,
I inquired, for what?
and demanded their authority.
One of them pulled a packet out of his pocket, and read a few lines of a long writing,
the amount of which was, that I was suspected of being inimical to the cause of America.
I pleaded with them for a considerable time,
on the injustice and oppression of imprisoning a man,
unless some crime was alleged against him.
They replied, they had orders, and must obey them.
I represented that I was an innocent man, and had not done anything I was ashamed of,
or to the injury of America.
They pretended that it was very disagreeable to them to execute such orders;
whereupon my dear wife told them, that Pilate washed his hands and said he was clear;
yet he was not so in the Divine sight.
Many serious remarks were made, but without effect,
though there appeared some tenderness in one of them.
Another said I should have a hearing when I came to the lodge,
where they had orders to take me.
They presented to me a paper, called a parole, and urged me to sign it,
to make my own house my prison, and be ready at the call of the council;
not to correspond with the enemy, as it was expressed; nor to do any act or thing,
by word or writing, prejudicial to the cause of America.
Knowing my innocence,
and that my religious principles would restrain me from
doing anything to promote the shedding of blood,
or to injure my country, I told them I could not sign such a paper,
as it would imply guilt, which I was free from.
They still urged my going with them; but I told them,
that as they had nothing justly to lay to my charge, and as my house was my own,
and I was a free man, I could not consent to comply with their unreasonable demand,
and could not leave my house without being forced.

When they saw I was resolute,
endeavours were used to prevail on my wife to urge my
going quietly with them but she was staunch and upright.
One of them then went and brought a guard of about ten men,
whom they had left in the street; and again urged my going with them.
But I still maintained my right as a freeman and a Christian.
He then took me by the arm, and said he would force me to go;
but I would not move from my seat.
The men he had brought into the house seemed averse to meddling with me;
but this man insisted that they should do their duty;
so I was lifted by two of them off my seat and led to the door.
My wife insisted on going with me; so my friend John Parrish, taking her by one arm,
and myself by the other, we supported her;
and with these soldiers we were conducted to the masons' lodge.
Though I believe she had not walked so far, at once, for two years, and was very poorly,
yet she was sustained, both in mind and body.

The people seemed generally serious, and many affected,
when we came to the lodge and were conducted up stairs.
Before we were put into a room, the person who brought the guard into my house,
demanded the keys of my desk.
I told him I thought he had no right to make such a demand, and I would give him none.
He then asked my wife, and she also denied him.
He then said he would break the desk open; and so returned to my house,
guarded by the same men; they broke open my desk,
and took out the rough minutes of the meeting
for sufferings for seven or eight months past;
and in other places which they searched, they found some other meeting papers,
and two bundles of manumissions for the freedom of slaves, which they took away.
But in all their searching, they could not find anything to their purpose;
and though they condemned Friends for publishing epistles,
especially the last Christian exhortation from the meeting for sufferings,
yet they now republished it themselves, at a time more critical than any heretofore.

"`On my coming to the lodge, I met there my brother James, and several other Friends.
We were favoured with support in our persecution;
though that evening and night was to me a season of trial of spirit,
and I had little sleep.
Yet in the morning my heart was tendered,
and from that time to the time when we were removed from the city,
I was preserved in a steady resigned state of mind.

"`Fifth-day, the 4th; Brother Israel, John Hunt and Samuel Pleasants,
were brought as prisoners, so that our number was twenty-three.
Previous to brother Israel's coming,
he and John Hunt and Samuel Pleasants had presented a remonstrance to the council,
and demanded a hearing as their right; but they were not admitted,
and informed that they could have no hearing,
and so were conveyed to the place of confinement.
Afterward we also prepared and sent remonstrances to the council and congress,
but could not obtain a hearing.

"`On first-day, the 7th, having had much company for several days past,
the inhabitants being affected with the unjust conduct pursued towards us,
we requested that we might be more retired;
and had a favoured opportunity in humbly waiting upon Almighty God,
so that the hearts of many were tendered,
especially in time of solemn prayer and supplication,
for the support and preservation of ourselves and our families.

"`On third-day, we sent for some of the persons who were instrumental in our being taken,
and demanded of them whose prisoners we were?
One of them said that none of us were his prisoners;
and the other did not own any except my brother Israel, John Hunt,
Samuel Pleasants and Phineas Bond.
In the afternoon an order from council appeared, for our removal to Staunton,
in Virginia; upon which we wrote another remonstrance against their proceedings.
Next day we were permitted to go homo to prepare for our journey,
and on the following morning I had a solid
opportunity in quiet retirement with my family,
and parted with my beloved wife in tender affection.
We were supported in this close trial beyond expectation,
the saying of the apostle being verified in my mind,
'`None of these things move me;`' being enabled to resign my
life and my all to the disposal of Divine Providence.
About eight o'clock I returned to my prison and continued until afternoon,
when two men came and informed us they were appointed to conduct us to Reading.

We demanded a sight of their orders, which they refused.
At length, after much altercation, one of them read a paper,
but another paper containing further orders, he absolutely refused to read,
or to give us a copy of it.
We entered a protest, and called in several inhabitants to witness it:
they were also informed that messengers were despatched to the chief justice,
for writs of habeas corpus; but they paid no regard to that.
The wagons, etc., being before our prison, we were at length forced out.
Many hundreds of people were ranged along the alley, some of them much affected;
and many poor blacks, as well as others, after I was in the wagon, shook me by the hand,
being affected with our hard treatment.
We were paraded through Third street, until we passed out of the city,
when the town-major and the guards generally left us;
though a few went with us to the falls of Schuylkill.
The next day we reached Pottsgrove.

"`Seventh-day, about eight o'clock in the evening, a guard of men came from Reading,
much incensed against us, who insisted on our setting out this night;
but after a considerable time we were permitted
to Stay till seven o'clock in the morning.
About that time the next day, the messengers despatched for the habeas corpus,
met with us, and our guides were notified thereof; but still they hurried us to Reading.
Here we found the people's spirits greatly enraged,
and many appeared to be in a wicked disposition;
but through the good providence of the Lord we were preserved from injury.
My father-in-law, Isaac Zane, being there, came up on my alighting from the carriage,
to salute me; but was laid violent hands on, and abused; and so was James Starr.
But after a while their wrath in part subsided,
and next day several Friends were admitted to see us.
The evening we arrived, we had an opportunity of religious retirement,

"`I was poorly all the time we were at Reading, which was during this week;
and although the chief justice had granted writs of habeas corpus for us all,
yet after our persecutors in the city heard of it,
they obtained from the assembly an act to supersede them,
and indemnify all persons concerned in our removal, contrary to reason and equity,
and even their own constitution.

"`First-day, 21st; Being guarded by the sheriff and some others, we proceeded to Lebanon;
and next day reached Harris's ferry, on the Susquehanna.

"`Third-day morning we crossed the Susquehanna, our carriages being driven over,
and some of us going in canoes.
Great had been the industry of our adversaries
to prejudice the minds of the people against us,
by lies and forgeries; yet the Lord in great condescension opened a way for us,
and softened the hearts of many; blessed be his name,
for his goodness both in preserving our minds calm and resigned,
and seasoning them with his grace.
In the evening we entered Carlisle without molestation.

"`Fourth-day afternoon we had a religious opportunity in awful retirement,
to wait upon God for the renewal of strength and comfort from him; which,
through his great mercy, were in measure vouchsafed.

"`Sixth-day morning we set out from Carlisle and reached Shippensburg in the evening.
This had been mentioned as a place where it was most likely we should be roughly treated;
but though the spirits of some seemed disturbed, yet on a little opening our case,
they were changed, and we were well accommodated.
Before supper we fell into awful silence,
and a concern came upon me to commemorate the goodness of God,
to thank him for his mercy,
and to pray for the continuance of his kindness to myself and beloved friends present,
and that he would condescend to remember and preserve our beloved connexions,
from whom we were cruelly separated.
Much brokenness of spirit appeared amongst us.

"`Seventh-day reached H. Pawling's, near the Maryland line,
and the next morning we had a seasonable time of solemn worship,
in which our minds were softened by the mollifying virtue of truth,
and the Divine witness was reached in many hearts.
The sitting concluded with fervent prayer for
ourselves and for this once highly favoured land.
Previous to leaving our own province,
we again protested against their unwarrantable proceedings; as also at Potomac,
on leaving Maryland, crossing the river at Watldns's ferry.

"`Second-day, 29th; Near Winchester I met a letter,
by which I found the inhabitants had imbibed some prepossessions against us;
yet we entered peaceably.

"`Third-day, the lieutenant alleged that the papers presented to him were so confused,
that he could not determine what to do with us.
About noon some turbulent persons assembled,
and demanded very peremptorily that we should be ordered out of the town,
threatening to force us out that afternoon.
The lieutenant moderated them by promising that a guard
should be kept at the doors of the house where we were,
and that he would despatch a messenger to congress, and another to their governor,
respecting us.
We endeavoured under this trial to gather into silence,
and my mind was preserved above the fear of man,
having been helped to resign myself and all I had, with my dear wife,
to Him who gave me breath and being.
The power of the Highest is able to stay the
wrath of man and preserve his dependent people;
blessed and praised be his holy name!

"`Fourth and fifth-days, an address to the congress,
and also one to the governor of Virginia, were prepared by us,
setting forth our case and enclosing our publications.

"`First-day, tenth month 5th; This morning we sat down together,
accompanied by Philip Bush and his wife.
Several of the guards were in the entry, and some others, white and black,
about the windows.
Our dear friend John Hunt, had a clear and lively testimony,
and the meeting concluded in prayer and acknowledgment of the goodness of the Lord.
In the afternoon we again assembled, and after a considerable time spent in silence,
our friend John Hunt stood up with these words: '`Say to the righteous,
it shall go well with him; but woe to the wicked, it shall go ill with him;
for the works of his hands shall be given him;`' asserting the
certainty of future rewards and punishments.
He opened also the early appearance of sin, the cause of the fall,
and the nature and difference of the offerings of Abel and of Cain;
and expatiated thereon, in a clear and lively manner.
The lieutenant was present at this meeting,
having never before been at any meeting of Friends,
and was much a stranger to us as a people.

"`Seventh-day, about noon the guards left us,
and we were without any the remainder of the day.
After breakfast nine of us took a walk two or three miles round, which was refreshing.

"`First-day, 12th; This morning we assembled in order for Divine worship, and some men,
brought from a distance as a guard, came in and sat with us;
the time was spent mostly in silence, and part thereof was exercising.
I had to make a few remarks at the close, respecting the nature of Divine worship,
and the necessity of labouring for a qualification to perform it in an acceptable manner.
The men who came for guards, thought there was no necessity for their continuance,
and went home again without license.
In the afternoon several Friends came;
but some persons of an envious disposition appeared disturbed,
and objections and discouragements were made to the Friends slaying to sit with us.
However, they finding most ease and freedom so to do, and risk the consequences,
we sat down and had a favoured opportunity.
The meeting concluded without molestation, and Friends departed in peace.

"`Fifth-day,
our company were notified that indulgence was allowed
us to ride or walk any distance within six miles round,
"`First-day, 19th; Our large room was pretty well filled,
and the Lord condescended to own and favour the gathering.
It was a solemn comfortable season,
and the doctrine of Christ was preached and flowed freely,
to the instruction and edification of many.

"`Sixth-day; This evening the houses in the town were illuminated,
and other tokens of rejoicing manifested,
for the capture of General Burgoyne and five thousand eight hundred men under him.

"`Eleventh month 26th; We held our religious meeting as usual.
Our friends John Parrish, on a visit to us, and John Hunt, had acceptable service;
but to me it was for the most part a season of deep poverty;
and I was ready to apprehend that the anxiety of some of our brethren
to be informed respecting matters relating to our outward affairs,
tended to exclude that good which is sometimes vouchsafed.

"`Fifth-day, I went to the preparative meeting at Hopewell,
which was a season of exercise and poverty.
Though there is an agreeable appearance of Friends, yet the minds of many are outward,
and rest in a form.

"`Twelfth month 3rd; In our meeting held this morning,
my heart was contrited and deeply humbled,
in a fresh commemoration of the tender dealings
of the Lord with us and our dear connexions,
in supporting and preserving under the various trials
and exercises which have attended since our separation;
and fervent desires were excited for dedication of heart, and that,
if permitted to return home,
we might not forget such gracious and tender dealings with us.

"`9th; Being the adjourned monthly meeting of Hopewell,
and a large committee meeting previously this morning,
I went to it with my brothers and H. Drinker,
and joined with Friends in a solid conference on the subject
of the first settling of the lands in these parts,
a doubt existing whether the natives had been fully satisfied for them.
The committee appeared unanimous in recommending to the
monthly meeting that a subscription be entered into,
to raise a sum to deposit under the care of the meeting for
sufferings and a committee of Hopewell monthly meeting,
to be applied for the benefit of the descendants
of the native inhabitants formerly seated here,
if to be found, or any others where it may be truly useful;
which report the monthly meeting approved,
and referred for further consideration to the next meeting.

"`17th; An order was received from the board of war to remove us to Staunton;
may the Lord continue his mercy to us.

"`18th; Guards were placed yesterday at the front and back doors of our quarters,
and we were ordered not to go out; but they were this afternoon released;
yet we were put under stricter confinement than for some time previous.

"`26th; In the afternoon we were visited by our friends William and George Mathews,
Isaac Jackson and Thomas Millhouse, and spent some time in solemn retirement.
Our spirits were contrited and comforted in a sense of the Lord's goodness,
and the preciousness of that unity which is experienced by those who know the truth,
and are concerned to live under its influence and operation.

"`First month 8th, 1778; More liberty to walk abroad for exercise and air.

"`13th; A colonel in the American army, who lately returned from camp, visited us,
appeared kindly disposed, and thought our case hard,
especially as we had never had a hearing, or been convicted of any crime.
While he was with us, another colonel came and showed a letter,
directing the orders of the board of war to be strictly put in execution.
He at the same time placed a guard at the front and back doors of the house.
We represented that the order from the board of war did not direct this;
and that there was no necessity for it,
for that he knew we had not given them much trouble.
He said he must obey orders, and that we must be removed towards Staunton.
The other colonel said he would stand engaged for us, as did our landlord,
who also said there was no need of a guard.
After about twenty minutes the guard was ordered away,
and our landlord came in and said he had engaged we should not go out, nor be visited.
This is the third time that guards have been hastily set over us.
Thus we are permited to be proved; yet through all, our minds are kept pretty quiet;
blessed be the Lord.

"`15th; A person waited on us, and acquainted us,
that he had attended to our case as fully as he was capable,
but other business being before congress, ours was deferred;
that some members appeared kindly disposed,
some were under a fear of disclosing their sentiments, and others warmly against us;
though he did not find that they had anything against us,
except the publications of our religious Society, that is,
the advice to our members to maintain a conduct
agreeable to our religious principles and profession.
He brought nothing to revoke the order of the board of war;
but upon conversing with the colonel who has charge of us,
he was willing to defer sending us away, at least for a week longer,
or until we hear further from congress.

"`16th; My mind for the week past has been very poor,
having been much hindered from that retirement
which I find needful for me to be exercised in.

"`19th; Andrew M'Coy called on his way from Pipe creek,
and acquainted us that nine Friends were named
to attend the congress at York on our behalf,
and that four Friends were appointed particularly to assist us,
in case we are removed to Staunton.

"`First-day, 25th;
Our religious meeting this day was attended by
our friends John Hunt and Edward Penington,
quartered in the country.
Our dear friend William Mathews,
arrived from Yorktown with an order from the board of war,
for the suspension of their former order respecting our removal,
which gave us some relief.

"`28th; George and William Mathews attended our meeting, which was held mostly in silence.
Towards the close I had to commemorate the gracious dealings of the Lord with us,
in affording us, for a considerable time since our exile,
the cup of consolation for our encouragement,
and to strengthen and support us in stability and faith,
though we had latterly experienced a season of drought and poverty;
under which dispensation I desired we might endeavour to profit, and not grow slack,
or insensible of the soul's needs;
being watchful that the mind is not permitted to wander,
but humbly to wait until the Lord is pleased to knock; and by thus waiting,
be ready to open, and again sup in his Divine presence.
The meeting was solid, and our spirits were somewhat refreshed.

"`Second month 2nd; Went with some of my companions to the monthly meeting at Hopewell,
which was large,
and our friend John Hunt had to speak of the judgments of the Lord in this land,
mentioning that he had heard, as with his inward ear, a voice proclaiming mourning,
lamentation and woe, unless the people repented and sought the Lord;
and remarked how opposite the revelling, dancing, balls, etc., now prevalent,
were to that humiliation which ought to be experienced.
He mentioned also,
that he apprehended he should not have the like opportunity again among them,
though he should leave that to Divine Providence,
and concluded with expressions of comfort to the truly religious.

"`Fifth-day, my dear father Zane arrived from Yorktown,
where he and several other Friends had spent about ten days, labouring for our release.
They were heard by a committee of congress,
and although they did not obtain their desire,
yet they had opportunity to obviate objections,
and manifest that the charges against us were false and groundless.
What was objected, was rather against the body of Friends than individuals.
One matter they pretty generally urged, was that Friends did not join with them,
or approve their measures.
Friends replied that it was our concern to promote peace,
and inculcate the principles of Christ; while it was theirs to promote war;
and therefore of course they must be opposite; to which they were silent.
It was comfortable to find they could not make out anything criminal against us.
Several wished us at home,
but granting a discharge would make them appear criminal in taking us up.

"`First-day, soon after the afternoon meeting broke up, we dropped into solemn silence,
and the Lord condescended to cover our minds with his love, and season them by his grace.
Both myself and father had to express counsel
and encouragement to stability and faithfulness,
and a caution to beware of giving way to impatience.
My heart also was engaged in prayer to the Author of our being,
that his mercy and goodness might be continued to us and our beloved connexions,
that we might all be preserved in his pure and holy fear, and under a sense of his love;
and that neither heights nor depths, things present, nor things to come,
might separate us from his love.
Our spirits joined in commemoration of the Lord's gracious dealings;
magnified and praised be his great and adorable name, and Christ Jesus the Lamb,
both now and forever.

"`Second-day, I rode with father Zane as far as Shanandoah,
on his return to Pennsylvania;
and then called and spent a short time with some
poor negroes in their quarters near the river.
What was said to them they received in love, and I returned towards my prison.

"`Third-day, Dr. Thomas Parke and James Morton arrived with letters from our friends,
and I was comforted in reading a letter from my dear wife,
being thankful for the Lord's goodness to her and me, in this season of deep exercise.

"`Fifth-day, I accompanied Dr. Parke and James Morton to Hopewell meeting,
at which were our friends Thomas Bailes and William Robinson,
who had gone about three months past with an intent to
pay a religious visit to the Delaware and other Indians;
but on their way they were stopped near a place called Sewickly,
carried prisoners to Hanna's town, and there kept for about twenty-seven days.
At first the people were very violent, and threatened their lives;
but after a time they became more moderate,
and even consented to their having a religious meeting.
They were shortly after discharged, the people agreeing to burn their court order;
but telling them that if they proceeded, they would be stopped at Pittsburg.
There is a great ferment at present among both the whites and the Indians,
on account of the injuries these poor people have received,
and the cruel murders committed on some of them, particularly near Pittsburg,
about two months since, upon the sons of Corn-stalk, the chief of the Shawanese,
and a man of great note among them; and on these considerations,
the Friends found freedom to return,
though Thomas expressed that his love and concern for the poor Indians still continued.

"`Second month 25th; I went to visit my beloved friend John Hunt,
quartered in the country, who had been very ill.
He expressed his joy at seeing me and my brother Israel, and we dropped into silence;
in which time our hearts were contrited, and John expressed that he was broken in spirit,
and thankful in being renewedly made sensible that the Lord had not forsaken him;
that for some weeks it had been a time of great inward stripping and baptism;
and he had a prospect that an exceedingly trying time would attend Friends as a people,
more deeply exercising than they had ever experienced,
and our deepest sufferings would be from some of the same family;
that many would make submission to this and the other,
but that the poor and some weak ones would be strengthened;
and he desired us to notice it.
He added, that under his present exercise, he had made a narrow search,
and desired the Lord to manifest, if in any particular he had done wrong,
or was deficient; nothing however, in particular was manifested,
but that there was need of becoming still more pure and holy,
and inwardly refined throughout.

"`28th; Our friend Thomas Gilpin is ill, and reduced to a very weak state,
but favoured with his understanding, and very calm and patient.

"`First-day, third month 1st; After our afternoon meeting broke up,
our banished friends being more select, we again dropped into silence,
and I had to press my beloved brethren to continue watchful and steady,
and not to look too much outward, nor be attracted too much homeward,
so as to bring them into danger of joining with things
that might not prove peaceful to their minds,
or to the honour of the cause and testimony of truth, for which we suffered.
Our friend Thomas Gilpin continued calm, resigned and sensible,
and quietly departed between twelve and one o'clock.
In his sickness he was disposed to be retired and quiet,
and several times towards his close, requested to be kept very still;
and I doubt not he was inwardly exercised in a preparation therefor.

"`This day is six months since I was first arbitrarily deprived of my liberty;
but I have been hitherto upheld by an invincible Divine power.
Oh! may I thereby be kept still, under all trials,
so that the Lord's name may be magnified.

"`Fourth-day, John Hunt seemed better, though he had but little sleep last night.
He expressed to my brother Israel and me,
that he had thought much of some expressions of John Woolman's,
in a time of great exercise and affliction, respecting true prayer; that it was deep,
and the place thereof was a precious habitation;
that it was not to be truly come at in the commotions of the mind, but in pure stillness;
adding, that at times he had been troubled with strange imaginations and unsettlement,
but that he had laboured after a state of resignation,
and he thought he could at times say, '`not my will, O! Lord, but yours be done.`'

"`22nd; Our friend John Hunt, had his leg amputated,
which he bore with Christian fortitude and patience.
I spent some hours with him, and found him calm and easy.

"`27th; I visited two persons, both on beds of languishing;
one with a pleuritic disorder,
and the other with the same fever that has attacked several of our captive brethren.

"`Fourth month 1st; My worthy friend John Hunt, departed about ten o'clock last evening.
On fifth-day a large number of Friends attended the funeral,
and some not professing with us, who appeared much affected;
his religious labours having had a place in the minds of many.
During his illness he was preserved in great patience and resignation,
and favoured with his understanding,
except that during two or three days before his departure,
he appeared somewhat at a loss at intervals; but sensible at the close.
He was a wise and experienced minister and elder,
who will be greatly missed in the church.

"`14th; A messenger arrived from Lancaster,
to inform us that the congress had ordered the
board of war to deliver us up to Pennsylvania,
and that two men were on their way here, to conduct us to Lancaster.
And on the 18th, our escort having arrived,
we engaged in preparing for our journey homewards.

"`On the 19th, after spending a short time in solemn retirement, we set out;
and on fifth-day crossed the Potomac at Nowland's ferry.

The wind being very high, and two poles breaking,
our passage was somewhat difficult and dangerous; but through the Lord's good providence,
we got safely over and reached our friend Richard Richardson's, near Fredericktown,
about twelve o'clock.
The next day we arrived at Yorktown much wearied,
but were cordially received and entertained.

"`Seventh-day, Henry Drinker and.
myself visited a young man confined in jail for his religious testimony against war,
who appeared in a tender disposition.
We found that our persecutors had not yet quite relaxed in their enmity.
James Pemberton and Henry Drinker waited on the president of the council,
informed him of our being here, and desired that we might be restored to our families;
he replied that the council would meet and consider our case.

"`Second-day; council met, and after spending some hours, came to the following result,
which was delivered to us: '`

[.embedded-content-document.court-order]
--

[.signed-section-context-open]
In Council, Lancaster, April 27th, 1778.

The case of the prisoners brought from Virginia, and now in this borough,
being considered,-- thereupon ordered--that they be immediately sent to Pottsgrove,
in the county of Philadelphia, and there discharged from confinement;
and that they be furnished with a copy of this order, which shall be deemed a discharge.

[.signed-section-closing]
Extract from the minutes,

[.signed-section-signature]
Signed, T. Matlack, Secretary.

--

"`This was far short of what we demanded; which was,
to be reinstated in our families in the manner in which we had been wrested from them;
but Timothy Matlack gave us to understand that the council would not do more,
and said they were determined to do no act that should
frustrate the operation of a law the assembly had made,
to confiscate the estates of those who went into the city.

"`30th; We reached the city without molestation, to the joy of our friends,
and I hope with thankfulness to the great Preserver of men.
May I ever remember the gracious dealings of the Lord with me during my exile.
He was indeed my preserver through various conflicts and trials,
the lifter up of my head, and my merciful sustainer,
in affording me peace and the softening virtue of his Divine presence,
which settled my mind in resignation to his holy will.
I found my dear wife as well as I could expect; blessed be the great Name, says my spirit.

"`First-day, fifth month 24th;
It became my concern this morning at our meeting in High street,
to advise Friends to give attention to the voice
of Divine Wisdom communicated to the mind,
as a more sure intelligence than outward counsel;
that our reliance being on the Lord alone, his interposing mercy might yet be towards us.
It was a favoured meeting, and Samuel Emlen being there, corroborated what I said.

"`Sixth month 17th; The British army remaining in the city,
were ordered to be ready by six o'clock in the evening, and lay along the redoubts, etc.,
all night.
Early in the morning of the 18th, they marched to Gloucester point,
and went over to New-Jersey.
Some of the American light horse then entered the city,
and large numbers of soldiery and of the former inhabitants,
came in by the 20th. The English went away
without suffering the inhabitants to be pillaged,
or any further destruction of property to be made, and the Americans came in quietly.

"`28th; Near Monmouth court-house, was a battle between the contending armies,
and it being very hot weather, many fell through the excessive heat,
as well as by sword and gun.

"`Seventh month 18th; I visited Christopher Sower,
who had been taken prisoner by the Americans, stripped naked,
and painted in different colours; confined at the camp for some time,
and at length released with a Pew rags given him.
The man that painted him and had part of his clothes,
was a few days afterwards seized with a violent pain, and died in great misery,
desiring that those clothes which he had taken from Christopher,
might be taken from his body; which being done, he expired.

"`Eleventh month 2nd; I visited two persons in prison,
and found them in a thoughtful disposition, and tender.

"`Fourth-day;
Friends in the city were sorrowfully affected with the melancholy scene enacted,
in putting to death the two persons above mentioned.
They appeared resigned, and died without a struggle.
Their countenances when deceased, looked like those of persons in an easy sweet sleep.
The burials were very large, and their execution alarmed and affected the inhabitants,
as neither of them had committed anything worthy of such treatment.
But their friends were comforted with a belief that they were gone well,
and they were strengthened to forgive their persecutors.

"`Third month 22nd, 1779; An English transport vessel,
with soldiers from Halifax for New-York, ran ashore and bilged, off Egg-harbour.
The people on shore observed their distress, and got ready with boats,
to go off to their assistance; but a privateer, lying near the vessel in distress,
would not allow it.
At length, however, one man, captain Job Carr,
whose heart yearned with compassion for them,
said that let the consequences be what they might, he would go to their relief.
Accordingly, with a son of Joseph Maps`', he went in his boat, and saved about forty-two;
but about one hundred and forty perished, who might generally, if not all,
have been saved.

The people on shore saw the poor creatures falling from the shrouds, as death,
through the severity of the cold, seized them.
A woman was afterwards found with a child tied to her, both drowned.
Oh! cruel and sad effects of the spirit of enmity, hard heartedness and war!
May the Lord, in his infinite mercy, soften and take away the stony heart,
and promote a more Christian spirit than is now generally prevalent.

"`Fourth month 11th; At our meeting in High street, were several libertines,
and such as had been disowned by Friends, and some not professing with us.
Our beloved friend Samuel Emlen, jr., was zealously concerned in public testimony,
beginning with the words of Jeremiah: '`My eye affects my heart,
because of all the daughters of my city;`' and after
some expressions to the dissipated daughters,
he called upon the women, in the words of the same prophet:
'`Yet hear the word of the Lord, O! you women,
and let your ear receive the word of his mouth; and teach your daughters wailing,
and every one her neighbour lamentation;`' repeating these words several times,
and proclaiming a day of wailing and bitter lamentation,
that he that rides on the pale horse, whose name is death,
would invade the habitations of some,
and that calamity and distress would attend many parts of this once peaceful land;
even this once peaceful and joyous city, the place of his birth,
if humiliation and turning to the Lord did not take place.
He was favoured with energy and power,
and was very close against the workers of iniquity,
but comfortable to the true seekers after God.

"`On the 22nd of this month, my dearly beloved brother, Israel Pemberton,
departed this life, aged nearly sixty-four years.
He had been much broken in his constitution, for about three years.
In his banishment to Virginia, with others of us, in 1777,
in which he remained a prisoner nearly eight months,
separated from an aged and endeared wife, beloved children and grandchildren,
and hurried in a violent manner from home,
among spirits exasperated by misrepresentations, he was endued with constancy,
and a good share of fortitude and patience.
The separation, however, nearly affected him, being a man of tender feeling and sympathy.
On his return he found his wife in a poor state of health,
and from the time of her departure he visibly declined;
and spent his time among his friends, as one sensible that his own departure drew near.
He appeared in a very tender frame of mind, and in the fore part of his illness,
expressed that he was much favoured in spirit.

For some hours before his departure he seemed to be free from pain,
and quietly departed without sigh or struggle.
At this awful season, a great solemnity and sweet calm attended;
and I doubt not he is gone to join the spirits of the just made perfect,
where the wicked cease from troubling, and the weary are at rest.
He was a man of good natural endowments, of a large understanding,
which was sanctified and rendered useful,
both with respect to temporal matters and those of greater importance.
He was very weighty on all occasions that affected the reputation and testimony of truth;
a true friend to the poor and needy in their distress, a great advocate of the negroes,
and a promoter of various public institutions, particularly of the Pennsylvania hospital,
of which he was a manager from the beginning.
All ranks of people appeared affected with his death,
and a very great concourse attended the funeral.

"`On the 8th of fifth month, I left home with the unity of my friends, weak in body,
yet under a solid covering of truth, accompanied by my father-in-law, Isaac Zane,
and taking meetings in the way, reached the quarterly meeting at Salem,
which was very large, and attended by some well concerned Friends;
though a more general godly zeal and true religious concern are much lacking.
Notwithstanding we have experienced the rod, and much affliction has attended our land,
yet greater purity and refinement, and more redemption from the spirit of the world,
are still needed.
We went from there to Greenwich, Cape May and Egg-harbour,
and reached home on the 31st. In this journey I was sustained through abundant mercy,
and favoured with a steady mind.
We had to observe the pernicious effects of war and strife,
by which many are involved in great calamity.
On the coast of Cape May and Egg-harbour, several vessels have lately been cast ashore,
and become a prey to the people, many of whom, by the booty of spirituous liquors,
corrupt themselves, and are led further distant from God and the teachings of his Spirit;
which, if regarded, would lead to compassion, meekness and purity,
and would destroy the spirit in man which delights in another's overthrow.
Friends appeared to keep clear of being defiled with the spoils of war,
either by purchasing the goods or otherwise.

"`Eleventh month 4th; At our meeting for sufferings, after weighty consideration,
a memorial was agreed upon to the assembly of Pennsylvania,
to express our sense of the grievous laws they have passed,
oppressive to tender consciences;
particularly respecting our schoolmasters in this city
being discouraged from continuing their schools,
in consequence of a further supplement to the test law.
Friends were received favourably, and such a weight and solemnity attended,
that an awe prevailed over the members during the reading of the memorial,
and on the observations made by some of the Friends.

"`Twelfth month 7th;
At Wilmington I heard of the death of a colonel in the American army,
who had been a schoolmaster in that town, and very active in distressing Friends.
On the 27th ultimo, being at the house of a Friend, he used, as it is said,
some endeavours to ensnare him; and at length queried of the Friend,
what he thought of General Washington?
He replied that he had heard he was a good soldier.
This raised the colonel, who compared him to Christ Jesus our Lord;
and mounting soon after, rode a little distance;
but his horse threw him and broke his scull, and presently he died.
He had, but a few days before, taken possession of a confiscated estate; and it is said,
obliged the man's wife to leave the place.
His sudden death, after such blasphemous expressions, was very affecting.

"`30th; Hearing that a master of a vessel, Jonathan Esthill, a Friend,
had lain in prison about three weeks, I went and had an opportunity to see him,
and obtained liberty to bring him to my house.
He was owner as well as master, and had been taken between Augustine and Antigua,
by an armed ship, called "`The Jay,`" fitted out from this place;
and thus lost nearly all for which he had been working hard for many years.
He is a steady, sober Friend, of the north of England.

"`First month 28th, 1780; Our friends John Parrish and Samuel Hopkins,
returned from a religious visit in North Carolina;
they gave an account of a Friend who has suffered
greatly for his religious testimony against war.
Being drafted to stand guard over part of Burgoyne's army, prisoners in Virginia,
he could not comply, and was therefore tried at a court martial,
composed of young officers; who sentenced him to have thirty-nine lashes,
which was executed in the presence of some hundred spectators.
Forty stripes were very heavily laid on, by three different persons,
with a whip having nine cords; but the Friend, though much torn, was supported;
and persuasions and threats were afterwards offered in vain,
to prevail on him to yield to service.
It was thought that the faithfulness of this
Friend and the severe suffering he underwent,
spread the testimony of truth.
The procedure gave great disgust, and one captain, it was said, laid down his commission,
declaring that if innocent conscientious men were thus treated,
he would not serve any longer.

"`Seventh month 20th; At the meeting for sufferings this day,
a number of Friends were appointed to labour for
the bringing back of Benjamin Gilbert and family,
taken captive among the Indians.
We met in the evening to confer on the subject,
and concluded to apply to the president and council for
liberty to send a person by land to Niagara,
or to obtain conveyance of a letter from New-York to Canada, round by Quebec.
The next morning we applied to the president, but he put difficulties in the way.
At length, after saying that it would look partial, to send for one family,
and not for others who were captives,
he promised to lay our statement of their case before the council.
In the afternoon he referred us to a committee of council, on whom we waited.
They represented the partiality of the proposal.
We reminded them, that these were our brethren,
that if every religious society were to exercise the same care,
the thing would be general; that it was our wish that all captives might be released,
and it was well known that we had ever manifested a
benevolent disposition to those under trials,
and had in former wars been at much expense and used
great endeavours to relieve many who were in captivity,
and obtained their release.
After we left them we conferred together,
and the next day represented the matter to council,
who concluded not to allow of our sending.
On the 28th we obtained the endorsement of a letter, by Timothy Matlack,
to send to New York, to forward some supplies to this afflicted family,
and the letter containing an anxious desire for their relief,
we hope it may open some way for them.

"`Eighth month 12th; The several testimonies and epistles issued by Friends,
which were published by our persecutors in 1777,
to justify the proceedings of the congress and council,
against those Friends who were then sent into banishment,
now appeared again in the newspapers, having a little piece prefixed to them,
to excite fresh enmity against Friends.
May the Lord disappoint the evil machinations of the wicked,
and afford faith and patience to his people to bear reviling and reproach,
for the name of Christ and his truth.

"`On the 24th,
Friends published '`A short vindication of the religious Society called Quakers,
against the aspersions of a nameless writer,`' in the Pennsylvania Packet,
of the 12th instant.^
footnote:[This Vindication was published in the Pennsylvania Packet, "`September 2nd,
1780.`"]

"`Ninth month 23rd;
Our yearly meeting began and continued until the 29th. It was a season of favour,
and held in solemn quiet, great peace and brotherly love.
The city, during this time was quiet; but the last day there was a stir made,
and it appeared as though evil was designed against Friends.
The effigy of Arnold was carted about with men on horseback, and a great rabble following.
They advanced towards Friends' meeting house in Pine street; but on the way, it is said,
hearing that the meeting was broken up, they turned down Spruce street.
Having occasion after meeting, to pass along Front street and by the coffee-house,
where a number of people were collected, some of them appeared very wrathful,
and cursed us as we passed, Henry Drinker being with me.
But the Lord, whose interpositions in many instances have been marvellous,
disappointed the evil designs of bad men, which might have been manifested,
had not the meeting concluded.

"`Having felt of late an increasing concern to cross
the great deep on a visit to my friends in Europe,
though I had been tor some days very poor and low in mind,
and did not know that I should have life and strength to open it to Friends,
yet at our monthly meeting on the 29th of twelfth month,
some time after the business was entered upon,
I felt as though it would be safest for me to make the attempt,
and was strengthened to do it in a solid manner; beginning with the words of Christ;
'`He that seeks to save his life, shall lose it;
but he that lays down his life for my sake and the gospel's,
the same shall save it.`' A solemnity spread over the meeting,
and after a time of solid waiting, several expressed their unity,
and a committee was appointed to prepare a certificate.
This was what I scarcely looked for, considering the smallness of my gift,
but the Lord is able to prepare the way for his own work.

"`Second month 3rd, 1781; Jacob Lindley, who lately returned from Carolina,
relates that some Friends, about ten in number,
were forced by the soldiery along with them,
when about to combat the British army in that country; and when they approached,
and were likely to fire at each other, these Friends, who refused to bear arms,
were put in the front, both parties being near, with their guns presented.
One of the Friends desired his brethren to do as he should,
and he fell flat to the ground, as did the rest.
A fire immediately ensued,
and the Americans were routed and many slain near these Friends, yet they escaped.
I thought this worthy of notice.

"`5th;
At our quarterly meeting I had to remark to Friends the
necessity there was to labour to have the eye single,
and to be truly devoted in heart.
I spread my concern before the meeting; much sympathy with me was expressed,
and my certificate endorsed.
My mind was favoured with a solid covering,
and I was very desirous that the meeting might not give way through a regard for me,
but that a single eye might be kept, as the matter was deeply interesting to Friends,
as well as to myself.

"`21st; Having been thoughtful about some Friends at Deer creek,
accompanied by David Sands, Samuel Emlen, jr., and some others, I set out;
and on fifth-day attended the meeting there, which was an exercising, suffering time.
Here are several valuable Friends, but much oppressed with a wrong spirit,
which is prevalent in some there.

"`Third month 15th;
Feeling some engagement of mind to attend the quarterly meeting at Warrington,
on the west side of the Susquehanna, I set out; and on the 16th called at Lancaster,
to see our friends Moses Roberts and John Hughes,
who have been prisoners upwards of eleven months, without conviction or trial.
They were supported in patience.

"`On the 17th I crossed the river Susquehanna,
and attended the quarterly meeting at Warrington on second-day;
where William Mathews laid before his brethren,
his concern for visiting Friends in Europe.
I reached home on fifth-day evening,
having cause to be humbly thankful to the Father of mercies.`"
