== Chapter IV.

[.chapter-synopsis]
* Third and last visit to Europe, and death.

From the time of his return home from his arduous labour in Great Britain,
John Pemberton remained under an impression,
that something more would be required of him at a future day,
in that quarter of the world.
For a time his diffident mind shrunk from yielding to the renewal of so trying a service,
among a people of strange language,
and little acquainted with the spirituality of true
religion and the nature of the doctrine of the cross.
The truly baptized servant cannot but feel the weight of such a service to be great,
and nature may sometimes shrink from the baptisms for the dead;
the yearnings of soul for the growth of the good seed of the kingdom,
in those hearts where it has in degree taken root and sprung up;
and from the "`deaths oft,`" into which the mind may be plunged,
for its own refinement and preparation from time to time,
for the work whereunto the great Master may see fit to send.
At length he gave up to the requirings of duty and spread his concern before the church.

The following extract from a letter written by
his brother James to a dear friend in England,
describing the exercise of his mind at this time,
and his earnest desire to proceed in his religious
engagements with the full unity of his friends,
will be read with interest.
It was written after the decease of John Pemberton.

[.embedded-content-document.letter]
--

The return to his relatives and friends after a
long absence on his former European visit,
was very gratifying;
though this pleasure was abated by the early discovery
that he came to us under a burdened mind,
from an apprehension that his duty was not fully performed;
which occasioned so great distress and conflict,
as sometimes to affect his bodily health.
But at intervals he was enabled to attend to various religious services at home,
and to perform visits to the meetings of Friends in
some parts of this state and that of New Jersey;
in which journeys he sought out obscure scattered families,
in a manner similar to that which engaged him when on your side.
Nevertheless, these engagements did not remove the weight of his exercise,
from which he could obtain no relief,
without imparting to his brethren of the monthly
and quarterly meetings the situation of his mind.

Here he met with sympathy and free consent to pursue his prospect of duty;
and spreading it before the superior meeting, it engaged deliberate and deep attention;
but though the rectitude of his concern was confessed without objection,
a hesitation being expressed by a few in respect to its full maturity,
he chose rather to bear his own burden,
than to move forward in so important an undertaking,
without the clearest evidence of the full unity of his brethren.
Thus a postponement took place, under which he laboured with exemplary resignation,
acknowledged by all who had opportunities of being witnesses thereof; and by many,
that no instance so instructive, had occurred to their notice.
It was now hoped by his relatives and intimate friends,
that his unreserved dedication would have produced a
satisfactory sense of having done all in his power,
and his free offering would be so accepted, that he might rest under such a persuasion;
which appeared to yield some relief.
But it proved temporary only; and at length after nearly two years detention,
and passing through much exercise,
he renewed his application to the monthly and quarterly meetings,
and obtaining certificates of the full unity of his brethren,
he again spread his concern before the general meeting of ministers and elders;
where it appeared that his burden had so weightily fallen on his brethren,
that with unanimous consent he was now set at full liberty.
My brother patiently waited to be ascertained of the right time of moving,
and two ships offering, one bound for Liverpool, the other for Amsterdam,
he visited them both,
and found his mind most disposed to engage with the captain of the latter.

--

It appears from a paper bearing date in the second month of this year 1794, and headed,
"`Memorandum in case of death, on leaving my native land,`"
that he was not without a sense
that his return home from his contemplated journey,
was very uncertain.
In this paper, after speaking of the time, when in early life,
he was "`caught in the holy net,`" while travelling with his friend John Churchman,
and mentioning his subsequent "`arduous trying time of duty for
several years`" in Great Britain and Ireland on his second journey,
he mentions with diffidence his labours, and concludes with the following remarks,
showing the humble state of his mind.

"`When I view my steps in life, and reflect how greatly deficient I have been,
I am humbled,
and have great cause to admire the compassion
and long suffering kindness of a gracious God;
and I may with abasement acknowledge that it will be of his mere mercy, if I am saved.
If I have been helped at times to be found faithful, it has been, and is,
through the efficacy of grace, and therefore no room to boast.
My failure in duty and in watchfulness has been great; though,
through the religious care of pious parents when young,
and an early sense of the divine fear,
I have been mercifully preserved from the gross evils of the world to this day;
which is a great mercy and favour.
But I have often passed under many hidden conflicts for disobedience and failure in duty;
and at times have been ready to despair,
and had to acknowledge that the Lord is righteous, whatever might be my portion;
but after days of sorrow, and nights of deep exercise,
he has been graciously pleased to renew light and favour, beyond my deserts.
Under a sense of which, I desire to be found more attentive, diligent and faithful,
during the residue of my days, esteeming the light of the Lord`'s countenance,
and the evidence of his peace, beyond all terrestrial enjoyments.`"

On the 27th of the fifth month he took leave of his beloved wife and family,
after a solemn parting opportunity with several of his relatives,
and the next day sailed from Newcastle in the ship Adrian.

On the 10th of sixth month he says,
"`I have been very thoughtful and solicitous to experience, if the Lord sees fit,
the seasoning grace and virtue of truth, to revive my drooping mind;
and have cause to be thankful that I feel pretty quiet.

"`First-day, 15th, it was proposed to have a meeting with the men,
but it did not meet with the captain`'s approbation,
so my companion and myself spent some time in retirement.

"`23rd; My mind was often this day, as at other times, turned towards the great Pilot,
craving preservation, clearness of sight, and perfect resignation;
and my heart was softened by the virtue of truth,
of which it is a favour to experience the least degree.

"`27th; This day in latitude fifty-nine degrees ten minutes, with a brisk wind.
The twilight in these northern parts is great, and for several of the last few days,
very little darkness.

"`28th; I have at times felt my mind deeply proved.
May the Lord in his great mercy sustain and preserve, under every dispensation.
He sees my dippings and knows my thoughts.
Sounded this evening, letting out one hundred and twenty fathoms of line,
but found no bottom.

"`First-day, 29th;
A religious opportunity with the ship`'s company being solidly proposed to the captain,
he could not well get over it, and consenting thereto,
most of the seamen came into the cabin and sat in a very quiet and becoming manner;
counsel was opened to them, and they parted solidly.

"`Third-day;
today we had a sitting in retirement to feel after the renewal of strength and patience.
We saw a large Dutch ship in the evening, but she did not give opportunity to hail her.

"`Fourth-day, about forty English miles from Shetland,
but little prospect of landing short of Amsterdam.
My mind received some comfort this morning, in being exercised towards God,
for which I am made thankful.

"`Sixth-day, having lately read Sarah Grubb`'s journal, and some parts several times over,
the lively sense she was favoured with, and the deep experience she gained,
through faithfulness to the gifts dispensed, is very instructive;
and I wish it may tend to increase my dedication.
She had her provings many ways, but was favoured to close in peace and full assurance;
a great and singular favour.
May I, may all the visited, be strengthened to hold out in faith and patience to the end.
My fears are often great, but hitherto the Lord has been gracious and merciful.
My companion and myself feeling our minds favoured with solemnity,
had to recount the gracious dealing of the Almighty with us and the children of men,
and to view the qualifications and services of
many brethren and sisters who are gone to rest,
and the various dispensations of the Almighty,
and how those who fulfilled their duty in their day were accepted.
These at times saw a more glorious day of light and truth,
which in its appointed season would spread.
It is faithfulness to the discoveries of the Light, that settles, strengthens,
establishes and qualifies to fulfil the work of the day.

"`First-day, seventh month 6th; The captain consenting,
most of the seamen met with us in the cabin, and a solemnity soon covered us,
seldom experienced in larger assemblies.
Counsel in the love of the gospel flowed freely, and appeared to be received acceptably,
A degree of the seasoning virtue attended, and when the little meeting broke up,
they came in an orderly manner and shook hands, departing seriously.

"`Third-day, spent some time in retirement,
in which my mind was instructed in the remembrance of
the blessed experience of the holy apostle,
when he could say, '`I am crucified with Christ; nevertheless I live; yet not I,
but Christ lives in me; and the life which I now live in the flesh,
I live by the faith of the Son of God,
who loved me and gave himself for me,`' This is a state which all ought to labour after,
but which requires great abasement and watchfulness to attain to.
May it become more my experience; then will the Lord`'s wisdom,
power and strength be more fully revealed, and he will become my joy and salvation.

"`Fourth-day, took a pilot on board, being about sixteen miles from the Texel,
and about four o`'clock saw land.
We have cause to be thankful that we have been so far preserved.
Although my mind has been often proved with great leanness and poverty,
yet I have been favoured with a calm.
Oh, may the Lord vouchsafe to open my way and give me faith to pursue it.

"`Fifth-day, 10th; We landed and lodged at a place called the Holder.
After taking refreshment we walked through
several streets and stopped to speak with some;
but found none to speak English, except the landlord at the inn,
the man at the post office, and an aged captain.
We could not find any religious seeking persons,
though many of the women seemed of good countenance.

"`Sixth-day, met with a German soldier who understood a little English.
Some observations were made to him, and he seemed serious.
Afterwards we met a Jew who spoke English.
He told us that there were not many who paid
much attention to the fear of God in that place.
He invited us to his house, and I had some observations to make to him,
which so far claimed his attention,
that he followed us to our inn and remained near an hour, until he saw us off,
parting respectfully.
I had also remarks to make to the landlord, respecting spending precious time at cards,
and giving men drink when they appeared to have too much before.
I am willing to hope that some impression was fastened on his mind.

"`We left the Holder about eleven o`'clock and passed over a sandy way, in a jolting,
clumsy wagon, and then proceeded by boat to Alkmaer.
We walked through many streets of this city, and were gazed upon by the people; who,
however, were respectful.
Next morning, taking a carriage, we rode about fifteen miles to Purmerent,
and there took boat and landed at the great city of Amsterdam about twelve o`'clock,
where we were kindly received by our friend John Vanderwerf.
On our way we had passed many good grazing farms, pleasant villages and neat houses,
yet a low flat country; and the nearer we approached Amsterdam, the lower the ground,
so that many houses are very little above the surface of the water.

"`First-day, seventh month 13th; Attended two meetings in Amsterdam, both solid;
and the spring of the gospel was opened in each.
My mind was made thankful for the help vouchsafed,
and John Vanderwerf thought himself helped in interpreting.

"`Second-day,
towards evening we had a religious opportunity in the family of Frederick Mentz,
one of the Friends here.
Gospel love and counsel reached towards them,
particularly to a daughter under great bodily infirmity.

"`Fourth-day; this morning an exercise that has for several days attended my mind,
being renewedly felt, an opening seemed to present,
to pen a few lines addressed to the inhabitants of this great city,
and it remains under consideration how to dispose thereof.
This being the day on which Friends of this place formerly held their mid-week meeting,
I was last evening free to propose one; which began about four o`'clock this afternoon,
and was attended not only by the few under our name, but by several others,
who behaved well, and the gospel spring was in measure opened.
I esteem it a mercy that amidst discouragement I should be so supported.

"`Sixth-day, the address to the inhabitants of Amsterdam being copied,
was dated this day, the 18th,
and delivered to John Vanderwerf to turn into the Dutch language.

"`First-day, attended the two meetings,
at each of which many of the inhabitants and strangers were present.
To me they were exercising, yet the gospel spring was measurably opened,
and the people were sober and attentive.
I had the few Friends together afterwards, both young and aged;
felt much sympathy for them, and laboured to impress their minds,
that the aged might live near the Lord, and be daily exercised to be replenished by him,
that they might be as lights to this city,
and preachers of righteousness in life and conduct;
and that the youth might regard the Divine call, and embrace the truth in the love of it.

"`Fourth-day, the address being printed, as follows, part were distributed.

[.embedded-content-document.address]
--

[.blurb]
=== Tender counsel and advice to the inhabitants of Amsterdam, by one who desires their present and eternal welfare.

The Scriptures of truth inform, and it is also confirmed by daily experience,
that '`It is appointed unto men once to die;`' and the
professors of Christianity assent to this truth,
that after death comes the judgment, and as our works have been here,
so will our reward be hereafter.
There is in each of us an immortal part,
which will be either happy or miserable when time to us here shall be no more.
And it is also very evident from many Scripture testimonies,
that God wills the happiness of all mankind; for, speaking by the mouth of his prophet,
he says, '`As I live, says the Lord God, I have no pleasure in the death of the wicked,
but that the wicked turn from his way and live;`' and immediately after,
he makes use of this moving language: '`Turn you, turn you from your evil ways,
for why will you die, O! house of Israel?`' And in another place, he says:
'`Look unto me, and be you saved, all the ends of the earth.`' Our blessed Lord,
in the days of his flesh, when on a certain time he drew nigh unto the great city,
Jerusalem, wept over it, and in the bowels of heavenly compassion, thus laments;
'`O! Jerusalem, Jerusalem, you that kill the prophets,
and stone them which are sent unto you,
how often would I have gathered your children together,
even as a hen gathers her chickens under her wings,
and you would not.`' Now as it is apparent from the foregoing testimonies,
that God created mankind to be happy, he has in mercy written his law in their hearts,
and placed a measure of his good Spirit in their inward parts,
which testifies against all evil,
and brings reproof and condemnation when his holy law is transgressed.
And it is man`'s duty and greatest interest to regard this law, which is light,
and square his actions conformably to its dictates;
for in obedience there is consolation and peace.

Being now advanced in life,
I have had opportunity of observing and also lamenting the mistake of many,
whose time and attention are taken up in an eager pursuit of
the false and delusive pleasures of this transitory life,
and an over anxious desire after the gains and profits of this perishing world;
in which they are so much involved as to neglect their duty to God and their own souls.
For the injunction formerly given, remains obligatory on us: '`Hear, O! Israel;
the Lord our God is one Lord; and you shall love the Lord your God with all your heart,
and with all your soul, and with all your mind,
and with all your strength.`' Whatsoever the mind of man is most intent and fixed on,
becomes his god, or idol.
Therefore my desire is,
that the inhabitants of this great city may seriously reflect
and consider what their minds are most intent upon,
whether it is to serve and please God, their great Creator,
and the dispenser of all their blessings,
and at whose disposal their lives and substance are, or to serve and please themselves.
For the Scripture says, '`Know you not,
that to whom you yield yourselves servants to obey,
his servants you are to whom you obey, whether of sin unto death,
or of obedience unto righteousness?`' And as the
judgments of the Lord are now abroad in the earth,
and great calamity and distress prevail and are brought near, and on your borders;
it is incumbent on all to be thoughtful and serious, turning their minds inward,
to inquire after the cause and end thereof; endeavouring thereby to learn righteousness;
regarding the example of the people of Nineveh, who, at the preaching of Jonah,
humbled themselves, and thereby obtained the compassionate notice of the Almighty;
so that the threatened destruction was withheld.
I have felt my mind much exercised and concerned
for the welfare of the inhabitants of this place,
during the few days that my lot has been cast among them,
and do fervently desire that the re marks and counsel I have penned, in gospel love,
which breathes '`peace on earth, and good will to man,`' may be read with attention,
and blessed to them.
So wishes, so prays your Christian friend,

[.signed-section-signature]
John Pemberton

[.signed-section-context-close]
From Philadelphia, in North America.

[.signed-section-context-close]
Amsterdam, Seventh month 18th, 1794.

--

"`Our meeting this afternoon was small, but favoured and comfortable;
and my mind was in measure bowed in reverent
thankfulness for the help hitherto vouchsafed.

"`We visited the foundling hospital, also an academy, in excellent order;
and in the afternoon went to the house of the Hopes`'; great in this world`'s goods.
In the counting-house there appeared to be more than twenty clerks.
A sensible young man, one of the partners, came to us,
with whom we had considerable conversation.
Endeavours were used to inculcate an impression of the
danger of the surfeiting cares of this life,
and the deceitfulness of riches choaking the heavenly seed;
I wished him to guard against this, lest it divert from the pursuit of better treasure,
intimating that peace with God was the best treasure,
and that on a dying bed the greatest worldly treasures would not purchase it.
We parted affectionately,
leaving him a copy of the tender advice to the inhabitants of this city.

"`Sixth-day, called at several houses where schools are kept,
and at the Menonists`' orphan house.
As we passed along the streets we distributed copies of the printed piece,
which were kindly accepted.
One man to whom a copy was given, followed and overtook us,
after we had passed him a quarter of a mile, or more; his mind seemed affected,
and he signified his desire of having more, which were given him for distribution.
This work is mortifying to the natural part; yet if truth and righteousness are promoted,
no matter how foolish the creature may appear.

"`Seventh-day; went this morning, not out of curiosity,
to visit the hospital and the house to accommodate aged persons.
I could not, for lack of an interpreter, convey much to them, yet my mind being affected,
they seemed to notice the solidity attending.
In the afternoon I went to the jail where prisoners for debt are confined,
and had to communicate such counsel as at that time revived,
which was received kindly by most, though, two or three appeared vain.
One man said he had been there fourteen years.
These visits are affecting to my mind, and not agreeable to the natural will.

"`First-day, 27th; attended the two public meetings for worship at Amsterdam.
To that in the morning there was a great resort, many strangers being in the city.
As they generally came out of curiosity, and were unaccustomed to silence,
they were coming in and going out, most of the meeting;
but a solemnity prevailed for a considerable time, which was comfortable.
I ventured to stand up after a long space of silence,
but the unsettled state of the people rendered it difficult to speak;
though some seemed solid and gave attention.
The afternoon meeting was held in silence,
except that near the close I had a little to communicate
respecting the blessed effects of true faith.

"`Fourth-day, the meeting was attended by some sober people besides the few Friends,
and was a favoured opportunity, the gospel spring being opened,
and the people behaving with solidity.
After the meeting we went on board a Vessel in which we had taken passage for Zwol,
and proceeded on our way with a light breeze.
This morning I had a seasonable opportunity with Lewis Boswel.
The words of Christ sprang in my mind, which he uttered to the young man who queried.
What good thing he should do to inherit eternal life.
Though he had kept several of the commandments, yet he lacked in a very important matter;
and though he turned away sorrowful, yet Jesus looked upon him and loved him.
From which I had much to remark to this goodly young man,
whose mind seemed much impressed.
I left Amsterdam in peace.

"`Sixth-day; we landed at Zwol this morning about six o`'clock, and went to a good inn.
After breakfast we walked through several streets of this city,
and entering a place where there were soldiers,
we found one who could speak a little English,
having been in America in the time of the troubles, sixteen years past.
I made some observations to the soldiers, which seemed to have some place,
and left one of the printed advices with them.
We afterwards visited John Erskine, a man in years,
but with a lively sense and clear judgment of the solemn truths of the gospel.
He has led a retired life for about twelve years; is no pharisee,
but sees his dependence and acknowledges that without Christ he can do nothing.
He believes that there is a church among the different divisions in Christendom,
but that they are, as it were, here one and there another;
and laments the condition of France, that even the rulers publicly disown God and Christ,
and have become Atheists.
He, however,
had faith to believe that they might be permitted as a rod to chastise the wicked,
that when that was effected the rod might be destroyed,
and that the present troubles would in the end produce a great change,
and be as a forerunner of better times.

"`Seventh-day, walked about Zwol to show ourselves to the inhabitants,
who appeared respectful.
In the afternoon we visited the house of correction, where were about twenty-five men.
Some counsel was given, which appeared to be kindly received.
One man said he was an Englishman, and had been there fifteen years,
having been condemned to a confinement of thirty-one years.
He seemed affected and shed tears.
We afterwards visited the women`'s apartment, where were about sixteen,
some aged and some young, to whom also counsel was given,
which appeared to be accepted in love,
and one that spoke on behalf of the rest acknowledged to the truths delivered.

"`An affecting sight presented today; five carriages, with four horses in each,
with much baggage, and people that appeared to be persons of property,
among them a count and an abbess, with their servants,
fleeing from Antwerp for fear of the French, who are making considerable advances.
This is one of the consequences of war, which brings misery every way;
and happy are they who are redeemed from its spirit,
and are under the dominion of Christ.

"`First-day, eighth month 3rd; Drummond Scott, a schoolmaster,
who had acted as interpreter, came to our quarters, and our little band,
being four in number with him, spent nearly two hours in silence,
and closed in supplication.
About four o`'clock we visited Colonel McClough,
who had been in the army about forty years.
Having presented him with a copy of the printed advice, he read a part,
and then desiring the family to be called, read the whole of it to them,
who were solidly attentive.
I have laboured after patience in my stay here, and this interview affords comfort.

"`Second-day,
I visited the barracks and communicated through such interpreters as could be met with,
to several little companies of soldiers,
some advice to impress their minds with the Divine fear; to which some gave attention.
We took tea with Colonel McClough, and visited a Latin schoolmaster, an aged man,
who told us he had read Barclay`'s _Apology,_ and approved of it.
I gave him B. Holmes`'s Serious Call, in Latin, and we parted friendly.
Some of these visits were mortifying to the natural part; but I wish to leave this place,
if possible, in peace.
We have had opportunity to distribute small books, etc., and had we the Dutch tongue,
our visit might be rendered more satisfactory to ourselves and beneficial to others;
however, we do as well as we can, and must leave the event.

"`Third-day,
we visited a young man who has been minister of
the Protestant French congregation in Zwol,
but is now prohibited from teaching in public,
as he could not take the oath enjoined by the States.
We found both him and his wife very amiable and tender-spirited people,
he being an enlightened man, and his mind seasoned by the truth.
He expressed much love for Friends, and having some time ago read Barclay`'s Apology,
he much approved of it.
His living, we understand, was one thousand guilders a year,
which is now taken from him for his conscientious refusal of the oath.
We parted from them in much affection,
and I had to recommend their seeking to have their minds clothed with wisdom from above,
rightly to enable them to train their six lovely children;
the necessity of which was acknowledged.
We went afterwards to the parade, and many soldiers being gathered,
I had to communicate some advice, which one of them, a solid man,
gave them in their own language.
They behaved well, and the opportunity was as satisfactory as could be expected.
I understand since, that these poor men are to march hence tomorrow.

"`I now proposed to leave Zwol, yet something still detains,
the cause of which I do not fully see; and must, therefore, exercise patience.

"`It proved a wet afternoon, at times raining very hard;
so that it was well we were restrained from departing,
particularly as in the evening we had a further interview with Peter Chevalier,
the minister of the French congregation, and his amiable wife,
I showed him the certificates granted me by my friends;
after supper a solemnity covered our minds, and dwelling under it some time,
I had to open my mouth and express the necessity and advantage of frequent retirement,
to wait for the renewal of strength and the participation of that heavenly bread,
which keeps the soul alive.
Their minds seemed tendered, and we parted in much affection,
John Erskine came to take leave of us,
and appeared under much concern for our safety and preservation,
urging the danger of travelling under the present circumstances.

"`Fourth-day, we left Zwol in the morning, and proceeded in a heavy clumsy vehicle,
through a country mostly very poor, with a sandy road, heavy dull horses,
and a self-willed driver, to Almeloe, about twenty-five miles distant,
and concluded to stay there all night, as our charioteer refused to proceed further.

"`Sixth-day morning proceeded to Lingen.
I was much exercised in approaching this place,
which is in the king of Prussia`'s dominions, and hoped not to be detained.
But feeling some exercise of mind I attended to it, and seeing a goodly looking man,
queried of him if he could speak English.
He could not, but took me to his house, where one spoke French,
and I found him to be the principal of a school patronized by King George III.,
and a chief magistrate in the town.
We spent several hours with him agreeably, and some remarks were made,
which he received in love.
I presented him with Robert Barclay`'s Apology, in German, and some other pieces;
and afterwards visited the German Lutheran minister, spent about an hour with him,
and he acknowledged to the propriety of some gospel truths and remarks made to him.
I parted from him, as from the other, with their desires for our prosperity and safety;
and then visited an aged man, who could speak a few words of English,
and who had had a stroke of the palsy.
He was too full of worldly matters, from which I endeavoured to direct his attention,
and to show him the propriety and necessity for him and myself to leave lower concerns,
and labour to become prepared for a better world.
He acknowledged the remarks were just, wished us preservation,
and I left some pieces with him.

"`Seventh-day; slept little last night, and did not feel at liberty to leave this place.
Today we paid visits to some learned men,
spending about two hours with professor Mieling,
with whom we had much conversation on religious subjects.
He showed tokens of regard; his aged mother acknowledged to the truths communicated,
and two young women present behaved well.
We also visited a very rich man, named G. A. Zeigler,
To this house our interpreter was averse to going, representing the family unfavourably;
however, we had as much satisfaction as in most of the visits we have paid;
the man having more sensibility respecting religious matters than I expected,
and a niece was tender.

They expressed gladness at our freedom, and many desires for our preservation.
We gave him William Penn`'s '`Rise and Progress`' and the '`Tender
Counsel,`' and left some pieces also at other places.
The reception we met with, and the labour which opened,
showed the propriety of our having stayed here;
this being a place of much outward learning,
but where Friends`' principles are little known.

"`Second-day, visited the college, where we were received kindly,
and afterwards spent some time with Abraham Campstede, a professor of languages,
I had to remark to him, that as I understood he was a man of parts and learning,
I wished him not to lean upon them,
but to seek to be endued with the wisdom that comes from heaven, which is pure.
He acknowledged the propriety of the remarks,
and we left with him William Penn`'s '`Rise and Progress,`' in German.

"`We visited J, Wilremar, a young minister; my mind was covered with gospel love,
and I made many remarks to him respecting the ministry,
and the necessity of waiting to experience the mind seasoned with the virtue of truth,
in order rightly to minister to others,
and also the necessity of regarding the counsel of Paul,
'`to be an example to the believers in word, in conduct,`' etc.;
to all which he assented, his mind being touched.
On parting he seemed very affectionate, and could scarcely let no hand go,
expressing many good wishes for my preservation.
Much labour has been bestowed in Lingen, and I have undergone great exercise of mind;
more so from the lack of an interpreter with a mind seasoned by the truth.
The one we had, who was a physician, was kind, but superficial,
and sometimes mixed a little of his own,
not being careful always to deliver exactly what I said;
so that I was often weary of him, but knew not how to do well without him.

"`Third-day, we set out for Osnaburg soon after five o`'clock,
travelled about three miles an hour, and arrived in the evening,
having spent about an hour at a town called Western I Capteln,
where we found one person who could speak English, with whom we had some conversation,
and left a copy of the '`Tender Counsel.`'

"`Fourth-day I spent under much exercise of mind.
We made diligent inquiry,
but could not find those friendly people of whom Sarah Grubb makes mention at Osnaburg.
We had thoughts of moving towards Pyrmont, but the way did not clearly open.
My spirits were much down, but I laboured to keep from sinking below hope.
The Lord has mercifully sustained hitherto, blessed be his holy name.
But these journeys among a people of strange language, without a steady interpreter,
and with close trials within, require faith, patience and stability.

"`Fifth-day, my companions having made diligent inquiry,
found an ancient man of about eighty-two years,
who appears to be one of the people Sarah Grubb alludes to,
and he agreed to give notice to some others.

"`Sixth-day, attended agreeably to appointment,
but waited nearly an hour before they all came,
being only five besides myself and companions; having a schoolmaster for interpreter.
It appeared discouraging; however, I desired them to settle into silence,
which seems difficult for the Dutch and Germans, as they are accustomed to much talk.
After a painful exercising time, in which it was difficult to get the mind truly stayed,
I uttered some remarks to show the necessity of
ceasing from the activity of the creature,
and having the mind exercised towards God,
looking to him to prepare the offering that will find acceptance:
and I had to revive the gracious promises made to those who seek aright.
Another religious opportunity was proposed to be held on first-day, to which I yielded;
but I left them heavy and sorrowful,
in considering that they profess to separate on
religious grounds from the assemblies of others,
and yet appear to have little depth of religious experience;
the pure life was not in dominion.
Our long detention in towns, and at public houses where there is a great resort,
is a subject of admiration and of inquiry with some, why we remain so long in a place;
they not knowing the conflicts of spirit which attend,
and the deep baptisms which travailers for the good of souls have to experience.
Our stay at Osnaburg has been painful,
and the prospect of advantage less than at most places;
but I labour for resignation and patience.

"`Seventh-day, had a very agreeable interview with the minister Martin, a sensible,
feeling, religious man.
We united in sentiment and spirit; many gospel truths being opened,
and some branches of our testimonies, the propriety of which he agreed to.
We parted under the seasoning virtue of Truth;
and this visit gave me more satisfaction than anything
which has occurred since our arrival at this place.
I visited also our interpreter, and my mind was opened to impart counsel to his daughter,
about eighteen years of age, which appeared to have place in her mind.
This evening we were visited by Martin and bis brother Dr. Klucker, a solid man,
head master of the Latin school in this place, and learned in several languages.
We gave him B. Holmes`'s '`Serious Call,`' in Latin, and the '`Short Account,`' in French,
and found that he possessed Barclay`'s Apology, in German.
These opportunities revived my drooping mind,
and gave hopes that our stay is in Divine appointment, however proving to ourselves.

"`First-day; this morning I had a request from the abbess of the nunnery,
to pay her a visit, and two o`'clock was appointed.
I went with an awe over my mind, not knowing what might he the issue; however,
we were received by her with solidity and respect,
and we spent nearly an hour acceptably with her.
She acknowledged the truth and propriety of sundry observations made,
and we parted affectionately.
I was in measure made thankful for this visit and the seasoning virtue that attended it;
and particularly that the cause was not injured, nor gospel truths withheld.

"`In the morning we had a quiet sitting in our chamber, myself, companion,
the interpreter, and another individual; the Lord favoured,
and it was a refreshing opportunity.
At dinner, there being a full company at table, my mind was exercised in solemn prayer;
but being in my own tongue, few could fully comprehend what was delivered.
An aged man, however, who sat near me, said '`Amen,`' at the close,
and I had peace in this dedication.

"`About four o`'clock we went to this ancient man`'s house,
and our company at this religious opportunity were eleven men and two women.
A considerable time was spent in silence,
when the gospel spring arose and our interpreter did better than heretofore.
Much was communicated, and several present were tenderly impressed, particularly one man.
We parted affectionately, with tears on both sides, my desires being for their welfare.
There is much innocence about the aged man and one or two others;
but the experience of the generality in the ground of true religion is small,
and there is a need of delighting more in silence.
After parting with these, we proceeded to the house of J. F. Klucker,
where we spent an hour and a half with him and his friend, the minister Martin.
Our conversation was in his library, which contains a large number of books;
and he said he had the Bible in twenty different languages.
I mentioned the necessity for a Christian to learn true wisdom, adding,
that we were weak creatures, and without watchfulness the mind was apt,
by too much learning, to be lifted up above the simplicity of the gospel.
Whereas, the greater the gifts and qualifications, the greater was the call for humility.
This was assented to,
and we parted solidly and with their desires for my being blessed and preserved.

"`This closed our day`'s labour,
and my mind was humbly thankful for the portion of wisdom and
strength mercifully vouchsafed to a feeble instrument.
I have had much conflict in this place, yet by labouring for quietude and patience,
the end so far has been more satisfactory than I hoped for: may honour,
majesty and praise be ascribed to the Lord, to whom alone it belongs;
and the creature be abased; for it is through his help that I have been upheld hitherto.
My path is a very humbling, mortifying one.
I may truly say in this journey,
'`I die daily;`' and fresh and deep baptisms constantly attend.
May the Lord strengthen inwardly and outwardly, until he is pleased to say, it is enough.
'`He leads the blind in a way they know not,
in paths they have not seen;`' and I only live from day to day.
May patience have its perfect work, and the Lord`'s time not be thought long.
If I am favoured to hold out to the end, and close in peace,
I am not very anxious where the body is laid, but I find watchfulness needful every hour.
May the Lord keep us under the fresh anointing, and increase our faith and dedication,
so that, maintaining a hunger and thirst after the bread of life, we may be kept savoury.

"`On second-day,
finding my mind still exercised for the small select number of persons above mentioned,
we visited eight families of them, and found comfort in several.
Hearing of a religious people about five miles distant, at a small village named Buern,
we went there on third-day, and were gladly received.
They soon collected, and we were mercifully favoured with an open meeting,
there being twenty-two present, including two children.
The minds of several were contrited.
They had in times past withdrawn from the parish worship,
and met together to edify each other; but being persecuted, and one of them, a woman,
beaten, they had but very seldom met of late.
We had much satisfaction in visiting these people,
and from there proceeded to Western Capteln, that place still resting on my mind,
and had an evening meeting with about fifty or sixty people,
which was also a favoured opportunity.
We visited also several Lutheran ministers.
I have sometimes admired that opposition has not been made,
as I have been very plain respecting the qualification of right ministry,
and the necessity of a regard to Paul`'s counsel to Timothy.
As some of these visits have been mercifully owned with
the tendering influence of the pure Spirit,
and afforded a degree of peace,
I am willing to hope our detention has been in Divine appointment.

"`Seventh-day, my mind was under a weight of exercise;
perhaps in sympathy in some measure, with the precious seed under oppression.
In the evening I went to the Lutheran orphan house to visit the children,
and communicated a little matter to them and their overseer.
Visited also a youth, who, by a fall, has, it is supposed, split his thigh bone.
He was tender, and expressed thankfulness for the visit.

"`First-day, the 24th; We met together this morning as usual,
our interpreter sitting with us; and soon afterwards Henry Lange,
Frederick Seebohm and Herman Schutamir, came in.
They are serious men, and appear and act as Friends.
They attended the meeting in the afternoon, along with others;
which was to me an exercising time.

"`Second-day we proceeded to Buer,
but there appeared very little openness towards proposing a meeting with the people;
so after a stay of a few hours we continued our journey to Bunde.
The Friends from Pyrmont continued with us.
I walked into several parts of the town of Bunde; the people seemed friendly,
but my mind was much stripped and exercised, as it has been for several days past.

"`Third-day, visited the minister of Bunde, and his wife,
she having expressed a desire to see us.
She appears a solid woman, and he a thoughtful man.
At table I found my mind exercised in supplication,
and through the Lord`'s mercy the seasoning grace attended.
We spent several hours at this house; and the gravity, the fewness of words,
and the weight which attended our conversation,
made our stay with them very satisfactory.
We called at several other houses and communicated counsel,
which appeared to be received in love, and with an acknowledgment to the truths spoken.
This seemed to make way to appoint a meeting.
It was attended by a large number, mostly young, and was more favoured than I looked for.

"`Fourth-day, after making some visits we took wagon and proceeded to Herwerden,
formerly the residence of the princess Elizabeth, whom William Penn visited.
After dinner we were called on by a serious man, who had been brought up a Romanist,
but has for some years declined attending their worship,
and for about twelve months past has met with a few seeking people near Bielefeld.
He seems to be in earnest in a pursuit after saving knowledge.
He told us of a young woman accounted rich, and gaily dressed,
who has experienced a great change.
She saw Sarah Grubb and Sarah Dillwyn passing along the street,
and their dress being different from what she had before observed,
led her to inquire who and what they were; and her mind became so affected,
that she in time took up the cross, changed her own dress, and has become a solid,
valuable young woman.
She and another zealous young woman have kept up a religious meeting,
some others joining them; and she sometimes speaks a few words in their meetings.
He also related the case of a youth who lived as a clerk to a merchant at Bremen;
who being uneasy with his situation,
wrote to his parents and had their consent and that of his employer,
to return to Bielefeld; and his clothing, which was fashionable,
coming by the stage from Bremen, his mother on first-day proposed his dressing,
in order to go to their place of worship; but he told her,
that those idols he would give up, and would not wear them again.
He is now a serious religious youth; and hearing of us, has set out for Pyrmont,
in hopes to see us.
These instances show that something is at work in the minds of the people.
May the Lord carry on his work and perfect it to his praise.

"`Fifth-day, we set out on foot to visit some religious people under the name of Quakers,
about four miles and a half distant.
It was a hilly road, yet we reached the place less fatigued than I expected.
The two men, who are brothers, were from home when we arrived;
but the women speedily collected, and we had a religious opportunity with them,
being six in number.
It was a tendering; time, the minds of all being comfortably affected,
and they being glad of the opportunity.
The meeting was held in a little room,
where they commonly meet on a first-day and sit in silence.
We remained with them about two hours, and then taking leave and going a short distance,
one of the men came home; so we returned and had a short opportunity with him;
then came back to Herwerden, through rain most of the way.
After drying our clothing, we attended a meeting which had been proposed yesterday.
There were about thirteen present, and it proved more satisfactory than could be expected.
But it is not the first time that religious opportunities have
suffered for lack of punctuality in meeting at the hour.
Some time before the meeting we were visited by the other of the two brothers,
and also a man from the Hanoverian territory, who is under the denomination of a Friend.
They had been to Bielefeld to see the friendly people there,
and came to Herwerden in hopes of seeing me and my companion.
They were encouraged to faithfulness.
The two brothers have for conscience sake suffered much, both in person and property,
from the priest and otherwise, but have been supported under suffering.
One had been a prisoner nine months;
and the other had been several times thrust into jail; once while building a house,
and in time of harvest, when he had many at work who needed his direction.
Much innocency and simplicity seem to attend them and their connections,
and they appear better grounded in religion than any we have yet been among.

"`Sixth-day, we took a wagon, and proceeded to a village called Ufeln,
and had a comfortable opportunity with a religious seeking travailer there,
a tender-spirited woman, whose heart was overcome at seeing us.
The husband at first refused to receive us, but she entreating him, he consented;
and though he seemed cool, yet after a little time he became more open.
I was very poorly, having taken cold by being wet yesterday,
but through the Lord`'s mercy was much better in the morning.

"`Seventh-day, the man was more open,
and consented that we might have a meeting at his house, which was more than I expected.
I had also an opportunity with the woman,
and encouraged her to persevere in faithfulness,
looking unto the Lord for wisdom and counsel.
She appears to have been under much exercise of mind, and has had trials and sufferings;
and seems in earnest to build on the right foundation.
Before leaving the house, I had something to say to her husband; whose mind was reached,
and we parted affectionately.
We had also a religious opportunity at the house of an aged woman;
her son and another man being present, and it was a season of favour.
The man, who, I suppose, was a neighbour, seemed affected,
and desired the Lord to bless us.
We hired a wagon, and set out for Bielefeld,
and after about five hours arrived there in safety.
I find that in many of the towns in Germany, under different princes,
there is a seeking people; but the fear of the priests, and of their neighbours,
has such place in their minds, that they are afraid to show themselves,
or make open confession.

"`First-day, eighth month 31st; This morning three men and one woman from the country,
and a few others, besides the hopeful young man so remarkably changed,
sat with us in a room at the inn.
It was a low exercising meeting.
Another was agreed to be held in the afternoon,
and those from the country engaged to spread notice.
About two o`'clock Lewis Seebohm, another friend of Pyrmont, came in with letters.
About four o`'clock we sat down, expecting some from the country.
Our company, however, was only two women and one man from the country,
and two men of the town, besides the youth above mentioned, the two Friends from Pyrmont,
and ourselves.
It was a more open time than that in the morning; tenderness prevailed,
and encouragement flowed to a tribulated exercised state.
A conference being held respecting another meeting,
one of the men present offered a room at his house,
it being suggested that the people did not choose to assemble at a public house.
This fear of being seen greatly prevails among awakened minds in this land.

"`Second-day; Very unwell this day; however,
I walked to the place where a meeting was to be held;
though not the house proposed yesterday, the landlord forbidding his tenant to permit it.
Another was therefore fixed upon, about a mile from our inn.
I went in great weakness, both of body and mind.
There were upwards of thirty people.
We spent nearly an hour and a half in silence; my mind was preserved quiet,
and a solemnity prevailed; the people generally being very still.
The spring of the ministry afterwards opened, and the minds of many were much affected.
At the close of the meeting some counsel was given,
not to be easily moved from their steadfastness, either by the fear of man,
or the many voices in the world, some crying, '`Lo, here is Christ,`' and some, '`Lo,
he is there.`' Such as were truly sincere were encouraged to meet together,
and not to be ashamed of sitting in silence; and although their number might be small,
to remember the Lord`'s promise was to the two or three who met in his name.
We parted with them in tenderness.
Some of these people seem sincerely disposed to
make progress in true religion and godliness,
and to build upon the everlasting foundation;
and some are under a very precious visitation,
and are desirous of being preserved under the humbling virtue of truth.
They are seeking the way to Zion, but are as sheep without a shepherd.
These were directed to the great Shepherd, Feeder, and Teacher of his people.

"`Third-day; I had much fever last night, resting poorly, and was unwell all this day;
but sat a meeting which was appointed at our inn,
to which some came that had not been present before.
I was favoured during the meeting, with strength to hold forth the doctrine of Christ.
Several minds were tendered, and I am willing to hope it was a profitable opportunity.
One woman came with her son about four miles, not knowing of the appointed meeting,
and brought a letter from her husband, Caspar Reining,
who has been with us several times,
hoping that we might be furnished with counsel to his son,
which would be as a seed that in time might bring forth fruit.
They returned home in the rain on foot after meeting.

"`Fourth-day, notwithstanding a fever continued on me,
I visited the parents of the young man before mentioned,
whose feet are turned into the way of righteousness.
The father looked fierce, but entering into conversation with him in a soft mild manner,
his countenance fell, he became familiar, and we parted affectionately.
In the afternoon we visited also, the parents of the young woman now at Pyrmont.
Her father at first refused to give us his company,
but after a while he was prevailed upon to come in, and appeared much agitated;
yet by introducing conversation in a familiar way, with some religious observations,
his countenance in measure fell; he sat down,
and I felt a degree of gospel love toward them,
with some expressions of desire for myself and them,
that we might improve the few days allotted us, that they may be our best days,
and we may experience a preparation for our great change.
We also visited one of their ministers,
who has shown much prejudice against the few who go under our name,
and uttered his venom even from the pulpit.
However, to us he appeared open, and desired for us a blessing at parting.
In the evening several of the friendly people came to visit us,
and C. Reining seemed under much exercise and concern
about reviving a meeting for Divine worship in silence;
though he did not expect many of the people hereaway to unite therein,
the fear of man being so great.
He and others present were recommended to labour to be retired
in their spirits and wait for the opening of Truth,
and for wisdom and strength to proceed,
so that when they engaged therein they might be steady.

"`Fifth-day, I had a fever all last night, and my companion sat up with me.
However, I was favoured to get into a perspiration, kept my bed all day,
and the fever subsided pretty much towards evening.

"`Seventh-day, the chill and fever was renewed, and I was very unwell all the afternoon.
It continued till midnight, with a great thirst,
yet through the adorable mercy of a gracious God,
I felt more of the incomes of his love and life-giving
presence than I have experienced for a long time;
so that I was enabled to make melody in my heart,
and recount his fatherly care and tender dealings with me from the days of my infancy.
Prayer and praises were living in my heart, and I had to bless his holy name.
This comfortable visitation of his love and mercy continued some hours,
and I was ready to conclude I might be soon released
from the trials and afflictions of this life.

"`First-day, ninth month 7th; This morning I felt exceedingly feeble,
yet went down to the meeting.
Several attended who had not been at meeting since our coming.
There was a quiet and solemnity in the time of silence,
which continued when I was called forth to minister;
and I hope it was an instructive opportunity.

"`Second-day, in the afternoon, I paid visits to two families,
in each of which we were favoured with counsel and instruction,
and they manifested their affection at parting.
These were people esteemed rich, and who have good stirring in their minds,
but are not yet brought to a willingness, without reserve, to confess Christ before men;
and thus some of them are standing in the way of honest inquirers in a lower station;
these saying.
What does such a man say to this doctrine?
After supper several came to the inn, and we had a religious opportunity,
the Lord condescending to open counsel, which reached the witness in their hearts.
As L. Seebohm lodged at the house of one of them, he heard him in conversation saying,
'`this doctrine of the cross is the same which Sarah Grubb preached to me;`'
but they entered into arguments to evade the force of the testimony.
Several of these people have separated from the public worship,
under an apprehension that they have seen further; they read much,
and being men of good parts, comprehend much in the head, and can reason and argue,
but will not as yet bow to the lowly appearance of Christ,
nor submit to confess him openly, by a subjection of the will,
and obedience to the truth.
I was much spent with these visits, and the labour in them, and had a fever all night;
yet was favoured with peace; a full recompense.

"`Third-day, very heavy rain the whole day.
In the afternoon a friendly good spirited woman came about four miles to see us.
She had been at several meetings,
and said that the first time she saw us she felt great love,
and would have been willing to entertain us and do her utmost for us,
had we needed her help.
She said, the people had strange notions respecting us.
William Neighmire, the youth before mentioned, also came to visit us.
His father had told him that he would have no more to say to him;
but he meekly asked him what he would have him to do, and speaking mildly to him,
his spirit was brought down.
William`'s faith and patience are much proved, but he appears fixed,
with the Lord`'s assistance, to pursue the path of peace.
Some others came to visit us.
There are many awakened minds, and if they had a few solid Friends with them,
a church might be gathered.
However, the Lord is sufficient for his own work, and as the harvest is great,
is able to raise up and qualify instruments for his service.

"`Fourth-day, we were visited by a man about eighty-four years of age,
who lives about five miles from Bielefeld, and who for thirty years has been,
by the people, called a Quaker.
He told us he was a worshipper of God in spirit, and that he was visited when a child,
but had not been faithful, which was his sorrow now in old age.
But I found he held erroneous notions, and was very full of words.
Silence was recommended to him, and as he acknowledged a failure in duty,
he was advised to be inwardly concerned to seek after Divine favour,
that he might be prepared to meet his Judge;
and cautioned not to trust in part of the work of redemption
being experienced after the death of the body.
He parted affectionately.
I afterwards ventured out, and we visited the merchant mentioned by Sarah Grubb,
having a comfortable religious opportunity with him.
He acknowledged to the truth of what was communicated,
and expressed thankfulness for the visit.`"

John Pemberton mentions seven other visits paid
in various families of serious people that day,
several of which were occasions of tenderness and contrite feeling to those visited.
After this he appears to have felt clear of Bielefeld.

"`Fifth-day, we proceeded to Lemgo, the roads being miry, from the abundance of rain.
Travelling in Germany is very tedious, the carriages being very heavy and clumsy,
and the horses accustomed to go at a walking pace.
The common rate is three miles an hour.

"`Sixth-day, set out from Lemgo about nine o`'clock, after having visited an aged man,
a weaver by trade, who goes under the name of a Quaker.
He seems a serious man, lives much retired,
and hospitably entertains travellers who call upon him.
We had a comfortable sitting with him, in which counsel was opened.
We arrived at Pyrmont about three o`'clock,
and were visited by several of those called Friends here,
and among them the young woman of Bielefeld, Charlotte Vanlaer.
I seemed to dread coming to Pyrmont, and now feel much stripped.

"`Seventh-day, feverish and poorly, and kept much retired;
yet some of the friendly people coming in, we had in the afternoon a comfortable sitting;
but my mind was principally directed towards two
young persons under the humbling power of truth.

"`First-day, ninth month 14th;
Attended two meetings held in a large room appropriated thereto
before these people became much acquainted with Friends.
Although under the ministry given there was much contrition,
yet I feared there were too many contented with the outside of things,
and not sufficiently exercised to press forward.

"`Second-day; this morning, with ten of the more solid part of the Friends,
I took an opportunity with a man of plain appearance,
and generally taken to be one of the Friends,
respecting whom I had been uneasy since the interview with him at Herwerden.
He now discovered himself more fully, as not being one in faith with Friends.
His going about from place to place, and living on the labours of others,
is of bad example and savour,
and he has endeavoured to sow confusion among honest inquirers,
and been the means of scattering and dividing.
He was dealt plainly with, and desired, as he was in the prime of life,
to apply himself to labour for his support.
Friends were cautioned not to give countenance to him, nor in future to entertain him,
as this implied more unity than they had with him, and might mislead the tender youth.
Soon after this conference he went off.

"`Fifth-day; in the evening I visited the agent of the Prince Waldeck,
to acknowledge the kindness of the prince to our Friends in his state.

"`Sixth-day; this afternoon was what the Friends here, call a quarterly meeting;
to which, at times, some from distant places have assembled.
This opportunity appeared like a meeting of conference:
they had to consider the propriety of opening a
school for the instruction of Friends`' children,
and a Friend present offered to undertake it for a while.
I had some remarks to make, which arose in the spring of the gospel.

"`First-day, ninth month 21st; Attended the two meetings, both exercising opportunities.
After that in the afternoon, the members continued together,
and had a satisfactory conference;
in which they united in the propriety of again addressing Friends in England,
that they might come more immediately under their notice and care.
Several of these Friends spoke solidly and feelingly,
that they had long been under an exercise on this account,
and they were glad a way now opened for it.

"`Seventh-day; for a month past, few days have been free from rain.
This damp affects my frame much.
My mind for several days, has been much with my dear friends in America,
as the yearly meeting is approaching.
May the Lord`'s good presence be with them, and furnish with wisdom and strength,
so that all things may be done to his glory in the transactions of the church;
that he may crown the assemblies with his life-giving presence,
that the body may be edified, the weak strengthened,
and the advices issued may be under the seasoning grace and virtue of Truth;
for it is his own works that praise him.

"`The country about Pyrmont is pleasant; the hills generally covered with wood; oak,
beech, birch and alder; and the bottoms are good meadow ground;
yet the land in Germany that I have seen, is generally a poor soil.
The roads are the most crooked and difficult for a stranger, of any country I ever was in.
I think that as to the generality of what I have travelled,
one third of the distance might be saved by making them more straight.
Scarcely any pains are taken with them, and on these wide commons there are,
except in a very few places, no direction posts.
But what served their forefathers, they make serve them.

"`First-day, 28th; Still at Pyrmont, and attended the two meetings;
also a conference with Friends in the evening,
in which they opened several matters which were subjects of trial to their minds;
and through gracious help, we offered the best advice we could.
They are tender, and desire to do right.

"`Fourth-day, attended the mid-week meeting at Pyrmont, which was laborious,
yet ended satisfactorily.
Next day, having been invited by the chief magistrate,
we spent about three hours with him and his family;
and expressing a desire to see the children, the wife readily collected them.
They sat down, and something was given to speak to them.
Much respect was shown us, and considerable discourse we had; but he was too full of talk.
We parted affectionately.

"`Sixth-day, a meeting being appointed at a village about two miles distant,
I walked there.
It was a very low exercising time, and a long space of silence;
yet there are some seeking, well-minded people.

"`Third-day, tenth month 7th; Paid a visit to a man esteemed a great lawyer,
and spent about two hours with him and his wife.
I showed them my certificates,
and had some serious conversation respecting the motive of leaving my native country.
Their minds appeared solidly impressed.
This man had been, some time past, much prepossessed against Friends,
and joined with others to give them trouble;
but the interference of the Prince Waldeck gave a check to them, and they are now quiet.
I trust this visit will prove no injury to the cause and testimony of truth.
He behaved well, and we parted respectfully.

"`Fourth-day, the meeting was well attended,
though some Friends had to come two miles through the rain and mire.
After meeting I had about ten ounces of blood taken.

"`Sixth-day; Frederick Seebohm, at whose house we are entertained, has five children,
and shows much religious care over them.
He instructs them in reading and writing, and has daily a sitting with them in silence.
I was this day at one of their little meetings, the four eldest being present.
They sat very quietly,
and the father`'s mind seemed bowed and exercised on his own and the children`'s behalf.
This little meeting held about half an hour,
and then the children were put to their books.
If this were more generally the practice of parents,
that rawness and undisciplined conduct,
which is too apparent in many places and families, would be removed,
and much profit redound to parents and children, and consequently to religious society.
For the Lord would not fail to bless such care, and would grant counsel.
May the world be less regarded,
and the knowledge of God and his ways be more diligently sought after,
that the durable riches and righteousness may be experienced and possessed.

"`First-day, 12th;
I was most easy to propose that the afternoon
meeting should be put off till three o`'clock,
and the inhabitants of the town invited; and Friends agreeing thereto,
we had a very crowded meeting, many not being able to get into the house.
The Lord condescended to favour, and the people behaved well.
Many came afterwards to take us by the hand, and appeared solid; among them two Jews,
one of whom was at meeting on first-day last.
After this public meeting we had a sitting with those who generally frequent the meeting,
and suitable counsel, caution and instruction were opened to them.
It was a contriting opportunity; but I was left poor, which may be safest for me.

"`On second-day, after visiting three families at the factory,
my way opened to leave Pyrmont for a time; and on third-day,
having through the Lord`'s mercy, considerably recruited in my health, with an easy,
quiet mind, and a humbling thankful sense that I had done what I could,
I set out about ten o`'clock for a town called Barrentrop,
which we reached on horseback in about two hours.
Hearing of some religious people, some of them were spoken to,
and in the evening we were visited by two men and two women,
to whom such counsel as then arose, was communicated; but the fear of man,
which brings a snare, had great place in their minds.
Next morning I was most easy to propose a public meeting,
and visiting the minister of the place, we mentioned it to him, and asked his company.
He said prudence was needful, and that he would rest at home;
but in the course of what passed at the interview,
he remarked that some matters were more clearly
stated and opened than he had before conceived,
and he parted with us affectionately, saluting each of us.
One of the seeking people who have separated from the priests,
undertook to give general notice; but his landlord, an envious old man, bitter,
and drinking to excess, threatened to turn him out if he did so.
An aged woman therefore spread the notice, but met with abuse from some,
who spat in her face; and an envious magistrate spread terror among the people.
He would not be reasoned with,
nor would he receive William Penn`'s '`Rise and Progress,`' which was offered to him;
but threatened me with the Stadt-house,
until the Prince de la Lippe`'s mind should be known and said we deserved to be taken up,
for walking the streets and spreading our principles.
He afterwards sent to tell me that he fined me five dollars, and forbade the meeting.

"`However, about the time appointed we sat down, and a few sober people with us;
but some rude boys rattled at the window shutters, and a man said to be the rector,
and master of a free-school in the town, came with a fiddle, and played for some time.
My mind, however, was kept quiet,
and I found it my place to sit about two hours in silent suffering;
at the close I had to make some remarks on the impropriety of
such conduct with the profession of a Christian.
Many people were in the barn adjoining the room we were in.
I told the children that their conduct resembled that of some children formerly,
who cried to the Lord`'s prophet, '`Go up, you bald head,
go up!`' and the Lord`'s displeasure was manifested to these.
This seemed to strike some of them with seriousness.
It was a painfully exercising time, but the people departed quietly.

"`Next morning, after paying two visits, we mounted our horses,
and about ten o`'clock left Barrentrop, hearing no more from the magistrate.
We proceeded to Lemgo, where we were cordially received.
Having taken a bad cold in a damp bed at Barrentrop, it increased, and I became ill;
I sent for a physician and had much blood taken, but was confined here a week,
and much oppressed in body and mind.
We were visited by several of the inhabitants,
and my companions had opportunities of dispersing books
and opening our religious testimonies.
On first-day I sat at the public table,
and my mind was drawn forth in humble supplication, which Lewis Seebohm interpreted.
A meeting being appointed to be held in the evening,
many gave expectation of attending it; but a magistrate,
of like persecuting spirit with that at Barrentrop, spread fear among the people,
so that our number was small.
As it was held in my chamber, I was enabled to sit throughout.
The Lord condescended to favour us, so that we had a comfortable meeting.
The aged landlord and his wife attended, and sat solidly.

"`The next morning the magistrate sent a request to see my certificates,
which I had shown to sundry persons last evening,
that he might satisfy the people who we were;
for some had surmised here and at the other town, that we were spies sent by the French,
to spy out the country.
He expressed himself satisfied, but said that we must not hold meetings,
and advised our leaving the place speedily.
My companions, for I was too unwell to go to him myself, told him,
that when we thought it right so to do, we should leave the place, and not before.
He was very angry, giving very little opportunity to say anything to him,
and sent word to an aged friendly man, who is one of Zion`'s travailers,
that if he came again to visit us, he should depart from the town.

"`On fourth-day I had proposed to hold another religious opportunity in my chamber,
but from the fear which had spread, and little notice having been given, we had but two,
the aged Friend and another man.
To the latter much was said to excite to deeper consideration, and the aged Friend,
to whom encouragement was administered, was much affected.
He dwells, as it were, alone, among a lifeless professing people,
yet is preserved in much innocency and liveliness.

"`On fifth-day morning, in a very weak state of body,
being wrapped up warm and placed in a carriage,
I was favoured to arrive safely at Pyrmont.
Although our visit to Barrentrop and Lemgo was attended
with much exercise and conflict of spirit,
yet we all felt that the journey was in the Lord`'s will.
L, Seebohm said it did him more good than much money,
in hopes that it may awaken some minds to behold the evil of a persecuting spirit,
and to see that those who are on a right foundation do not fear the threats of men,
so as to be discouraged from performing their religious duty,
I thought I saw my way as clear to these places, as any I have visited;
yet I did not expect to find such a persecuting spirit.
The poor man at Barrentrop, who was threatened by his landlord,
afterwards visited us at Pyrmont, and informed us that his landlord had warned him out.

"`Eleventh month, 8th; There are nearly twenty here who are considered as members,
yet there are several lively spirited innocent persons, not yet brought into membership,
and the number who usually attend the meetings, is between forty and fifty.

"`My lungs have been much hurt, and my body greatly reduced; yet the Lord, through all,
has mercifully supported my mind in much calmness and resignation,
and it is my desire that these afflictions may tend to my greater purification.
My steps in Germany, hitherto, have yielded me more satisfaction than any former journey;
yet there are seasons of buffeting, deep wading, and close baptisms,
and I am mercifully kept poor and dependent, a safe state for me.
The end of my journeying in Germany is now hid from me,
and as I have been mercifully preserved hitherto, to wait in patience for the true light,
so I desire to be kept patient.

"`As B. Holmes`'s '`Serious Call`' is allowed by
many to be as suitable as almost any tract,
for the middling class of people,
I have proposed to Friends in London to have a fresh translation in the German;
and it is a matter of great importance to have translations made by a Friend,
who being well acquainted with the principles we hold,
can readily take the author`'s meaning, and do strict justice.`"

Speaking about this time of the prevalent dangerous practice
of our young persons travelling on the continent of Europe,
John Pemberton says: "`A Friend in England makes this remark:
'`What advantages in the view of thoughtful parents,
can possibly compensate for the exposure of their children to the
dangers which surround them in these tours for improvement?`"
And he adds his own belief that, "`nine out of ten become vitiated,
and deny their religious education, "`30th; Still at Pyrmont, and very tender,
having been slow in recovering,
yet have attended all their meetings as they came in course, except two; and this day,
appointed a public meeting, which was large and solid,
and rendered satisfactory through the goodness of a gracious God.

"`Twelfth month, 14th; The last week has been a deeply exercising time to my mind.
This afternoon was a public meeting, and I laboured according to ability given;
but the people are superficial, and know little of vital Christianity, resting in a form,
and depending on the priests, outward ceremonies, and will-worship.

"`18th,`" This afternoon the chief magistrate visited us,
and spent about four hours with us.
He is a worldly-wise, and eloquent man.
Much conversation passed respecting gospel ministry; and although,
to support the priests, he for a time, argued that such who attend on the altar,
should live of the altar, and others should labour in order to support them,
yet in the end he seemed to acknowledge it would be better otherwise.
My companions represented how much good he might do, if he sought for divine wisdom,
and was guided thereby, in judging of matters,
regarding the tender scruples of conscientious persons.
His mind appeared reached, and he said that if the present priest should be removed,
some agreement might be made before another was established,
to prevent some difficulties which now subsisted.
He parted from us respectfully, inviting us to visit him at his own house.

"`First-day, 21st; The meetings this day, as well as on fourth-day,
have been exercising opportunities.
I was favoured with letters from my dear brother and wife,
mentioning the removal of many inhabitants of Baltimore, and some few in Philadelphia,
to their everlasting home, by the yellow fever;
also an epistle from the meeting for sufferings in London to Friends at Pyrmont.

"`28th; All last week I was very unwell with an inflammatory fever,
and am again reduced to a weak state.
At meeting this morning I was led in a close searching line,
to stir up and awaken the attention of the professors of truth here,
many of whom are much at ease.

"`First-day, first month 4th, 1795; Yesterday I was very unwell,
as I had been all the week, and spent the night heavily,
which appeared as though it might have been my last.
In the afternoon of this day a chilliness came over me,
with symptoms of a closing time being near; under which, through the Lord`'s mercy,
my mind was preserved calm and resigned.

"`First month 11th; All the past week I have continued in a tried situation,
and have become very weak, yet favoured with patience and resignation.

"`18th; Reduced to a very weak state.
This evening I had a solid conference with two persons, who have shown a self-confident,
ranting spirit.
They were brought down, and acknowledged their error.
My companion was helped to set the testimony over such exalted self-righteous spirits,
which despise dominion,
and are not willing to be subject to the discipline and good order,
in wisdom established among Friends, but call it the prescription of men.

"`The frost continues severe, and by the advance of the French into Holland,
the intercourse by post is stopped.`"

[.asterism]
'''

The above is the last entry in his diary.
The following account of his illness and peaceful close,
is taken from a manuscript in the hand-writing of his friend, William Dillwyn:

"`On the 23rd of the first month, he appeared in the morning to be much better.
In the afternoon of that day some Friends came in to see him.
Very soon afterwards he was suddenly seized with a chill and fever,
which obliged him to go to bed.
His illness continued the succeeding night, accompanied with vomitings,
and such pain in the breast and side, that his surviving until the morning,
appeared doubtful.

"`On the 24th he continued very ill.
The physician came in the morning,
and regularly repeated his visits twice a day afterwards.
On his expressing a wish that the medicine prescribed might answer the purpose intended,
John Pemberton answered, '`My hope is in the Lord.`'

"`The 25th, he appeared to be no better, though very quiet and resigned;
never uttering an impatient word, although in much pain.
The 26th, he seemed in the morning to be a little better;
but towards evening his pain increased.
His physician now intimated a doubt of his recovery.
In the evening,
understanding that his friends were under difficulty
from the arrival of some hundreds of soldiers,
French emigrants, to be billeted on the inhabitants of Pyrmont,
after a little pause he said, '`Friends are often brought to the difficult and narrow gate,
and therefore it is necessary to act in the counsel of best wisdom;
and if anything is imposed on them by the laws of the country,
or the authority of the magistrate,
to suffer it in the meek and patient spirit of Jesus.`'

"`On the 28th, in the morning, he had a little sleep.
In the evening a hiccough came on, which increased the apprehensions of danger.
Before noon, being raised up, and his companion sitting behind to support him,
another of his friends being also present, he expressed himself to this import:
'`Friends who live in the truth, and are concerned to fulfil their religious duty,
have often deep proving seasons to pass through,
before they come to a clear discerning of the Divine will,
with respect to leaving their own habitations; and when they come at that,
and travel abroad in the service of the gospel,
they have also many and deep baptisms to pass through:
but on looking over my stoppings along in this land,
I have had to believe that I have laboured faithfully to discharge my duty,
and have peace therein;
although in the present sickness I have felt more poverty of spirit than in
those heretofore;`' with more weighty observations not well recollected.
The Friend mentioning his firm belief that his coming among them was in best wisdom,
and that his religious labours had been useful and acceptable to the sincere-hearted,
and attended with a blessing, he replied,
'`I have nothing to boast of.`' In the evening a young woman came in,
whom he desired to sit down, and after a pause, he said in the words of the apostle,
'`Let brotherly love continue;`' adding, '`This is not only necessary for the men,
but for the women also;
and without this we are but poor creatures.`' Afterwards he delivered
some tender counsel respecting the little Society at Pyrmont,
for which he seemed to be much concerned.
He intimated also that the event of his present illness was hid from him;
but instructed his companion, if he should be now taken away,
to write to his beloved wife and to his kinsman in London,
remembering his dear love to them, and informing them of the particulars of his decease.

"`The 29th, on his awaking in the morning,
the physician said he thought his disorder not worse;
but his natural strength being much exhausted, and the hiccough continuing,
he had but a poor day, and little sleep.
In the course of it, he said,
'`It seems to draw nearer and nearer to the solemn
close.`' On the 30th the disorder much increased;
in the afternoon, he said, '`I have not been so tried in any sickness in all my life,
although I never experienced so much of the love of God,
in any of my journeys heretofore, as I have in this.`'

"`On the 31st,
about three o`'clock in the morning he was a little relieved from the
oppression and difficulty of breathing which he had laboured under;
and said, '`It is a great favour to know that my Redeemer lives; and because he lives,
I live also:`' expressing also, to his companion,
and the friend who had mostly assisted him, his sense of their kindness,
and of the care with which he had been nursed,
and also his wishes for their growth and increase in all that is good.
That friend remarking how pleasing and encouraging it was to see him so much resigned,
he answered nearly as follows: '`Ah, we may see miracles are not ceased!
Great and marvellous are His works.
He is mighty to save, and able to deliver to the very uttermost,
all those who trust in Him.
His ways are ways of wonder, and past finding out.`' Between nine and ten o`'clock,
the physician, after feeling his pulse,
intimated his opinion that he would not continue much longer.
Asking what the doctor said, and being informed, he said calmly, '`We must be resigned.
We must be resigned.`' This answer, and the composed manner in which it was delivered,
affected the physician so much,
that he expressed his surprise and pleasure at seeing him, in such circumstances,
so resigned; on which he said,
'`This is what we all are taught to labour for.`' After this
he said much on the different spirits which were endeavouring
to persecute and lay waste the Lord`'s church,
adding, '`My heart is heavy on account of these things;`' and again,
'`The spirit searches all things, yes, the deep things of God:
We should perfect holiness in the fear of God.`' After some other expressions,
evincing the awful collected frame of his spirit, he added,
'`But I do not want to launch into many words,
but to bring into a sameness of soul.`' About noon, he said triumphantly,
'`I am departing for heaven; from you all,
to the kingdom of God and of Christ.`' His mind
now seemed to be wrapped up in divine love,
continuing to speak of God, of Christ, and of his kingdom;
and the last words which could be distinctly understood,
uttered about two o`'clock in a melodious voice, were, '`I can sing the songs of Zion,
and of Israel.`' After this, he continued to breathe easier and easier,
until about fifty minutes after six o`'clock in the evening,
when his gentle spirit was released from its earthly tabernacle.

"`On the 3rd of the second month,
his body was solemnly interred near the centre
of the burying ground of the Society in Pyrmont,
in the plain simple manner directed in a paper written
by himself in the preceding eleventh month,
addressed to his companion, and endorsed,
'`to be opened after my decease;`' the spectators of this, to them, new scene,
manifesting their satisfaction on the solemn occasion.`"

Thus peacefully, though in a foreign land, was gathered to eternal rest,
the spirit of one who had long borne about in the body, the marks of the Lord Jesus,
and who had waded in deep and oft repeated
baptisms for the welfare of the church of Christ.
He was a man of great meekness and gentleness,
but firm in maintaining the faith once delivered to the saints.
He was remarkable for the low estimate in which he held his own Christian attainments,
preferring others to himself,
and ever seeking the unity of the true members
of the church in his religious engagements.
To such a degree indeed, did he value this unity, that on one occasion,
finding that some had imbibed uneasiness respecting his services in the ministry,
he travelled several hundred miles and presented himself before these his brethren,
requesting a full and open development of their feelings,
in order to a removal of the ground of jealousy.

One who knew him well, and accompanied him in one of his journeys in Scotland,
speaks of him in the following terms:
"`My heart feels a tender sense of his sincere benevolence and worth,
that I know not how to express.
He was indeed a disinterested man.
The desire of wealth and distinction, and the general pursuits of other men,
seemed hardly to make a part of his motives.
The glory of God and the good of his fellow-creatures,
seemed to be the pure spring of his actions.
I have been told that on the day of his marriage,
a time when most men are so taken up with their own happiness,
as to forget that there is misery elsewhere,
he ordered provisions to be sent to all the prisoners in Philadelphia.
I have also been informed, that frequently on market days,
he would himself go and lay out his money for the like purposes.
Yet, humble in all his expectations, and diffident of his own attainments,
I remember when we were once conversing seriously on the subject of futurity,
he observed, '`When the Almighty sees fit to release me,
I should be thankful to be at rest.`' The true
Christian is ever lowly in his pretensions,
and more concerned for the work than the reward,
in resignation leaving all to the righteous Judge of heaven and earth.

"`In his disposition he was modest;
yet when his duty led him among the great and distinguished, his manner was plain,
solid and dignified.
To the different ranks of sober people, he was open and communicative.
He was likewise an uncommon observer of what passed before him on the stage of life,
not only beholding with ready attention the conduct of mankind where he came,
with a judgment of its tendency,
but also having a knowledge of the various regulations
of general society and of the useful avocations of life.
In the public prisons, those receptacles of human wretchedness,
the sweet influence of his Christian charity was diffused,
not only in donations to relieve the misery of hunger and want,
but in expressions of kind concern for that part which never dies.
His reverence for the Divine Being was very great,
and he felt little less than anguish of heart,
if at any time he heard the holy name profaned.
His reproof on these occasions was indeed serious, and his expostulations were earnest;
evincing a conscientious love and duty to the Almighty and an interest for
the eternal well-being of those who were transgressing his law;
and he seldom failed of bringing such transgressors to
own the evil and express their sorrow for it.

"`In his life and conversation he was a preacher of righteousness.
His conversation and conduct were instructive, edifying and impressive; and,
distinct from his labours as a minister, the cause of religion, sobriety and virtue,
was forwarded by his company.
His innocent mind, as in its sphere, seemed to delight in the company of children;
yet he paid perhaps a still more marked attention to age and infirmity;
and I do not remember sharper expressions of his disapprobation,
than when he found the hoary head insulted, and the claims of declining years neglected.

"`To the poor he addressed himself with great tenderness and condescension.
It was admirable with what interest, ease and delicacy,
he would enter into the private concerns of poor families, with a view to do them good:
he might, indeed, be said to be the poor man`'s confiding counsellor and friend.
If the sober and industrious lacked capital to begin business,
if he had it not of his own, he went to borrow for them,
and entered into security for the payment.
And when the solemn undertaking of his visit to Great Britain was drawing to maturity,
lest any should suffer by a transaction in which he had any concern,
he came to a resolution of disposing of estates, I have been told,
to a considerable amount, paid off the sums for which he was engaged,
and took the securities upon himself.

"`When the good order of our religious Society required his assistance,
either in supporting the testimony, or in dealing with delinquents,
he proceeded with that religious boldness that
accompanies a conscientious and disinterested mind.
In what concerned its religious order and economy,
he was clear in his conceptions and ready in expression;
yet to the judgment of others he paid the greatest deference.
If his patience was at any time suspended,
it was when he thought he had fallen short in the performance of his religious duty,
often saying, '`Ah!
I am a poor unprofitable servant;`' yet many can bear testimony,
that health and strength of body, and the comforts of this life,
were sacrificed to the service of his great Master.`"

"`Behold an Israelite indeed, in whom is no guile!`"
