[#testimony-phila.style-blurb, short="Testimony of Philadelphia Monthly Meeting"]
== Testimony of the monthly meeting of Philadelphia, concerning John Pemberton.

He was the son of our valuable and much esteemed friends, Israel and Rachel Pemberton.
By an early sense of the Divine fear, joined to their parental care and pious example,
he was preserved from the delusive vanities and evils into which youth,
through the force of temptation and overlooking the monitions of Divine grace,
are often seduced; so that under the Lord`'s favour and blessing,
the remark of Solomon was verified in him: "`Train up a child in the way he should go,
and when he is old he will not depart from it.`"

He was born in this city, the 27th of the eleventh month, 1727.
On coming to manhood he proceeded on a voyage to England,
in the same vessel with our beloved friends John Churchman and William Brown,
who were drawn in gospel love to visit the churches in that country and parts adjacent.
His inducements to this voyage appear to have been business,
and for the benefit of his health but soon after his arrival in London,
feeling his mind religiously inclined to accompany John
Churchman to a few meetings in the country,
he was further engaged to continue with our said Friend
in his travels through most parts of England,
Ireland and Holland.

In the early part of this journey, at a meeting held at Penzance, in Cornwall,
he said a few words in public testimony; and, as John Churchman relates,
"`tender and broken, accompanied with a good degree of the savour of truth.`"
Thus, though he left home on temporal concerns, having received a Divine call,
he may be said to have done, in measure, as the disciples of our blessed Lord,
who left their nets and followed him.
Having travelled together about three years, they parted in much love and unity.

His ministry was sound, instructive and edifying;
being concerned to inculcate the necessity of great
circumspection of life and purity of conversation,
that thereby our religious profession might be adorned through
humility and a reverent sense of the Lord`'s omnipotent care over us.
He was very useful in our meetings for discipline,
being zealously concerned for the support of our
Christian testimony and the good order of the church;
manifesting a tender regard to such as had missed their
way and became the objects of care on that account.

He was careful in the remembrance of the apostle`'s exhortation,
to visit the fatherless and widow in their affliction,
and to keep ourselves unspotted from the world; so that it may be truly said of him,
he was ready to do good and to communicate,
and to honour the Lord with his substance and with the fruits of his increase.

Feeling an engagement of gospel love to visit the churches in Europe,
and having the concurrence of his brethren, he embarked for London, at New-York,
in company with our friend William Mathews, in the twelfth month, 1782.
The vessel being taken on her passage, in the English channel, near the isle of Wight,
by a privateer from France, they were carried to Dunkirk; though soon after released,
and arrived in England in the second month following.

He continued in England, visiting the meetings of Friends in various parts,
until the ensuing yearly meeting held in London, which he attended;
from which he proceeded to the northern counties, and embarked at Liverpool for Dublin,
where he arrived in the seventh month.

In the fifth month, 1785, he returned to England,
and attended the yearly meeting held at London in the sixth month following;
from which he proceeded to the western parts of that nation, and from there to Scotland,
visiting the Orkney islands and several other places.

He spent about two years in that country,
where his religious labours appear to have been very acceptable,
especially to the poor people inhabiting the Orknies.

After his return from there, he remained in England,
visiting the meetings in London and many other places, till the seventh month, 1789,
when he embarked on his return to this city.

After continuing mostly with his family several succeeding years,
sometimes visiting meetings in the neighbourhood of this city,
and those more remote in the adjacent country,
a concern under which his mind had been exercised
previous to his last return from Europe,
from an apprehension of not being fully clear of some parts thereof,
continuing and becoming increasingly weighty,
he revived and spread the same before his brethren;
and obtaining their concurrence to return there, embarked in a ship bound for Amsterdam,
the 28th of fifth month, 1794, arriving there the 12th of seventh month following.

Previous to his embarkation,
his mind being deeply impressed with reflections on the uncertainty of life,
and affected with a tendering sense of the Divine
goodness and mercy extended for his preservation,
he left some observations in writing, from which the following is extracted:

"`When I view my steps in life, and reflect how greatly deficient I have been,
am humbled,
and have great cause to admire the great compassion and
long-suffering kindness of a gracious God,
and with abasement, acknowledge it will be of his mercy, if I am saved.
If I have been helped at times to be found faithful, it has been,
and is through the efficacy of grace, and therefore no room to boast.
My failure in duty and watchfulness has been great.
Through the religious care of pious parents when young,
and an early sense of the Divine fear,
I was and have been preserved from the gross evils of the world to this day,
which is a great mercy and favour.
But I have often passed under many hidden conflicts for disobedience and failure in duty,
and at times ready to despair, and had to acknowledge the Lord is righteous,
whatever might be my portion; but after days of sorrow and nights of deep exercise,
he has been pleased to renew light and favour;
under a sense of which I desire to be found more attentive, diligent and faithful,
the residue of my days,
esteeming the light of the Lord`'s countenance and the evidence of his peace,
beyond all terrestrial enjoyments.`"

He remained at Amsterdam a few weeks;
in which he appears to have been engaged in religious
labour towards the inhabitants of that city,
to whom he addressed some "`Tender caution and advice,`" which was printed in Low Dutch,
and distributed amongst them.

Finding his mind drawn to visit the few Friends settled at Pyrmont, in Germany,
he proceeded on the journey, and got to Hertford, in Westphalia,
the 27th of eighth month.
The next day, walking about five miles to see some religious people,
and being caught in the rain, he took a heavy cold;
the effect of which he never fully recovered.
After being some time confined there, he was enabled to proceed by Ufelen, Bielefield,
Lemgo, Barrentrop, etc., to Pyrmont, where he arrived the 12th of ninth month,
having had meetings and acceptable service at all the before mentioned places,
and many others on his way from Amsterdam, particularly at Bielefield,
where he had a large public meeting, and many select opportunities,
and also visited numbers of the principal inhabitants, being generally well received,
and his religious labours appearing to be acceptable.
A memorandum made the 6th of ninth month, when at Bielefield, says,
"`The chill and fever renewed; I was very unwell all the afternoon,
and it continued till midnight with a great thirst: yet,
through the adorable mercy of a gracious God,
I felt more of the incomes of his love and life-giving presence,
than I have experienced a long time; that I was enabled to make melody in my heart,
and recount his fatherly care and tender dealings with me, from the days of my infancy;
and I had to bless his holy name.
And this comfortable visitation of his love and mercy continued for some hours,
that I was ready to conclude I might soon be released
from the trials and afflictions of this life.`"

Between this time and the latter end of the tenth month,
he had several public meetings at Pyrmont, Barrentrop and Lemgo,
though not without some opposition at the two last places;
and notwithstanding his weak state of health,
he regularly attended the meetings of those professing the truth at Pyrmont,
having also many private opportunities with them in their families;
faithfully labouring for their settlement on the true foundation.
His bodily weakness increasing, he was unable to travel,
and was much confined to his bed; but about the middle of the first month, 1795,
he was so much better as to be able to walk about his chamber,
and his physician thought him almost out of danger.
A few days after, he was suddenly seized with a chill and fever,
which again confined him to his bed; and his illness so increased the succeeding night,
that his surviving until the morning appeared doubtful.
He continued very ill for several days,
yet was favoured with much calmness and resignation of mind.
On the 27th he was easier, but said, "`If I get through this time,
it will be a hard struggle.`"
On the 28th, being raised up by his desire, he expressed himself to this import:
"`Friends who live in the truth, and are concerned to fulfil their religious duty,
have often deep proving seasons to pass through,
before they come to a clear discerning of the Divine will,
with respect to leaving their own habitations; and when they come at that,
and travel abroad in the service of the gospel,
they have also many and deep baptisms to pass through.`"
The 29th, his natural strength being much exhausted, he said,
"`It seems to draw nearer the solemn close.`"
On the 30th, the disorder much increased.
In the afternoon he said, "`I have not been so tried in any sickness in all my life;
although I never experienced so much of the love of God in any of my journeys heretofore,
as I have in this.`"

On the 31st, about three o`'clock in the morning,
being a little relieved from the oppression and
difficulty of breathing which he had laboured under,
he said, "`It is a great favour to know that my Redeemer lives, and because he lives,
I live also,`" Between nine and ten o`'clock the physician intimated his opinion,
that he would not continue much longer: asking what the doctor said, and being informed,
he replied calmly, "`we must be resigned--we must be resigned.`"
This answer, and the composed manner in which it was delivered,
affected the physician so much, that he expressed his surprise to see him,
in such circumstances, so resigned: on which he said,
"`This is all we are taught to labour for--we
should perfect holiness in the fear of God.`"
About noon, he said, triumphantly, "`I am departing for heaven, from you all;
to the kingdom of God and of Christ.`"

His mind now seemed to be wrapped up in Divine love, continuing to speak of God,
of Christ, and of his kingdom; and the last words which could be distinctly understood,
uttered (about two o`'clock) in a melodious voice, were,
"`I can sing the songs of Zion and of Israel.`"
Near seven in the evening, he departed,
being in the sixty-eighth year of his age:--a minister about forty-three years.

On the 3rd of the second month,
his body was solemnly interred in the burying
ground of the Society professing with Friends,
in Pyrmont, in a plain manner, which he had directed; the spectators of this,
to them new scene, appearing to be much affected on the solemn occasion.
