[#testimony-pyrmont.style-blurb, short="Testimony of Pyrmont Friends"]
== Testimony of the monthly meeting of Friends at Pyrmont, in Westphalia, Germany, concerning John Pemberton, of Philadelphia, in North America.

Seeing it is recorded in Holy Writ, and confirmed by experience,
that the "`memory of the just is blessed;`" and our beloved friend John Pemberton,
having, on a religious visit to Friends and friendly people in this nation,
finished his course, and laid down his head in peace amongst us;
the consideration of his religious service,
and the lively sense thereof remaining fresh and as a good savour on our minds,
has engaged us to transmit a testimony concerning this our beloved friend, to posterity.

He was often led, in a manner unusual in these parts, to go into unknown houses,
gather the family about him, and after an awful pause, to distribute wholesome doctrine,
counsel and advice among them.
This manner, as it were, like in the apostles' days,
to break the bread from house to house, seemed sometimes at first to surprise the people;
but when, after a short while,
their minds were overshadowed by that invisible power which accompanied his words,
and the witness of truth in them was reached, tears were often beheld to flow;
and at parting,
the unknown were observed to take their leave of him as if well acquainted,
in a tender and affecting manner.

His arrival at Pyrmont was on the 12th of the ninth month,
and his stay amongst us about four months;
during which time he was mostly very poorly in health,
but nevertheless almost daily occupied in the service of Truth;
for as his bodily health permitted him,
he not only attended punctually our public and monthly meetings,
and visited Friends in their families,
but had also many private opportunities and
several public meetings with the town's-people,
which were very numerous,
and wherein he was enabled to preach the free gospel of Christ with Divine authority;
so that not only sometimes the whole assembly
seemed to be clothed with an awful reverence,
but also the hearts of many were moved, and the witness of God in them reached,
by his living testimony.
At such opportunities, he seemed,
to the admiration of those who knew his weak constitution,
not to feel his bodily weakness at all, usually lifting up his voice as a strong youth,
to testify of the great love of God towards mankind.

It was his principal concern to turn people from darkness to light,
and from the power of Satan to God;
endeavouring to show that God has given a measure of his Spirit,
light or grace to all men, as a talent, which he has placed in their hearts.

His ministry was in plainness of speech, and attended with Divine authority;
for his words, whether they contained exhortation, comfort, or reproof,
reached the inward states of those whom it concerned; and he has often spoken,
both in our meetings and at other opportunities, so exactly to the state of individuals,
that there was no doubt left, but he was led by the unerring Spirit of Truth;
and more especially in his particular service among us,
as fellow-professors of the same principles of that unchangeable truth,
for the promotion of which he spent his life.

The solemn reverence of his waiting spirit appeared so manifest in his countenance,
that others who beheld him, were thereby invited to stillness;
and such as had a desire of hearing words,
were taught by his example to turn their minds inward,
to the measure of grace in themselves;
showing that it is infinitely better to keep silent before the Lord,
than to utter words that are not accompanied with the
life-giving and baptizing power of the Spirit;
which must needs enliven them if they be truly profitable.

After his return to Pyrmont, he had repeatedly accesses of an inflammatory fever;
and on the 23rd of the eleventh month, in the evening,
it seized him so suddenly with a violent chill,
that he was obliged to leave the company of some friends, who were come to see him,
and go to bed.
Next morning the physician came to see him, and at parting,
wishing him that he might get better; he replied,
"`my hope is in the Lord;`" and he continued in a patient, resigned state of mind;
although to appearance, in great pain of body.
His mind seemed to be totally free from temporal concerns,
and only occupied with objects relating to everlasting truth: and particularly,
he seemed much concerned for the welfare of the little Society of Friends in this place,
even to his very last moments.

A few days before his decease,
his companion mentioned to him a strait and difficulty
that Friends of Pyrmont were brought under,
by reason of several hundreds of French emigrants who
were come to take up their winter quarters,
and to be billetted on the inhabitants of Pyrmont.
After a little pause, he said in substance as follows:
"`Friends are often brought to the strait and narrow gate;
and therefore it is necessary and incumbent for them to act in
the counsel of best wisdom and if anything is imposed on them
by the laws of the country and the authority of the magistrate,
to suffer it in the meek and patient spirit of Jesus.`"

His disorder having much increased, he suffered exceedingly;
but kept remarkably patient and resigned;
and being a little relieved from the great oppression
and difficulty of breathing which he had laboured under,
he said, "`It is a great favour to know that my Redeemer lives,
and because he lives, I live also.`"
This he expressed about three o'clock in the morning of the 31st,
being the day of his decease; and a little after,
he said to his companion and the Friend that assisted him, "`You are very kind,
and I have been carefully nursed;
I wish you may grow and increase in every thing that is good,
and become a spiritual and holy house unto God.`"
A while after, a friend said to him,
that it was pleasing and encouraging to see him so much resigned;
to which he replied nearly as follows:
"`Ah! we may see, miracles have not ceased;
great and marvellous are his works;
he is mighty to save and able to deliver to the very uttermost,
all those that trust in him; his ways are ways of wonder and past finding out.`"
And about nine o'clock, he said, "`The Spirit searches all things; yes,
the deep things of God.`"
Seeming to be much exercised in his mind about the professors of Truth at Pyrmont,
he said, "`Some are now very full of themselves, and are persecuting the Lord's church;
but it is a wrong spirit.
There is a spirit that is doing the church much harm; but I am not of that spirit,
and it is best to avoid that spirit which sets up for itself.
They run from one evil spirit to another; and it is a deceiving spirit.
My heart is heavy on account of these things.`"
A while after this, he said again, "`The Spirit searches all things, yes,
the deep things of God.`"
And then, a little after, he expressed himself nearly as follows:
"`The fear of the Lord is a fountain of life, which opens the mysteries of God's kingdom;
but the wisdom of this world is foolishness with God;`" adding,
"`but I don't want to launch into many words, but to bring into a sameness of soul.`"
About twelve o'clock he said in a triumphant manner,
"`I am departing for heaven, and from you all, to the kingdom of God and of Christ.`"
After this he said, "`You can prove these things,
whether they are agreeable to the scriptures of God and of Christ, yes or no.`"
And then he expressed in a weighty manner nearly as follows:
"`It is not circumcision nor uncircumcision, but a new creature.
Faith comes by hearing, and hearing by the word of God,
which lives and abides forever,`" And a little after, "`They who are justified,
are justified by the faith of Jesus Christ.`"
And afterwards he earnestly said, "`Woe unto the world because of offences.`"

His mind seemed to be overcome with Divine love, and his words were of God,
and of Christ and his kingdom: and the last that could be distinctly understood,
which he uttered with a melodious voice, were these:
"`I can sing the songs of Zion and of Israel;`" which is a
demonstrative proof that he had not followed cunningly devised fables;
but the living substance of Truth and true religion.
