== Chapter II.

[.chapter-synopsis]
* Second visit to Europe
* Travels in England and Ireland.

"`Having had the concurrence and unity of the monthly, quarterly,
and yearly meetings of Friends, to which I belonged, in the religious exercise of mind,
which the Lord, as I apprehended, begot in me,
to resign to his will in visiting my friends in Europe;
I used diligent endeavours to settle my worldly concerns;
in which I reverently acknowledge the Lord made way for me; and in the fourth month,
1782, it appeared to me best to join our dear friend William Mathews,
under a like religious engagement.
At our quarterly meeting of ministers and elders, held on the 4th of fifth month,
I was free to let my dear friends know, that the time for me to leave them appeared near;
which quickened my attention to do everything that appeared necessary, previous thereto.
This kept me busily engaged, visiting divers Friends;
with some of whom I had seasonable opportunities,
in which the softening virtue of Truth prevailed, and I hope,
made profitable impressions.

"`Second-day, sixth month 10th, 1782;
Many Friends came to take their leave of me in much affection,
and we had some solid opportunities in retirement that evening and next morning.
My heart was humbled under a sense of the love, sympathy and concern for me,
begotten in the hearts of my dear friends and some others.
Having parted with them and my tenderly beloved wife,
accompanied by my dear brother James, etc., I set out to overtake William Mathews,
who was then visiting meetings in Bucks county.
Previous to his leaving the city, viz: on the 23rd of fifth month, I went with him,
my brother James, and some other Friends, to William Moore, president,
whom we acquainted with our religious prospect.
He appeared tender and concerned for us, and particularly so for me,
as we had been acquainted from school boys, and the penalty of the laws was great,
for departing without consent.
We informed him that we did not mean purposely to displease,
but apprehended that to those who had nothing in view
but an honest discharge of duty in the sight of God,
and the promotion of piety and virtue, no difficulties should be given.
After this we sent something of like import to the council; as follows, viz:

[.embedded-content-document.letter]
--

[.salutation]
To the president and council:

Having, by the constraining power of God`'s love influencing my spirit,
been at times engaged to call sinners to repentance and amendment of life,
and to publish the glad tidings of peace, life and salvation,
through Christ Jesus our Lord and Saviour;
and finding my mind drawn by the same Divine power and love,
to visit my brethren in religious profession in Europe, as the Lord may open my way;
I have, agreeable to the regular, decent, and orderly way, used in our religious Society,
solidly opened my concern to Friends here, who,
after deliberate and weighty consideration, have signified their sympathy,
unity and concurrence with this religious engagement, by their certificates;
leaving me to the Lord and the guidance of his holy Spirit.

And believing the time to be come for me to move forward, and leave my native country,
my near connections, and whatever is dear to me in this life, I inform you hereof:
and do declare, that I have no sinister view or worldly concern to promote;
but singly the honest and upright discharge of a duty, laid and enjoined on me,
as I believe, by that Almighty and holy Being who formed us for his glory,
and hath a right to our service, to be obeyed and followed in all things;
for therein consists our peace and happiness here and forever.
And believing the gospel of Christ to be free,
the true ministers hereof ought to be free also,
and not interrupted in their religious endeavours for the promotion of piety,
virtue and godly living.
Under this consideration, and not from a disposition to give offence,
I dare not make the consent of human authority a
condition of my obedience to Divine requiring;
yet am willing, by thus making my case known to you,
to remove all occasion of misapprehension or misrepresentation.
And recommending you with myself to God, and to the word of his grace nigh in the heart,
that by attention and obedience thereto, we may experience peace in our minds here,
and happiness hereafter,

[.signed-section-closing]
I remain your real friend,

[.signed-section-signature]
John Pemberton.

[.signed-section-context-close]
Philadelphia, Fifth month 30th, 1782.

--

"`Sixth month 12th; I desire to be kept humble, patient and resigned.
Poverty attends me, yet as we passed from house to house in our journey,
I had to break bread spiritually.

"`13th; I overtook William Mathews at Hardwick, in New-Jersey,
and was most easy to continue there until first-day.
On seventh-day we joined Friends in drawing up a
representation of the sufferings to which they were liable,
by an oppressive law made some years before.
The meeting at Hardwick was large, and divers appeared hopeful; yet,
alas! the life of religion is low;
but Truth helped to labour in the honest discharge of duty.
We went thence to Paulin`'s kiln, and had a meeting there.

"`18th; Very hot weather.
We were much spent in riding about forty miles to New-Cornwall, in New-York.
On the 20th we reached New-Marlborough, and the next day attended monthly meeting there.
Thence we took meetings at Crum Elbow and the Creek, meetings settled within a few years,
and large.

"`Second-day, 24th; We had a large meeting at the Nine-partners; thence to Oswego,
Apoughquague, Oblong and Amawalk; many professors and a plain people,
but the life of religion at a low ebb.
At Oblong we met with J. Eldridge, who appeared to be in a very ranting spirit,
and seemed to value himself upon a certificate he had from New-England.
I told him I hoped he would not represent that he had one from Friends in unity.
It is right to be tender towards the man, yet necessary to set him in his proper place.
I urged his speedy return home, and not to impose upon Friends in his way,
by appearing in meetings, which he did at Oblong the day before we reached there.

"`While we were at Amawalk,
five young men came boldly into the room in which we were sitting at a Friend`'s house,
three of them armed.
I thought as I quietly sat, I felt the perturbation of mind they were in;
and apprehended, as I afterwards understood was the case,
that they were going out to seek prey,
being such who made a spoil of all they could take or meet with,
without respect to party.
I was affected under a consideration of their situation and evil life.
They were going towards the part we intended for next day.

"`First-day, sixth month 30th; We set out early,
and passed through a country formerly well settled, but now much deserted;
so that rubbish was growing over fields cultivated in past years,
and grass in them and along the way side, which would have afforded much hay;
the sight of which was affecting.
We passed through without hindrance, though we saw some military men on the way,
who had just returned from lying in the woods through fear of their enemies.
Alas! how are some who profess the Christian name misled,
and how will they risk health and life for false honour!

"`On first-day we were at Shapaqua meeting; then to Purchase, Mamaroneck and Westchester.
These meetings were low exercising seasons; and my mind was greatly stripped,
not being able to see my way clearly; yet I was engaged in some labour, in each meeting.
After this we proceeded to New-York; the country from Amawalk hither, the way we came,
being much deserted, except by Friends, who mostly kept their habitations.
Though many of them were robbed and spoiled, and some had met with much personal abuse,
yet the Lord had been gracious; and none appeared to want the necessaries of life,
though they lived and fared differently from what they once had done.
It would have been comfortable to find that these
sufferings had had a more profitable effect,
and that the professors of the blessed truth had
become more truly alive in their profession.
There is, however, a precious seed in most places, and some promising youth;
but in the general, life is much wanting.

"`In New-York, accompanied by dear David Sands, I visited several families;
and on first-day we were at two meetings, both large.
But, alas! a worldly spirit is prevalent, and the desire of gain has captivated many.

"`I have abundant need of the prayers of the faithful, for I am proved,
and expect to be '`in deaths oft;`' but I labour to keep the word of the Lord`'s patience,
and however simple, to be faithful; and my mind has been mostly quiet,
and steadily desirous to move as Divine Wisdom may direct.
As we have passed along, the state of religion has been very low,
yet in every place the Lord has a precious seed, a concerned few.
And indeed, '`had not the Lord left unto us a seed,
we might have been as Sodom and like unto Gomorrah.`' But many are at ease,
and an inward fervent labour is much wanting.

"`Seventh month 9th; We crossed to Long island,
and the next day were at a large meeting at Westbury.

"`28th; We have attended divers meetings on the island,
and yesterday the quarterly meeting ended here.
There are many valuable Friends, but it has been a baptizing time to me and my companion.
Yet, through favour, my mind has been preserved quiet, and in a good degree resigned,
knowing that those who are admitted to be glorified,
must be willing to suffer where the great Master suffers.
I cannot forget my dear friends in Philadelphia, whose labour is great.
So will the reward of the truly diligent and faithful be,
who care more to be exercised in the Lord`'s work and service, than in their own,
and to have their eye in their Head, and to be preserved single.
This will give us to see things, which by many may be overlooked.
Indeed it is a great attainment to keep self under,
and a steady watchfulness is necessary.

"`The yearly meeting here appointed thirty-seven Friends,
and directed the two quarterly meetings to appoint so many in each,
that the number altogether might not be less than fifty,
to compose a meeting for sufferings.

"`Third-day, the 31st;
My mind being drawn to attend the quarterly meeting at the Purchase, on the main,
I crossed the ferry at Whitestone,
and next morning went to the quarterly meeting for ministers and elders,
where many solid valuable Friends met.
The meeting was owned, and my spirit measurably comforted.

"`Sixth-day, the meeting for sufferings met;
that part appointed by the quarterly meeting, and those of the yearly meeting,
who reside on the main; and during our sitting,
a number of armed men rode up to the meeting house.
They appeared noisy and rough, so that there was room to think they designed mischief;
but finding the quarterly meeting had ended, they seemed disappointed.
They came, as was supposed, with intent to take Friends`' horses; but few being there,
and these mostly mean, after some time they rode off.
Several Friends, in coming to this meeting, were much beaten and abused,
and upwards of twenty horses were taken, some by the British,
some by the continental party, and others by persons who live between the lines,
under no rule.
My mare was stolen in the night.
Friends appeared very patient under their trials,
though some were a great distance from their homes.
The losing of my mare I blame myself for, a secret uneasiness attended my mind,
and a gentle hint to keep her up that night, which I spoke of,
but did not sufficiently urge.

"`Third-day, I came by water to New-York.
On fourth-day was the monthly meeting there, which did not end till the next day.
Here, as well as in other places,
there is need of the revival of more deep religious concern,
for a qualification to labour rightly in the cause of Truth.

"`Eighth month 25th; We have spent about a week with our dear friend David Sands,
who is seeking opportunities among the people of Long island,
not in religious society with us; and has had eight meetings among such.
There was an openness to promote meetings, and to receive the doctrine of truth.

"`30th; We parted with him yesterday, about fifty miles eastward of this place.
Westbury.
He appears better fitted than most I have known for this weighty engagement.
His open, easy, and innocent way, has great place, as well as his ministry.
It was with much reluctance he parted with us, and a trial to me to leave him.
But considering the season advanced,
I thought prudence directed our drawing nearer to the place of embarkation,
if the way should open.

"`31st; There does not appear a likelihood of a passage soon offering.
We went to look at several vessels, previous to the 14th instant,
but the way did not seem open to me.
In the right time it may; which I desire to be helped patiently to wait for, and to move,
or not to move, as the Lord shall see meet.
It is a great thing to be enabled truly to say, '`Not my will, but thine, O Lord,
be done.`' My strength and experience are far less than they might have been,
had the early visitation of Divine love been faithfully attended to,
a willingness wrought to become a fool for Christ`'s sake,
and fleshly reasonings not suffered so much to prevail as they did for many years.
I am concerned that the youth of the present day may bow under the Divine yoke,
and willingly learn of Him who is meek and low of heart.

"`First-day, ninth month 1st; Went to Westbury meeting,
and in the afternoon had a large meeting with the black people,
held in said meeting house.
They behaved well.

"`11th; It remains uncertain when a fleet may sail; though some men-of-war, it is said,
are likely to depart hence, when private ships also may sail;
but these are either prizes, or fitted in a warlike manner,
neither of which would be easy to me.

"`Tenth month 2nd; At Westbury, met with our friend David Sands,
on his return from a laborious visit to the people in the east part of Long island;
where he had above seventy meetings, and met with an open reception.
My mind hath been much with my friends in Philadelphia, in deep sympathy,
and humble inward prayer that the Lord`'s arm might be revealed,
and that the machinations of seducers and evil men may be frustrated.

"`Fourth-day, eleventh month 6th, was the monthly meeting at New-York,
at which David Sands and myself mentioned a
desire to visit some of the families of Friends,
and some who have dispersed in this season of difficulty; which being concurred with,
we visited sixteen families this week, in which Truth favoured with counsel,
to our own peace and the comfort of the visited.

"`16th; This week we visited thirty families; four young men fled from their friends,
in one of the families.
The Lord continued to favour with wisdom and strength.

"`23rd; Visited this week, twenty-seven families,
spending a considerable time in one family, at two separate opportunities,
where there is a painful division.
Had a comfortable opportunity at Lindley Murray`'s:
he and his wife are tender hopeful Friends.

"`Twelfth month 5th; Went on board a boat and arrived at Staten island,
in order to visit the dispersed of our religious Society there,
and on the 10th returned to New-York again,
having had seven appointed meetings on the island, besides private labours.

"`There was great openness among the people.
The meetings were solid and weighty, and such an awful silence prevailed,
as is rarely felt in our religious meetings.
Our dear friend David Sands, laboured much, and many hearts were tendered.
No Friend, except our worthy deceased friend, Abraham Farrington,
had before had a religious meeting there, that can be remembered.
The people lived for some years without a priest, and having experienced many trials,
and not being bound to any set form,
appeared more open to receive the impressions and doctrine of truth.
I believe we went in an acceptable time to those who were formerly members,
and are now dispersed, and to the inhabitants generally.

"`It looks likely I may soon leave my beloved native shore,
and be tossed on the wide ocean, proceeding to new baptisms and trials.
Oh, that I may be kept faithful.
I find sorrowfully, that I have yet to struggle hard with a cowardly disposition,
which at times prevails.
I feel my own weakness and disqualification for so weighty an embassy;
but the Lord hath hitherto furnished, and helped beyond my desert or expectation.
I have him only to depend upon, and wish I may be kept simple, faithful,
and resigned to be any thing or nothing, as he may see meet.
It is a great trial to nature, to become mean and little.

"`21st; About two o`'clock, taking a solemn leave, went on board the ship New-York,
with my companion William Mathews: she is much crowded with passengers,
who are respectful to us; but their company will be trying,
as there appear few who have much sense of religion.
The Lord hath hitherto helped, and kept me in a state of resignation; and I can say,
with one of old, I desire neither poverty nor riches,
but that he may feed me with food convenient for me.

"`24th; We are now under way, with a fair wind.
I continue favoured with a quiet mind and humble trust.

"`First month 12th and 13th, 1783; Wet and stormy;
so that we went with bare poles and the dead lights all in.

"`24th; Between six and seven o`'clock, P. M., we saw a light,
supposed to be the light-house on one of the Sciily islands.
We have great cause to be humbly thankful to the Preserver of men,
in thus far being gracious to us, though unworthy,
and the time of many on board has been badly spent.

"`First-day, 26th; This day we saw land, having had a fine run all night.
Our passengers were much rejoiced; but my mind was attended with heaviness,
having been impressed with a belief the night preceding, that we should be taken,
but was willing to shake it off.
Before night the joy of many was turned into sadness.
We saw a vessel for some hours making towards us.
While she was a considerable distance off, I did not like her;
but the captain thought it was an English cutter, coming to impress men;
when she came alongside, too late we were convinced to the contrary.
The people on board her fired a number of small arms,
and then hoisted their boat in order to come on board; which, in their return,
was stove and lost, and several of our seamen narrowly escaped.
They then demanded our boat, and were in much hurry for it,
as we were within about two leagues of an English fleet of thirty-two sail.
They crowded much sail through fear of being pursued, and it was a tossing, stormy night.
But myself and William Mathews being in our apartment, kept quiet,
and saw but little of the hurry when the men first entered the ship.

They were very furious, and it was a favour no lives were lost by violence,
for some threatened much.
Andrew Peterson, one of the best of our hands, was lost when the boat was stove,
and one of their hands also, as they told us.
Captain Grant and one of our passengers were sent on board the privateer,
besides our seamen; and more were ordered, but secreted themselves.
Indeed it was running a great risk, to send them from the ship, as the sea was high.
They left only two hands and a boy on board belonging to the vessel,
and that night the ship and the privateer being separated,
the people put on board to govern the ship, proved very unskilful:
they appeared afraid most of the time.
The passengers generally remained on board,
but our captors were assured we would not attempt to hurt them.
I may acknowledge, to the praise of the Lord`'s name,
that my mind was preserved in great stillness and resignation.
Indeed, good is the Lord and abundant is the advantage of an humble trust in him,
who can create a calm in the midst of tumult.
Divers of our passengers were in great fear and agitation.

"`Third-day, came in sight of Calais, and a boat coming on fourth-day morning,
took some of our passengers and part of their goods,
but they were long in getting to shore, and suffered much with cold and wet.
The vessel was ordered to Dunkirk; and the captain of the privateer being now on board,
we sailed towards this place.
But it was difficult to keep a sufficient number on deck to work the vessel,
they being very busy in plundering the passengers`' trunks, etc.;
so that before we reached Dunkirk, there was scarcely a box or trunk unopened,
except mine and my companion`'s, which they promised should not be molested.
On fifth-day the captain went ashore,
and sent a vessel off for the remainder of the passengers, etc.; but the wind being high,
after she got to the vessel the rope broke and she swung off,
and did not again reach us till evening.
We went on board her about seven o`'clock, with our trunks,
and most of the goods of the passengers who had landed at Calais,
which the people took as plunder.
We were in this boat, rolling all night, and had but little rest, which,
with losing rest the two preceding nights, made it trying; but the Lord sustained us.
We landed between eight and nine in the morning, and being hurried from the boat,
were taken to the house of one of the privateer`'s men, where we were refreshed.
I lost my bed, some clothing, and my saddle-bags.

This afternoon we were guided to a house to lodge;
where we continued all the time we were in Dunkirk,
much exercised with the filthy conversation of the privateer`'s men,
who frequented the house.
Several of them lodged in the room with us, which was exceedingly trying.
A sorrowful event occurred on fourth-day evening, while on board, among this wicked crew,
whose evil conversation we could not avoid, and on whom reproof made little impression;
a jest being often made of every thing serious.
A stout, hearty young man, one of the privateer`'s crew,
who had been quarrelling and swearing much, called upon God to damn his soul!
And though I used much entreaty with him and the other to cease,
it was a considerable time before they could be prevailed with.
This young man, within half an hour afterwards,
fell from the fore-top-mast yard upon the bow of the vessel, and thence into the water,
and was supposed to be killed by striking on the bow.

I endeavoured to impress them with seriousness after this sorrowful event;
but so vain and ungodly were these miserable people,
that they only jested and made ridicule of this man`'s death.
So much wickedness as we saw and heard whilst these men were on board,
and since being in Dunkirk, I never knew.
They appeared ripe for every evil act, and boasted in their impiety,
I mourned on behalf of so many likely young men giving themselves up to so much baseness,
and becoming so hardened in sin.

"`Second month 3rd; I have endeavoured to look inward,
and to wait for the directions of the great Master,
but no service has yet been pointed out.
We have been viewed by many, and I believe seriously.
Last evening we spent some time acceptably with three sober persons,
I did hope to find some religiously disposed people among the many English, etc.,
resident here; but the world is sought after, and the privateers being generally in port,
the town is crowded with a set of the most profane men I ever was among;
which grieved us much; but the Lord in mercy has supported hitherto,
who can make hard things easy, and sweeten every bitter cup.

"`4th; We left this wicked place, noted for privateers,
who are now stopped from proceeding out of port,
on account of preliminaries for peace being signed.
Wc took coach, and reached Calais that evening.

"`7th; Sailed about four o`'clock in the morning, and after a boisterous passage,
arrived before three o`'clock at Dover, and went to the house of our friend Richard Low,
where we were kindly received.
In the evening we had a comfortable religious
opportunity with several Friends at his house,
in which my mind was much contrited,
under a sense of the Lord`'s goodness in bringing us safe among our beloved friends.

"`8th;
My mind has been for some days attended with an
anxious concern that my dear friends in America,
and particularly in my beloved city, may be kept humble, steady and watchful.
Notwithstanding there may be a prospect of an accommodation between the powers at war,
yet some close exercises may attend our religious Society.
The Lord hath been with them in wisdom and counsel,
in seasons of deep exercise made a way when there appeared no way,
and directed their steps to the exaltation of his great name.
I wish his mercies may be remembered, and his wisdom and counsel sought in future steps.

"`9th; First-day was at the two meetings at Dover,
which some Friends from Folkstone attended.
The Lord`'s merciful regard was vouchsafed in both meetings,
and the tender impressions of Truth had some place in the minds of many,
both of the youth and more advanced.

"`10th; I visited eight families of Friends, being the whole number in Dover;
it appeared to me that a renewed visitation was extended to many,
and I was comforted in this discharge of duty.
In the afternoon set out for Folkstone,
and in the evening had a large meeting with Friends and the people of the town,
who behaved with much solidity; and Truth favouring, it was very satisfactory,
I had religious opportunities in three families this evening,
my mind being concerned for the beloved youth, and engaged in much love to them.
Many of them were tendered.

"`11th; Visited two Friends under bodily infirmity,
and then attended the monthly meeting at Folkstone.
Afterwards parted with Friends under a sense of Divine love and favour,
and proceeded to Ashford,`"

[.offset]
After having meetings at Ashford, Canterbury, Margate, etc.,

"`16th; Was at two meetings at Canterbury, both favoured opportunities.
The people behaved solidly,
and the doctrine of truth appeared to have place in many minds.
Visited three families in the evening.
My mind was thoughtful respecting Deal, and I proposed the matter to Friends;
who encouraging a visit there, notice was agreed to be sent.

"`17th; Set out early for Deal, accompanied by divers Friends of Canterbury.
Some of the town`'s people attended the meeting, who behaved soberly;
counsel and doctrine were opened to them;
and my mind was relieved and favoured with quiet for yielding to this duty.
Then returned to Canterbury.

"`18th; After a religious opportunity in a Friend`'s family,
in which the tendering goodness of the Lord was felt,
we took carriage and reached Rochester,
and were kindly received by our friend William Horsenail, who, with many others,
several of whom were formerly shipwrights, and laboured in the king`'s dock-yard,
near this place, had been convinced of the truth.
My heart could but commemorate and acknowledge the goodness of God,
in preserving us to this day under his favourable notice.

"`Fourth-day, 19th; Attended the meeting at Rochester;
said to be the largest in this county,
though thirty years past it was so reduced that there was but one Friend.
It was a comfortable refreshing time.
Feeling a draught still towards the people,
I appointed a meeting to be held in the evening;
and notice being sent to the dock-yard at Chatham, the house was filled,
and it was a good meeting; praised be the Lord!

"`Fifth-day, not finding my mind thoroughly easy,
I stayed the mid-week meeting this morning; and Friends being select, except one woman,
it was a relieving comfortable time to me.
Here William Dillwyn met us, and we set out for Gravesend,
and went to the house of a Friend, a shipwright, who has much business.
The honest labour exercised towards him on account of his business, yielded me peace,
and I believe was not unkindly taken by him.

"`Sixth-day, reached our friend Joseph Row`'s house, in London,
between one and two o`'clock.
My mind was covered with awfulness in entering this great city.

"`First-day, 23rd; Attended the meeting at Grace-church street in the morning,
and at Devonshire house in the afternoon, which were large and solid,
though the latter was silent, except a few observations I had to make.
Many Friends collecting at Joseph Row`'s, we had a weighty opportunity,
though under a sense of poverty.

"`Second-day, attended the morning meeting of ministers and elders;
and I was enabled to be faithful, in plain dealing, which I believe was received in love.
Many have need to come more into a right example of plainness and self-denial.
Met with Christiana Hustler and Hannah Wigham,
they being engaged in the weighty service of
visiting families in part of this populous city;
a laborious work indeed.

"`First-day, third month 2nd; Attended the meeting at Devonshire house,
which was large and divinely favoured; the goodness of God being manifested,
in renewedly extending his gracious call,
to awaken a people who have too generally lived in
forgetfulness of the manifold mercies dispensed to them.

"`Second-day, attended the morning meeting;
where was a large appearance of men and women Friends.
The Lord opened counsel through many concurrent testimonies,
in plain dealing with ministers and elders, and it was an edifying time.

"`Fourth-day, attended the meeting at Gracechurch street;
small as usual on the men`'s side.
The world takes up the time and attention of many, and diverts from better prospects.
It was a solid meeting, and good flowed to the youth.

"`24th; Attended the quarterly meeting at Hertford.
The business was conducted under a good degree of solidity.
Yet for the want of a living zealous care to purge the camp, dimness and weakness prevail.
There were some close remarks made, especially on the subject of tithes,
many being suffered to remain members, who pay them,
and so trample upon the testimony of truth held forth by our worthy predecessors,
who suffered deeply for conscientiously refusing
to comply with such anti-christian demands.
I had to express my belief, that truth and righteousness would not spread and flourish,
until the Society was purged of such unfaithful members.
Having experienced much poverty of spirit since I left London,
and not being able to see my way until returning from meeting,
and the path then appearing most clear to go towards Norwich,
I parted with my dear friends, with whom I had travelled from family to family in London,
in much unity, in visiting the seed there.

"`First-day, third month 30th; At meeting at Norwich,
I had to remark to Friends my concern of mind,
at their negligence respecting the time appointed forgathering;
meetings being often much hurt by the late coming of many who live at a distance,
and do not leave home until the time they should be at meeting.

"`Fifth-day, at meeting at Wymondham, attended by Friends from several places,
and some of the sober neighbours; yet it was heavy and laborious.
Next day returned to Norwich; thence to Yarmouth, Long Stratton, Diss, Brandon,
Bury and Bardwell; a small meeting, there being only two men, one woman,
two boys and two girls, besides the Friend who went as guide to us.
Thence to Needham and Sudbury, and had a meeting there, to which came many people;
and I hope some profitable impressions were made.

"`26th; We are now in the county of Essex.
The meetings in Suffolk and Norfolk are generally very small,
and some not likely to be maintained long, unless there be a revival.
The spirit of the world and an eager desire after its gains, pleasures and friendships,
have been exceedingly baneful.
The Lord having blessed in basket and in store, many who were useful in their day,
their success in gaining much wealth, hath been, for want of due reflection,
a means of raising the minds of many of their descendants above the pure witness;
these have rejected the cross, and been carried away and lost to the Society;
which is indeed sorrowful; for great favours call for great gratitude,
and this is manifested by humility and faithfulness.

"`First-day, attended two meetings at Saffron Walden,
where the state of religion is at a low ebb.
I hope I may be enabled to '`keep the word of the Lord`'
s patience;`' but it is a stripping time,
and I am led into suffering with the seed.

"`For some weeks after I landed in England, my mind was seldom free from a sense of good;
but dry seasons have attended since; yet I believe I am in my place,
and have no room to murmur,
for the dispensations of Divine Providence are in unerring wisdom.

"`Second-day, to Bishop Stortford, where the monthly meeting for Hertford was held,
and in the evening I joined three Friends in a religious visit to four families.
Seventh-day, I saw the house and residence of the wicked Bishop Bonner;
a Friend has since lived in it, and the monthly meeting was sometime past held there.

"`Fifth month 12th; This morning we set out towards Bristol; refreshed at Dunstable;
and hearing there were a few under the name of Friends, I went to see them,
and had a little counsel to drop at each house; then proceeded to Tring,
and found some tender spirited Friends: thence to Aylesbury and Witney.

"`14th; The meetings we have been at have been generally small, with respect to Friends;
those not of our Society, in most places, manifest a willingness to attend;
but their views and expectations are much outward.
Were the professors of the blessed truth more generally
redeemed from the spirit and friendship of the world,
and did they live and appear more conformable to their profession,
light would spread and truth prosper more.
But the eager pursuit after earthly treasure,
and employing in schemes of trade and business, talents, which,
if sanctified by an humble submission to the Truth,
might be greatly useful in removing burdens and
scattering the darkness which now prevails,
is cause of sorrow.
Much labour is wanting in this land,
and some mourn the fewness of rightly exercised servants.
So much barrenness prevails, that I sometimes think it scarcely quits cost to travel.

"`The consideration of what step will be advisable to take, to expose to the public,
or those in power, the evils of the African slave trade,
is likely to come before the yearly meeting from the meeting for sufferings.
A shocking case lately appeared: William Dillwyn writes me,
that one hundred and thirty-three poor creatures were lately thrown overboard alive,
from a ship bound from Africa to the West Indies, more with a view to make a good voyage,
as they term it, than from necessity.

The negroes were weakly, and not likely to sell for much, and so to recover insurance,
they made a plea of necessity.
The insurance, as I am informed, was recovered, but it makes some stir and noise,
and may tend to open the eyes of some.
It seems that but few know the iniquity of the trade.

"`Fifth-day, proceeded to Cirencester, and had a meeting there;
and on seventh-day arrived at Bristol.

"`First-day, fifth month 18th; Was at three large meetings in Bristol,
which were favoured.
On second-day morning a meeting for ministers and elders;
and in the afternoon one was held for those who usually frequent our religious meetings;
in which our friend Robert Valentine, laboured zealously in much plain dealing.
He and myself went to a widow Friend`'s house,
where we had a favoured opportunity with some youth and others.
Third and fourth-days, meetings were held;
which many teachers of different societies attended.
There were several appearances in the ministry,
but our friend Catherine Philips had the most extensive service,
in a clear line of doctrine, and the people were attentive.
These meetings being well over, and favoured with the overshadowing wing of Divine love,
is cause of thankfulness and reverent acknowledgment to the great Shepherd,
who is still manifesting that he is willing to be gracious,
and gather into his fold the scattered of the flock.
There was a large appearance of the beloved youth,
to whom a fresh visitation is extended; and some, I hope,
will submit thereto and become useful.
But it is very sorrowful to observe some meetings in this land wholly dropped,
and others in a declining way.
Many are willing to come to our meetings, but when they consider the doctrine preached,
and look at the example of many of the professors of the truth,
it is to be feared they stumble.
But the foundation stands sure, and the Lord still knows who are his.

"`Third-day was the quarterly meeting for Gloucestershire, held at Frenchay,
and divers Friends coming from Bristol, the house was crowded.
The business being entered upon, it appeared that great weakness prevailed;
but the use of a committee to visit the monthly meetings,
to join in strengthening the hands of concerned Friends in the
maintenance of our religious testimonies and discipline,
being pointed out, the meeting went into a nomination.
This meeting held upwards of seven hours.
In the evening I had a pretty seasonable opportunity with some,
who are wide from the simplicity which Truth leads into.

"`28th; Feeling some exercise therefor to attend me, I thought it best,
as the present time only is ours, to return to Bristol, to spend a few days more;
though I was not idle when there.
But I have private employ, which my companion, William Mathews, does not seem led into.
So I returned with my kind friend John Lury, and two other Friends,
and was openly received.`"
Sixth to second-day, visited divers families, and attended several meetings.

"`Sixth month 2nd; Went to the meeting of the overseers,
and in the afternoon to the adjournment of the men`'s meeting,
which held from three o`'clock until half past eight.
There are some well concerned Friends here;
but they are kept under by a lofty overruling spirit, that is not properly baptized,
but suffers the will and wisdom of man to prevail and act in the church;
and sorrowful it is, that a carnal worldly spirit,
that is not subject to the Truth nor the cross, has spread and caused desolation.
There are many tender youth in this city who might be brought forward,
if there were more of the leading members who preferred
the cause of Truth to all worldly considerations,
and lived under the spiritual baptism.
Third-day, I left Bristol and reached Melksham, and on sixth-day arrived in London.

"`7th; Though absent in body, my heart yearns for my brethren at home,
with desires for their preservation and advancement in the Truth.
I am very sensible that a field of labour will open,
to guard Friends and keep them from stepping into
schemes of trade and unprofitable worldly cares.
It will indeed be sorrowful,
if any who have been brought to see the vanity of the world and its friendships,
and had their prospects towards enduring good, should lose the sense thereof,
and run with a giddy multitude into the pursuit of earthly treasure.
In obtaining this they may be greatly disappointed,
and may lose the enjoyment of that favour which is better than life.

"`16th; The yearly meeting closed about nine o`'clock, P. M.,
and I was thankful that it ended so well; being on the whole a good meeting.
And though there were some who intruded by worldly wisdom,
and gave uneasiness to the truly exercised, yet the strength of such is much broken,
and truth and its testimony gain ground.
There were at this meeting many well concerned Friends and hopeful youth.
A petition to the parliament, to prevent, if possible,
the poor negroes being brought from their country,
was approved of and signed by about three hundred in the meeting.
It was presented in parliament the next day, favourably received and read.
The yearly meeting appointed a committee to visit Norwich, Bristol, Northumberland,
Staffordshire and Wiltshire, to promote their joining with adjacent counties,
as quarterly meetings, some of them being reduced.
Meetings in many places are small and weak, so that the prospect is gloomy;
yet it is evident that the glory is not wholly departed from Israel;
but a living concern is still maintained.

"`17th; Rose early, took coach and came to Wellingborough,
in company with our dear friends Esther Tuke and Benjamin Middleton.

"`Sixth-day, the 20th; Was at the quarterly meeting at Leicester,
in which it was evident that the life of religion was very low,
few being livingly concerned for the exercise of our Christian discipline.
Had a comfortable opportunity with some young people, and then proceeded for Nottingham,
several Friends being in company.

"`First-day, the 22nd; Went to the general meeting at Warnsworth,
and sorrowful it was to find that religion is at a low
ebb in a place where once it greatly flourished;
many have inherited the estates, but not the virtues and godly zeal of their forefathers.

"`Second-day, attended the monthly meeting at Leeds.
The meeting for business was large and measurably favoured; and on third-day,
coming to York, attended the meeting for ministers and elders, which was large and solid.
On fourth-day was held the quarterly meeting,
and in the evening a large favoured meeting for worship,
to which came many of the town`'s people.
On fifth-day, about eight o`'clock, a committee met, appointed by the quarter,
to visit the monthly and preparative meetings;
in which several weighty matters were opened,
tending to stir up and encourage Friends to labour for the good of the body.

"`Friends at the quarterly meeting were reminded of the exercise of that pious man,
John Woolman, who laid down his life in this place, respecting the poor black people;
and they were desired, in the recess of parliament,
to use their influence with such of its members as they were acquainted with,
to induce them to think seriously on this subject, and labour to check the slave trade.
There was a large appearance of solid, weighty Friends, and many promising young people,
which tended to give a comfortable hope.
There are some in most places who are preserved under a sense of truth,
and concerned for its prosperity.
With respect to the petition lately presented to parliament, against the slave trade,
Edmund Burke told Richard Shackleton, he was sorry that he was not present,
as he could have spoken his abhorrence of this detestable traffic.
And another distinguished member called upon a Friend,
and expressed his hearty willingness to afford any assistance he could in this matter.
So that there is more encouragement than was expected.
These accounts I expect, will be cordial to dear Anthony Benezet +++[+++of Philadelphia,]
and many others.
I much desire that my dear friends on that side, may keep steadily on their watch,
and be truly faithful to the openings of Divine counsel.
Many deep exercises may be their portion.

"`There is a ranting spirit in some in this land, who give Friends trouble.
Thirteen persons have lately been disowned, who were concerned in ships carrying guns,
which has alarmed many; some of whom manifest an Ishmaelitish spirit;
so that such as are engaged for truth`'s testimony everywhere, meet with their trials.

"`Seventh-day, sixth month 27th;
This morning had a solid parting opportunity with our dear friends William Tuke and wife,
at whose house we had been kindly entertained at York, and proceeded to Darlington.

"`First-day, was at two meetings there, and on second-day went to Durham.
In the evening was a meeting for ministers and elders, which was small and dull.
Some religious service opened, upon hearing the answers to the queries; which,
though close, appeared well accepted.
Here we met with our friend John Stevenson,
who some years past visited Friends in America.
Third-day the quarterly meeting opened by a meeting for worship, which was large.
It was sorrowful here, as well as at other places,
to observe the deviation of some who make profession with us,
from that plainness and simplicity which Truth leads into.
Many have multiplied their outward store,
and the youth have soared above the pure witness and despised the cross.
In the meeting for business, many seasonable remarks were made,
to excite to a more attentive care and concern to put the discipline in practice,
and I believe some honest Friends were strengthened.

"`Sixth-day was the quarterly meeting for Westmoreland;
in the evening a public meeting for worship, both low and exercising seasons;
neither of us had anything to offer.

"`Seventh-day, went to see several Friends,
and laboured to attend to the opening of truth, but I was so bound as in fetters,
that I had little to communicate.

"`First-day, seventh month 6th; I was at two meetings in Kendal;
and on second-day at the general meeting at Preston Patrick,
to which many came from Kendal and other places.
It was a season of deep exercise to me.
On third-day morning was a meeting for ministers and elders,
for Lancaster monthly meeting; then the monthly meeting for business;
and in the evening a meeting for ministers and elders for the quarter.
And on fourth-day was the quarterly meeting.
All these meetings were seasons of exercise; my mind, both in and out of meetings,
being deeply proved, yet kept in a good degree of patience and resignation.
On duly pondering my steppings, I was not accused of wilful omissions or commissions;
and believed I was dipped into a sympathy with the pure seed,
which lies oppressed in the hearts of many.

"`Fifth-day, not being fully easy to leave Lancaster, I attended their mid-week meeting,
in which I found my mind more at liberty.
Spent part of the remainder of the day in visits, to my relief and satisfaction,
among some who had deviated widely from the simplicity of the truth.

"`Sixth-day, my companion having set forward for Liverpool yesterday,
I took coach this morning in company with Richard Shackleton,
and arrived at Liverpool in the evening.

"`First-day, the 13th; Was at two meetings there,
in which counsel was opened to divers states.
This meeting is much increased since I was here, thirty years ago;
but flocking to places of trade, and getting money, being the great objects of many,
and the improvement of the spiritual gift not being properly attended to,
it is not to be admired at, that the life of religion is low and the seed oppressed.
However, there are some valuable hopeful Friends here.
I believe a concern for better times grows, and a gracious visitation is renewed to many,
which, if attended to, will qualify to bring forth acceptable fruits.
It would grieve our dear friend Anthony Benezet, were he here,
to see with what earnestness and diligence,
numbers of vessels are fitting out for Africa.
The great profits made last year, have stimulated many,

"`Fourth-day, the 16th; I was yesterday at the monthly meeting of Hardshaw,
held at Warrington, being that from whence my grandfather went.
I felt more interested in it, as having sprung out of it, from my forefathers;
and was pleased to find that the discipline appeared to
be conducted with more regularity and zeal,
than in most I have been at in this nation.

"`Sixth-day, 18th; About two o`'clock set sail in the brig Dublin, captain Sergeson,
and on second-day following, in the afternoon, we landed safe at Dublin;
being mercifully preserved in our passage,
though our vessel struck on a place called the Kish, on the evening of first-day,
the weather being very foggy.
On this sand bank, in the third month last, an East Indiaman struck and sunk,
and all on board perished;
so that we have cause to be humbly thankful we were guided safely.
I went to the house where I formerly quartered,
and was kindly received by William Taylor and his mother.

"`Third-day, attended the meeting at Meath street, at which were mostly young people;
good was felt therein.
The rest of the week visited several families,
in company with Friends appointed to that service.
It is very affecting to walk the streets of this city;
the crowd is nearly as great as in Cornhill or Cheapside, London, at noon;
but the appearance very different.
Such multitudes of miserable objects I never beheld in so short a space.
The scarcity and dearness of grain, the decline of divers branches of business, but most,
the vast number of whiskey shops, create great misery and destitution.

"`First-day, attended two meetings in Dublin, both measurably favoured;
though the great neglect of assembling at the time appointed,
particularly in the morning, hurt that meeting.
At the close of the second meeting the women being desired to keep their seats,
the queries were read and solidly considered, and some seasonable remarks made.

"`Third-day, was the day for holding the men`'s and women`'s meetings;
the business was conducted well, but the number of rightly exercised Friends is few.

"`Fourth-day, my friend William Mathews,
appearing disposed to attend the quarterly meeting for Leinster, and I being easy also,
though my prospect on first landing was northward, we set out,
reached Ballitore in the evening, and lodged at Richard Shackleton`'s.

"`Fifth-day, reached Enniscorthy in the evening, much wearied;
and on sixth-day attended the quarterly meeting of ministers and elders,
which was a low season.

"`Seventh-day, was a large and exercising meeting, the minds of many being outward,
which increases the burden of the true travellers; and the Lord sees meet, in wisdom,
to disappoint the expectation of those whose eye is more dependent upon man,
than upon Him, from whom all that is truly good, whether immediately or instrumentally,
proceeds.
Little was said in this meeting, except some remarks I had to make;
and then we proceeded upon the concerns of the church, which business was conducted well.
This day I received a number of letters from my dear friends in America,
which came by my dear friend Nicholas Wain, lately arrived at London,
on a religious visit to Friends in Great Britain.
I have great cause to be humbly thankful,
that the Lord is moving upon the minds of my friends thus to salute me,
and express their sympathy and unity with my religious engagements.

"`First-day, eighth month 3rd, was a large meeting,
attended by many sober people of the town.
My companion, and my dear friend Mary Ridgway, had the public service.
This Friend, by faithfulness, has become an able minister, devoted to the cause of Truth,
and much exercised for the promotion of righteousness.

"`Fourth-day, went to Edenderry, which was formerly a large lively meeting,
but now much reduced,
and few rightly labour for the experience of true religion and godliness.

"`Sixth-day, a meeting at Oldcastle, at which were two Episcopal ministers,
and divers not professing with us.
The meeting held nearly two hours in silence, after which I had a short testimony.
One of these ministers spent some time with us in the afternoon, and appeared a solid,
thoughtful man.
Next morning he sent a kind letter and a short essay on the calamities prevalent,
tending to excite proper considerations in the
minds of the various ranks among the people.

"`Fifth-day, 14th;
Yesterday came to Dungannon to attend the quarterly meeting for Ulster,
to be held near this place.
It is dull travelling in this land.
There is great decay from the life and substance of religion and godliness in many places.
Many meetings, both here and in England, are dropped, and more are likely to be so.
Places for trade increase by removals, and that lessens meetings in the country.

"`The account of many, in my native land, letting their minds out into the world,
gives me much concern.
It shows what poor weak mortals we are,
that when from under the heavy hand of affliction,
we soon forget the covenants made in the day of distress.
If those who have seen, in the day of proving,
the vanity and folly of grasping after the world,
and whose spirits were measurably redeemed and purified, turn again to it,
they may become more insensible than ever; and if trials return,
which in some shape or other, they probably will,
such may fail to find that confidence and Divine
support they mercifully experienced in the late trials.
Did not the Lord cast up a way for many, and cause the meal and the oil to sustain,
beyond what they could expect?
My heart yearns for my dear brethren,
and abundantly desires that warning and counsel may not fail to be given.
I have thought of the great concern and care of the worthy William Edmundson,
when Friends in this land were in danger,
as great prospects of worldly gain were opened to view;
how he laboured to curb that inclination; and how his labour was blessed,
by a submission on the part of his brethren.
May the watchmen maintain their ground, and labour for the good of their brethren,
not being discouraged if some requite evil for good.

"`There is a good prospect here of outward plenty;
though during the last winter and spring, the poor suffered grievously,
and had not much charity been extended, multiudes must have perished.
It is true, they are idle, and increase their misery by a thirst for whiskey.
But many that would labour, have not work,
and there are swarms of beggars and miserable objects indeed.

"`Sixth-day, went to the meeting for ministers and elders, held at the Grange,
near Charlemount, which was small and a low season.
Seventh-day was the quarterly meeting for Ulster province, which was large.
There was a good appearance of Friends, the meeting was favoured,
and the business carried on well.
First-day was a large parting meeting, also favoured.

"`Second-day, went to a meeting called Toberhead, which was large and solid,
the people conducting well.
There is but one Friend, Jarvis Johnson and his family, here, in unity with Friends,
and few that make profession.
So many attending on so short a notice,
I thought gave a good testimony respecting our friend`'s conduct.

"`Third-day, proceeded to Londonderry, and had a large meeting in the court-house.
But there were many rude, giddy people,
who took more liberty in that place than they might have done in some other;
balls and other frivolous entertainments, being often held there;
which rendered the meeting less satisfactory.
My companion, nevertheless, had pretty large service,
and divers remarks were made on their conduct, and rebukes given.
Though such rude behaviour was very discouraging, yet good was in the meeting, and some,
I hope, were benefitted.
We were satisfied that we gave up to this prospect of duty.

"`Fourth-day; early this morning we left the city, and after crossing the ferry,
parted with three of the Friends who were with us,
and the others went with us to Newtown Limavady.
My spirit had been clothed with great heaviness before leaving the city,
and I had expressed my feelings to the Friends; who encouraged my stay,
and kindly offered to tarry with me.
But my companion apprehending himself clear, I ventured to journey.
The burden, however, increased so much, that I proposed to return,
to seek another opportunity at Londonderry; to which my companion, with great reluctance,
agreed.
His backwardness increased my concern; but the minister of the Society called Methodists,
being willing we should have his meeting house, notice was spread;
and on fifth-day morning we had a large meeting, which was still and much favoured,
many being tendered through the power and influence of Truth,
under the seasoning virtue of which it ended.
Now we concluded we might go;
though I had felt some concern respecting the prisoners confined in jail here.
I hoped, however, that I might go forward, but on the way my burden increased,
so that I had little rest the night following.
I gave up, much in the cross, to return again to Londonderry,
and a Friend bore me company.
After dining, we went to the jail and had the prisoners together;
and it was sorrowfully affecting to see so many, mostly youth, and some quite young,
who through a disregard of the Divine fear,
had brought themselves into misery and disgrace.
They behaved soberly and took the visit kindly, and some appeared affected.
It did not yield me so much comfort as I had hoped for;
but having endeavoured with sincere and honest
intention to discharge myself of apprehended duty,
I laboured to be still.
There are none of our Society at Londonderry, nor within thirty English miles of it,
or thereabout; but in the Lord`'s time there may be some gathered.

"`In the afternoon I visited an elderly woman and her son, both religious people;
and the conversation yielded some satisfaction.
About the seventh hour I went again to the Methodist meeting house,
notice of a meeting having been spread.
There was a large gathering of people, many of them of the upper rank,
and who had not been at the previous meetings.
A greater solemnity seemed to spread than I had
observed at either of the preceding opportunities;
and I believe it might have been a profitable season, though spent mostly in silence;
but the minister, who, I suppose, concluded he must be active, got up and had a formal,
dry discourse, and afterwards went to prayers, as he called it.
This I thought was in the will of the creature,
not seasoned with the salt of the covenant, and rendered the opportunity burdensome.
And my companion and myself keeping our seats with our hats on, it was noticed,
though not in words, and I apprehend, gave some displeasure.
We returned to our lodgings heavy; and when I awoke in the morning,
my mind was clothed with sadness, and continued so.
But I could not clearly see any duty pointed out;
and having had my mind open to discharge what might be
laid upon me in the meeting last evening,
I feared staying, lest the cause of truth might suffer.
I left the city a second time, and had not only a very wet,
but a sorrowful ride to Maghara, where we lodged at an inn.

"`First-day, eighth month 24th;
Last night was one of the most distressing I ever experienced, and I had little sleep.
A fire seemed to be kindled within me; yet, fearing that by returning again,
the appearance of instability might prejudice the good cause,
more than anything I could do would advance it, after much trial of mind, I went on;
but on the road I had no peace.
At Ballymena I met William Mathews, and was with him at a crowded meeting.
My mind was in a tried state, yet near the close of the meeting, feeling some engagement,
I kneeled down to prayer, in a broken, contrite manner;
and afterwards expressed a few words to the people.
I soon took opportunity to open the distress of my mind to William Mathews,
and informed him of my fear of bringing dishonour to the truth, adding,
that I could not think of returning to Londonderry without some suitable help.
He agreed to consider the matter.
So after dining at a public house, we proceeded to Grange,
where an afternoon meeting had been appointed; this was large,
and the house more commodious than that at Ballymena.
Much good counsel was communicated, and the people were generally solid.
At the close of the meeting William Mathews informed me,
that if I could be easy to proceed and take the meetings in Ulster, he would,
if the weight dwelt with me, return to Londonderry.
So we proceeded towards Antrim, and lodged at Shane castle.

"`Fourth-day, notice being generally spread, we had a very large meeting at Lurgan,
both of Friends and the town`'s people, who do not profess with us.
It was a solemn meeting, the people behaving well.
My mind continued much proved.

"`Fifth-day, went to a meeting at Lisburn, which was for the most part,
heavy and exercising; yet good revived, and it ended comfortably.
After dinner I had a conference in a humble, broken spirit, with William Mathews.

"`Seventh-day, having had Belfast often in mind,
I was not willing to forego the opportunity of a meeting there; so we set out early,
and readily obtained the room over the market place, where the sessions are usually held.
Pretty many came, and though some were unsettled, yet upon the whole,
the meeting was as satisfactory as could be expected.
I was much stripped, and many fears attended my mind,
both before and after the appointment of this meeting, feeling myself very weak.
Yet I was thankful that I was favoured with stability,
and that the meeting was in measure owned.
Our dear friend John Gough, and divers others from Lisburn,
were at it and were satisfied, which rendered it more easy to me.

"`First-day, eighth month 31st; Went to a large meeting at Ballinderry,
held in a malt house; and towards evening were at a meeting at Hillsborough,
which was dull.
My spirits and bodily strength were much exhausted, not only by hard travelling,
but by peculiar exercise of mind, that I was ready to give out;
but was somewhat recruited next morning.
Attended meetings at Rathfriland and Moyallen, and a large one at Ballyhagan.
Having passed through all the meetings this way, my mind was in much exercise,
being proved with so much barrenness,
that it was difficult to know what step to take that would end in peace.

"`Seventh-day, went to Dungannon and had a meeting in the Presbyterian meeting house,
the minister and many respectable people being present, who behaved well.
The meeting was held to a good degree of satisfaction.

"`First-day, ninth month 7th; Went to the Grange; the meeting was large,
but it was a low season.
We dined at the widow Greeves`'s, and then set out and had a wet ride to Moneymoore.
On second-day morning we set out in the rain, and reached Dungiven; where I had,
when there before, felt the reaches of love towards the inhabitants;
and these being somewhat renewed, I ventured to appoint a meeting.
The inn-keeper being willing we should have one of his rooms, gave notice,
and divers good looking people came, who generally behaved well.
Though I was weak, yet what was delivered was cordially received,
and the people departed in a loving mind.
Having some small tracts relating to our religious principles and testimonies,
I handed them to the people, who appeared glad of the opportunity.
No meeting of Friends, I suppose, had ever before been held here.

"`Third-day, reached Londonderry about the ninth hour.
I was under deep exercise of mind.
My return to this city, for various reasons, was not an easy task,
though the minds of the people are open, and we were received cordially;
some Friends who went on before us, had provided a place and given notice of the meeting;
so that about the eleventh hour we met again in the Methodist meeting house.
Many came and behaved well, except that three or four young people, for awhile,
appeared light.
These were warned, and it seemed to have some place.
Some expressed their satisfaction; and having laboured to fulfil what I believed right,
I feel tolerably quiet.
I have not had eighteen days of such deep proving, as of late, since I landed in Europe;
but I came to be instructed in mortification and abasement,
and desire to be kept single and resigned, and if my life is but given me for a prey,
I hope to be content.
I visited the prisoners again, and found their numbers had increased;
tarried at Londonderry, and sent some books to the mayor.

"`Fourth-day, my mind continuing in a very proved, exercised state,
I was deeply engaged for divine direction, I visited three families,
who received me kindly; and after dinner set out, and passing Strabane,
reached Newtown Stewart; the next day went to Omagh,
and on sixth-day to Cavan and Ballynacrig.

"`Seventh-day, six weeks`' meeting at Moata-Grenoge.
There was a solemnity in the meeting which I was glad to feel.
Our friend Richard Shackleton, was in a lively manner concerned in the ministry.
Here we met our valued friends Mary Ridgway and Jane Watson.
Third-day, attended a crowded meeting at Ballymurry,
divers people of the upper rank being there; and it was to a good degree of satisfaction.
My mind having been deeply exercised several days, and very heavy yesterday on the road,
and in the evening after our journey ended,
respecting a visit to the inhabitants of Sligo, I thought it best after this meeting,
to inform William Mathews of my prospect, and leave it to him to go or not,
though his company was very desirable.
But as a meeting had been appointed to be held on fifth-day at Tullamoor,
he thought it not right to omit attending it.
So with two Friends I set out, but was so much tried on the way,
with poverty and blindness, that I was almost ready to turn back; however,
under deep exercise we reached Elfin, where we quartered at an inn.
I had little sleep.

"`Fourth-day, breakfasted at Boyle, and reached Sligo about the fifth hour.
The session-house being procured for a meeting, notice was given for one tomorrow morning.

"`Fifth-day, my mind was much bowed,
with fervent cries that the Lord might be pleased to grant light and favour.
In this humbled state I went to the session-house,
to which many well looking people came, and appeared satisfied with what was delivered.
I went to visit the prisoners confined in the jail, which they took kindly;
and we distributed several small tracts relative to our religious principles.
We reached Boyle to lodge, "`Sixth-day, setting out early,
we reached Ballymurry about the third hour; but I was very heavy and distressed,
which I kept much to myself.
In the evening, Mary Ridgway and Jane Watson on a religious visit,
had a sitting with a family here; in which my mind was so covered with distress,
that I concluded the cloud of suffering which prevailed, was altogether owing to me,
and was ready to leave the room; but after near two hours spent in painful suffering,
the Friends opened their mouths, the one after the other, in close searching doctrine.
After this opportunity I took occasion to open the
state of my mind to Mary Ridgway and Jane Watson,
and Richard Shackleton, at which they were affected with tender sympathy,
and expressed their satisfaction with my company and the frame and labour of my spirit,
and told me they did not wonder that increasing
distress had attended me since coming to that family,
for some sorrowful things had happened therein.
They uttered some suitable counsel to my present situation, which tended, in some degree,
to my relief.

"`Seventh-day, feeling it best to endeavour to get up with William Mathews,
I parted affectionately with the above Friends on the road, and proceeded to Moat;
had religious opportunities in two houses there, and reached Tullamoor in the evening.

"`First-day, ninth month 21st; Reached Mount Mellick; found William Mathews well,
and attended the monthly meeting, which was large, but exercising; a dull,
easeful disposition prevailing, though there were in this place, some hopeful Friends.

"`Second-day.
Yesterday and this morning,
I was favoured with letters from my dear wife and brother James,
which tended to revive my drooping mind, and excited thankfulness,
in finding the Lord was rich in mercy to my wife in my absence.
I have had for some weeks past,
little leisure and less capacity to salute my dear friends.
I have been led into a path, new and singularly proving;
but at all the places we were respectfully received,
and I believe an open door is left for further labour.
I am so poor and weak, and so full of fear of overdoing,
that pain attends me respecting some places, though I endeavoured to do my best.`"

After this they attended meetings at Montrath, Knockballymagher, Roscrea, Kilconnermoor,
Limerick, and some other places.

"`Fourth-day, tenth month 1st; This morning we proceeded to Charleville;
which place having been much in my thoughts, I was most easy to propose a meeting.
The widow at whose house we put up,
having a large room which she was willing to let us have, it was seated,
and notice being spread through the town, the meeting was much crowded.
Though for want of better knowledge, some were unsettled, yet many behaved soberly.
William Mathews had a large, seasonable opportunity,
and truth impressed the minds of many.

"`Fifth-day, rising early, we proceeded, and reached Samuel Neale`'s in the evening,
where we were joyfully received.

"`Sixth-day, attended the meeting at Cork,
where there was a comfortable appearance of plain young people.

"`First-day, the 5th; Attended two public meetings in Cork, the first of which was silent.
Though there are many valuable Friends here, yet many others are superficial professors.

"`Third-day, was at the mid-week meeting in course,
and also the men`'s meeting for business.

"`Fifth-day, had a comfortable opportunity at Samuel Neale`'s, and then took horse;
and as I drew near to Middleton, where we proposed to refresh ourselves and horses,
I felt some engagement of mind to hold a meeting; and notice being accordingly given,
a pretty many gathered, and some counsel was imparted,
which appeared to be well received.
We passed on to Youghall, and were kindly entertained by our aged, valuable friend,
the widow Elizabeth Richardson, who was my hostess at Limerick when here before.
It was comfortable to find she was truly alive in spirit; as much so as most in this land.

"`Sixth-day, the meeting at Youghall was favoured, my companion having a very open time.
After dinner we had a comfortable opportunity with a young Friend,
a daughter of a merchant in Cork, who is convinced and converted.
She is much rejected by her parents, who do not approve her change.
We then proceeded to Caperquin.

"`Seventh-day, we had a large meeting in the market-place, which, I hope,
did not lessen the reputation of truth; many expressed their satisfaction.
We reached Clonmel in the evening and attended the meeting of ministers and elders;
and first-day, two public meetings and an evening opportunity at Robert Dudley`'s,
to which came many Friends.
These meetings were exercising, yet some counsel opened in each.
There was a large appearance of plain, hopeful youth, especially among the females.
Attended the quarterly meeting for Munster, and then had a meeting at Garryrone.
My mind was much exercised in the prospect of going back to Charleville;
but labouring to be resigned, and gathering some elders, with a few other Friends,
I laid my exercise before them.
I was encouraged to pursue my prospects, however feeble I might feel;
and as my companion was more disposed to attend the meeting at Clonmel,
I resigned him in love; though on my part under discouraging thoughts.

"`At Clonmel, the elders having a conference,
deputed two Friends to take an opportunity with William Mathews and myself;
being dipped into sympathy and concern for us and for our religious service,
they thought it right to propose our parting,
under an apprehension that our service might be more extensive.
As our prospects at times varied,
they feared our minds were more burdened and oppressed than perhaps was right.
Their care and sympathy I could but acknowledge;
but told them I did not see my way clear to part,
and that I considered myself not fit to journey alone.
They did not press it,
but left the matter under our consideration until after the meeting at Garryrone;
and if then our concerns led different ways, advised to attend thereto.
It is a great blessing, that notwithstanding the low, languid state of things, a living,
feeling sense, is still preserved in the church.

"`Fifth-day, proceeded to Charleville and appointed a meeting.
A number of people came, supposed to be of the more reputable inhabitants.
Many of the lower class were deterred, as we were informed,
by the Romish priest having reprimanded the widow who
kept the inn we were at when here before,
for suffering us to have a room for a meeting.
He had made some do penance for attending it, by walking seven miles out, and back.
This made the meeting smaller, though more came than our room could hold.
Some favour was shown to us,
and I had cause to be thankful that this day`'s work was so well over.

"`Sixth-day, awaking very early, a fresh exercise attended me,
in a prospect of going to Mallow.
After rising, I got my companions together, and solidly laid the exercise before them;
and they encouraging me, we reached Mallow about noon.
I was much stripped of inward comfort, but I ventured to give notice of a meeting:
a large number came, and I hope the reputation of truth was not lessened.
One man, a soldier, came to me after meeting,
and in a solid manner thanked me for the good advice given.
On seventh-day, my mind having been again exercised in the night season,
I feared to go away without attempting another meeting.
After which I prepared to leave Mallow, and reached Cork in the evening, more easy,
I believe, than I should have been,
had I come away without giving them the opportunity of another meeting.

"`A sorrowful gloom attends this land,
and it is to be feared that things are ripening for a scourge.
A set of people are taking the same steps, or nearly so, that were taken in America;
meetings and resolves are frequent, and there is a heavy cloud felt;
as was at the beginning of our troubles.
Ireland is a land in which I have been deeply proved, and the great Master keeps me poor;
perhaps in this state I am more attentive to his voice,
and the want of spiritual bread makes me willing
to yield to what is hard to the natural part.

"`How I may now be led, I know not; I live from day to day, and hardly see, one day,
how I may be led the next.
But, however we may be proved and led in paths not heretofore known,
yet if pure wisdom and strength be vouchsafed, there will be no lack.

"`Fourth-day, having yesterday laid before divers Friends in Cork,
a concern that had for some days attended my mind,
respecting a visit to the people of Kinsale,
I set out this morning and had a very wet journey, my friend Edward Hatton, etc.,
accompanying me.
Many came to the meeting, which was in measure owned, and counsel flowed to the people.

"`Seventh-day, rising early, set out for Waterford and arrived there in the evening,
much wearied with a long ride, the ways hilly and bad.
We passed through Dungannon, and saw the rock where our dear friend Susanna Morris,
was shipwrecked.

[.small-break]
'''

+++[+++This truly evangelical minister of Jesus Christ, as John Griffith calls her,
suffered shipwreck three times; but the occurrence here alluded to,
was about the year 1731,
on her voyage to pay a religious visit to Friends in Great Britain and Ireland.

Joseph Taylor, from Raby, in England,
was returning in the same vessel from a similar service in America.
The following is condensed from her own account of this memorable occasion:
"`Soon after I got out to sea, I dreamed that our ship would be lost,
and there remained on my mind a solid weight, for fear it should be so.
But at times, I thought it had been as some other dreams;
and yet I thought it safe to dwell humble and low before the Lord.
I again dreamed the same;
and yet was weak as to being fixed in a belief of the truth of it,
until the Lord was pleased to favour me with his goodness,
and in one of our meetings to make it known to me,
that we should surely suffer shipwreck.
And then, for a season, I was in trouble.
But Oh! blessed forever be the name of our God;
for I had soon a good answer returned into my bosom, of our preservation,
and that if we would be faithful, we should have our lives for a prey.
I hinted something of my mind to the captain, who seemed somewhat startled;
and lest he should be too much discouraged, I had it given me to tell him,
that I should see him safe on shore.
It was some time before it came to pass and when
I hinted a little of what was made known to me,
to Joseph Taylor, I found that it seemed like idle tales to him.
So I forbore to go further in the relation of it to him;
yet I was preserved so as not to stagger in my mind,
or disregard the manifestations made known to me, from Him that is true.
And as I endeavoured to dwell near Him who is faithful and true,
my habitation was pleasant, until the sudden outcry was proclaimed,
and nothing appeared but the destruction of all our lives.
Then, for a time, my outward tabernacle greatly shook and trembled.
But, blessed be the great Lord of all our mercies, the time of trembling was soon over,
and what was made known to me was renewed,
that the all-wise God would command the proud waves,
that they should not come at his servants to hurt them; as it was said:
'`Touch not mine anointed, and do my prophets no harm.`' And so it was,
the great God did preserve us, I believe, for his own name`'s sake.
It was the time called Christmas-eve, and very cold; and we had, for two days,
little sustenance for our bodies; and many times our heads were under the great waves,
which rolled over us after the ship sunk,
by reason of the strokes she got on the dreadful rocks.
Afterwards she drove, until she settled on a sand bank.
In that distress I had no help of man, or counsellor but the Lord alone,
and thereby thought it best for me to get to the upper side of the vessel,
and fix my seat by the shrouds, where I was favoured so that I kept my hold,
when the waves rolled over us; and we remained in that wet condition about nine hours,
in a cold time of frost and snow, before any of us got relief.
And yet I was not hurt--the Lord is pleased to favour his
heritage--though many of the ship`'s company lost their lives;
some perishing with the cold, and others were drowned.`"

John Griffith mentions the following additional particulars of this event,
narrated to him by Joseph Taylor: "`The ship was driven on her broadside,
yet did not soon break; but the sea running high, broke over her,
and several of the crew were washed overboard and drowned.
The captain, Susanna Morris, Joseph Taylor, and perhaps one more,
scrambled up to the upper side of the ship, and held fast by the shrouds,
the sea frequently breaking over them.
Joseph Taylor told me, Susanna never discovered the least impatience,
in word or countenance, all the time; but he confessed that he once, in a flutter,
or impatience, did say to this effect; '`We might as well have gone at first,
for we shall be drowned.`' She looked upon him, and said nothing; but, he said,
her looks were a sufficient rebuke for his impatience and distrust.
After they had held a considerable time by the shrouds,
this extraordinary woman had a sense given her,
that they would not be safe on that side of the vessel much longer;
and although it seemed very hazardous to move and fasten to the lower side of the ship,
she urged them all to attempt it, believing it would be the means of their preservation.
She at length prevailed, and they moved, in the best manner they could,
to the lower side of the ship; and soon after they had fixed themselves,
there came a great swell of the sea, and threw the vessel quite flat on the other side;
so that if they had not moved, they would all have been drowned.
A priest being informed that there were some persons alive in great distress,
came down to the beach and charged his people not to hurt them,
but use all means to save their lives, threatening that if they refused to comply,
they should never have their sins forgiven.
And through the assistance of a merciful Providence, they brought them safe to land,
and treated them with great hospitality.`"

"`And now,`" says Susanna Morris,
in concluding her account of this wonderful preservation,
"`I write not this relation because I would have any to think the better of me; no,
that is not what I aim at; but that the poor in spirit, or weak in their own eyes,
if willing to serve the Lord, may take a little courage to trust in the Lord,
and be truly willing to serve him in all that he may require of them.`"]

[.offset]
Returning to Journal:

"`First-day, tenth month 26th; Was at three public meetings at Waterford this day;
that in the evening was attended by a large number of
the inhabitants not professing with Friends.
All these were exercising meetings,
the professors of the truth being involved in the spirit of the world.
It is to be feared, that through a desire of gain,
some have not been free from joining with a spirit that upholds war;
for notwithstanding there may not be a taking up gun or sword,
yet contracting for provisions and other matters, in the way of trade, for fleets, etc.,
tends to sully and bring dimness and reproach on our profession.

"`Third-day, had a meeting at Ross, with the few Friends there,
and some other inhabitants; and on sixth-day reached Dublin, where I met William Mathews.
I attended the half-yearly meeting of ministers and elders for the nation;
also two public meetings;
and second-day was spent in transacting the affairs of the church;
some former advices were agreed to be revived,
to caution against too eager a pursuit of the world.
There is a pretty large appearance of Friends now here;
and although there is a general languor, many being involved in the world and its spirit,
yet there is a concerned number who continue to have the cause of truth at heart.

"`Fourth-day was a public parting meeting, which was solemn;
and then the meeting for ministers and elders,
in which I opened a prospect which had attended me for some days,
of visiting several places where no Friends reside, which was united with.
Mary Ridgway spoke in a prophetic way, of a day approaching,
that would try the foundations of the professors of truth.

"`First-day, at the meeting in the afternoon, our dear friend Samuel Neale,
had to express in a lively, feeling manner, his sense of a day approaching,
which would prove the faith and try the foundations of the professors of the truth.
He had not only at that time, but at divers others, been made deeply sensible thereof;
whether by pestilence, or other means, he could not tell;
but he exhorted Friends to prepare for trials.
In the evening we had a religious opportunity at our quarters,
Mary Ridgway and Samuel Neale, and divers other Friends being there.
Here also he had to speak to a state in danger, and mentioned the case of Jonah,
whose gourd was taken away; which he believed might be the case with some present.
May I, and may all watch and live in humility, in which is preservation.

"`My mind is engaged to visit Newry and some other places,
the prospect of which is deeply humiliating; but I cam.e for peace,
and must pursue the line that leads to it.
The sympathy of many brethren has been manifested,
indeed more love shown than I could expect;
I desire to be preserved from wounding the cause, if I cannot advance it.

"`Our dear friend Mary Ridgway, in much feeling sympathy,
accompanied me on third-day to Drogheda, where the meeting was held in the session-house,
and was attended by several hundred people.
One person, after meeting,
expressed his thankfulness that a renewed visitation had been extended to him,
who through unfaithfulness to some former touches of good,
had not made progress in religion.
He was very tender; and if but one is brought forward,
it is worth undergoing baptisms and trials for.
The rain has prevented our going forward to Newry.
My suffering is great, and the sense of my own weakness depresses me: however,
I ought not to complain.
Here our aged friend James Christy, met us.

"`Sixth-day, proceeded to Newry, and had a meeting in the Presbyterian meeting house;
the minister having offered it.

"`First-day, attended the youths`' meeting at Lurgan,
where our friend John Gough had very acceptable service,
in close and pertinent remarks to parents, and also to the youth.
In the evening, divers Friends being present,
we had a religious opportunity at our quarters.
My mind was deeply proved,
under the prospect of visiting places where there are no Friends;
and our friend John Gough, was dipped into sympathy with me, as he afterwards told me,
though he knew not what rested on my mind.`"

After this he visited Moyallen, and then returned to Dublin.

"`Third-day, summoning the elders, overseers and ministering Friends,
I laid before them the deep provings of my mind; and on solidly weighing the matter,
they encouraged my return to the north.
I was much stripped and proved, and remained so for many days:
I have had many trials of faith since I came into this island,
and when they may terminate I know not.
I have been particularly led to visit places where there are no Friends;
and knowing my own unfitness,
and how much the reputation of truth is concerned in such movements,
it bows my mind greatly; however, I have no right to dictate, or say, what doest thou?

"`Fourth-day, I went to Lisburn, to my dear friend John Gough`'s,
where I had a kind reception,
and conferred with him about the prospect I had of visiting some remote places;
he was dipped into sympathy with me.
At the close of the meeting next day,
our friend opened his mind respecting joining me in my prospect,
if way opened for his leaving home.

"`First-day, twelfth month 7th; Attended a large meeting at Lurgan,
and paid religious visits to three families.

"`Second-day, being joined by William Pike, I left Lurgan,
and on the road met with our friend John Gough, and two others;
and we proceeded on our journey northward.`"

He held meetings at Ballinacree and Coleraine, and thence went to Newtown Limavady;
where, he says, no meeting of Friends to his knowledge,
had been held since William Edmundson visited it.
The people, he adds, behaved well, and the meeting was favoured.

"`Sixth-day, rising early, we reached Strabane, and strove for a meeting;
but the provost, to whom we were recommended, being from home, the burgesses,
on conferring, refused us the town-hall.
So in the afternoon we went to Lifford, about three quarters of a mile from Strabane,
and readily obtained liberty of the court house: we had a pretty large meeting,
but in general they were a light company; yet counsel opened,
and we were satisfied with having laboured to do our duty.
We returned to Strabane, and two of our friends waiting upon the provost,
he excused himself from letting us have the townhall.
So in the morning John Gough wrote a letter to the provost, burgesses, etc.,
which he and I signed,
informing them that it was the only instance in the course of a long journey,
that we had been refused being accommodated with a place for a religious meeting.
However, having liberty of the court house at Lifford,
the inhabitants of Strabane were invited, and some came;
and the people behaved better than at the meeting yesterday.

"`First-day, went to Newtown Stewart, and at the inn had a large room offered us.
A large meeting it was, and very satisfactory.
There never had been, as I know of, a meeting of Friends held here before,
except that as our friend John Alderson, upwards of twenty years ago,
passed through the town, he had an opportunity with a few of the people.

"`Second-day, we reached Omagh, and applied for a place to hold a religious meeting,
which was readily obtained.
There was a large gathering of people in the jail and court house, who behaved well,
and some were very solid: the meeting was open and satisfactory;
the curate of the parish was there.
No meeting of Friends, that I can learn, was ever held here before;
and though things looked at first dark and discouraging,
yet light and favour prevailed when we met.
After the public meeting was over, I had an opportunity with about twelve felons,
men and women.

"`Third-day, reached Dungannon, and the province meeting coming on,
my companions left me, departing to their several homes.
I went forth, in this journey, with scarcely any faith, and was kept low,
yet was favoured with encouraging company, and got on better than I expected.
May I be enabled to praise the Lord, though unworthy of the least of his mercies.
My dear friend John Gough, was wonderfully opened and enlarged in doctrine,
and if I am exercised in order for others to be in the way of doing good,
I desire to be content.
I believe the testimony of truth was exalted, and an openness left for others to follow.
I now wait, not knowing how I may be led after the province meeting; though,
as more labour of like sort opens to my view,
it is uncertain when I may get away from these parts.
But as dear John Woolman remarked,
we have no just cause to murmur at the different paths
which Infinite Wisdom sees meet to lead into.
I think my trials are great,
but I know I have increased them for want of exercising the small portion of faith given.
I take no step, but with the solid sense,
sympathy and unity of the most feeling and judicious members; and, as a man,
glad should I have been, had they put a negative on my concern.
It is indeed strange that I should be thus exercised;
but those who have accompanied me have been much favoured; and I am willing,
if good is done, that others may not only have the greatest share of peace,
but of praise; though truly there is no praise due to man.`"

In a letter written about this time to his brother, James Pemberton,
he thus speaks respecting the interesting subject of the wrongs of the African race:

"`I was anxious to hear how you fared at the yearly meeting.
So agreeable an account is cause of thankfulness; and I was pleased with the step taken,
to lay before congress the afflicted state of the injured Africans.
They have said much about liberty, and I wish, in this affair,
they may manifest their regard thereto.
It is pleasing to find that the case of this people
becomes more and more seriously considered,
as this gives hope that good will arise, and deliverance come in time.`"

After this John Pemberton returned to Lurgan, taking meetings in his way;
and John Gough and James Christy again joining him,
they visited a number of places where no Friends resided.
His short account of this tour,
contained in the following extract from a letter to his wife,
shows the earnest exercise of an humble mind, to be found in the path of duty.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Lisburn, First month 3rd, 1784.

My dearly beloved wife,
"`Desirous that thou mightest hear from me as frequently as possible,
I now again sit down to salute thee in unabated love,
desiring that the Divine Arm of strength that
wrought a willingness in us to be separated,
for the discharge of duty to Him and the promotion of piety and godliness,
may continue to be mercifully near to preserve and sustain, inwardly and outwardly.
I believe we may appeal to the great Searcher of hearts, that our eyes were truly single;
and blessed be his name, we can testify to his goodness, that hard things have,
through his gracious help, been made in measure easy,
and bitter portions have been sweetened by his love.
May we be still helped to trust in him, and by waiting upon him,
receive strength to journey forward in the high
and holy way cast up for the redeemed to walk in;
that through his mercy,
we may receive '`the white stone and the new name;`' and in the solemn close,
be admitted to join the heavenly host in the triumphant song.

Since my last, I have been another tour, accompanied by my dear friend John Gough,
and other kind friends; had seven meetings in seven days,
and rode one hundred and thirty miles,
notwithstanding the days were short and the weather unusually cold.
In these journeys we were often on horseback nearly two hours before sun-rise,
yet were preserved in health.
Three of these last meetings were held in Presbyterian meeting houses,
two in a methodist meeting house, and one in a large chamber of a market house,
all large, solid and quiet; and our friend John Gough, in this, as in the former journey,
much favoured.
I consider these journeys as making way for other servants.
I was called to surrender all, in a time of difficulty and danger,
and am now engaged in a trying path, to prepare the way, as I conceive,
for others better fitted.
When I may be released, I know not; I see no end at present.
I find it very difficult to preserve peace to my mind; fears, doubts and diffidence,
and too readily giving up my own feeling and judgment, bring stripes.
Many drooping moments have I had in this land;
though I believe few have met with more sympathy from truly concerned Friends.

By a letter received yesterday from Cork, I find William Mathews was there.
He attempted to go twice for England, but was stopped in mind;
yet I apprehend he will get away before me.
But if we are enabled to fill up our respective duty, the reward will be sure.

Things seem ripening here for confusion and distress; and the Lord in mercy,
may be awakening some to prepare a hiding place in the day of trouble.

Now, with the tenders of endeared affection, I bid thee farewell;
being thy faithful husband,

[.signed-section-signature]
John Pemberton.

--

He continued for some time in the northern parts of Ireland,
visiting many places where no Friends resided, and having meetings at several towns,
where no Friends`' meeting had been before held.
John Gough and James Christy were his constant and sympathizing companions.
Ballymena, Ballinderry, Moix-a, Stramore, Moyallen, Lisburn, Shane castle, Castle Dawson,
Toberhead, Bellackey, Portlanon, Ballamoney and Ballinacree,
were among the places visited during the first month, and a part of the second.
At Lisburn he attended the quarterly meeting for Ulster, and after this was over,
remarks:

"`I had an opportunity with the ministers and elders,
who manifested much brotherly sympathy with me in the exercised path I have trodden,
and yet am likely to tread; in which they were careful to avoid discouraging me.
I also opened to them a desire prevailing in my mind to have
another opportunity with the inhabitants of Lisburn;
in which they acquiescing, in the evening we had a large meeting, solid,
and I hope profitable.

"`Second-day, second month 16th; This morning we set out for Londonderry;
my mind never having been easy since I was last there.

"`Third-day, endeavours were used last evening, to meet with the mayor of Londonderry,
in order to obtain the town-hall to hold a meeting in; but he being gone to a play,
which did not break up till midnight, it was about one o`'clock this day,
before we obtained leave.
Notice being then given, the principal inhabitants attended;
and the meeting issued full as well as could be expected,
among a people much void of true religion;
the pursuit of worldly gain and false pleasures,
taking up the attention of the people of the upper rank.
My spirit has been much burdened in this place, and is yet more particularly bound to it.

"`Fourth-day; the sins of the people in this city lay so heavy upon me,
that I had little rest after a day of great exercise.
In the morning I arose and wrote to the mayor, and so left the place.
In crossing the water, and on the road,
my mind was taken up with thoughts respecting Strabane; but hoping it would wear off,
I proceeded about nine miles.
I then told the Friends with me, my situation; who kindly agreed to accompany me.
So we turned towards Strabane, and arriving there between the fourth and fifth hours,
we ventured to apply to the provost for the townhall,
though it had been denied us when here before.
He, consulting some others, informed us that we might make use of it.

"`Fifth-day, the place being prepared,
and notice given by the activity and diligence of my worthy, aged friend, James Christy,
the meeting began soon after one o`'clock, and was large; many,
or most of the principal inhabitants, and many of the poorer sort also, being there.
The Lord was graciously near, to uphold me and open my way,
so that I left the place pretty easy, and came to Claude.

"`Sixth-day, the wind being high, and a sleet falling,
it was with difficulty we could get along, or sit on horseback; and it blew so hard,
that in riding a few miles we were very wet, and I feared we might be lost,
as the roads were so filled that we could scarcely find the path;
and were obliged to stop at a poor man`'s house,
to dry ourselves and get some refreshment.
We reached Dungiven, where we were obliged to stay the remainder of the day,
which was as blustering and snowy, as I have known,
and I fear many people and cattle will be lost.

"`Seventh-day, I thought it best to turn my face towards Londonderry again; having,
through weakness and hurrying away, omitted to visit the prisoners in that place;
and reaching it soon after three o`'clock, we had a religious opportunity in the jail,
and the prisoners took our visit kindly.
Greatly affecting was it to see so many fellow beings in such a situation,
most of them having brought distress upon
themselves through disregard of the Divine fear.
I left a small sum with the jailer, to hand to the most necessitous.
We then visited three families of sober people; and this making it late,
we found some difficulty in procuring lodging; but after trying several inns,
were at length admitted.
Having eaten but little, and been much exercised all day, I was faint;
yet after taking refreshment, had some sleep.

"`First-day, 22nd; Awaking early, my mind was renewedly exercised,
and I found it most easy to go to the meeting of the Methodists;
and after their service was over, I requested liberty to speak a few words;
which I did tenderly,
expressing my persuasion that there were some tender people among them,
who sought the favour of God; and yet a fear attended me,
lest they might rest too much upon outward performances, in hearing preaching, praying,
and singing of psalms;
and that it was my belief they would make as great
advances in the Christian path and life of religion,
were they to study and practice silence more.
As I expressed myself in soft language and much tenderness, I hope I did not hurt any;
and one afterwards told me he believed none would take my observations amiss,
being delivered in love.
Now I thought I might leave this city, which had been a place of deep exercise to me.
We crossed the ferry,
and there I found some desire to have a meeting at the town on that side the water,
and the people appeared satisfied with the opportunity.

"`Second-day, reached Newtown Limavady, after a small meeting at Ballycally.
In our way we called at a free-school for the
education of the children of such Roman parents,
as choose to send them to be brought up in the Protestant religion.
My expectations were disappointed, finding the house very dirty,
and a strict care respecting the poor children wanting.
Our visit was received kindly by the master.

"`Fourth-day to second-day, at Coleraine, and had two meetings.
I also found some stop respecting proceeding;
and a renewed exercise attended my mind respecting Londonderry, which remained with me,
at times very heavy, while at Coleraine, I opened a little of my exercise to my worthy,
aged friend James Christy, who was solidly impressed with it,
but hoped it was only a trial of faith.`"

This concern, which was of a peculiarly trying nature,
remained with him for several weeks, until his mind became at length resigned to it,
under a conviction that peace was to be obtained only
through faithfulness to the pointings of duty,
however contrary to the natural feelings.
In the mean time he continued for the most part,
visiting many places in that part of Ireland, which he had previously had in prospect,
having a number of meetings in places where there were no settlements of Friends.
At Ballycastle, he says:

"`We had a large and favoured meeting in the chamber over the market-place,
the people generally coming.
Several Episcopal ministers attended it, as also one Ezekiel Boyd,
with his wife and children, the proprietor of the town and lands about it,
who pressed us to take dinner with him; but after some friendly discourse,
we excused ourselves and proceeded to Clough.

"`Fifth-day, after a meeting at Clough, we passed on and reached our friend T. Irwin`'s,
near Ballymena, where we dined and had a religious opportunity with his family;
and then went to visit a sick man,
confined to his bed by illness brought on through intemperance.
He having, some days before, expressed a desire to see me,
I visited him and dealt plainly with him.

"`First-day, third month 7th; Attended the men`'s meeting at Lurgan,
and received many letters, which had been lying some time for me.

"`Second and third-day, at Stramore.
It is sorrowful to hear that so many people are flocking to our city +++[+++Philadelphia,]
for the sake of pursuing after earthly treasure.
Our religious Society is brought into great disrepute in some parts of this land,
by the failure of many under our name, for very large sums,
through embarking in government contracts;
some of whom now acknowledge that a blast has attended every Friend who engaged therein.
I wish it may teach others more care; but the hands of some in Great Britain,
as well as in this land, are deeply defiled,
by entering into matters very opposite to the testimony of truth:
so that the hearts of many are made sad;
and some who are truly concerned that occasions of reproach should be removed,
are looked upon as busy meddlers.
For there are those who are in the spirit of Sanballat and Tobiah.

"`Seventh-day, the 27th; I have had a slow fever and cough,
by hard travelling in very severe weather and close exercise of mind,
which rendered it needful to lay by awhile.
I am now recruiting, and should have recruited faster,
were it not for the weight of exercise that attends my mind.
I expect in a few days to leave this, to be led as the great Shepherd opens the way.
If I am mercifully preserved upon the foundation,
and in obedience to and reverent trust in the all-powerful Arm, all will be well.
It is a great attainment to be wholly given up.
It is only hereby that the mind becomes stable, and a happy calm is known.
We are too apt to look at some requisitions as hard, which are so to the unregenerate,
unmortified part.
But to those who can unreservedly say, it is their meat and drink to do the Lord`'s will,
hard things become easy, and mountains are removed;
I find I am far from having already attained; the creaturely part is ready to shrink,
and fears to prevail.
But the Lord is merciful, and if I am but kept to the end,
and favoured with an admittance into the gate of the holy city, it is all I look for.
May the Lord be near, and preserve in an humble watchful state,
and in a daily exercise to labour for daily bread.
Trusting to former experience and sliding into a relaxed state, will assuredly bring loss.
The nearer we are concerned to live to the Fountain, the more fresh will our spirits be,
and the more ardent our concern to be fitted to fill up our allotment,
both in the church and in life.
My path is widely different from what I expected when I left home.

"`First-day, fourth month 18th; Rising early, we went through Strabane to Raphe,
and had a large meeting in a malt-kiln;
and afterwards set out in the rain and had a very wet ride over the hills to Letterkenny,
where we lodged; and on second-day, our landlady offering a large room, it was seated,
and we had a pretty satisfactory meeting; though, as Friends were much unknown,
some at first appeared shy.
But they were afterwards pleased with the meeting, and some were for making a collection.
The landlady said it was the only visit they had had at which there was not a collection.
I told her and a friendly man who was speaking of this matter,
that I had never received sixpence for preaching,
and that none of our ministers were paid, believing in the words of Christ:
'`Freely ye have received, freely give.`' We left the people favourably impressed.
At several meetings besides this, persons were for promoting subscriptions,
wondering how we sustained the expense of travelling, without pay.
I was deeply exercised upon leaving this place, respecting my next proceeding;
and having for many weeks borne my exercise,
I became much resigned to follow the prospect, let the consequence be what it might.

"`Third-day, fourth month 20th;
Set out early this morning and reached Londonderry between seven and eight o`'clock,
and concluded to prepare to fulfil what appeared my duty.
And my kind friend James Christy, having prepared some wrapper,
had it made up in the form of a cloak;
and thus I passed through two gates and the main street of the city.
We walked slowly, and my mind was covered with much solemnity and awe.
At some places I proclaimed repentance to the inhabitants.
Some appeared struck with admiration, but not the least affront was offered,
nor any mob followed.
Coming at length near my quarters, my mind being very quiet, I was free to turn in,
but soon found I was not fully released.
The Lord has been merciful, and I trust,
accepted a part of the service that engaged my mind.
It was very humiliating; yet I was favoured with great composure in the performance of it.
My path is strait and not common in our day: but He that formed us hath a right to direct.
I could have given up my natural life, had the Lord seen meet to accept it,
rather than to return to this place and to fulfil the prospect.
But with Him, obedience is better than sacrifice, and in a steady subjection,
hard things become easy.
May I be preserved not to wound the testimony.

"`The next day, the exercise continuing with me, after much solid weighing,
about the tenth hour I passed through two other gates of the city,
and through two or three streets where I had not been before,
as also the main street again; and several times had some little matter to express,
warning the people to remember the mercies of God, and to turn to the Lord of hosts,
lest his righteous judgments overtake them,
as they had been poured forth in other countries.
The people were very civil, and though it was their market day,
and the time of the assizes, and the streets about the market-place, in particular,
pretty full of people, yet no taunt or insult was offered.
As I had seen much rudeness among boys in this place,
I had some reason to fear a mob might follow, and my life be in danger;
but no such thing appeared; all was quiet.
Finding my mind, as I thought, somewhat eased, we prepared to leave the place;
and not being able to get over the ferry at Derry, we went by Strabane,
and reached Omagh in the evening, where we lodged.`"

The substance of what John Pemberton delivered to the people on this occasion,
is thus stated in a memorandum in his own hand-writing, found among his papers: "`Repent,
repent, O! all ye inhabitants of Londonderry and of this land,
while the Lord`'s mercies are continued unto you!`"

A number of people gathering about him at one of the gates,
after repeating the above words, he expressed that it was a great cross to him, as a man,
to appear as he did,
but that he believed it was required of him to be as a sign to this people;
and that if the highly favoured people of this land did not humble
themselves and manifest greater gratitude to the Author of all blessings,
it was easy with him to permit trials to overtake them,
as he had permitted trials and chastisements to
overtake the inhabitants of his native land,
for their ingratitude for great favours conferred upon them.

"`Sixth-day, returned to Stramore, and unexpectedly met with William Mathews,
Patience Brayton and Rebecca Wright; and our meeting was mutually satisfactory.
Though it was a great trial to give up to this journey,
yet being favoured to return in safety,
I had occasion to be humbly thankful to the great Preserver.

"`Seventh-day, attended the quarterly meeting for Ulster, held at Moyallen; a low season.

"`First-day, fourth month 25th; The meeting was large,
many not professing with us attending.
William Mathews had, yesterday at the close of the meeting,
to speak of a day of trial that in some way or manner would overtake,
wherein the professors of the truth would be deeply proved;
and therefore Friends were exhorted to be prepared for it.

"`Second-day; this morning rising early, I set off for Armagh,
accompanied by our dear women Friends from America, and some other Friends.
The court-house being granted, we had a large meeting,
and the people generally behaved well.
This city is the residence of the archbishop;
but though the resort of abundance of those who profess to be ministers of Christ,
yet the life and virtue of godliness are not
more prevalent here than in some other places.
After dinner we went to the large new jail, and visited the prisoners, nearly forty,
and three of them under sentence of death.
Many of them were young men, and some grey-headed;
and it was an affecting sight to see my fellow creatures loaded with heavy irons,
and others also through a disregard to the Divine fear,
brought into suffering and confinement.
Much sympathy attended my mind for them, and I laboured, according to the measure given,
to awaken in them proper reflections, and a regard in future, for the Divine fear.
Some appeared tender.

"`Fifth-day, had a meeting at Castle Bellingham, to which many people came;
and among others, as it was said, four Romish priests.
Two of these priests came into the meeting late, appearing as travellers.
While our dear friend Rebecca Wright was speaking, one of them burst into laughter,
and some young women and girls, and a few men, behaved lightly.
After she sat down,
I endeavoured to expose the inconsistency of such
conduct with the solemnity of such an occasion,
though that room was not built purposely for religious meetings;
and I informed them that in my native land,
it was considered as one mark of good breeding, to behave well in places of worship.
Notwithstanding this inconsistent behaviour of some, much owing, I believe,
to the novelty of a woman preaching, yet others were sober,
and appeared solemnly impressed.
I took an opportunity, after meeting, of speaking with these two disorderly priests,
and told one of them that by his appearance,
I took him to be one who professed to be a minister, and that such conduct disgraced him;
to which he made no reply.

"`At Drogheda my mind was deeply weighed down, as I apprehend,
in sympathy with the Seed of the kingdom in suffering in many hearts.

"`Sixth-day,
reached Dublin in time to refresh ourselves before the quarterly meeting for Leinster;
and there I was also refreshed by the company of many dear friends,
after a toilsome journey of five months, in a very arduous employ,
yet mercifully sustained beyond expectation.
May the Lord be praised!

"`Second-day, the half-yearly meeting for business was opened,
and continued by adjournments.`"
After this he had meetings at Timahoe, Athy, Cooladine, Wexford,
and several other places, and then proceeded to Enniscorthy.

"`Third-day, attended the meeting, which was favoured,
many reputable sober people of the town being present.
After their departure I had an opportunity with Friends,
and pointed out the necessity of waiting for that
wisdom and power which influenced our worthy ancients,
and qualified them to maintain our religious testimonies with propriety,
making such opportunities seasons of edification.

"`Fourth-day, arrived at Kilkenny, and the room over the market-place being granted,
we had a large meeting, which was pretty quiet.
John Duke of Ormond, the mayor, the sheriff, some of the magistrates,
and other principal inhabitants attended, and many of the lower rank also.
At this place the meetings of Friends have been often disturbed, but this was peaceable.
The duke, after meeting,
said that Friends should at any time be accommodated with the same room.
The sheriff also, at the departure of the people,
joined in an endeavour that no disturbance should occur,
for there were many rude boys who were prevented from getting into the meeting,
and were very restless and bold.
In the morning I found myself not easy to leave this place
without an opportunity with the prisoners in the jails.
In the county jail there were about twenty persons confined,
several of whom appeared impressed with the advice given them.
We left some money with the jailer, to be laid out in bread and milk for them;
and then went to the city jail and visited the prisoners there.
This opportunity was not so comfortable,
though they acknowledged the kindness of our visit.

"`Sixth-day to second-day, fifth month 24th, at Ballinclay.
Notwithstanding my hurry, I am not yet loosened from this island.
Great is the mercy of God toward her inhabitants,
too few of whom properly lay it to heart; yet there is a seed that God will bless,
and after a day of trial, may raise up to be testimony bearers of his truth.
I am not my own, and find obedience alone produces true quiet;
great enjoyment I cannot boast of; the Master keeps me low and poor;
and I find I am not to live by bread alone,
but by every word that proceeds from his mouth.

"`Sixth month 24th; I continue to journey as heretofore,
but my rides have not been very long at a time,
having been for several weeks employed in the counties of Wexford and Wicklow.
I was this day week on the sea-coast,
visiting the descendants of those who came from England with Strongbow,
in Henry the second`'s time.
They differ from the general inhabitants of this island in their dialect,
retaining much of the old English, or Saxon speech.
The meetings were quiet, and we parted lovingly.
I hope a solid care still dwells with me, to move under the guidance of Divine wisdom,
and to watch when notice may be given to cease, and leave this island.
I saw my way into it, but cannot yet see my way out.
Friends continue their kindness, sympathy and love,
but I wish to get away before any shall think I dwell long among them.
It is satisfactory to hear that my dear friends are not
uneasy with my singular steppings in this land;
I feel my own weakness, and consult my friends on every movement,
and hope always to go along in the unity.

"`I find that the yearly meeting of London,
has yielded to the women Friends a regular yearly meeting; which was one,
among other matters, that made me much desire to get to London,
to join in promoting it.`"

The reader will probably recollect,
that this important subject had been brought forward thirty years previously,
at the quarterly meeting of York, by William Brown,
and that John Churchman and John Pemberton then took a deep interest in it.
But the yearly meeting at that time did not see the way to unite in the proposal,
referring it after solid deliberation to a future year.

"`Sixth month 29th; Received letters from my brother,
with the sorrowful tidings of the decease of our worthy friend, Anthony Benezet,
who will be much missed in our city; being not only a pious example,
but greatly devoted to serve mankind.

"`Seventh month 3rd; Attended the quarterly meeting at Mount Mellick,
which was large and pretty open.

"`Second-day, set out for Tullamore, Thomas Cash now joining me as companion.`"

He had a meeting in the barracks at Tullamore, and afterwards visited Athlone, Loughrea,
Galway, Gort and Ennis, in the county Clare,
having meetings among a people very much in bondage to
the superstitions of the Romish church,
and tyrannized over by their priests.
At Loughrea, he says, that after the meeting,
a Romish priest stood in the street and beat some of his people with a stick,
threatening to excommunicate them for having attended the meeting.
He adds:

"`Trouble seems ripening in this land; my path remains to be very mortifying to me,
and did I not experience the unity of the more solid part of Friends,
I could not abide therein.
It will be cause of rejoicing to be released, but the Lord hath a right to direct.
With respect to our religious Society, the state is very low in this land.
The world and many of its customs prevail, to the great hurt of the church.
Dear Anthony Benezet, in his letter, received the day before I had account of his death,
mentioned one, which, he says, was increasing on that side of the water; and which,
from my first landing in Europe, I have borne my testimony against: that is,
furnishing the table after dinner and supper, with bottles of wine and glasses.
Where this is practised, the life of truth, I am persuaded, will gradually decline.
It lays snares in the way, and is a pomp that should be withstood.
I believe it hath hurt the professors of truth in this land much.
Many live high among us, as well as others; whereas, multitudes appear almost famished;
and it is greatly affecting to see the vast numbers of poor,
and the multitudes confined in jails.

"`First-day, seventh month 25th; Attended the meeting at Limerick,
which was very exercising for a considerable time; a sleepy,
unconcerned spirit prevailing; but Truth at length arose,
and it ended more lively and comfortable.
Great is the mercy of God to a forgetful people.

"`Fourth-day, after meetings at several places we had a wet ride to Killarney,
over a barren mountainous country, and on fifth-day had a large, quiet,
and favoured meeting there, held in a room over the market-place.
Among others, Lord Kenmore, a papist, attended; also a colonel and some soldiers.
This Lord Kenmore kindly inquired how our friends now fared in America,
and spoke very respectfully of William Penn.

"`Sixth-day, we reached Cork in the evening, glad to get among Friends again,
and were kindly received by my dear friends Samuel Neale and wife.

"`First-day, eighth month 1st; Attended the meetings at Youghall, both large,
and very suffering seasons, though there were many goodly looking Friends.
In the evening was a full gathering at our quarters,
where they usually hold an evening meeting on first-days; it was an exercising time,
held in silence, except some little said by Joseph Poole.

"`Second-day was a large meeting, mostly held in silence, and a suffering time.
I had to make a few remarks at the close.
Then the business for the province came on, and was a more lively season.

"`Third-day, had a meeting appointed for the inhabitants, which was very large,
quiet and favoured.`"

Soon after this they returned to Cork and remained there and in the neighbourhood,
for several weeks.
On the 24th of eighth month, they went to a small village called Baltimore;
"`and notifying the people, had a large meeting, generally of Protestants, and very poor.
These people live by fishing and boating,
and some of them by plundering vessels in distress; they behaved with much sobriety,
and parted with us affectionately,
divers expressing their thankfulness for the opportunity.
This meeting was held in an open old castle, without a roof,
but it accommodated us pretty well.
Just as the meeting broke up, the parson of the parish rode up near the place,
telling us that hearing of the meeting he came to see how his people conducted,
and insisted much on our calling at his house to take refreshment.
We parted affectionately, and proceeded to Bantry, over a wild country.

"`Fourth-day, the parson, John Bemish, who descended from Friends,
being willing we should hold a meeting in the Episcopal worship-house,
the people were notified, and we had a large quiet meeting, more open than I expected;
for in the morning we had been beset by three Romish priests,
who appeared alarmed at our coming;
and we had much reasoning with them at the inn where we quartered.
Divers town`'s people were present.
One of them, a dark ignorant man, asserted his disbelief of the Holy Scriptures.
They insisted much on the necessity of baptism in their way,
and on the traditions of the '`fathers,`' etc.
One of these afterwards expressed his concern at their conduct.
I was fearful they might use endeavours to
prevent their people from attending the meeting;
but a large number were present,
and I believe some were enlightened with the opportunity.

"`Fifth-day, we set out early for Crookhaven, the extremity of the land.
The people, and their employ, here, are much as at Baltimore, looking very rough,
yet ready to admit a meeting; which was held in a field among the rocks,
some sitting on seats, and others on the rocks and ground.
They were very quiet, and the opportunity was favoured.
Part of the road today being very rocky, and impassable for any carriage, it was tedious,
and we returned much wearied.

"`Seventh-day, a meeting being appointed at Kinmore,
to be held under a shed on the premises of James Douglass,
deputy agent to Lord Shelburne, many came, and it was a solid good meeting.
James Douglass appeared astonished,
saying there were double the number of Protestants that
usually attended their place of worship,
besides many Romans; adding that he did not expect half the number,
and admired at their quiet behaviour.
Some expressed their satisfaction with the meeting.
We dined early, and set out for Belvorney, where we arrived in the evening,
having several smart showers in passing the rough high mountains.

"`First-day, arrived at Macroom,
and notice was given of a meeting at 5 o`'clock in the evening.
It being a popish wicked town, the priest not only cautioned the people not to attend,
but directed them to attend '`prayers`' at the same hour that our meeting was to be held.
Notwithstanding this, many came, and some Protestants of rank, but these came mostly late.
The meeting was more favoured and quiet than could be expected,
though some appeared at first to have envy and malice in their hearts.

"`Second-day, went to Dunmanaway,
both myself and Thomas Cash reduced to a state of weakness and poverty of spirit.
I thought it safest, however poor and low, to propose a meeting;
and many of the people being Protestants, they readily offered a school house.
Many were much tendered by the power of Truth, my companion having a very open time,
though I had but little to offer.

"`Third-day, Thomas Cash inclining to stay at Bandon two or three days,
I set out for Cork, and arrived at my dear friend Samuel Neale`'s about one o`'clock.

"`Fourth-day, ninth m-onth 1st, continued at Samuel Neale`'s,
poorly and much worn in body and mind,
yet have cause to be humbly thankful that we were
preserved from personal harm during this journey,
and that the Lord in mercy has favoured with counsel
and strength to pass through much arduous labour.
Blessed be his holy name!

"`Fifth-day, 16th of ninth month; since the above I have been diligently employed,
having had meetings at Passage, Glanmire, Cove of Cork, Cloyne, and Castle Martyr,
all large and quiet, and the people appeared generally solid and satisfied,
and parted in love; though at two of the places among seafaring people.
From Castle Martyr we came pretty directly for Waterford,
and attended the quarterly meeting for Munster, which was large,
and many promising youth were there.
Though I am long detained in this land, I have little rest,
and when I may be released I know not, but strive to keep patient.
I endure seasons of great stripping and poverty,
yet the Lord`'s strength is made perfect in our weakness.
The work is his, and the power is of him,
for of myself I am the weakest of all the Lord`'s servants.
Dear Thomas Ross and Samuel Neale are hinting to me,
that I shall not get away until next year: it will be trying indeed if I am so kept;
but the Lord hath a right to direct.
I wish not to stay longer than is right,
and to attempt to flee would only multiply sorrow.
I take the unity of Friends with me, having laid myself open both at Cork,
at the late quarterly meeting, and this day, at Clonmel.

"`Tenth month 4th, at Catherlough; I was so solicitous last week for a release,
that I believe it was not well pleasing to the Lord;
being left in a state of great weakness and stripping; so that I find I must submit,
and beg for a renewal of patient resignation.
I have, with my dear companion Thomas Cash, had large meetings at Mitchell`'s-town,
Tipperary, Cashell, Thurles and Templemore, also at Birr, Kilconnormoor,
Knockballymagher, Ballanakill, and this place; also a large meeting at Abbey Lix.
Here I had to begin, after a longer space of silence than usual,
with expressing the value of patience,
and the necessity there was for our labouring to
be clothed with a resigned disposition of mind,
in our religious gatherings for the solemn act of worship;
that by truly waiting on the Lord, the the fountain of all our mercies,
we might experience our minds seasoned by his love and grace,
and be prepared to worship him aright.`"

After being at Cooladine, Kilconnor, Ross, and a number of other places,
he returned to Dublin, to attend the half-yearly meeting there, and thus proceeds:

"`I attended the meeting of ministers and elders for the nation of Ireland,
in which there was instruction.
In the evening spent about two hours with John Gough,
on his essay of a History of Friends.
On fourth-day, spent about two hours with him again, in hearing his essay read,
and parted with divers dear friends about to return to their homes.

"`The half-yearly meeting was large and favoured.
I think in many parts of Ireland there is an increase of zeal and devotedness,
and a comfortable appearance of hopeful youth.
There is a commendable concern spreading here, as well as in Great Britain,
for the institution of schools for the children of Friends;
and subscriptions are promoted, to establish one or more in each province in Ireland;
also one for girls at York, England, to be visited and inspected by female Friends;
and however difficult it may be in our own country,
I hope Friends will continue to revive the matter.

"`Eleventh month 19th, went to Newtown Prosperous,
accompanied by Thomas Ross and his companion, and divers Friends met us there.
We had a meeting with the inhabitants, to whom Thomas Ross was drawn forth largely.
Thence went to Edenderry.

"`First-day, 21st, attended two large meetings at Edenderry.
"`The corpse of a young man was brought into the morning meeting,
which induced many not professing with Friends, to give their company.
The necessity of a timely preparation for death was enforced,
and Mary Ridgway had a powerful testimony.

"`Fifth-day, went to Phillipstown, accompanied by Thomas Ross,
and had a meeting with the inhabitants; visited the prisoners;
and on seventh-day we made a stop at Clara, and had a quiet favoured meeting.
Third-day, to Rosscommon; where the priest, as we were informed, intimidated the people;
notwithstanding which, there was a pretty large meeting; considering the place,
it was quiet, and many appeared satisfied.
Visited the prisoners here also; and on sixth-day went to Athlone, and had a large,
solid, good meeting with some of the inhabitants.
Afterwards returning to Moate-a-grenoge,
we were openly received by Barclay Clibborn and family.`"

About this time John Pemberton was affected with a disease in his right hand,
which assumed a threatening appearance, and rendered it necessary for him to submit,
for several weeks, to medical treatment.
He continued however, to get out to meetings at Moate.

"`I continued,`" he says, "`at Moate throughout the first month, 1785,
and endured much pain most of the time, as I had done the preceding month,
but was favoured to get to all the meetings as they came in course.
Poverty of spirit, however, and much stripping, was my allotment.
But the Lord in great mercy preserved in patience and resignation;
blessed be his holy name!
During my stay here,
I was favoured with many acceptable letters from my dear wife and brother in America,
and from many friends in this land and in England,
expressive of sympathy with me in my close provings;
which were cause of humble gratitude.
The wound now began to heal fast, but the inflammation having continued so long,
and the pain so great, I had little use of my hand for a long time.

"`Second month 8th, my dear friend Richard Shackleton came to visit me,
and stayed until the 11th. I was under a very close exercise at this time.
On the 10th, my beloved aged friend Thomas Ross,
came to Moate from a sense of religious duty to join me in my travels;
and on the 14th we visited three families of Friends; and the next day went to Ballymore,
and held a religious meeting there in the Episcopal worship-house.
The minister attended and was respectful, and the meeting was large and favoured.
On the 16th, we went to Ballymahon, and had a meeting there.
The popish priest used endeavours to prevent the people from coming; nevertheless,
the meeting was pretty large, and owned, considering the darkness of the people,
it being a popish town.

"`First-day, 20th, attended the meeting at Kilconnor-moor,
and in the afternoon visited a Friend who had been long confined with a paralytic stroke.
The next day, after two meetings at Shenstone and Brusnea, proceeded to Rosscrea,
and were kindly received and entertained by our friend John Pim.
Next day we went to Burros, in Ossory,
and had a large and very comfortable meeting with the inhabitants.
Many Protestants live here,
and among these the meetings are generally more lively than among the poor dark Romans;
and yet the Lord is looking towards these,
and some become tenderly impressed with the virtue of truth.
As there are a few under our name in this place, we had them together, before we left it,
and counsel was delivered to them.

"`On the 24th, we set out for Ballyragget, with intent for a meeting there.
But the priest (it being a popish town) used endeavours to prevent it,
though the inhabitants pretty generally manifested some desire for such an opportunity.
I sent for the priest, and many people came also, and we had much discourse.
He seemed to assent to the truths, but said the people, even the children,
knew all we advanced, and they did not want to be instructed.
He was very full of talk, so that it was difficult to find room to speak.
There was another priest, a dark, ignorant, rash young man, who denied the Scriptures,
and often went in and out of the room, much disturbed.
He was several times reproved, and I believe many present were ashamed of his conduct.
As many people attended, and our faith and principles were opened,
as far as we had opportunity, we concluded it might suffice.
Some were very attentive and sober.
The priest asked us to dine with him, though he so opposed us.
He was crafty, and was uneasy at so many attending, and sent some away.
He wanted to get us to his house, that we might converse more privately;
but this did not answer our end, for we wanted the people informed.
After he left us, several sober soldiers came into the room,
with whom we had a solid opportunity.
They offered a room in the barracks, that we might have a meeting;
but after dining at the inn, we proceeded to Kilkenny.

"`Rising early on second-day we set out in a thick fog for Waterford,
and there met with our dear friends Mehetabel Jenkins, Hannah Bevington,
Sarah Stephenson, Samuel Neale, and many others,
and were with them at the meeting for ministers and elders;
a time of instruction and seasonable counsel.
Second-day was the quarterly meeting, large and favoured; the business conducted well,
and many suitable remarks made in considering the state of the several meetings.

Third month 1st, attended the meeting at Waterford, and a very large one in the evening,
appointed for the town`'s people.
It was thought that several hundred went away, as they could not get in.

"`6th; Bonds and afflictions are my daily portion; for when one day`'s labour is over,
the weight of another is upon me; and the Lord,
who knows best how to deal with his children, keeps me poor and low, "`The burden,
in every part where I have been, lies on a few;
but the Lord is as able to save by few as by many; and the more singly-devoted,
the more will these be exalted; and these light afflictions, which are but for a moment,
will work for those who keep the word of his patience, and hold out to the end,
a far more exceeding and eternal weight of glory.

"`22nd; The weather yesterday being cold and stormy,
it was not thought prudent to cross the water at Passage, a village below Waterford,
as we had proposed.
So this morning, being the fourth-day of the week, we returned to Passage,
and the custom-house officer having provided the king`'s boat,
with six oars-men and three officers, we rowed to Duncannon,
and had a meeting in the yard of the castle, a strong fort.
Many who attended were soldiers, with some of the inhabitants of the village.
Much counsel, in gospel love, flowed towards them.
My companion, after meeting,
had some satisfactory conversation with an officer who
had been in America during the troubles.
Thence we proceeded in the same boat, to Ballyhae, and had a comfortable good meeting,
the boatmen attending both these opportunities.
On our landing, we were met by Rudolphus Green, the custom-house officer,
who insisted on our going to his house.
We complied, and after taking refreshment, returned to Waterford, much wearied.

"`Seventh-day, accompanied by Isaac Jacobs, I went about three miles,
to visit a chartered school, where about forty children are educated,
being brought up to industry as well as learning, until fit to place as apprentices,
when a fee is given with them.
It was better conducted than one I before visited.
I had some counsel to drop to the children.

"`First-day, the meeting this morning at Waterford was large and solid,
I had some thing to say towards the conclusion,
respecting the great value and necessity of attaining
to a true inward waiting upon Almighty God.
But a forward woman, in a ranting deluded spirit,
stepped from the lower part of the meeting to the gallery, and there told a dream,
which created uneasiness, and in part took off the solemnity that had prevailed.
Friends, afterwards had a solid opportunity with her,
but she was in a self-confident spirit.

"`Sixth-day, being the day of their men`'s and women`'s meetings, it was a favoured season.
During the consideration of the state of the meeting,
a concern was begotten in my mind to testify against
the evil and pernicious effects of stage plays,
and how ensnaring they were to youth;
and Friends were urged to think whether something was not due from
them to represent to those in power the hurtfulness of this evil.
The concern spread over the meeting,
and a committee was appointed to consider what mode to pursue.
Some extracts were made from several authors, the Prince of Conti, William Penn,
Robert Barclay, S. Hume, etc., which Friends agreed to have printed,
testifying against the evil effects of stage plays, and other vain divertisements;
and a letter was also written, and signed by Thomas Ross and myself,
directed to the mayor and other magistrates of Materford,
expressing our concern in finding so much encouragement given to plays,
and urging them to labour to suppress these, and other evil pastimes,
and to exercise their authority against profane swearing and other evils.
I visited the jail, and on second-day morning, the poor in the poor-house,
being upwards of one hundred.
They were thankful for the visit.
I then set out with dear Thomas Ross for Kilmacthomas, about twelve Irish miles,
and had a large favoured meeting; proceeded to Dungarven;
and on third-day had a large meeting in the court-house.
Friends apprehended we should have a disturbed time,
but He whose power subjected evil spirits formerly, preserved us,
so that the meeting was quiet, weighty and solemn.
An aged man, a magistrate, attended, and expressed his satisfaction with the meeting,
saying that he never heard such doctrine before.
I observed a man near me, as soon as I stood up, take out his paper and pencil,
to make notes; but I was favoured not to be intimidated.
Thence we went to Youghall, and on fourth-day to Ardmore, and had a quiet good meeting.

On fifth-day afternoon, I went to Clashmore, and had a large open meeting,
all except a very few being Romans;
yet the meeting was as quiet and solemn as most of those among Friends.
I was much worn and fatigued this evening, so stayed at Youghall on sixth-day,
and in the evening had a very large meeting with the inhabitants,
which was open and satisfactory, some being under the humbling impression of Truth,
and looking towards Friends.
The Lord favoured with his gracious help, and his name was praised.
Before I left Youghall, I visited the hospital, or infirmary,
and had some advice for the few there.
On seventh-day we came to Cork.
The week before this was not much less laborious than this has been;
and indeed little else but great toil has been my allotment in this land,
I am kept low and abased, and am engaged to beg my daily bread,
and each day to crave to be helped this once.
May the Lord be magnified; for I am a poor creature to be thus led:
his own works praise him.
I labour to keep my eye single, and to lean to the Lord for wisdom,
strength and utterance, and to keep within the limits of my small gift.
May all live near that source which nourishes and keeps alive,
and preserves in a holy zeal.

"`Fifth-day, fourth month 14th; Went to a village called Blarney, and held a meeting,
which was large, and owned by the prevalence of gospel love,
and the doctrine of Christ Jesus was preached.

"`Sixth-day afternoon, had four religious opportunities in the jails;
the felons and debtors in each jail being separated, we took them so.
It was indeed greatly affecting to see so many fellow mortals crowded in dirty,
stinking prisons.
They were glad of the visit, and some assented to the truth of what was delivered.
One of the jailers told Samuel Neale afterwards,
that the jails never had such a visit paid them before,
and he wanted liberty to say something about it in the public papers; but this I forbade.

"`First-day, between the afternoon and evening meetings, I visited the Bridewell,
and found a young hearty black man, who knew me, and said he was born in Philadelphia.
It appeared as if he had been much imposed on.
I compounded with his creditors, and got him released from confinement;
and he being without shirt, or shoe, or stockings, I provided him some clothing,
and he promises to repay as speedily as he can, after his arrival.
I have engaged also for his passage, that if he does not pay the captain,
or his friends for him, I am to be accountable.
Samuel Neale accompanied me to Bridewell,
and we released here also a young man detained for his fees.

"`Fifth-day, we proposed to leave Cork;
but I was not clear without attempting a religious opportunity with the soldiery;
and application being made,
had a meeting of some hundreds of them in Friends`' meeting house.
Two colonels and some other officers attended, one of whom was called a lord.
The meeting was in a good measure satisfactory, through the Lord`'s gracious help.
After this we speedily set out.

"`Second-day, we went to Ballyporeen, and obtaining a place,
the people generally gave their attendance, though it is a dark popish place;
and it was said the priest of this parish had
warned the people not to go to hear the Quakers.
Hence we went direct to Clonmel, and the next day had a large, open,
good meeting with the inhabitants, Friends and others.
Several Episcopal ministers were there, and many soldiers.
This was a weighty meeting,
and strength was given to publish the glad tidings of the gospel,
and way of life and salvation to the people, to our ease and their satisfaction,
as many expressed.
One Episcopal minister, before he left the meeting, came up to me and expressed thanks.
I told him, if any good was done, thanks were due to God, and not to man;
for we were only instruments.
Towards evening I went to the jail and had the prisoners arranged in the yard,
and gave them some advice, which they acknowledged.
Most of them were young men in their prime, and divers loaded with heavy irons,
a sorrowful sight indeed; two men and one woman were under sentence of death.

"`Sixth-day, reached Dublin;
and on seventh-day the national meeting of ministers and elders was held.
It was, however, a very cloudy, proving time.
Little was said in the line of ministry;
but what was delivered tended to promote a serious examination
and inquiry for the cause of such prevailing heaviness.

"`The general meeting, on the second, third and fourth-days, was large,
and a great appearance of hopeful youth of both sexes.
It was a solid quiet meeting.
I have had a slow fever for several weeks, with a cough and pain in my breast,
owing to constant exercise.

Being likely soon to leave the island,
I can say that I have laboured to avoid doing harm,
if I have not been instrumental of much good;
and though my path has been singular and arduous,
yet the Lord hath helped and borne up under many deep exercises,
and made way for me among a people much strangers to our religious principles.
To these I believe a gracious visitation is extended.
May the Lord prosper his work in his own way and time,
and bring forward the beloved youth of our religious Society,
many of whom are under the virtue of Truth.^
footnote:[Samuel Neale thus speaks of the
religious services of John Pemberton in Ireland:
"`Dear John Pemberton is a most dedicated vessel in the Master`'s house.
He seems to leave no stone unturned, to perform what he believes to be his duty,
and has remarkable openness amongst the Catholics, who are in general,
the most ignorant of our inhabitants.
Amongst this class of people our dear friend labours much,
and I believe his service is successful.`"]

"`On sixth-day morning I embarked for Liverpool,
in company with my beloved aged friend Thomas Ross, also Edward Hatton, James Christy,
jr., and Thomas Taverner, of this nation, going to attend the yearly meeting in London.
We landed about eleven o`'clock the next day, at our destined port.

"`Next day being the first-day of the week, invitation was given for the afternoon,
and many inhabitants came.
The meeting was more open and favoured than could be expected
in a place where such a wicked trade is promoted;
there being some hundred vessels fitted out in a year, from this place,
for the coast of Africa, to make slaves of the inhabitants of that country.`"
