== Chapter III.

[.chapter-synopsis]
* Travels in England and Scotland.

"`Fifth month 13th, 1785;
We left Liverpool on second-day morning and arrived in London yesterday afternoon,
after calling at Coventry and attending their meeting on fourth-day;
a close searching time, but the Lord gave utterance.
We travelled two hundred and three miles in little more than three days.

"`Seventh-day, attended the yearly meeting for ministers and elders,
which was instructive; and on first-day, 15th, two meetings at Grace-church street,
both large, many not professing with us being present, who looked for words;
but there was not much preaching in either meeting.

"`Second-day in the morning, the meeting for ministers and elders again sat,
and was a large solid meeting.
Our dear friends John Storer, John Townsend and Thomas Colley,
spread before the meeting their concern for visiting their brethren in America;
and our friends Nicholas Wain and Samuel Emlen,
expressed their expectation of liberty soon to return home.
In the afternoon the business of the yearly meeting opened.
At the first sitting down, our friend Nicholas Wain,
had some very close hints to give respecting worldly wisdom and riches usurping,
showing that these ought not to govern in the church; but the seasoning virtue of Truth;
and that under this, all, even the weakest and poorest, had the same right to speak.
I believe it was a profitable hint.

"`Third-day, both meetings were solid, and that forward spirit,
which by worldly wisdom had often interrupted the service and hurt meetings,
was much kept under.
On second-day afternoon, the 22nd,
the meeting concluded very solemnly in supplication by George Dillwyn.

"`This yearly meeting was very large;
and perhaps in few which have been held in London for these fifty years past,
had there been less of the floating worldly wisdom manifest;
and there was much less interruption than usual by wise harrangues;
Friends maintaining a solid exercise, kept down that spirit.
It is cause of great thankfulness that there are many
weighty brethren and sisters still preserved,
and I believe that a concern increases for the promotion of righteousness.
A large number of hopeful young people, both male and female, attended the meeting,
and the mouths of several were opened in public testimony.
A good account was given of Ackworth school.
There are a number of valuable Friends in Yorkshire,
who have much of the weight of it upon them,
and seem to exert their best endeavours for the benefit of the institution.
It requires close attention and great wisdom to guide such an affair.
The women`'s yearly meeting ended on seventh-day evening.
Dear Thomas Ross and myself, accompanied by John Storer and Richard Shackleton,
made a visit among them just before they closed,
and it was comfortable to find the Lord was with them.

"`Third-day, went to Tottenham and spent about a week there, for the sake of rest,
and with a hope of recruiting in health after
long and constant exercise of mind and body.

"`Fifth-day, sixth month,
2nd. This morning I took leave of my dear friends George Dillwyn, Samuel Emlen, etc.,
and in company with dear Thomas Ross, and some other Friends,
reached Chelmsford in the evening.

"`Sixth-day, proceeded to Colchester, and lodged at John Kendall`'s;
and on second-day attended the quarterly meeting at Ipswich.

12th, went to Norwich quarterly meeting and the next day was at two large meetings,
attended by many of the inhabitants not professing with Friends.
The testimony ran close against the liberties that prevail among the professors of truth;
and Nicholas Wain was led exceeding closely in the afternoon meeting.
On fourth and fifth-days, visited the prisoners in the Castle and the city jail.

"`Third-day, the 28th, reached York,
and attended the quarterly meeting for ministers and elders.
It was large, and many valuable Friends were present;
my dear and aged companion was led in very close service among them.
We lodged at William Tuke`'s.

"`Fourth and fifth-days, the quarterly meeting for business.
Daniel Snowden, aged about ninety years,
walked twenty-four miles to this quarterly meeting, and sat four or five hours in it,
having his hearing and faculties admirably.

"`Sixth-day, visited the prisoners in three jails.
In one there was a very large number of felons and debtors; some were tenderly impressed.

"`First-day, at Darlington.
At the close of the afternoon sitting, Friends were desired to stop,
and counsel was communicated, tending to excite to a steady circumspect conduct,
that their light might shine among their neighbours.

"`Fifth-day, a meeting for the inhabitants of Sunderland was held in the evening,
large and much favoured; many minds being tendered with the pure influence of truth.

"`First-day, attended a general meeting at Benfieldside,
to which resorted many hundreds of people,
so that we were obliged to hold the meeting in a field.
The meetinghouse, though larger than many, would not contain half the people.
The day of the Lord was proclaimed, and the way of life and salvation opened to them.
Though they behaved soberly, and many were tenderly impressed,
yet there was not that openness to receive the word with joy,
as was the case when dear George Fox entered that part in 1653,
(called in his journal Derwentwater.) The fields then appeared white unto harvest,
and the Lord by judgments had prepared the minds of the people to embrace his love,
and to be open to instruction.
On second-day we came over the hills to Newcastle,
and next morning attended the monthly meeting at Shields, which held about five hours.
My companion had a favoured opportunity, chiefly directed to Friends,
beginning with George Fox`'s exhortation, '`Friends,
keep all your meetings in the power of God.`' Patience
Brayton and her companion were also here,
and had good service.
Except this week, we have had nine, ten, and eleven meetings a week,
since we left London, which is greatly exercising to body and mind.
But I want to fulfill my mission, and if it please the Lord, to return to my native land;
the time for which, I do not see, though I often think of my dear friends there,
with desires that He may be with them,
and strengthen them for the arduous work of their day.
The ways of the Lord are a great deep,
and he has a right to employ where and how he pleaseth; may his name be reverenced.

"`We had many large meetings in and about Sunderland, and North and South Shields,
and much openness; also at Morpeth, Alnwick, Felton, Kelso, in Scotland, Berwick,
Eymouth, Dunbar, and Haddington, and two at Edinburgh, yesterday,
the 7th of eighth month.
But we find at some places in Scotland, that though the meetings have been large,
the people are so bound to forms, and the prejudices of education,
that we have not experienced so much openness as in England.
Esther Tuke, Elizabeth Hoyland, Philip Madin, John Abbot and Henry Taylor,
with dear Thomas Ross, and myself, are our company.

"`At Haddington we found some difficulty to obtain a place for a meeting;
the provost refusing the Town Hall.
But a large house, built for training and exercising horses, being applied for,
was readily granted; and though it was out of town, and the morning; having been rainy,
made it rather dirty walking, yet a large number of people gathered,
the priest among the rest, and were quiet, and I believe many parted satisfied.

"`At Edinburgh we had the few professors together,
with some of the students under the character of Friends;
and on third-day had a large meeting at Leith; the next day at Kirkcaldy;
thence to Cupar, Dundee, Aberbrothwick, Montrose, and Inverbervie.
Thomas Ross had to speak particularly to the people,
to wean them from the teachings of men.
Thence to Stonehaven, and so to Aberdeen, where we had four meetings,
all large and satisfactory.
On fifth-day we designed Friends to be select; but the people seeing us go to meeting,
many came; nevertheless the testimony ran much to Friends,
showing what it was that gathered us to be a people,
and that it is the same power that must now preserve us.
The way was pointed out,
by which our first friends were led into a denial of the world`'s ways and practices,
both in speech and other things,
and that although it brought grievous sufferings and persecutions,
yet their faithful upright walking at length gained them esteem,
and discerning men now despise those who deviate
from our known testimonies and principles.

"`Thence to Inverary, Old Meldrum, and Kinmuck.
Some Friends live at the five last places.
Here we parted with dear Esther Tuke, Elizabeth Hoyland, and Henry Taylor,
who steered for England; and with Thomas Ross, Philip Madin and John Abbot,
we set out further north, and had meetings at Elton, Petershead, Fraserburg, Banff,
Portsay, Cullen, and Fochabers, where the duke of Gordon, his wife,
and many others from his family, came to the meeting.
Thence to Forres, Nairn, and Inverness; and here dear Thomas Ross was poorly and spent;
my mind continued much exercised in further prospect of duty,
yet as he was not fit to go into a more desolate country,
I attempted to set my face with him towards England; but became so distressed,
that on the 4th of the ninth month, he urged my leaving him, and pursuing my prospect;
and our Friend Philip Madin, promising to take care of him,
I reluctantly parted with him; and with John Abbot, of Huntingdonshire,
and Alexander Cruickshank, of Old Meldrum, returned to Inverness.
We had two very large and satisfactory meetings there,
and crossing into the highland shires of Ross, Sutherland and Caithness,
had meetings at Boulie, Dingwall, Milltown and Tain.
Three Presbyterian ministers, also Lord Ankerviile, so called, and Sir Hector Monroe,
attended the meeting at Tain; the latter expressed their satisfaction,
and Ankerviile pressed us to his house.
This meeting was a season of favour; and the way of life and salvation was pointed out,
under the seasoning virtue of truth.
May the Lord, the great helper, have the praise!
We distributed some books, as we usually do after meetings,
and then hastened on our journey, and crossed a water with one of the ministers,
who with his wife and daughter, was at meeting at Tain,
and pressed us on our return to call at his house in Sutherlandshire, and tarry a night;
and if we inclined to have a meeting we should have his
'`kirk,`' and he would notify the people.
We were afterwards very openly, and without affectation, kindly received and entertained,
and though a very stormy, snowy day, had a gathering of reputable people,
and the Lord condescended to favour us.
This man was so civil and sincere,
that he offered to suspend his morning and evening prayers, if they were offensive to us.

"`From Tain we went directly for Wick, where we had three large meetings.

"`Ninth month, 11th;
This day is three years and three months since I parted
with my dear wife and comfortable habitation;
in which time many and deep have been my probations, but the Lord hath helped hitherto.

"`13th; Proceeded to the northernmost part of Scotland, and crossed to South Ronaldsay,
one of the Orkney islands, having about three hours passage.

"`We continued on these islands five weeks,
in which time we rode about three hundred miles by land,
and went about seventy-four miles by water, not allowing myself one day`'s rest,
and had forty-four meetings, mostly large.
Sixteen were held in their kirks, so called,
which being offered by their ministers for the accommodation of the people,
I was free to accept them, and we were kindly entertained at several of their houses.
When I considered their openness to offer their worship houses,
and some of them to send their servants to notify the people, appearing sincere,
I was free to accept their invitations.
And indeed, in some places there were no other suitable houses to accommodate us;
for the country, as well as the people, is generally poor, and few inns.
We met with much civility, and were accommodated at some of the best houses.
The provost of Kirkwall, William Lindsay, had his house always open to receive us,
as we passed backward and forward; he was a feeling, sympathizing,
sensible and considerate man.
We visited six of the islands, viz: South Ronoldsay, Burra, Flota, Wass,
Grimsa and Pomona.
This last is about thirty-six miles long and ten broad,
and we spent most of the time on it.
The poor people on Grimsa, where there is a worship house,
told me there had not been a sermon there before, for more than seven years.
Though there is no great real hunger and thirst after righteousness,
yet the people seem free from some of the vices that prevail in many places.
They live in harmony, and would come from one to five miles to a meeting.
I believe there were from two to three hundred people at some meetings,
and at others five hundred and upwards.
I look upon my proceedings as only paving the way for others, and believe,
though a poor creature, I have left love in every place, and an open door.
My mind was deeply proved throughout the journey,
and I was not clear in leaving the islands, there being many more;
but the weather was very boisterous, and snow came on;
and the thoughts of being detained in a cold country,
where we must be beholden to strangers, and perhaps confined all winter,
I could not reconcile, and hoped my gracious Master would have compassion.`"

This anxiety to get away occasioned him much mental conflict.
He thus mentions one attempt which they made to
escape from the field of apprehended duty,
and what it cost him.

"`Ninth month 27th; The weather very stormy, with frequent showers of rain and hail;
yet we had a full meeting, much spent in silence;
and having laboured to be resigned to return to Pomona,
I sat the meeting with more satisfaction.
The opportunity was favoured, and some were tender.
On fourth-day, looking again towards crossing the Firth,
renewed the unsettlement of my mind,
but strong were my desires to be released from these islands;
and so we proceeded to Burwick ferry, on the south side of South Ronaldsay.
When we came there, the boatmen refused to cross.
Though I did not feel myself clear of these islands,
yet both myself and companions were disposed to go, as the season was advanced,
and we were far north and had a very difficult passage to cross.

On fifth-day, the wind being lower, and it appearing likely for us to cross,
we placed our horses on board a boat and put out to sea.
But showers of rain coming on, and high tempestuous winds,
after passing one third part over, it was judged prudent to return;
one of the men saying he did not know what sort of people they had in the boat,
having never been obliged to return before.
I thought of Jonah, for my mind continued heavy and not peaceful.
On getting ashore we set out, and at Carra ferry had a meeting held in a barn,
to which many poor people came, to whom advice was given in innocent simplicity.
Dined on potatoes this day, which led me into a deep feeling with the poor.

"`Tenth month 19th; Went to Burwick and crossed the Pentland Firth with a fair wind,
and through favour got safely over.

"`23rd; Went to Thurso, the largest town in Caithness,
where we provided a spacious room in a warehouse; but when the people were assembling,
it was thought it would not contain a fourth part of them;
so the chief magistrate proposed our going to the '`kirk,`' which being opened,
it was supposed seven hundred people assembled,
to whom the gospel was preached in a good degree of the demonstration of the Spirit;
though it was a trying time to me for many hours before the meeting,
and my mind had been much stripped and tossed.
But blessed be God, he owned the meeting,
as also another large meeting in the same place the next day,
through the condescending goodness of the Lord,
the great helper of his depending children.

"`We left Thurso in the rain, and proceeding about nine miles,
a man of good appearance stood near his house looking at us,
and kindly invited us to take up our quarters; which we accepted,
and had a meeting that evening at his house, with his servants and neighbours.
Setting off early next morning, we had a long rough ride through much snow,
and over bad roads; and had meetings at Golspy and Dornoch, Tain, Cromartie,
and Fort Ross.
Here were many raw people, yet they generally behaved well,
and the meeting was full as well as could be expected.
A person who was at it,
told me that he believed there were only himself and one other person,
called Sir Alexander McKenzie,
that were ever at a meeting of our religious Society before.

"`Sixth-day, awoke this morning under great exercise of mind,
and crossed the ferry to Nairn; where there was a market,
and my companion having a concern to go into it, I accompanied him.
He stood at the market-cross, and spoke to the people, many of whom stood amazed,
yet they were sober, and some solid.
We then proceeded to Forres, Elgin, Fochabers and Keith,
and afterwards had a large satisfactory meeting at Huntley.
At Montrose I parted with my dear friend Alexander Cruickshank,
who had been a kind companion and fellow-helper, though not in the ministerial line.
He returned home, and John Abbot and myself crossed the ferry and proceeded to Dundee.

"`Third-day, eleventh month 14th, crossed the water, and passed on to Cupar,
where we refreshed ourselves, and found our visit to that place as we passed northward,
had left a profitable impression.
The people would have been pleased with another religious opportunity.

"`Fifth-day, rode to Edinburgh, and the next third-day reached Newcastle.
I was enabled to bear the fatigue of riding better than I expected.
The meetings in these remote parts have been generally large, the people behaved well;
and I have laboured by watchful attention, to keep in the meekness and simplicity,
so that I hope the reputation of the blessed truth has not suffered.
Since I left London, that is, from the 2nd of sixth month, to eleventh month 23rd,
I have travelled about two thousand miles,
and been at about two hundred and seven meetings, besides visits to prisons, schools,
families, etc.

"`I was detained at Newcastle, in visiting families.
On second-day, twelfth month 12th, the business of the monthly meeting was entered upon;
in which my mind was engaged to urge Friends to a proper care over their members;
and a committee was appointed to visit those who deviate from our religious testimony,
in complying with the priests`' demands, and who have launched into the world`'s customs,
in dress, etc.
From thence I reached York on the 24th,
coming there to see my dear aged friend Thomas Ross, who has been poorly several months.

"`Fourth-day, 28th, at Leeds.
The quarterly meeting for Yorkshire opened with a meeting for worship,
in which Rebecca Jones, lately returned from Ireland, had good service,
and had to proclaim a time in which that quarterly
meeting would be thinned of elders and active members,
and that the burden must rest on the youth, who were encouraged to come forward.
It was a solid weighty time.
On fifth-day the business of the meeting was resumed,
and Rebecca Jones spoke of a time coming when the foundations of Friends would be proved;
and exhorted to labour to be prepared for it,
when the blast of the terrible might be as a storm against the wall.
The minds of many appeared tenderly affected.

"`Third-day, the affairs of the church were transacted,
and in the evening was a public meeting.
I was silent, as I have been much of late, it being a stripping purging season.

"`Fourth-day was the meeting for ministers and elders,
in which several testimonies were borne, but I inherited barrenness.

"`Third-day, attended the monthly meeting at Stockton, and on fifth-day went to Yarm.

"`First month 19th, at Crawthorne.
I have indeed great cause to bless the Lord,
in that he has inclined the minds of many in near sympathy
with me in the singular path I have had to tread;
and it ought to have engaged me to more resignedness of mind
and unreserved dedication than has sometimes been the case.
The flesh is weak, and we often suffer loss by parleying and looking out too much,
and suffering our own fears, or thoughts of what others may say or think, to prevail.
I have been hitherto, through great mercy, preserved in the unity,
and I wish ever to dwell in such abasedness as to be kept in it; but my own natural will,
joined to the desires of some, hastened me out of Scotland sooner than was prudent.
I know that some, out of near sympathy, have wished my line was turned;
and having striven for it, I have brought on much inward proving; and indeed outward too;
for I have been poorly ever since I left Scotland,
though wonderfully preserved for the most part whilst there,
I have not attempted a meeting for those of other
societies since I entered England from the north,
until last first-day.
I have since had two meetings, large and open, which have relieved me a little.
However mortifying or singular, I must go the way I am led, or I may go home;
for I seem to have little to do among Friends.
I live but from day to day.

"`The general state of our religious Society here is low;
yet there is a remnant preserved,
and in most places some who labour to keep their habitations in the truth.
The attention of Friends has been lately much taken up
respecting a small society formed in France,
called by our name.
Friends in London have had much satisfaction in conversing
with a person who brought a copy of an epistle from them.
He was brought up to the law, but left it from religious scruples,
and has since followed weaving.
He is a man of substance, of a sweet disposition and sensibility,
and is concerned that some who profess the light of Christ,
are in the practice of powdering their hair and wearing large silver buckles, etc.,
which truth led him out of There are several in their
little society who speak in their meetings at times,
particularly a woman, who speaks with power, tendering the hearts of the people,
not only of their society, but strangers who come out of curiosity.
It is evident the light is spreading,
but these poor people will probably be brought under great sufferings,
as they have not withstood the priests`' demands,
nor the hiring of substitutes on account of war; though they have had scruples,
and wanted advice.

"`In the last month, I received a letter from William Lindsay, provost,
or chief magistrate of Kirkwall, in the Orkneys,
who was very kind to me and companions when there, part of which follows:`"

[.embedded-content-document.letter]
--

[.salutation]
Dear sir,

It was with great satisfaction that I received
and read your letter of the 14th of last month,
from Dundee.
The warm and kindly expressions which you make use of, proceed, I am fully convinced,
from a feeling, sincere and benevolent heart.
I have long had the highest admiration of the manners
and sentiments of your society in general,
though I never had a personal acquaintance with any of
them before I saw you and your two companions,
who have not by any means lessened the esteem which I formerly entertained of it.
It is much easier, however, heartily to approve, than sincerely to imitate.
Many in this country remember you with unaffected good will and kindness,
and have been frequently enquiring whether any word has been got from you.
We have daily instances of the instability of human life and affairs.
I wish we may all make that application of it which you recommend.
And now I wish,
that that goodness which has guided and protected you
through a journey so perilous and fatiguing,
may continue to attend you, and at length restore you to your friends and country,
in the enjoyment of that peace and tranquillity of mind,
which can be experienced by those only,
who have discharged the duties to which they have been called,
faithfully and with a good conscience.
Whether I shall ever see you again or not,
I hope I shall long remember those persons who were the
first to give me a palpable evidence of that innocence,
simplicity and benevolence of manners,
for which their Society has been so much celebrated.
I am with great regard, dear sir,

[.signed-section-closing]
Your friend, etc.,

[.signed-section-signature]
William Lindsay,

[.signed-section-context-close]
Caldwell, near Kirkwall, 3rd Dec. 1785.

--

"`Fourth-day, first month 25th, 1786, at Ayton.
I have had five public meetings lately, some of them very large and open.
I find the Lord owns me in this path.
I continue poorly, but healing virtue enables to fulfill each day`'s duty.

"`Sixth-day, attended the monthly meeting at Castleton,
which was a seasonable good meeting,
though the testimony ran closely against a lukewarm
spirit and formal profession without life,
and also against a worldly spirit.

"`Seventh-day, went to Moorsom, and the neighbours being notified, many came.
Some were tender, but too many careless professors of Christianity.
I laboured as well as I could under the strength afforded.
A sergeant of the army came, with some other people, from Gisborough to this meeting,
he having attended the meetings at Gisborough and at Ayton; and two women,
one of them far advanced in years, who live at Ormsby,
walked about seven miles to Ayton meeting, being some time under convincement.

"`Second month 7th, at Lindley Murray`'s, near York.
I came to this place on second-day of last week,
hearing that my worthy aged friend Thomas Ross, was reduced to a weak state.
I found liberty to come and abide with him, and have since attended on him with diligence.
He is gradually wearing away; but preserved in a happy state of mind,
and full of good matter.

"`Though many are regardless of the Divine fear,
and are treasuring up wrath against the day of wrath,
yet the glorious gospel light spreads, and many we find, are believing in it.
Surely the Lord intends to gather,
or he would not engage some to go amongst a dark superstitious people,
to shake them from their false dependence,
and turn their minds to the teachings of the good Spirit in their own hearts,
and also to open the way for such labour.
Indeed, though I am such a weak instrument, yet way hath been wonderfully opened for me;
so that, as I have formerly mentioned, ministers and great men of the earth,
have countenanced the doctrine of the gospel and acknowledged the truths delivered.
For many weeks I laboured to turn from this path,
but found it produced perplexity and barrenness; so that I returned to it,
and latterly have had several open comfortable meetings in the upper part of this county.
I seem likely to continue here a while for the sake of this worthy ancient.
He has been very solicitous for my company,
and I desire to discharge the care of a faithful friend to him in his last moments.

"`So much snow has fallen, that some of the oldest people do not remember the like.
I have rode through heaps that were as high as my head when on horseback.

"`Second month 15th, I attended upon my aged friend and comfortable companion,
Thomas Ross, with all the care I well could,
until I closed his eyes on second-day morning, the 13th instant, about ten o`'clock,
at the house of our dear, and I may say, worthy friend, Lindley Murray.
He removed thither from William Tuke`'s, on the 26th of twelfth month, being open,
airy and retired.
For a week before his departure, he wanted great attendance,
being rendered very helpless;
yet his understanding was preserved until just at the close,
though he lost his speech about three hours before.
He often begged he might have an easy passage, which was granted to him,
though for several days he endured a good deal of pain.
He drew his last breath with apparent ease,
and I doubt not is gone to the general assembly of the just,
to reap the reward of a devoted well spent life, saying the day before he died,
that he had been fighting the good fight above fifty years,
and hoped he should have the reward.
A very comfortable evidence of this often attended him; that it may be justly said,
'`the righteous hath hope in his death.`' I wish his
descendants may be concerned to know the God of their father,
and serve him with a perfect heart; that so their end may be alike glorious.

"`His remains were deposited in the silent grave, on fifth-day the 16th,
next to the remains of dear John Woolman.
Rebecca Jones was much favoured at the grave, and our dear friend George Dillwyn,
at the meetinghouse, where a large company gathered.`"

Thomas Ross was born in Ireland, in the county of Tyrone,
and educated a member of the Episcopal church.
He came to America about the twentieth year of his age, and settling in Bucks county,
Pennsylvania, was convinced of the Truth as professed by Friends,
and received into membership by Buckingham monthly meeting; and in the year 1753,
became a member of Wright`'s town monthly meeting.
Not long after his convincement it pleased the Lord to
bestow upon him a gift in the ministry of the gospel,
in which he experienced a growth, and was exercised to the edification of his brethren.
He frequently visited meetings in these and the adjacent parts,
and in company with John Griffith paid a religious
visit to the northern and southern colonies.

Towards the close of the year 1783, after being raised from an attack of severe illness,
his mind was renewedly drawn to visit, in the love of the gospel,
the churches in Great Britain and Ireland,
of which he had had some prospect for several years;
and spreading his concern before Friends,
he received testimonials of their sympathy and unity from the monthly, quarterly,
and general spring meeting,
and prosecuted the concern as set forth in the following memorial respecting him,
which will doubtless be acceptable to the reader, viz:

[.embedded-content-document.testimony]
--

[.blurb]
=== Testimony of York monthly meeting, Great Britain, concerning Thomas Ross, late of Wrights town meeting in Bucks county, Pennsylvania, a minister, who departed this life at Holdgate, near the city of York, the 13th of the second month, 1786, in the seventy-eighth year of his age.

"`To perpetuate the memory of the just,
by endeavouring to render their examples and precepts beneficial to others,
is a debt due to posterity as well as to the praise of His name,
by whom they have been made more than conquerors, and become pillars in his house,
which go no more out.

"`Having the unity and near sympathy of his friends and brethren at home,
as appears by sundry certificates, he embarked in the fourth month, 1784,
with divers other Friends, under the like religious engagements,
and arrived in London just before the yearly meeting, which,
though under bodily infirmities, he attended.

"`He was detained by indisposition in and near that city for some time after.
When a little recovered he travelled towards Bristol,
and after some religious labour there and in that neighbourhood,
sailed for Ireland and arrived at Cork; visited the meetings of Friends in that nation,
which when he had nearly gone through,
he found his mind engaged to join our friend John Pemberton, of Philadelphia,
in religious labour, principally amongst those who do not make profession with us.
After the national meeting in Dublin he returned to England,
attended the yearly meeting in London, those at Woodbridge and Norwich,
the quarterly meetings of Lincoln and Durham, and divers other meetings,
and then proceeded in this religious service to Scotland.

"`His bodily indisposition increasing,
he was under the necessity of resting at Old Meldrum, Edinburgh and Newcastle;
from which last place, taking a few meetings in his way,
he reached York the 2nd of eleventh month,
and was at our monthly meeting the day following,
which was the last meeting he was able to attend.

"`During the course of his travels we have abundant cause to believe
his religious services were truly acceptable to Friends,
and well received by others; for,
having an especial eye to the puttings forth of the Divine hand,
his ministry was attended with living virtue and deep instruction;
though '`not in the words which man`'s wisdom teacheth,`' yet in godly simplicity,
and with a zeal according to true knowledge.
He was wise in detecting the snares of the enemy; faithfully, and without partiality,
warning those who were in danger of falling therein; and,
as in the course of his own sanctification,
he had been made deeply acquainted with the necessary
baptisms peculiar to that important work,
so he was furnished by living experience and the renewings of holy help,
with qualifications to administer in tender sympathy,
pertinent and wholesome counsel to the true Christian travellers;
and so to dip in the present state of the church,
as profitably to '`declare unto Jacob his transgression, and to Israel his sin.`'

"`In meetings for business he was particularly serviceable,
his remarks being mostly short, pertinent, and very instructive;
exciting to a steady attention to divine counsel
in the transacting of our Christian discipline,
and therein to exercise true judgment, without partiality and respect of persons.

"`During the course of his illness he was preserved in a heavenly frame of mind;
on almost every occasion dropping instructive counsel
and advice to Friends who attended on and visited him,
of which the following collection is but a small part.
He frequently said,
that he knew not why he was continued in such an exercised state of bodily weakness,
yet doubted not, but that it was all in wisdom, and for some good end; adding,
'`It was not for the clay to say to the Potter, why hast thou made me thus?`'

"`Sitting in the family where he was during the forepart of his illness,
he expressed himself thus: '`Dear young people, keep to your first love.
The Bridegroom of souls will not be unmindful of the bride, whilst she remains chaste:
some of you, I believe, are espoused to Him.
O, the ardent desire which I feel for the youth!
Thy name is as ointment poured forth, therefore do the virgins love thee.`'

"`The same day:--'`I have not sought mine own honour,
but the honour of Him who first drew me from my habitation,
and have great reason to praise his name.
One thing which inclines me to think my work may be nearly done, is this,
that it never appeared to be laid upon me to pay a general visit to England.`'

"`At another time said, '`O, the harmony there is in the Lord`'s family!
Ephraim shall not envy Judah, nor Judah vex Ephraim;
nothing shall hurt or destroy in all thy holy mountain.`'

"`Again, under bodily oppression,
'`I find no relief but when I feel a revival of that which is the healer of breaches;
but that is not at my own command.
My mind was last night much drawn out to my fellow-labourers.
O, that they may keep little!--I have remembered that saying.
There are a few names even in Sardis, who have not defiled their garments;
and I hope there are a few in York.
Dear friends, what a people we should be, did we dig deep enough;
our lights would shine before men; we should be as the salt of the earth.
How many, who have begun well, have had their garments defiled with the world,
and are become like the salt that has lost its savour;
they are as dead weights in our assemblies,
so that the living are scarcely able to bear the dead.
O, Friends, keep to the Truth, for it shall rise above the heads of gainsayers.`'

"`At another time, '`I could not be more at home anywhere,
it revives me to see the children about me.
I tell you, young people, the hardest thing I ever found in my passage was,
when I was right to keep so.
O, the desire I felt to get here! the love I feel
for you is like the love of Jonathan and David,
it extends over sea and land.
It is like the precious ointment, so that some can say with one formerly.
Neither heights nor depths, principalities nor powers, things present or to come,
shall ever separate us from it.

"`The least star casteth a lustre, as the glorious luminaries in the outward creation;
so that we may say.
Great and marvellous are thy works.
Lord, God Almighty, just and true are all thy ways, thou King of saints.`'

"`Again; '`Commune with thine own heart, and be still; this is doing business:--O,
how precious Truth is! it may employ us on the highway,
and in our outward engagements -- dear friends, let us prize it.`'

"`To the physician; '`The outward man grows weaker,
yet inward support waxeth stronger and stronger.`'

"`The same day he said, '`It is a great favour to have a brook by the way--O,
I see my way over all! it is like a foretaste of what is to come:
blessed are the dead who die in the Lord; when he breaks in upon us,
it is like balm--there is balm in Gilead--there are
many not willing to go to the house of mourning,
but there is occasion for it; it being high time to repair the breaches.

"`'`I have thought for many weeks past, the curtain was nearly drawn;
there seemed but few sands left in the glass;
and yet I sometimes feel such a travail for Zion`'s prosperity,
and the enlargement of her borders,
that I am ready to think the day`'s work is not yet done;
and at other times I feel so feeble and weak, that all seems nearly over:
the event I cannot tell, but am favoured to be resigned.`'

"`At another time; '`Think nothing too near or too dear to part with, dear young people,
to purchase the truth: your parents cannot give it you,
though they may give you all they can; it is the Lord`'s prerogative.
I have thought it was a great favour to have an education in the truth;
but I have been grieved to see many born in the Society, like Esau,
selling their birth-right.
Be not ashamed of the cross, dear friends, deny Him not before men.`'

"`Again; '`Beware of lawful things;
these lawful things are the strongest baits Satan ever laid for our Society.
O, these lawful things, they have hurt many.
What a testimony would it be, if Friends were to shut up their shops on week-days,
to go to meeting; which ought to be the main concern;
though many consider worldly things as such.
When we have done all we can, we are but as unprofitable servants;
we can add nothing to Him, who is the fountain of goodness!
O, that ocean of ancient goodness, I seem at times,
as if I was swallowed up in it--I have cause to be
thankful that I am favoured with a resigned mind,
and have no will, either to live or to die--O Father, receive me into thy bosom.`'

"`At another time; '`O, my heart is knit to you, my friends,
and to the seed which is in bondage in many hearts;
and though you may have to go with it into the wilderness, yet be not discouraged.`'

"`Feeling himself easier and his mind favoured, he said, '`O,
when He puts in his hand as at the hole of the door,
how does it smell of sweet myrrh--I hope I am not insensible from whence my help comes.
He sometimes hides himself as behind the curtain;
yet we must not awake or disturb our beloved, until he please.`'

"`To a Friend; '`Keep to thy gift, and look to the Giver,
and have no confidence in the flesh.`' On the general state of mankind, he said thus;
'`O how has my mind been oppressed in observing that
profaneness which abounds amongst the people,
many of whom draw iniquity as with cords of vanity, and sin as with a cart rope.
Yet I have this satisfaction,
that I have not failed to reprove many of those I have seen in this state,
and have often advised innkeepers and others,
to discourage all kinds of wickedness in their houses:
my advice hath been generally received without gainsaying,
and I have comfort in the discharge of this duty,`' Sympathizing with faithful Friends,
he remarked, '`Where there are a few faithful labourers, the work falls heavy upon them;
we cannot expect to rise high when the seed lies low.`'

"`Under much bodily affliction, he said,
'`How can one die better than in the Lord`'s service?
for he has been indeed, a wonderful counsellor.
He has many times opened a way, when I could see no way;
he will never leave nor forsake those who trust in him.`' Again; '`It is a trying time,
and yet I believe I have a well grounded hope of having done my duty.
I feel no condemnation.
O, dear friends, what a favour indeed,
that we have an unction from above! keep to the truth and its testimonies.`'

"`At another time;
'`It will not do for any to rest contented with having known the Lord in days past,
and years that are over and gone; we must follow on to know him;
a supply of daily food is requisite;
and if there is not a hunger and thirst after righteousness,
we may be sure the mind is distempered; but O,
how have I been pained to see and feel many of the professors
of the truth going after the world and its spirit;
who instead of being way-marks,
are as stumbling-blocks to honest inquirers--the state of these is lamentable.
I have been comforted in the prospect of a rising generation,
if they are not hurt by those who ought to be helpers, loving the present world.

"`'`I have in my time met with many cross winds and boisterous waves,
but have been preserved in a care to keep near
to the point that guides to the harbour of rest.
For these fifty years I have been endeavouring to fight the good fight of faith.
O, dearest Father, not my will, but thine be done--O, when will the curtain be drawn?
that this mortal may put on immortality and eternal life, which will, I do believe,
be my happy portion.`' To some Friends about to take leave of him,
'`let your lights shine wherever you are--I have not much to say,
but there is a great deal comprised in this.`'

"`To some young people; '`You are in health; prize it, and make a good use of time;
for to the most diligent, such a time as this will prove very trying.`'

"`He would often, in thankful commemoration of the goodness of God to him,
break forth in these words: '`What shall I render unto thee, O Lord,
for all thy benefits!`'

"`A few days before his decease, on a Friend returning from meeting,
he said he had been favoured with such a calm, that he hoped he should have passed away.
And a day or two before he died, he broke forth in these words:
'`O joy! joy! joy!`'
Again; '`O death where is thy sting?
O grave! where is thy victory?
the sting of death is sin.
I see no cloud in my way, I die in peace with all men.`'

--

[.offset]
John Pemberton thus proceeds:

"`28th; Attended the monthly meeting at Thirsk, which was pretty large,
and there I mentioned to Friends my thoughts of
a meeting with the inhabitants of Buroughbridge;
and my dear friend Robert Proud offering to accompany me,
we returned in the evening to his house at Carleton-miniot.

"`Fourth-day, went to Buroughbridge and Boswell Middleton,
and having procured the town-hall, we had a large meeting,
and upon the whole tolerably favoured.
Sixth-day, to Burrowby, thence to North Allerton, and on seventh-day, to Osmotherly,
and had a meeting in Friends`' meetinghouse.
My dear friend Robert Proud was favoured, but to me it was a poor low time.
This hath been my state for some time past, being much proved in mind.
Here I parted with Robert Proud, and with Isaac Taylor proceeded to Bilsdale,
over a hilly road, the weather cold, and considerable snow on the ground.

"`First-day, third month 5th,
went to Bilsdale meeting under great lowness and discouragement.
The meeting was full, many not in profession with us attending.
The people were directed not to place their dependence on man,
but upon the teachings of God`'s spirit.

"`Third-day, attended the monthly meeting at Scarborough.
The meeting for worship was low, yet some instruction opened,
in the complaint uttered respecting Ephraim and Judah,
that their goodness was like unto the morning cloud and early dew,
which soon passeth away;
and those not in profession with us were exhorted to put their trust in God,
and not in man.

"`Fourth month 2nd, at Ayton.
I have been diligently engaged in Yorkshire, having had many large meetings,
and also visited about seventy families at Scarborough and Whitby.
It is wonderful that so much openness should be in many places,
where there are few right examples.
At the last mentioned place there is a very sorrowful departure.
Almost throughout this land there appears a willingness
to hear the testimony of truth declared;
and I hope a gathering day will come; though a day of trial may first take place,
to shake the earthly hearts of the people, and discover the rottenness of others.
Many lamentable things happen among us--sorrowful failures, by grasping after the world,
and not being limited by the pure truth.
One lately,
which makes and will make as great a noise as
any that of later time has happened amongst us.
I was uneasy when at the Friend`'s house, and took divers opportunities to speak to him,
but did not expect things were as they now appear.

"`I evidently see that in the path I tread, great watchfulness is needful,
among a people accustomed to be fed with words.
I endeavour to keep in the simplicity,
and am mostly clothed with deep poverty,--a poor creature,
and often ready to be dismayed.`"

During the remainder of this month he was diligently occupied
in various parts of the counties of Durham and Northumberland,
being deeply proved in mind under an apprehension of not being clear of Scotland.
He reentered that nation near Kelso, on the 29th of fourth month,
and reached Edinburgh two days afterwards.

About this time, having heard with much sorrow of the disreputable failure of one,
at whose house he had formerly been entertained,
he wrote to a friend of that neighbourhood;
and his feelings on the occasion may be gathered from the following extract:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`Sunderland, Fourth month 22nd, 1786.

[.salutation]
"`Dear friend, D. S.,

"`The disreputable and unjust conduct of+++_______+++, I am persuaded,
must give thee and every sensible judicious Friend much pain.
&hellip; not only unjust in betraying the confidence placed in him,
and making use of the property of others without their knowledge or consent;
but very inconsistent with the holy, pure principle we profess,
which leads to self-denial; and those whose minds are bounded by this principle,
do experience it to limit, respecting worldly pursuits: though, lamentable it is,
that many among us are burying their talents in the earth,
and eagerly grasping after worldly treasure.
The Lord, in great wisdom, sometimes sees meet to blast the expectation of these,
that others may be warned to guard against the snares
of the world and an ambitious craving mind.
Religion leads to a proper industry; but it teaches to avoid surfeiting cares,
and that our chief concern be to lay up treasure in heaven--to seek above all,
the peace and favour of God; which must be by loving him with all our heart,
and being faithful to the manifestations of his light, grace and truth.

"`When I was at N+++________+++, and lodged at +++________+++`'s, I was often uneasy,
and at divers times spoke to him respecting the multiplicity of his engagements,
urging him to bring his affairs into a narrower compass:
though I did not apprehend he was so variously engaged, or in so deplorable a condition.
But, as it proves, that while at his house, both before I entered Scotland,
and since my return, I was entertained at the cost of others, and not eating his bread;
I am most free, to calculate, as nearly as I well can, what it might amount to,
and request thou wouldst present the sum to the assignee,
to be joined to what may otherwise arise towards paying his creditors.
Thou knowest that we, as a religious society, have always pleaded for just dealing,
equity, and truth.
And as I came from my native land under a sense of duty to Almighty God,
and from love to mankind, to promote, as the Lord might see meet to enable me,
righteousness and truth in the earth, so I wish to manifest, by my conduct,
in all respects, that I am sincere.
If this is not thought sufficient, please to add, and I will repay thee.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
John Pemberton.

--

The amount thus directed to be paid to the assignee, was seven pounds ten shillings.

"`Fifth month 10th; What is called a yearly meeting was held here +++[+++Edinburgh]
last week, which however is no meeting of record,
though they have long corresponded with the yearly meeting in London.
The few Friends in Scotland,
being now convinced that they are incapable of
maintaining a yearly meeting with propriety,
have agreed to request the yearly meeting of London to
take their circumstances into close consideration;
and have proposed that the whole Society in that part
might be considered as one quarterly meeting,
to be held, however, half-yearly.

"`31st; at Old Meldrum.
I came yesterday from Aberdeen, where we had been to attend their meetings on first-day,
and meeting for discipline, at which there were two notifications of marriage,
which I suppose has not been the case at any meeting there for a long time.
I am through mercy pretty well,
considering the trial of mind that has attended
on thinking of again going to remote places.
Alexander Cruickshank of this place, who was with me last year, is going,
and Isaac Taylor of Yorkshire, besides Thomas Cash.
I desire to do no more than may be evidently required,
and if I move under right direction, the great Master is able to support and preserve.

"`I left Old Meldrum, and went to Chapel Siggot,
and finding most ease in appointing a meeting,
notice was spread and we had a pretty satisfactory meeting in a barn.

"`First-day, sixth month 4th, at Auch Medden.
Notice having been spread yesterday, and the Methodist meetinghouse being procured,
we had two very large favoured meetings, particularly the last,
in which the testimony of truth was in a good degree exalted,
and the hearts of many tendered.
A gaily dressed young woman, who was at the meetings here,
wrote a letter to us expressive of her gratitude
and satisfaction with those opportunities.
I afterwards had some of her company.
She was solid, and her mind tender.
When I passed this place before,
I was under deep exercise of mind on account of the people in that neighbourhood;
but for want of proper resolution passed away, and suffered much,
and met with discouragements, when I proposed returning.
The meetings now being large and favoured gave me ease.`"

After this they had meetings at Gordontown, Banff, Campbell-town, Fort George, Cromartie,
Golspie, etc., and on the 16th of eighth month, being at Caldwell near Kirkwall,
he thus writes:

"`I have entered the Orkneys, and have been much employed since,
in passing from from isle to isle.
Since the last of the fifth month,
I have been exposed to many provings inwardly and outwardly;
but have been hitherto mercifully supported, and have experienced much kindness,
particularly in the Orkney Islands.
I have visited eleven called the Northern islands, and an island called Stroma,
in Pentland Firth; also two others which I was at last year.
It is very evident that visit left profitable impressions,
and made the way much more easy for us now.
The meetings have been generally very large and quiet, and most of them favoured seasons,
in which the minds of many were much tendered;
often from two to five hundred were present.

On those eleven islands we had twenty-six meetings.
It was mostly rough weather, through the seventh month,
and we were detained on Westra about a week.
How soon I may be released I know not,
but desire to be favoured to see clearly the right season to depart.
It is a great favour, under religious concerns, to see the time for moving from home,
and to attend to it;
and I believe it is equally important to determine the
right time for leaving the countries visited.
There may be danger through fear to overstay, as well as through fear to return too soon.
May the Lord guide by his counsel, and direct my steps aright.
To dwell in a state of deep humility and watchfulness, as well as faithfulness,
is abundantly needful.
I dwell under the daily cross, and little but conflict and provings are allotted me;
yet the Lord has condescended to furnish for his own work beyond expectation.

"`On first-day evening, the 13th instant, we had a large meeting at Kirkwall,
held in their cathedral.
My kind landlord, William Lindsay, thinks there were more than fifteen hundred present.
Many say they have seldom seen it so crowded.
They are generally a moral sober people.
Though I have passed over many waters,
I have rarely heard an oath or ill expression from any.
The books spread, I believe have been useful, and have removed prejudices.
The winters being long and the days short, many read much;
the writings of Mosheim and others respecting Friends, had hurt some;
but what they have seen since has set many to rights.

"`The next day went to a parish called St. Andrews, and had a large meeting,
which was measurably favoured.
The minister, John Scolley, an aged man, who had offered his worship house,
stood up before the breaking up of the meeting and
recommended the counsel that had been delivered,
to the notice and practice of the people, saying it was gospel truth.

"`On third-day, the 15th, I was most easy,
though in a low state of mind from various causes, to appoint a meeting at Orphir;
we went, and many assembled in the kirk, so called; but the meeting was mostly dull.
After this meeting Thomas Cash concluded to go to some
of the other islands which I had visited last year,
so we parted for a season, Joseph Taylor and myself returning to Caldwell.

"`Ninth month 30th; Set out for Graemeshall, where I was kindly received by P. Graeme,
and as it was very stormy during this and the next day, we continued at Graemeshall.
The wind was so high, accompanied at times with rain, that much corn was damaged,
being cut off at the ears by the violence of the wind.
Being desirous of proceeding for England, on second-day,
a sloop being just ready to sail for Stronsay, with a fair wind,
we were prevailed upon to embark in her, and sailed several hours;
but the wind proving high and contrary, we were obliged to return to Holm sound,
having been on board from half past eight, A. M., to near ten o`'clock at night.
Next morning we hired horses for Kirkwall, and there took boat for Shapinshay,
and were received kindly by Alexander Pitcairn.

"`Fifth-day, had a meeting at Lapniss, held in a barn, or store-house,
and though the morning was rainy, it was large;
but the life and comfortable spring of religion were much wanting.
Spent the evening with some satisfaction in opening the order of our discipline.

"`Third-day, the 12th;
The wind was high and the water rough--a boat arrived at Burwick from Caithness;
but the skipper expressing doubts of his being able to get over, we declined embarking,
and stayed at the ferry all night.
A Methodist minister came over in this boat,
the first of these people that has visited Orkney.

"`Fourth-day, the wind still boisterous; continuing so the two following days,
for the most part, so that we could not cross the Firth.
On seventh-day, the morning proved more favourable, and a boat coming from Caithness,
we embraced the opportunity of returning with her,
and were about two hours and a half on our passage.
We soon after took horse and reached the widow Sinclair`'s, at Brabster Dorner,
in the evening.

"`First-day, ninth month 17th; Through fear of offence, by travelling on this day,
we continued at the widow Sinclair`'s,
and had a little sitting with her and her children after breakfast.
In the afternoon I was visited by Alexander Sangstre,
a man who seems convinced of our religious principles.

"`Sixth-day, proceeded to Tain, and in crossing the ferry near Lord Ankerville`'s,
we met him; and he pressing us to dine with him, we complied,
and our visit was taken kindly.

"`Third-day, 26th; This morning we crossed to Fort George.
It snowed much last night, and the hills were very white this morning.
After dinner we had to ride in a heavy storm of sleet and snow to Billeward,
where we were well entertained at a good inn.

"`We came the Highland road, through a rough country; but great pains having been taken,
this road is better and shorter than the coast road, with good entertainment.
We had a meeting on seventh-day at Dunkeld, held in a large loft or drying room,
belonging to a manufactory.
Many people attended, and it was a more favoured time than I expected.
It is likely no Friend ever attempted a meeting here before.
The meeting was at first fixed to be held in a large room not fully finished,
in the inn where we lodged; the bailie of the town, the landlady and others,
approving thereof.
But after notice had been given to divers of the inhabitants, one Captain Dick,
a military officer, came into the town and forbade the use of the room.
On which I had discourse with him; but he said he did not want it consecrated,
and that it was built to dance in and accommodate genteel company.
I told him I was sorry that any one who professed the Christian name
should prefer vanity to seriousness and religion;
and that I had been through much of Scotland and England, and scarcely met with the like;
and was sorry that on my going out of Scotland, where we had met with great civility,
I should have such an account to give respecting his conduct.
And in another opportunity after meeting,
I told him that it was the sentiment of the ancient reformers,
that as many paces as a man took in a dance, so many paces he took towards hell,
remarking that he might think this harsh, but it was their sentiment.
He said, he then had taken many steps towards hell.
He was a vain man, but I spoke pretty closely to him.

"`After dinner we proceeded to Perth, and on first-day afternoon had a large,
crowded meeting in the council, or courthouse, which was in a good degree favoured.
When I saw the crowd and considered my own feebleness, my mind was much sunk;
but I was graciously helped, and hope no dishonour arose to the good cause.

"`Second-day, reached Edinburgh in the evening much wearied.
If the Lord see meet to employ me now among Friends, or grant a release to return home,
I shall esteem it a favour,
for it remains a great trial to tread the path in which I have been so long exercised.
I have at times been too resolute to turn aside, for which I have suffered;
but rich in mercy is the great '`I AM,`' with whom we have to do;
or my portion would have been among the miserable.
It requires great watchfulness, humility and abasedness,
to keep duly under the subjecting power and at all times faithful.
I often fail and am brought weeping to the cross, and to beg the great Master`'s mercy.
He hath indeed been long suffering, but I often fear I shall never learn wisdom.
May my friends be helped to pray for my preservation and
steady perseverance in the straight and mortifying path.

"`First-day, tenth month 8th;
Had a large satisfactory meeting in the town-hall at Jedburgh,
and had very different treatment from what dear Samuel
Bownas met with when he visited that place.
Several magistrates attended the meeting,
and one of the bailies sent for me in the evening,
and I went and spent some time at his house.
He and his wife seemed to have a regard for Friends.

"`Third-day, we heard of Ann Jessup and her companion Hannah Stephenson,
having appointed a meeting at Solport, to which we went.
The meeting was low, and these two Friends wholly silent.
We dined and proceeded to Sikeside, and had a meeting at Kirk Levington,
which was wholly silent.
A young man afterwards remarked, that they had not been used to silent meetings,
a person then present preaching at all their meetings.
We were glad we kept our places.

"`Seventh-day, rising early we had a religious opportunity in a family,
and then went to Kirkbride.
By the time we got there we were wet.
The meeting was small, and religion here is very low.
Some few of the neighbours not professing with us came in, and one afterwards said,
"`if they had had a candle and could see the inside of those called Quakers,
they could not have more plainly told their state.`"
We dined at J. S+++________+++`'s, but he was too busy,
as he thought, to get to meeting.

We then proceeded to Wigton, and on entering the town, there was a great uproar,
and the streets were much crowded with people,
who had been spectators to the wicked and inhuman practice of baiting a bull.
The poor creature seemed much abused, which sorrowfully affected my mind,
in considering how opposite such cruelty is to the
disposition which the gospel of Christ inculcates.

"`Fourth-day, went to Gilfoot, and attended the monthly meeting.
The season of retirement and public worship was one of much poverty and deep exercise;
but the Lord favoured with some strength towards the close.
I had to remark the difference between such who were commissioned of man,
and had their tuition and education for the trade of preaching, as it is termed,
and those commissioned of God; the one could, and it was feared too often did,
move in his own will; the other must wait for the great Master to put forth,
of whom it is said, '`he putteth forth his own sheep,
and goeth before them;`' pointing out that it was not the expression of words,
but words seasoned by the grace of God, that could profit the people.
I understood after the meeting, that a priest was there, who sat quiet and well.
The meeting for discipline was an exercising time.
Many observations were made, to stir up Friends to honesty in religious care,
but to little effect.
It appeared that the discipline was very little supported;
but I did believe there was great cause for attention to it,
were a proper concern exercised.

"`I attended fourteen meetings in Cumberland in company with our dear friend Ann Jessup,
and her valuable companion H. Stephenson,
but was not easy without returning into some parts of Scotland.
I parted from them on sixth-day with reluctance,
but they were sensible it was in best counsel, which was some strength to my mind.
Isaac Taylor and myself went to Carlisle, and attended the monthly meeting there.
Truth opened counsel in the meeting for worship,
and many observations were made in the meeting for business,
to stir up Friends to a proper search.
I had to remark the low state of our religious Society in Cumberland,
and that if the discipline, which was established in the wisdom of truth, was neglected,
and those who were remiss in attendance of religious meetings,
or in other branches of our testimonies, were overlooked, that death and barrenness,
which now sorrowfully prevailed, would increase.
I also told them, that if they had honestly discharged their duty,
and there was no cause for religious care,
they were better off than Friends in other places,
who were much exercised in their meetings for discipline.
They seemed more open to receive counsel than two other meetings we had attended.

"`I left Carlisle in the evening, and on first-day,
in company with our friend David Ducat of Carlisle,
and my kind young friend Isaac Taylor, had two large meetings in the townhall at Hawick,
a flourishing manufacturing town in Scotland.
They were open and satisfactory.
Being invited to take tea with Thomas Usher, an attorney,
we had some seasonable conversation with him and others
on several branches of our religious testimonies,
particularly respecting tithes, to their satisfaction.
Retiring to our quarters, my mind was much exercised respecting the line I was to pursue,
and continued so much of the night.

"`Second-day, after breakfast, when ready to mount,
I felt most easy to proceed towards Edinburgh, Glasgow, etc., and set out.
Passing through Selkirk, my mind grew very uneasy, yet I went on for about four miles,
when we stopped to refresh ourselves and horses.
I had some seasonable conversation with the family to mutual satisfaction;
the man of the house censuring their ministers for
being more concerned for the fleece than for the flock.
Many things were opened to them, and we parted in love.
My mind continuing much exercised, I returned to Selkirk;
and the town-hall being granted, we had a very crowded meeting.
Though many were very raw and ignorant of true religion,
yet numbers were tenderly affected.

"`Third-day, visited the English school.
The master, who had been at meeting last evening, received me very courteously,
and expressed that he had attended the meeting under prejudice,
but found he was mistaken in his apprehensions respecting us,
and was glad he was at the meeting.
He made inquiry respecting several things, particularly baptism and the supper,
so called; and we parted in love.

"`The weather this month has been mild and favourable, which is a mercy,
as much oats and barley is not yet reaped.
I am favoured with better health than usual,
and able to endure fatigue beyond expectation;
riding sometimes nearly forty miles in a day, on horseback.

"`Seventh-day, twelfth month 30th; Returned to Wigton, in Cumberland,
having been absent in this last journey to Scotland, forty-six days;
in which time we were at upwards of fifty meetings--six at Glasgow, at different times,
several of which were much crowded and open; also at Port Glasgow, Greenock, Paisley,
Dumbarton, etc., generally two meetings in a place.
The people in the south of Scotland being much
divided respecting what they call religion,
were not at first so open as in the more northern parts;
but the first meeting softening them, the second was generally large and favoured;
and we left them in love and favourably impressed,
some acknowledging they had been misinformed respecting us and our principles.
The magistrates were generally respectful, particularly at Dumbarton, where,
I believe in much sincerity, we were offered the freedom of their town.
But they were informed that we came not to seek honour of men,
but in love to visit the people, and to be found in the discharge of a religious duty.
They said we deserved respect, and that this was the only testimony they could give.
We acknowledged their civility,
but told them that their granting the town-hall to accommodate a meeting,
and attending it themselves, was a sufficient testimony of their respect.
The deputy sheriff insisted that we should spend the evening at his house; which we did,
and were treated with as much openness and freedom from unnecessary compliment,
as though we had been at a Friend`'s house.
Many acknowledge the principle,
but are not brought to a willingness to submit to the cross.

"`At Moffat, the chief bailie, David Gregg, refused the town-hall,
and was very wide in conduct and disposition from the provost and sheriff at Dumbarton,
and from those in almost every place in Scotland.
We could scarcely obtain liberty to speak to this man, he soon turning his back upon us.
Neither could we obtain the school room, which was also under his direction.
But at length we obtained a carpenter`'s shop, and had a crowded meeting.
Some serious people attended, but generally they were a very raw ignorant company.
John Johnson, a magistrate, attended the meeting,
and afterwards sat awhile with us at the inn,
and expressed his concern at the bailie`'s conduct.

"`At Gillfoot, on our return from Scotland, we attended the monthly meeting.
We had but a poor, cold meeting, few there being deeply concerned for themselves,
and so not rightly exercised for the cause and testimony of Truth,
Many valiants were formerly raised up among these hills,
who were engaged to proclaim the day of the Lord,
and were instrumental in gathering many to Christ.
We passed that morning through Udale and near Langlands, mentioned by dear George Fox.

"`Second month 7th, 1787, at Eglesfield, Cumberland.
I have been two months in this county among Friends, in great stripping and leanness,
especially for some weeks past.
I compare myself to one whose gift is sealed up, and left without succour,
but I strive to keep quiet and patient.
Friends are kind, and wish me to consider it as a time of rest; which I should do,
could I experience the great Master`'s presence near, and the sustaining bread dispensed.
I look homewards, but light does not spring.

"`Third month 30th; Attended the quarterly meeting at Carlisle,
where I met with my dear friend George Dillwyn.
I have been long in this county, and ceased from appointing meetings,
though I have had but little real rest.
This is what we cannot come at when we please.
It has been a stripping and cloudy season with me,
and I have had to search and review my steps.
Omissions more than commissions, are marked against me,
for which I have great occasion to be deeply humbled.

During the last six weeks I have attended many meetings in the west part of this county,
in seaports and other towns, large and satisfactory,
being united with our dear friends John Hall, Jane Pearson and Barbara Drewry,
three valuable ministers.
An open door is left.

This week I have attended six meetings belonging to Northumberland;
and expect to go into Scotland again.
This may appear singular to many of my dear friends,
but the reduced state to which I have been brought,
has wrought a willingness to go anywhere, or to be any how employed,
for the light of the great Master`'s countenance, and a return of life.
The prospect is humbling, but I am not my own, and I seek not honour from man;
many trials have attended me among that people;
and it is not desirable to the creaturely part to enter there again.

"`Fourth month 2nd; This morning George Dillwyn parted with me,
he proceeding towards Kendall;
and after dinner David Ducat and myself left Carlisle also, and proceeded to Longtown,
where we had a large meeting, held in the inn.`"

Thence to Langholm, Annan, Dumfries, Kirkcudbright and Gatehouse.

"`Some Englishmen have at Gatehouse a large cotton factory, worked by water,
the wheel being fifty-two feet in diameter, and six feet wide.
Several hundred people are employed.

"`Third-day, 17th; This morning we went for Wigton, and obtained the courthouse.
The Lord was gracious, and owned the meeting with his good presence,
to my humbling admiration.
Blessed be his name!

"`Seventh-day, we turned for Newton Stewart,
in order to obtain a meeting among the miners again, and arrived at Crea-bridge-end.

"`First-day, about noon, David Ducat and myself sat down, and the landlord,
his wife and daughter,
and another person came and sat with us in a religious opportunity.
In the afternoon we went to Blackrock, and had a meeting in the school house.
Second-day, had a wet ride to Glenluce; the meeting was much crowded,
and through the Lord`'s goodness and help, was a favoured opportunity.
An aged man at the conclusion acknowledged in a solid manner,
that '`the Spirit had helped.`'

"`Fifth-day, at Port Patrick.
Many gospel truths were delivered.
Those who attended behaved well, and divers wished they could recompense us,
being sensible our motive was their good.
We took horse and proceeded to Stranrawn; where,
with some exertion we obtained the town-hall.
The magistrates and a large number of people met, and the Lord condescended to favour,
so that it was a profitable meeting.
A man aged about seventy-one, requested after meeting some opportunity with us.
He came to our inn, and we found him a serious person.
Having once had an opportunity to see Robert Barclay`'s Apology,
he acknowledged that the doctrine contained therein was consistent with his judgment,
and expressed his great satisfaction with the meeting.
The next day he dined with us and parted in tenderness, seeming convinced of the truth.

"`I proceeded with my companion, David Ducat, along the west coast of Scotland,
to many large towns and populous places, until the 15th of fifth month,
having attended in six weeks and two days, sixty-three meetings, mostly large,
the Lord in abundant condescension and mercy having made way beyond expectation,
and opened the minds of the people, magistrates, ministers, etc.;
though it is a part where the people are much divided and embittered,
one sect against another; there being,
many '`lo heres`' and '`lo theres,`' labouring to draw disciples after them.
What they call preaching, is chiefly railing one against another;
which made our way in some places more difficult;
but the first opportunity set the people to thinking,
and caused a second opportunity to be more solid, open and satisfactory,
they being evidently convinced that our motives were disinterested,
and that our labour was to turn the mind from man and all human trust, to God.
Thus we left every place with the good wishes of the people.

"`At Irwin, several Presbyterian ministers, who met there on account of a Presbytery,
attended the meetings, and the Lord in his mercy and goodness was pleased to favour,
so that the gospel was preached in the authority thereof,
to the awakening of divers minds.
We spent some time after dinner, with these Presbyterians, being sixteen persons,
fourteen of whom I took to be ministers, to to mutual satisfaction.
They inquired respecting divers matters, which were in simplicity answered.
I showed them my certificate, which was read,
and they commended our order and care over our members.
On parting, as they had wine before them, I was free to revive the care of holy Paul,
who kept his body under, lest, while preaching to others,
he himself should become a cast away;
and I told them that this care was needful for all who professed to be gospel ministers.
They acknowledged it, and we parted with their good wishes.
Two young men came into our inn and desired an opportunity of conversing with us;
but we found they had been led away with the airy notions of a people called Buchanites.

"`At Kilmarnock we had a meeting in the grammar school, which was very large,
the room being exceedingly crowded, and many without.
The Lord condescended to favour, and the free grace of God offered unto all,
was testified of, and the way of life and salvation opened,
which seemed to have place with many.

"`At Renfrew we applied as usual to the magistrates, but could not obtain the townhall,
nor did they seem open to our having a meeting in the place.
The provost being a young man, it appeared to be more out of fear than moroseness.
However, we obtained a large school room and had a full meeting.
The people behaved well beyond expectation, and my companion had a clear good time,
pointing out the mistake of many,
in imagining that faith is imputed to them for righteousness,
without a ceasing from sin and self-righteousness,
and coming to learn of Christ and to be subject to his rule.

"`I was often very solicitous during this journey,
to be permitted to attend the yearly meeting in London;
and at length I did break loose from Hamilton, near Glasgow,
and reached London the 23rd of the fifth month.
The yearly meeting for ministers and elders, began on seventh-day, the 26th,
a large number of solid Friends attending.
Eight of us Americans remaining here,`" viz: George Dillwyn, William Mathews,
John Pemberton, Zachariah Dicks, Rebecca Jones, Patience Brayton,
Rebecca Wright and Ann Jessup, "`attended this yearly meeting,
which was the largest I have known here, and the largest body of plain and solid Friends,
men and women, that I think I have ever seen together.
There was a very hopeful appearance of beloved youth, clothed with innocence,
and under the baptizing power of Truth.
May the Lord preserve them in his pure fear,
and cause them to grow '`as calves of the stall.`' A concern
for the support of the discipline and gospel order increases,
and there is a prospect that the number of quarterly
meetings will be lessened by several counties uniting,
so as to increase their strength.
The women`'s yearly meeting has been the means of
many solid women attending from various parts,
and of bringing them more under the weight of the service.
There was much harmony in this yearly meeting.
The strength of the worldly wise was much brought under, so that there was little display.

"`To go back to the north is to me no pleasing prospect.
I spread my case before Friends at the yearly meeting for ministers and elders,
and laid myself open to counsel.
Much sympathy was expressed, and the result was,
to leave me to the Lord and the guidance of his good Spirit.
I hastened from Scotland in order to throw myself open to Friends,
and it would have been pleasing to me, as a man,
had they told me I had been long enough from home.
I expect to attend the general meeting at Colchester,
and if after that I do not feel a release from the north, I must submit.
My dearly beloved wife appears full of expectation of soon seeing me;
but crosses and disappointments are our lot in this probationary state;
and may she be sustained in patience and humble acquiescence,
for herein alone is true peace experienced.

"`Sixth-day, sixth month 8th; Attended the meeting at Grace-church street,
held mostly in silence.
I had a little matter at the close,
being the first testimony I have delivered in a
public meeting since I came this time to London.

"`Seventh-day, took coach and arrived at Colchester about two o`'clock;
and about five o`'clock the meeting for ministers
and elders for Essex quarterly meeting began.
Our friends Deborah Darby and Rebecca Young, from Shropshire,
and George Follows and wife, from Warwickshire, attended it.
I lodged at my old acquaintance John Kendall`'s.

"`Second-day was the quarterly meeting; a profitable season.
"`The business was conducted commendably,
and many useful remarks were made through the influence of gospel love and concern,
to stir up Friends to an honest discharge of religious duty.

"`Second-day, 18th; To Woodbridge, and attended the quarterly meeting.
The Lord opened counsel, in the reading of the queries and answers, and my companion,
Zachariah Dicks,
had to bear testimony against divers things which appear
inconsistent for the professors of Truth to be found in,
as falling capes, powdered hair and wigs, etc.
On the use of powder, I had here, as well as at Colchester,
to remark that when I was in the Orkney islands last summer,
many families had not meal for themselves and children, for many days,
and some for weeks;
and that the waste thus made would feed many--that although
some might reason that what they used was but little,
yet when all that was so used was summed up, it would supply the wants of many.

"`Fifth-day, rising early, we took chaise and went to Leiston, where we had a meeting,
many of the inhabitants of the village coming in.
The meeting was favoured,
and Friends being desired to continue their seats after others separated,
we had an opportunity with them,
to excite to a diligent care in attending their meetings,
and to circumspection in all respects consistent with our holy profession.

We dined at the widow Jessup`'s, at the Abbey, whose ruins we viewed;
and after some religious communication with some young people, we proceeded to Beecles.

"`Sixth-day, notice being given, many gay people attended, and some play-actors,
who were to exhibit their evil and vanity in the evening.
A close testimony went forth against such scenes of dissipation.
The people behaved well, and the Lord in mercy owned us in our exercise.
Friends keeping their seats after others left the meeting,
my mind was drawn towards a state that had long lived in a neglect of religious duty,
and in a disregard to the Lord`'s call and visitation;
and yet at times felt desires enkindled for a return, but concluded it was too late,
and therefore might continue to indulge in wrong courses.
I pointed out this to be the suggestion of the enemy,
and pressed this state to look to Him who is mighty to save,
and whose mercies are yet continued,
believing that by humbling the heart and knowing the gift of sincere repentance,
remission of sins might be experienced.
Friends were incited to diligence in the attendance of meetings,
and circumspection in all parts of their conduct,
that they might be lights in their neighbourhood,
holding forth an inviting language to serious inquirers.
Soon after the conclusion of the meeting, our kind friend, Edmund Peckover of Norwich,
came with his chaise to conduct us thither.

"`First-day, attended two meetings at Yarmouth.
The minds of Friends being much outward, and too much accustomed to words,
the meeting was mostly spent in silence.
My companion, Zachariah Dicks, had nothing to offer;
I had some remarks to make to excite Friends to look to the Lord, and wait upon Him,
for supplies of wisdom and strength.

"`Second-day; The quarterly meeting at Norwich, which was favoured.
Third-day, attended two public meetings for worship.
In the morning our aged worthy friend Ruth Follows, had deep searching service.
In the afternoon many not of our religious Society attended, and my friend Z. Dicks,
had a good time in searching labour.
Fourth-day, the remaining business of the quarterly meeting was entered upon.
It was an instructive time, and Friends were open to receive help.
Some close remarks were made respecting the
cause of the obstructions to the growth of truth.

"`Sixth-day; this morning early, we had a religious opportunity at Edmund Peckover`'s,
and then set out with him for Edmundsbury, where we arrived about four o`'clock.
A meeting was held in the evening, some of the principal inhabitants attending,
with a Presbyterian minister, and divers of that people.
It continued in silence about two hours;
then both Z. Dicks and myself had something to offer,
part of which pointed out the necessity of waiting for the influence of the spirit,
to minister profitably, and that it was such ministry,
proceeding from disinterested motives, and real desire for the people`'s good,
that could reach the witness and build up in the pure faith which works by love.
It was an exercising meeting, but I hope ended well.

"`Seventh-day, arrived in London in the afternoon,
and spent the evening with our exercised friends Patience Brayton and Rebecca Wright.
There is no Friend here, I believe, on a religious visit,
who has left greater impressions than Patience Brayton has done,
and a sweet savour in all places.
Though she may not be of the wise, as to this world,
she is greatly honoured of her Master,
and has been deeply led into the state of meetings and particulars.
It is the Lord`'s doings and marvellous in our eyes.`"

Whilst in London, he wrote a letter to his niece, Hannah Morton, of Philadelphia,
from which the following is extracted.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, seventh month 7th, 1787.

[.salutation]
Beloved niece,

Thy lines came speedily to hand by our friends John Storer and Thomas Colley,
who landed safe, and favoured with health,
and soon after posted to their respective habitations.
It was comfortable to find they were strengthened
inwardly and outwardly to fulfill their religious duty,
and to return with the evidence of peace.
This is what I have with diligence laboured for, but when I may be released, I know not.
I much long for the time.
The dispensations thou hast experienced are proving;
I wish they may be sanctified to thee.
It is a favour to be brought to see the emptiness and vanity of the world,
and its glitter, and to have the mind turned to aspire after that which is permanent.
I desire thy preservation in humbly seeking after and
following the counsel and direction of the Prince of peace,
that by following on to know the Lord,
thou mayest experience thy heart enlarged and thy mind strengthened,
and become a burden-bearer and partaker in the arduous labour of the day.
The harvest is great, and the strength of the burden-bearers at times ready to fail;
but the number of the faithful may multiply, if the divine call is regarded.
As thou art favoured with talents, may they be rendered truly useful,
by seeking unto the Lord, who can strengthen to every good word and work,
and render them double.
Our time here is short, and wise are such who work while it is yet day,
taking up the cross, and being willing to become fools for Christ`'s sake.

There are indeed many of our relatives and dear friends removed since I left home;
and we are journeying also to the same period.
May we so run as to obtain.
Thy present situation requires great circumspection, and I desire thee to be guarded,
that if any solicitation offer, to change thy situation in life,
thou mayst seek counsel and attend to the secret intimations of truth,
which may be thy preservation.

[.signed-section-closing]
I am with near affection, thy loving uncle,

[.signed-section-signature]
John Pemberton.

--

"`Seventh month 18th;
I have been waiting to take my leave of our dear friends about to embark,
expecting tomorrow to bid them farewell.
I laboured for liberty to depart with them, but could not with peace;
and the thought of steering north again, when the season is so far advanced,
is deeply proving.
But to force myself, contrary to conviction, is not safe,
nor would my return be comfortable to my dear friends,
unless in the counsel of pure wisdom.
The Lord hath hitherto marvellously helped; blessed be His name.

"`Spent the after part of the day with my dear friends Rebecca Wright, etc.,
who were at my quarters;
and Rebecca Wright said she had clearly seen the propriety of my return into the north.

"`Sixth-day, I took my leave of my dear country folks and divers other Friends,
and taking coach for Nottingham, rode all night,
and arrived safely there about seven o`'clock in the evening of seventh day.

"`First-day, attended two meetings at Nottingham, both dull and exercising;
and my mind being low.
I was not faithful in attending to a gentle motion to appoint a meeting for the evening;
which brought condemnation and distress for some days.

"`Second-day, reached Ackworth in the evening,
and on third-day morning went into the several schools, where much decorum is observed.
The children appeared improving in the several branches of learning.
There are one hundred and eighty-three boys and one hundred and fourteen girls.
They are instructed to observe a time of solid waiting before and after meals,
when a great solemnity attended.
The house is exceedingly well calculated for the purpose,
and stands in a fine open fertile country.
So many children being trained up in a sober religious education,
as well as with suitable learning, seems likely to prove a blessing to religious society,
as well as to themselves as individuals,
and I hope will afford solid satisfaction to those who have the care of this institution.

"`Fifth-day, the children were examined, and two public meetings for worship held.
Lord Sidney was at the meeting this day and yesterday,
and his wife at the second meeting, as well as many others not making profession with us.
It was a solid meeting, and our friend John Storer was favoured in his public testimony.

"`Sixth-day, in company with Solomon Chapman, proceeded to Undercliffe,
and seventh-day to Settle, where I arrived much wearied.
I received a letter from my valued friend, Patience Brayton,
and a small addition by dear Rebecca Jones, which were very consolatory.
Five dear friends, viz: William Mathews, Zachariah Dicks, Patience Brayton,
Rebecca Wright and Ann Jessup, embarked on fifth-day evening from Gravesend,
in the ship Pigou, bound for Philadelphia.
May the Lord guide them in peace and safety to their native shore.

"`First-day, attended the meeting at Settle, which was a low suffering time to me:
it being their preparative meeting, the queries were read,
and divers observations made thereon, to excite Friends to an attention to duty.
A public meeting in the afternoon was rendered, through best help,
in a good degree satisfactory.

"`Fourth-day, proceeded through rain to Penrith, attended their monthly meeting,
and on fifth-day went to Carlisle.
Sixth-day I spent at Carlisle, preparing for my journey,
and towards evening went to the jail, and had some counsel to impart to the felons,
etc.`"

At the above mentioned monthly meeting at Penrith,
he laid before Friends a proposal for Thomas Wilkinson, of Yanwath,
in the neighbourhood of that town,
to accompany him in his contemplated arduous journey in Scotland,
having no other companion than David Ducat, who was considerably advanced in years.
The meeting agreed to the proposal,
and Thomas Wilkinson soon after joined him at Conheath, on the sea-shore,
arriving just in time to sit down with them in meeting.
As Thomas Wilkinson kept a diary of this journey,
which in some particulars is more full than that
of his meek spirited and diffident companion,
we shall diversify the narrative by extracts from it,
adding what may appear important from John Pemberton`'s own account.

Eighth month 7th; John Pemberton says:
"`My mind being very heavy all this forenoon and drawn to the village called Bridge-end,
near Dumfries, we concluded to return; and on our way we rode about six miles or more,
with one Stuart, a sensible, thoughtful man, who yielded to the truths we conversed upon,
respecting our religious principles,
and of calling the days of the week and the months according to Scripture,
saying that he had never before considered the propriety of it,
but acknowledged that it was most consistent.

"`Sixth-day, 10th; The provost of Dumfries having yesterday granted the town-hall,
a meeting was held this morning; in which my companion, David Ducat, had lively service,
though it did not please some formal, earthly, bigoted spirits, old in profession,
but not acquainted with the virtue, life and power of truth.`"

From Dumfries they proceeded to Ruthwell parish, and had a meeting;
in which John Pemberton says:
"`Much counsel in gospel love flowed to the people;`" thence to Mousewald parish,
where they were refused a barn to hold a meeting in, but at length procuring another,
the owner of the first, after the meeting, came and expressed regret for having,
through prejudice, denied it; after this they went to Bank-end, where, he says,
they could get no one to take them in,
and consequently had to go back to Ruthwell to lodge; but returning the next day,
they held a meeting, which "`was much crowded,
and favoured with the flowings of gospel love, which so opened the hearts of the people,
that they were desirous of our stay, and offered to provide us with lodging.

"`Fifth-day, went to Kiltown, but could not get entertainment,
the inn being taken up with visitors come to bathe in the salt water.
As it rained very hard we were obliged to go to the house of the tide surveyor,
where we were kindly received, and he granted his barn; where, notwithstanding the rain,
we had a pretty large meeting.
Before the meeting began, our friend Thomas Wilkinson, of Yanwath, Westmoreland,
came to us and brought me letters,
with comfortable news of the welfare of my dear wife.`"

First-day, had a meeting in the barn of a respectable widow at Lantonside;
"`where,`" says Thomas Wilkinson, "`perhaps between two and,
three hundred people collected, and behaved with becoming stillness.
Silence, which to them might be a new thing, appeared neither tiresome nor difficult,
and the meeting seemed to be a much favoured one.`"

John Pemberton says of it, that "`the Lord favoured,
and divers expressed their satisfaction, and that if we continued in these parts,
we should gather all the country;
little considering that two or three meetings held wholly in silence, would weary them.`"
Thomas Wilkinson adds; "`Another meeting was held in the evening;
after which John Pemberton took me with him to visit a person of some distinction,
who lived near, having a religious concern to speak to him;
but he avoided giving an opportunity, and went off; his wife, however, seemed respectful.

"`20th; Passed on through Dumfries,
and had a meeting in the evening in the parish of Glossburn;
but it was with the utmost difficulty that any place could be had to meet in;
and after some hours of fruitless application,
all that could be obtained was an old barn, of which part of the roof had fallen in.
It was trying to the natural disposition,
not only to go from door to door soliciting accommodation,
but afterwards to sit down amidst broken timber and the ruins of a mouldering building,
as spectacles to a wondering people.
But after humbly waiting for some time,
encouragement and peace seemed to spring up amidst these disheartening circumstances.
Jacob worshipped the Almighty while leaning on his staff,
and I believe worshipped him as acceptably as did
Solomon amid the splendour of his temple at Jerusalem.
My aged friends both appeared in testimony,
and John Pemberton seemed to be particularly favoured.

"`From Glossburn, on the 21st, we proceeded to Sanquhar,
where the people appeared to be settled in a suspicious ignorance, and where,
notwithstanding the mild exertions of John Pemberton, we were refused the townhall,
the school house, etc.;
and it was with some difficulty we even obtained a barn of our landlord,
though himself had come of Friends`' families.
John Pemberton felt sensibly such unkindness,
but his love to the people was still greater than his discouragements.
We gave notice of a meeting, which was attended by a tolerable number;
and wishing to soften the minds of the people, John Pemberton appointed another next day.
The people were still shy and unfriendly, though one young man of the medical profession,
showed some kindness.

"`23rd; Went to New Cumnock,
where again we took much pains to obtain a place to hold a meeting in,
but all seemed shut against us.
John Pemberton observed that he had never known it so difficult before.
We then went to a school a little way from the town;
the master said he would grant the use of the house,
but should like to have the minister`'s consent; to him we applied,
and found him rather a venerable looking old man.
John Pemberton informed him, that from a sense of duty and a love to mankind,
he had left his native country of America, and was come to see the people of this land,
and that if he pleased to consent to the schoolmaster`'s granting his school house,
we proposed to have a religious meeting there in the evening.
He replied, '`The people here are well informed,
and we have no need of you.`' John Pemberton said he had met with very kind and
liberal conduct from many persons of his profession in different parts of Scotland,
mentioning the names of several; that he, at this advanced age,
had come some thousands of miles to see the people,
and that he hoped he would consent to the request.
He then asked, '`What do you think of the sacrament?
What do you think of baptism?
John Pemberton replied, '`We think, with the Scriptures,
that it is not the putting away the filth of the body,
but the answer of a good conscience, that is essential;
and we are not concerned to turn men from form to form,
but to turn them to God.`' He answered, '`It will not do; it will not do:
I have read your Barclay, and do not like him;`' with other remarks,
that were such a violation of good manners, that I forbear to insert them.
After some more fruitless efforts, I returned to the schoolmaster,
and sitting down by him, began to converse on other subjects,
when he presently said we should have the school house;
and being told the time we proposed to hold the meeting,
he directed his scholars to spread information through their families.
A tolerable number assembled, who behaved well,
and the meeting was in degree satisfactory.
A young man, the old minister`'s son, and the schoolmaster,
came afterwards and spent the evening with us.

"`Went to Old Cumnock.
Similar difficulties continued in procuring a place to meet in.
At length some liberal-minded women accommodated us with a pretty large house,
where we had a crowded and satisfactory meeting;
in which John Pemberton was favoured in proclaiming many gospel truths.
He was often concerned to explain,
that true religion and substantial happiness consist not in speculative opinions,
but in purity, and in living under the cross of Christ,
in knowing our peace made with God, and feeling his love prevailing in our hearts;
and he generally enforced these truths by pertinent texts of Scripture.

It sometimes happened that we met with individuals,
who started objections to the principles of Christianity; on these occasions,
John Pemberton with serious firmness, assigned the reasons of his belief,
in the appearance in the flesh, of our Saviour upon earth,
and what he then did and suffered for mankind, and his spiritual appearance in the soul;
both which are not only to be sincerely believed,
but his refining power is to be felt and cooperated with,
that the corruptions of our nature may be done away,
and that we may be made followers of the holy pattern that was set before us,
when '`the Word became flesh,
and dwelt amongst us;`' and finally be made fit
inhabitants for that pure and heavenly kingdom,
where no evil can be admitted,
but the presence of the Father and of the Son will be enjoyed forever.

"`25th; Proceeded through Kilmarnock to Kilmaurs,
where we found it easy to obtain convenience for holding a meeting,
perhaps owing to John Pemberton`'s acquaintance with Alexander Munro,
who had served as a major in the British army during the war.
He procured the council house for us; where, on the 26th, we had two meetings,
Alexander Munro, his wife and family attending.
We spent the evening agreeably with him and his family.
John Pemberton`'s conversation was truly edifying,
opening our principles and the order subsisting in our Society, which were much approved.

"`28th; Passed through Glasgow to Kilpatrick.
Here we found a great change in the minds of the people:
we easily obtained a commodious room; the people seemed cordially disposed;
flocked round us, invited us to their houses,
and treated us with much kindness and respect.
A meeting was held on the 29th,
which several hundreds attended and generally behaved soberly.
It seemed to me the most favoured meeting we had held since I joined them.
The next day John Pemberton proposed holding one in the evening at Dunglass,
a village a little further.

Here we met with nothing but openness, civility and kindness.
A large body of people assembled in the evening, and were still and attentive;
many of them sat as solidly as if they had professed with us.
Both our friends were much favoured in public labour, John Pemberton remarkably so.
Towards the close of his testimony he drew an affecting description of his own situation,
and his motives for leaving his own country, saying that his beloved wife,
his native country and dear connections,
were as near to him as those of other men to them;
but the love of mankind and his sense of duty to the Almighty, prevailed over all.
He described this island as a highly favoured land,
whose received mercies call loudly for our gratitude;
for while surrounding nations had been visited with the sword, with pestilence,
with earthquakes, inundations and other calamities, this had been spared.
After meeting the people crowded round us; many were desirous of conversing with us,
requesting John Pemberton`'s company; with which he complied,
opening our principles among them, and exhorting them to a sober and godly life.

'`We entered the Highlands on the 31st,
after travelling through a mountainous and thinly peopled country,
where we met with many of the poor inhabitants
coming down to the lowlands against harvest.
We reached Inverary, from Carindow, at the head of Loch Fyne,
on the 1st of the ninth month, and were received with great openness.
On lirstday, the 2nd,
many of the Highlanders came from the mountains to their place of worship at Inverary.
There are, as I was told, two sermons commonly preached on first-days,
the one in English, the other in Erse or Gaelic,
which is the language of the Highlanders.
While walking round,
I was pleased and affected at the solid deportment of the Gaelic assembly,
which had collected to the amount of several hundreds,
and stood generally silent without doors, till the English sermon was finished.
We had our meeting appointed in a large room at the inn,
at the time the last might be supposed to conclude; the room was soon filled,
and many hundreds stood without.
The duchess of Argyle, with her son and daughters,
and several other persons of distinction attended; the duchess sat very solidly,
and her mind seemed to be thoughtfully exercised.
John Pemberton appeared with power and authority, both in testimony and prayer;
and though what he had to offer was in no way flattering to elevated stations,
when the meeting closed, the duchess came up and shook hands with him,
expressing her satisfaction, and making some friendly inquiries.
Another meeting was appointed at five o`'clock in the afternoon,
in a shed belonging to the duke.
I think nearly a thousand attended, and behaved with becoming stillness.`"

John Pemberton remarks, that "`it was a pretty open time;
some expressed their satisfaction,
and one man said he never knew his Saviour until this day.
The necessity of a regard to the grace of God that brings reproof for sin,
being the mercy and favour of the Almighty, was pointed out,
and that such who disregard its instructions,
are slighting the means offered for salvation, and thus rejecting their Saviour.
The people attended mostly in the Highland dress,
and many appeared with innocent countenances.
Taking a walk, after meeting, in the grounds of the duke,
I met with him and his three children, and two other persons.
He entered into familiar conversation, and spoke respectfully of our friends, adding,
that he had heard so well of the meeting, he was sorry he was not with us.
I gave him William Penn`'s '`Rise and Progress,`' to present to his wife.
He said he had read the small piece I had sent him,
(Randall`'s Account.) I told him I had also sent him a piece respecting the slave trade,
and wished him to join his influence for the suppression of so iniquitous a traffic.
He acknowledged it to be a bad-trade.`"

Thomas Wilkinson`'s account proceeds: "`3rd;
John Pemberton felt concerned to have another meeting, which,
in order to accommodate the poor labouring people, was appointed at six o`'clock.
The duke and duchess, with their family and visitors, attended,
and sat solidly amongst us.
I thought the meeting was very satisfactory.`"
John Pemberton says, "`The Lord in mercy favoured the opportunity;
for which may our minds bow in reverence.`"
"`David Ducat appeared,`" adds Thomas Wilkinson, "`with a convincing testimony,
and John Pemberton with great life and power.
The witness in several seemed to be reached;
the duchess in particular appearing to be much affected.

"`4th; Passed on to Lochgillphead; had an evening meeting there,
and another at eleven o`'clock next day.
After meeting we set off for Ormsay, and had a sample, for perhaps ten miles,
of ancient Highland road, which admits the travelling of but one person at a time;
we however arrived safely, and were received with true hospitality.

"`6th; Had a meeting in one of the barns of our kind host, captain Mac Laughlane,
of which he and his servants spread information round the neighbourhood;
but as in these parts not many understand English, no great numbers attended.
After meeting John Pemberton collected the captain`'s sisters, four agreeable young women,
and after a little space of silence, had some affectionate exhortation for them.
On the 7th, captain Mac Laughlane`'s younger brother, also an officer,
accompanied us some miles on foot; and we had a meeting at Tarbet, by Loch Fyne,
in the evening.

"`8th; Went to Campbell-town, where the provost granted the town-hall,
and we gave notice of a meeting to be held the next day.
When it drew near the time, we received a few lines from the provost,
expressing his fears that the crowd that might be expected would endanger the floor.
We had not time to provide another place,
so we concluded to offer ourselves at the public market-cross; it was a tall stone,
surrounded with steps; we went and sat down thereon in silence by ourselves.
In a little time the people began to gather round us, looking on one another and on us,
perhaps wondering what it meant,
as I believe no meeting was ever before held by any of our Society in these parts;
yet no scoffing or insult was offered us, nor any light behaviour observable.
Our minds were turned inward, and I believe,
experienced something of the promise made to those whose hearts are stayed on the Lord,
and who trust in him.

Though it was long before anything was said, refreshment and peace were experienced.
John Pemberton then in a lively manner exhorted
the people to become acquainted with their Maker,
and be at peace with him.
The day was very hot, and John Pemberton was ready to faint,
from being exposed bare-headed to the sun.
Another meeting was appointed for the afternoon,
and a green that lay before the '`kirk`' was recommended as a suitable place.
I went to place some chairs, and the crowd that surrounded and followed me was very great.
I believe that in a few minutes after my friends took their seats,
nearly fifteen hundred assembled.
Many were on the walls and on the neighbouring trees; a general stillness prevailed,
and it was not long before way opened with John Pemberton for religious communication.
Though I am fearful that what was delivered could not be
distinctly heard by the most distant of the assembly,
yet no disorder ensued;
and I trust we were thankful to the Father of mercies and Fountain of good,
for preservation and peace amidst such a host of strangers.`"

12th; John Pemberton remarks: "`Divers came to the inn, and we parted solidly,
having their wishes for our preservation.
After dinner, finding our way open to the southward, we proceeded to Southend,
near the Mull of Kintire; and there not being accommodation for us at the small inn,
we were kindly received by the minister, David Campbell, an aged man, and blind.
He expressed much regard for our religious Society,
believing them to come nearer to the primitive Christians than any people on earth.
We lodged at his house, being introduced to him by his son-in-law,
major Archibald Campbell, of Campbell-town, who met us on the road.
He had been in America during the troubles, and had a favourable opinion of Friends.`"

13th and 14th; They had two meetings there and one at Nockney hall, in a mill.
They lodged on the 15th at the house of a poor farmer,
whose family was religiously disposed, and entertained them kindly.
It was the practice of this family to assemble together, both morning and evening,
at which times they sang a psalm, read a chapter in the New Testament,
and afterwards kneeled down to prayers.
When these were concluded, on this occasion, the master of the family said,
that if our friends had anything to communicate, they were ready to hear it;
on which John Pemberton remarked, "`that he was concerned to caution them,
lest such religious practices, if unattended by correspondent feelings,
might degenerate info a form.`"
On the 17th they had a meeting at Tynelane, and on the 18th another at Southend,
John Pemberton not having been able to feel his mind quite clear of that parish.
In the evening, being at David Campbell`'s, his daughter said to John Pemberton,
"`You see, Mr, Pemberton,
father has given you his '`kirk`' and attended you several times;
suppose you go to church on Sunday, and hear father:
we have some elegant preachers in the Highlands.`"
To which John Pemberton gravely replied,
"`We have a testimony to bear against a hired ministry.`"
Thomas Wilkinson remarks, that when they came to take leave of this hospitable family,
it was "`with some tenderness on both sides.
Margaret Campbell, the daughter, observed that it was hard to have such guests,
and never to see them more.`"

21st; Thomas Wilkinson`'s account proceeds: "`Rode to Lochgillphead.
About noon a terrible hurricane arose;
two vessels from Loch Fyne were riding at anchor in sight; one of them broke loose,
struck on a sand bank and filled.
The seamen belonging to the other, except a little boy, were on shore.

To go to their own vessel seemed impracticable:
they often attempted to fetch the men from the other,
but the waves as often heaved the boat on shore again.
Many people were on the beach; and the lamentations of the women were pitiable.
We exerted ourselves; and after dragging the boat along the shore to another point,
the seamen were able to bring off the hands from the nearest vessel:
all our concern was now for the boy.
I proposed dragging the boat along the shore, perhaps almost a mile,
to a situation whence it might be driven by the waves to the other vessel;
the seamen however did not adopt the proposal,
and the dark shades of the tempestuous night closed on the poor boy.
The reflections arising from this circumstance spread a sadness over our minds,
and when day broke in the morning it was perceived that the vessel had gone down.`'

"`22nd; Proceeded to Goatfield, and were kindly entertained by Joseph Latham,
superintendent of the Argyle iron works.
We had two meetings next day at this place.
On the 24th we proceeded to Aroquhar, where on the 25th we had a meeting,
a solid and favoured opportunity; and after dinner we travelled a few miles to Luss,
where we had a meeting in the evening, attended by a considerable number of people.

"`26th; We had now rode an hundred miles on our return towards England,
partly on account of David Ducat`'s poor state of health; he, however,
now seemed recruiting; and John Pemberton`'s prospects opening northward,
we had a meeting in the evening at Tarbet, by Loch Lomond;
which was at first much unsettled by the disorderly conduct of a person in liquor;
but having placed him in a chair, and taken my seat by him, he became still,
and the meeting issued favourably.

"`27th; Proceeded to Tynedrome, and had a meeting there;
a good degree of solemnity was experienced in the time of silence.
I thought it one of the most satisfactory meetings we had had;
and I believe we rejoiced in humble thankfulness that our heavenly
Father had refreshed us together with his good presence,
and filled our hearts with his love and the love of our fellow creatures,
in such a poor solitary part of the earth.

"`28th; Passed on to Dalmally, a pleasant and populous vale in Glenorchy.`"
Here they had a meeting, and John Pemberton remarks:
"`The Lord was graciously pleased to favour,
so that the gospel was preached under its enlivening influence.
The people behaved well, and the minister of the parish, Joseph Mc Intire,
was very respectful, and invited us to his house.
He made inquiry respecting some of our principles, which we explained to his satisfaction.
He was of a very open disposition,
and liberal in his sentiments respecting the universality of God`'s love.
He, with his wife and several of his children attended the meeting, and sat very solidly.
In conversation he lamented the lightness that he had
observed in England in time of public worship;
which is too often the case.
He inquired of me respecting the practice of asking a blessing before meat.
I told him our views, which both himself and his wife acknowledged to be right,
and he confessed that too little thought often attended when grace, so called,
was said.`"
Thomas Wilkinson remarks, respecting this minister`'s wife, that she "`was a plain woman,
and when we were on the subjects of an hired ministry, war, etc.,
notwithstanding the profession of her husband,
and that she had a son or sons in the army, she was unequivocally of our opinion,
and spoke her sentiments without reserve.

"`29th; Set off for Bunawe at five o`'clock in the morning; passed on to Lorn Furnace,
and took up our lodging at the house of John Satterthwaite, who, with his wife,
were the only members of our Society in the Highlands of Scotland.
The next morning many came several miles to the meeting;
lakes and arms of the sea run up here among the mountains in various directions,
which the people were seen crossing in boats from different quarters.
A considerable number assembled and behaved with remarkable solidity;
and though it seemed scarcely reasonable to suppose
that any of them had been at a meeting before,
yet they sat as still and orderly as if they had been trained up amongst us.
It is often no easy matter to make strangers feel the
propriety of waiting in silence before the Lord.
As the outward order of society sometimes suggests hints that lead towards Divine truths,
it is remarkable that the various professors of
Christianity have not more frequently discovered,
that the servant who waits in silent attention on his Master,
is the most likely to discover his will.
Thus it appears to me that the most acceptable homage to the all-seeing,
all-knowing Master and Sovereign of the universe,
is a waiting in humble reverent silence before him:
and when we meet for the purpose of worshipping him,
instead of rushing into his presence with speeches of our own contriving,
the fruits of our own self-sufficiency,
that it is more pleasing in his sight to wait in all humility and singleness of heart,
to feel his love operate in our minds and his good Spirit refresh our hearts.
Thus would his worship, whether in vocal homage, or silent adoration,
be an offering of his own preparing, and acceptable in his sight;
and while such a disposition prevailed, even if he saw meet,
for the trial of our constancy, to withhold his sensible presence from us,
I have no doubt that our patient dedication of heart would be well pleasing to him.

"`Tenth month 1st; We set off for Fort William,
and crossed some lakes and arms of the sea.
Here the females are employed in the most laborious exercises;
we were rowed over lakes and arms of the sea by women, who,
when we and our horses were on board, would plunge into the water, push off the boat,
and then spring with cheerfulness to their oars.
We had proceeded about ten or fifteen miles,
when John Pemberton consulted us about returning back a few miles.
He said he had felt a concern to visit a place we had passed, yet, wishing to get on,
had not discovered it to us; but that it now felt so heavy,
he hardly seemed able to proceed.
We returned; and towards evening finding ourselves among poor huts,
without inn or place of accommodation where we could lodge,
we observed Loch Nell house at a distance, towards which we rode.
After alighting, being shown to where the venerable owner,
the widow of Sir Duncan Campbell, stood overlooking some workmen,
John Pemberton told her he had '`a favour to ask of her;`' and on her inquiring what,
he replied, '`only a night`'s lodging;`' to which she answered courteously,
'`you are very welcome to that.`' She entertained us with great kindness,
and soon discovered to us that she was a niece of May Drummond`'s,
and had seen much of Friends.

We had a satisfactory meeting in one of her offices in the morning, herself,
family and servants attending.
Immediately afterwards I set off for Cragnook,
to make preparation there for a meeting in the evening,
and easily obtained all the accommodation that could be had; but it was a poor place.
I rode among the little huts for many miles, but many could give me no answer at all,
and some shook their heads, and could just pronounce,
'`no English.`' A few persons gathered in the evening,
and after meeting we returned to Loch Nell.
It was dark; we had a little arm of the sea to cross, and the tide was in;
but protecting Goodness seemed to attend; for though it was deep,
we rode through in safety, and arrived about eleven o`'clock at night.

"`3rd; Passed on to Portnacrash, where we had a meeting in the evening.`"
John Pemberton says on this occasion,
"`It was not pleasing to be prevented from pursuing our journey;
but a fear attended my mind that I should not be easy if I left the place,
though in deep poverty.
The meeting was attended by divers of the principal people hereaway,
and the Lord in mercy condescended to favour, so that it yielded satisfaction to many,
which was freely expressed.`"

Thomas Wilkinson says:

"`4th; We entered Lochaber, and proceeded to Fort William.

"`5th; Had a meeting at eleven o`'clock, which a considerable number of people attended.
David Ducat appeared largely in testimony, and in a line so singular,
that I was somewhat apprehensive of the consequences.
We were now among the clans of Cameron and M`'Donald, which rose in the rebellion of 1745.
The conduct of such as rose up against their lawful sovereign was fully displayed,
and it was remarked,
that outward allegiance might be observed by those who are rebels at heart;
but that this sort of conduct could not impose on the King of Heaven.
There were some present who had been in the rebellion; however, the meeting was quiet,
and afterwards, John Pemberton was remarkably favoured in testimony.
I never remember his thus appearing with greater life and power.

"`The evidence of truth prevailed over error and prejudice;
for some who entered the meeting scoffingly, soon became serious,
expressed their satisfaction afterwards, and showed us much kindness and attention.
The governor, who had attended the meeting,
engaged us to breakfast with him next morning in the fort.`"

John Pemberton remarks:
"`Near Ballahulish,`" where they breakfasted on their way to the fort, "`is Glencove,
where about seventy persons, of the M`'Donald clan,
were murdered by order of King William.
The officers who commanded, were playing at cards with some of the party,
before they committed this horrid crime.
One child, being at some distance, escaped,
and was grandfather to the mistress of the inn at Fort William, who, with her husband,
Donald Cameron, was very respectful to us while at their house,
and parted affectionately,
he saying he had not had so much satisfaction with any guests since he kept an inn.
In the morning we breakfasted with the commander of the fort.
Captain Cochran, who, as we had spoken to him the evening before,
summoned the soldiery to attend a meeting this morning in the barracks,
which through mercy was also favoured.
This Capt.
Cochran was wounded at the battle of Bunker`'s hill,
and has now one ball remaining in his shoulder, and another in his thigh.
He told me he had on a short waistcoat, which had fourteen shots through it.
One lodged in his body, but was extracted.
I reminded him that it was a miraculous escape, and should be remembered.
He acknowledged that he should be very ungrateful, were he to forget the mercy.
He seemed reached by the visit, wished us well,
and wrote by us to the governor of Fort Augustus, whither we were going, to recommend us.
We reached Fort Augustus in the evening, and soon after,
myself and Thomas Wilkinson waited on the governor, Alexander Trapaud,
who received us kindly, and said he would order a place for us to hold a meeting in.
His wife is a descendant of the Barclay family, by a Cameron;
and five or six of the descendants of Robert
Barclay were at the meeting at Fort William.`"

Thomas Wilkinson adds:
"`The weather had been uncommonly fine during our journey through the Highlands,
yet we beheld large quantities of snow in the cliffs of Ben Nevis,
so that I presume on these mountains it never entirely dissolves.
We also saw this day, many poor huts, entirely built of and covered with sods.
Oh! ye that solace yourselves in your costly apartments,
while you tread the softest carpets, or press your beds of down,
remember the poor Highlander, who sits on the earth,
or stretches his weary limbs on the hard heath gathered from the mountains.

On first-day, when their minister had finished,
the governor gave information to the people of our intended meeting,
and sent us word immediately.
On our arrival we found a large and orderly congregation;
amongst whom several gospel truths were published.
John Pemberton appointed another meeting in the evening,
and intimation being given to the officers that
the company of the soldiers would be acceptable,
they gave directions that they should attend.
The soldiers had received orders to march next morning,
in order to embark for the West Indies.
John Pemberton was much enlarged in testimony amongst them;
the season seemed like a farewell;
he signified that he had often felt a near regard for soldiers,
and intimated the uncertainty of life to all men,
more particularly to those in their situation;
and he affectionately recommended them to have the fear of God,
and the thoughts of their latter end, daily before their eyes.

"`8th; We passed through Strath Errick, which is the Frazers`' country,
and arrived at Inverness in the evening.
John Pemberton had been at Inverness two years before, and from what he suffered there,
he owned, that as a man he had rather have rode five hundred miles another way,
than visit it again; yet the drawings of duty seemed to lead thither,
and to these he gave up.
A large and respectable company collected the next day, and behaved solidly.`"
John Pemberton remarks, "`The meeting was owned by the Master`'s countenance and presence,
and the people were dealt plainly with.
We appointed another meeting at six o`'clock in the`'-evening, which was more crowded,
and was a satisfactory opportunity.`"

Thomas Wilkinson adds,
"`I believe that in the evening my friend possessed himself in peace,
which was a lesson of encouragement and instruction;
for though the way of our duty is sometimes covered as with tempests and with clouds,
yet, if we advance with all humility as to ourselves, and with confidence towards God,
the light of his favour will often disperse the darkness,
and we shall journey forward in peace.

"`We were about to take leave of the Highlands,
which is perhaps as rugged a country as is inhabited by man,
but where we might acknowledge we were favoured, both outwardly and inwardly.
The hospitality and kindness of the inhabitants more than
counterbalanced the unpromising aspect of the country:
their respectful attention, their open and susceptible minds,
ready to receive religious communications,
together with the gracious ownings of His presence,
whose cause we were endeavouring to promote, were sources of comfort to us,
that cheered our passage through these comparatively solitary regions.

"`11th; The day was very stormy.
An affecting account came in the evening of six
men being drowned in ferrying over a river,
the passage of which we must have attempted, if we had gone forward.

"`12th; Passed to Elgin, where we had a meeting; after which we proceeded to Cullen;
and on the 13th rode through Banff to Macduff,
where John Pemberton had held a meeting before, but had left the place uneasy.
We met with considerable openness, and appointed a meeting;
a number of solid sober-minded people attended, and the meeting was satisfactory.
In coming along, John Pemberton had observed White-hills, a fishing village,
which he was desirous to visit;
so I returned a few miles to procure accommodation for a meeting, and to give notice.
I was received at first agreeably by the people to whom I was recommended;
but on mentioning my profession and errand, they showed considerable dislike;
the mistress of the house observed with some warmth,
that they would have nothing to do with either Quakers, clergy, or bishops,
or any such people.
However, after some further conversation and explanation, way opened.
The prejudices we had to combat as we passed along,
were among the difficulties of this journey;
and it was sometimes even difficult to preserve becoming seriousness,
on hearing the people relate the strange and
unaccountable ideas they had formed of our Society.
Whatever use might arise from the labours of my friends
in promoting a reformation of life among the people,
and in making them more acquainted with the means of salvation,
I believe this journey might have use in removing a load of prejudice from their minds,
and opening a door to future labour, if called for by the Master of the harvest.
I returned to my companions at Macduff,
where we had the most crowded meeting in the evening I remember to have seen in Scotland;
the people were remarkably still, and John Pemberton was livingly opened in testimony.

"`14th; At ten o`'clock a meeting was held at White-hills, in a new unfinished house,
which was entirely filled; some sat on beams above, and many were without.
David Ducat appeared in an informing testimony, as did John Pemberton,
who was remarkably favoured.
Another was appointed in the afternoon.
Five serious young people came from Banff on purpose to attend the meeting,
and stayed the second, which was crowded, but orderly.
It was agreeable to find an alteration take place in some minds.
Our landlady, who was so odd in her remarks yesterday, now treated us with much kindness,
and in taking leave of us, expressed her earnest desires for our welfare.

"`15th; Proceeded to Old Meldrum,
where we were once more refreshed with the sight and society of our Friends.

"`16th; Rode to Aberdeen.
Ancient Robert Hervy, nearly eighty years of age,
walked eighteen miles through the rain to the half-year`'s meeting:
he seemed to possess an innocent green old age.

"`18th; On this day was their half-year`'s meeting.
Much business came before them, and it was satisfactory to see the honest care of Friends.
In the evening, at John Pemberton`'s request,
several Friends of the half-year`'s meeting had a solid conference.
He informed them that without a full sense of his services being completed in the north,
he had come above a hundred and twenty miles to that meeting.
He still found a concern lie with weight on his
mind to visit the northernmost part of Scotland;
but to return at this advanced season of the year into such a country,
seemed at the hazard of life.
He wished Friends to feel with him, and communicate their sense freely,
for it was a matter of great weight.
Friends, from outward appearances, mostly discouraged the undertaking,
for all the passages through the northern country were
frequently blocked up with snow for many weeks together;
yet they left him to Divine direction and the feelings of his own mind,
expressing much sympathy with him, and being sincerely desirous of our preservation.
Though it was to myself a serious thing to be confined for
months together in the impassable valleys of Caithness,
yet I felt resigned to go north or south.`"

The weather being very wet, they stayed in and about Aberdeen a few days to rest.
On the 23rd they left that city, attended the meeting next day at Killmuck,
and on the 25th arrived at Old Meldrum again.
On the 26th the weather became exceedingly cold, with a severe frost,
and John Pemberton began to feel some symptoms of indisposition.
Though he had felt resigned to proceed northward,
yet he now found some relief from the undertaking for the present,
and they set their faces again towards the south.

On the 29th, Thomas Wilkinson says, "`We passed Urie to Stonehaven.
Something of a sorrowful feeling accompanies the
survey of places once the residence of wisdom,
piety and virtue; especially when no traces are found of the former inhabitants.
Such was the reflection in passing Urie;
and we were not much comforted by what we found at Stonehaven,
but our sorrow was more mingled with commiseration.
We visited the poor scattered remains of our Society there, seven in number.
We found them weighed down by the pressure of poverty;
their children had left them and the Society together;
and there remained scarcely a comfort of life to cheer their old age.
John Pemberton entered feelingly into their situation,
expressed his solicitude for their eternal welfare,
and administered to their outward necessities.
Ah! ye that dwell in remote and lonely situations,
let me recommend to you the dwelling near that Power that will preserve and support you,
and be the means of your present and everlasting comfort.
Ye too, to whose lot is committed the care of rising families;
endeavour to cultivate in the tender minds of your children
the precious seed sown there by the hand of Divine Goodness.
You will not, perhaps, then be deserted in your old age;
neither would the places where righteousness has flourished,
so soon become barren and desolate.`"

John Pemberton says with respect to this remnant at Stonehaven;
"`We found them aged and very infirm, and not able to meet together;
three of them were so deaf that we could not make them hear; one was blind,
and all were poor, inwardly and outwardly.`"
He adds; "`On third-day we proceeded through rain and fog to Inverbervie,
and feeling some draught for a meeting, concluded to stay there.
The meeting was held in the townhouse, which was filled.
It was a favoured opportunity.
The priest was present.
Something was said respecting ministry,
though I was then ignorant of any professing to be ministers being present,
except my companion and myself.`"

On the 1st of the eleventh month they entered Montrose, where they held two meetings,
and then passing through Brechine, Johnshaven, a village on the sea-coast,
St. Siris and Dundee, at all which places they had meetings,
they reached St. Andrews on the 7th. They had a meeting with
the inhabitants that evening and another the next day,
respecting which latter, Thomas Wilkinson says;
"`A great number of persons were at the meeting,
and I trust it was attended with increased solemnity.
My friends were enabled to labour in the life, among an attentive and solid people.
Though we were now among colleges, professors, and the learned,
yet we found much openness as well as kindness.
John Pemberton had found his mind particularly drawn to this place;
we approached it with some degree of awe;
yet our visits to few places were more agreeable and satisfactory.
St. Andrews is a place with its buildings in ruins:
other places in Scotland have had their cathedrals of considerable splendour,
particularly Elgin and Arbroath, which are now demolished and deserted.
Splendid edifices for public worship seem to be more likely to excite
admiration in the minds of the audience for the ingenuity of the artist,
than to dispose the people to that humble frame of mind,
which becomes them when assembled before the Lord.
Christianity enjoins an inward and spiritual worship;
and ought not its accommodations to partake of its own simplicity`'? Perhaps
it is the vanity of man that pretends to assist the cause of heaven,
in building palaces for men to humble themselves in; perhaps, too,
it is his pride that pulls them down with such
fury as was used to the places I have mentioned.
The ostentation that built, and the religious fury that demolished,
might be equally remote from true and unaffected piety.

"`9th; Leaving St. Andrews my companions rode to Cupar.
I went a few miles another way, to a place called Leuchars,
to make preparation for a meeting on first-day;
but I found it difficult to obtain a place.
Among others I applied at a school; but the master,
with looks of bitterness that I cannot easily forget,
shut the door in my face without giving any reply, while I was explaining my errand.
I was not, however, discouraged from further applications, and went to the castle.
The master was not at home, but his wife cheerfully granted me a large barn.
I then spread information, and leaving the place, joined my companions at Cupar,
where we had a meeting in the evening.

"`10th; Rested.
Being the fourth day of resting since leaving England.

"`11th; Set off for Leuchars.
As we approached the place, we saw a large crowd assembled about the barn,
to all appearance a mob.
As we entered, they seemed a rude tumultuous set of people, amongst whom, however,
we were mercifully supported.
Their disorderly behaviour suddenly subsided, they became settled and still,
and it proved a very solid and satisfactory meeting; for, as if in an instant,
the minds of the people seemed prepared to receive the
gospel truths that were largely spread amongst them.

"`12th; We went to Pittenweem.
The magistrates were very shy of granting us the town-hall;
I believe that I waited five or six times on them before it was obtained.
We had two meetings there on the 13th, and way so opened,
that we met with some remarkable instances of kindness.`"
John Pemberton observes, "`The meetings were large,
many of the principal inhabitants were present, and the Lord in mercy favoured.

"`14th; Moved on to Anstruther, and obtained their Town-hall, where we had a large,
but rather unsettled meeting, chiefly from a general thoughtlessness about religion.
We had another in the evening; full as many attended,
and their behaviour was perhaps rather improved;
though they still appeared to have much to learn of religious seriousness.

"`15th; We went to Crail, where the people, we were informed, were dark and bigoted.
We easily, however, found entrance among them, and had a meeting in.
their town-hall at twelve o`'clock, which was very full.
The people seemed rude and undisciplined; but after they got settled, behaved tolerably,
and another meeting was appointed at six o`'clock.
The assembly in the evening, with some small exception, was one restless crowd,
which it was difficult to impress with any ideas of seriousness or order.
John Pemberton informed them, he had held meetings with the blacks from Africa,
and the Indian natives of America, men accounted heathens and savages,
but had never seen any thing like such behaviour in them.
The people were at one time so unsettled,
that when he rose to deliver what came before him, he was obliged to sit down again.
However, at more quiet intervals, he was enabled to discharge his duty among them.

"`16th; We were now drawing near Edinburgh,
and John Pemberton finding himself almost worn out with exercise of body and mind,
proposed our going thither to rest for a few days.
We passed through several towns and villages which he had mostly visited before;
and arriving at Edinburgh in the evening,
were kindly received by our friend George Miller,
at whose house we rested about ten days.
But though we ceased from travelling, the service of John Pemberton was not suspended.
His love to Friends, and care for the good order of the Society,
were manifested during our stay.
We attended the monthly meeting of Edinburgh, in which his labours were serviceable.`"

In reviewing the late journey, John Pemberton remarks in a letter to his brother,
"`It is fifteen weeks since we entered Scotland,
in which time we have attended one hundred and thirteen public meetings.
The weather for six weeks has been very wet;
I believe that during five weeks my great coat was not for six days fully dry;
yet I have been preserved from taking much cold, which is a great mercy.
But I wanted to be a few days at a Friend`'s house,
for I have little satisfaction at taverns,
and until we came here we had but four days cessation from meetings or riding,
in the fifteen weeks, which is trying to nature; yet the Lord in mercy hath upheld,
and made way for us in every place.
Since we left Aberdeen,
we have been mostly among fishermen and those who reside on the sea-coast.
The meetings have been large,
but many of the people more raw and undisciplined than among the Highlands.
I have now been nearly round Scotland; yet there is work enough for a year or two more;
but if it be the Lord`'s will to release me, I shall consider it a mercy.

"`26th; Thomas Wilkinson proceeds.
Had two meetings at Musselburgh; but little openness appeared in the people,
and perhaps they were seasons rather of exercise than of refreshment.

"`27th; Went to Preston Pans.
A considerable number of people assembled;
and another meeting was appointed at eleven o`'clock next day.
But few attended, and the conduct of some was painful; yet gospel labour was bestowed,
and John Pemberton closed the meeting in fervent, living prayer.
We had intended after this to leave the place,
but John Pemberton still felt a compassionate regard for the people,
and found his mind oppressed when about to leave them;
so we gave notice of another meeting in the evening, which was more fully attended,
and accompanied by more becoming behaviour,
though without doors there was much rudeness.`"

We may now resume John Pemberton`'s own account of the remainder of his journey.

On the 29th they arrived again in Edinburgh, and attended the mid-week meeting,
John Pemberton`'s mind being in a low proved state,
desiring to be released from this arduous field
of labour in which he had been so long engaged,
yet not daring to withdraw himself without an
evidence of the approbation of the great Master.

"`On sixth day,`" says he, "`my companions desiring to proceed for England,
I set out with them, though my mind was loaded, and I could not see my way thither;
and it growing more heavy the further I went, returned the next day,
having rode to Selkirk and back unprofitably.
At Selkirk I parted with my kind friend Thomas Wilkinson, he proceeding homeward,
and myself with David Ducat returning to Edinburgh.

"`Fifth-day morning, had a long cold passage across the Firth,
and it was eleven o`'clock at night, before our horses were landed.`"

They visited Levin, Dysert, St. Andrews, and a few other places, having several meetings;
then returned to Edinburgh; and afterwards finding a liberty to leave Scotland,
passed through Kelso and Carlisle, and arrived at Wigton on the 26th of twelfth month.
The next day was the quarterly meeting for Cumberland; "`which,`" says John Pemberton,
"`I hope was to edification.`"
He continued during the winter visiting meetings in Cumberland,
Westmoreland and Lancashire,
at some of which he mentions having the company of Martha Routh,
William Jepson and Thomas Colley.

About this time he received a letter from his
valued friend and fellow-labourer in the gospel,
Samuel Neale, who was then in a declining state of health.
After mentioning his bodily afflictions, he instructively remarks:
"`I find the '`Ancient of days`' near me at times, and when this is the case,
I feel neither sickness nor pain.
I have much pleasure in reading and looking into the steppings of the flock
and companions of Christ in the morning of our day +++[+++as a religious Society.]
Alas! what did they go through and suffer.
I often wish that the present generation would look into the experience and
sufferings of those who loved not their lives unto death,
who were champions in the Christian warfare,
and turned not their backs in the day of battle,
who bore the burden and heat of the day,
and smoothed our path in the wilderness of this world.`"

John Pemberton was much interested in the subject of the abolition of the slave-trade,
which was now taking deep root in the minds of serious and enlightened people in England,
chiefly owing to the exertions which had been made by members
of our religious Society to spread correct information and
encourage a sound tone of sentiment on that affecting subject.
Lindley Murray, who then resided at York, wrote to him about this time,
that "`the cause of the poor blacks gains ground in this nation.
Several great men have earnestly espoused it,
and a respectable member of the house of commons, +++[+++William Wilberforce,]
has given notice of his intention to bring in a bill for the prohibition of the trade.
I understand that he was joined by Fox,
and that he is a particular friend of the minister, Pitt.
The intent of the bill is to make it felony for any British
subject to take a negro from Africa without his consent.`"
His frequent correspondent, George Dillwyn, who was then in London,
also alluded to the subject, referring, however,
to what was then taking place in their own land, in the following terms:
"`I note among other articles of intelligence,
that the convention have proposed to preclude the new congress
from interfering with the slave trade for twenty-one years,
after all their pretended respect to the natural and unalienable rights of mankind,
and so much light being thrown upon the subject of slavery.
How can such a provision be considered otherwise than as a
designed sanction to every crime which that trade involves,
and a setting at naught the Power to which, in their late contest with Great Britain,
they so solemnly appealed for the sincerity of their motives?
As a part of the people who are to be bound by the new system,
I hope Friends will find it their duty to enter a timely and full protest; for,
though they may not succeed to their wish, it is of importance to be clear,
and if they have not omitted their duty, the retrospect may afford satisfaction.`"
John Pemberton remarks: "`I think it is wisdom in Friends,
to avoid mixing with the fluctuating state of
affairs and the political debates of the people;
yet,
when such glaring contradictions appear to their former declarations respecting freedom,
it may be proper deeply to consider what Truth might lead to,
in showing our disapprobation of such unjust conclusions.`"

About the 1st of the fifth month, 1788, taking a southerly course, he went to Stockport,
and attended the burial of the wife of George Jones: "`they had,`" he says,
"`been married but about eighteen months; many of the town`'s people came in;
and though their expectation was too much outward, the meeting was in measure favoured.
Then I proceeded towards London, and lodged at Chapela-Frith.`"

Thence passing through Stoney Middleton,
situated in a wild and beautiful part of the mountainous country of Derbyshire,
and through the forest, from Mansfield to Nottingham, he reached London on sixth-day,
the 9th of fifth month.

"`Second-day was the yearly meeting of ministers and elders,
in which Rebecca Jones expressed to Friends how she had
been employed since the last yearly meeting,
and that though she did not yet see the time of her embarking,
she expected her visit was nearly closed.
A solid covering attended the meeting, and she had, in a close manner, to give counsel,
reciting the words of the apostle respecting such who were once quickened,
had tasted of the heavenly gift and partaken of the powers of the world to come;
that if these fall away, it is impossible to renew them again unto repentance,
seeing they have crucified to themselves the Son of God afresh,
and put him to open shame; but she added, that though impossible with men,
all things were possible with God.

"`In the afternoon the business of the yearly meeting was entered upon,
after some profitable labour from John Storer and Samuel Neale.
This meeting continued until the 20th; it was large,
and attended by many solid Friends from various parts, both male and female,
and a very hopeful appearance of the beloved youth.
There is an increasing zeal and concern for the support
and well conducting of the discipline of the church;
which, however, wants care in many places,
There are many who love ease and are earthly-minded.
Some are groaning under a sense of weakness and
a wrong spirit bearing sway in some meetings,
and would be glad of help: but others do not desire to be aroused,
or turned out of their old way.
A suitable minute was made to authorize meetings to deal with and
disown such as are concerned in the disreputable species of gaming,
called stock-jobbing, which has brought many families to poverty,
and much disrepute upon Friends, through the conduct of some professing with us.
Many observations were also made on the evil of drawing and redrawing bills,
which practice had occasioned much reproach.`"

After the yearly meeting, in company with some Friends,
he passed into the counties of Essex, Suffolk and Norfolk,
attending the quarterly meetings at Ipswich and Norwich,
and having appointed meetings at a number of other places in those parts.
At Holt, he says they attended the meeting on sixth-day,
which was a favoured opportunity; and remarks,
that although but two men and no women belonged to this meeting,
yet they regularly met twice in the week for the purpose of Divine worship.
After this, he says: "`We proceeded to Wells,
and a meeting having been appointed at six o`'clock, it was filled with many sober people;
but their minds being much outward, it was held a considerable time in silence.
At length John Abbott had a little seasonable matter,
and afterwards I had something to offer,
and the latter part of the meeting was favoured.`"

Thence he passed through Lynn Regis, Lincoln, Broughton, Gainsborough, etc., to Beltoft,
which he describes as "`a poor and almost forsaken meeting.`"
Afterwards he went to York to attend the quarterly meeting for that county;
thence through Darlington, Durham, etc., to Kendal,
where he attended the quarterly meeting for Westmoreland,
and had the satisfaction of meeting with his beloved friend and fellow-labourer,
James Thornton,
who had just landed from America on a religious visit to some parts of Great Britain.
From this time they travelled much together,
having near unity and sympathy for each other.
From Kendal they went to the general meeting at Preston Patrick,
thence to Lancaster quarterly meeting, whence passing to Settle,
they travelled through Yorkshire, having a number of meetings at divers places,
and arrived on the 2nd of eighth month at the house of Thomas Colley at Sheffield.
This dear Friend had been now some months returned home from
an arduous journey in the service of the gospel in America.
At this place John Pemberton writes as follows:

"`Eighth month 4th; We were last week at Ackworth,
and united with a committee appointed to inspect the Institution.
Upon the whole, it is wisely conducted.
The girls`' schools are in excellent order, there being one hundred and six girls,
under the care of religious and well qualified teachers.
All the departments under the matron`'s care, are neat and clean and in regular order,
as is also the farm; though it requires great labour and attention to keep things so.
The prospect is pleasing,
of so many youth likely to be trained up in discipline
and with a sense of religion impressed on their minds,
as well as to be instructed in outward learning.

"`Ninth month 1st, at Ives, in Huntingdonshire.
I have hitherto been mercifully preserved under conflicts of various kinds,
often wading under much discouragement, weakness and poverty, and,
since the last yearly meeting, much bodily weakness.
I have now been obliged to lay by for ten days at Oakham in Rutlandshire,
whence I moved hither, to the house of John Abbott, who went with me the first time,
to the Orkneys.
I am now much better, the cough is almost gone, and the fever much moderated;
though I am still very feeble.
While I was encountering many outward hardships
and difficulties among rocks and mountains,
and islands, the Lord mercifully preserved in health,
and sustained the mind to persevere and press through;
but now in passing along with less of outward hardships and difficulties,
I am more feeble in body, and also in mind; but I labour to keep in the patience,
and have many friends who deeply sympathize with me.

"`Dear Rebecca Jones embarked on the 13th ult.
on her return, and it was satisfactory to find she was favoured with much peace,
and an evidence that she embarked at the right time.
She had been wonderfully upheld, preserved and furnished, through her journey;
and knowing whence come wisdom and strength to labour rightly, was kept humble,
and ascribed the praise to the Lord, unto whom it belongs.
She loves to see the Lord`'s children walking in the truth,
and the professors of the light walking in the light.
I often sympathize with the burden bearers,
and wish them strengthened and preserved from dismay:
it is a great favour for each to mind his own calling,
and to labour to fulfill his respective duty.
If such who have been called are not faithful, the loss will be their own.
Had I been more attentive, more faithful and diligent,
the crown would have been more weighty.
I have nothing to boast of, but am often humbled under a sense of my frequent failures;
but the Lord hath been, and is, very merciful.

"`I am sorry to find that a vain parade has been
countenanced and promoted in my native city.
Excess in vanity is very prevalent in this highly favoured island.
As favours from on high are multiplied, so are the minds of the people captivated,
indulging in abundant vanity, folly and wickedness.
Boxing upon stages, whereby several have been killed,
is one among the scenes of brutality, which of late have been much promoted,
to the reproach of the abettors, and dishonour of the name they hold.`"

After his recovery from this indisposition,
he visited several towns in the counties of Huntingdon and Cambridge,
At Littleport he remarks that there was but one family of Friends,
though formerly there were many; and adds:

"`It appears that there was great convincement very early in these counties,
and many meetings settled that are now extinct.
Some meeting houses have been sold, and some closed; and others appear likely to be so,
unless the Lord see meet to bring in others by the powerful influences of his love.

"`Ninth month 17th, I set out with my friend John Abbott,
and attended the quarterly meetings of Warwick and Leicester,
and came to Mansfield on the 27th, to attend the quarterly meeting for Nottinghamshire.

"`29th; I have now been at three quarterly meetings,
wholly silent with respect to ministerial labour, except yesterday afternoon;
sitting under deep suffering.
The meeting for discipline was profitable.`"

Soon afterwards he attended the quarterly meeting for Northamptonshire,
held at Wellingborough, at which he says he was silent in the public meeting,
but had some labour in the meeting for business.
After this he visited several meetings in his way towards London,
where he arrived on the 12th of tenth month,
and continued in that city and the neighbourhood for several weeks.
On the 20th he attended the adjourned quarterly meeting, "`in which,`" he says,
"`much time was spent to little profit,
many being apt to speak without sufficient weight;
and a spirit is evident that would lessen the weight of women`'s meetings,
through jealousy.
It was an exercising meeting;
but our dear friend George Dillwyn had a seasonable time at the close,
much to the purpose, so that it ended in a solid frame.

About this time he began to think that he might
soon be released from this field of labour,
and went on board a ship for the purpose of feeling
after the propriety of taking passage in her homewards.
He returned, however, "`not quite easy`" to take such a step at present,
and received a letter from his fellow countryman, James Thornton,
expressive of an opinion that he would scarcely get away before the next yearly meeting,
and encouraging him to persevere in faithfulness, by this reanimating sentiment:
"`None that I know of have more real helps,
in a united sympathy and unity of the living members of the church, than thou hast.`"
John Pemberton remarks on this subject a few weeks afterwards:

"`The sympathy expressed by Friends for me is very grateful,
and I desire I may be favoured so to steer my course as not to forfeit their unity.`"

On the 27th of eleventh month, he remarks, in a letter to his brother James,
in allusion to his dear friends at home:
"`If Friends can be brought to deny themselves of importing spirituous liquors,
or dealing therein, except as medicine, it will be a great thing;
but I expect it must be a work of time and patience.
I felt, more than thirty years ago,
a restraint in my own mind respecting the importation,
which was one motive to my declining a trade to the West India Islands.`"

On the 29th he left London on his way to the west of England,
and arrived at Bristol on the 2nd of twelfth month.
Here he again met his friend James Thornton, and remained about a month.

"`On second-day,`" he says,
"`I attended a meeting of ministers and elders for the monthly meeting of Bristol,
in which some useful labour was exercised.
Having had some engagement on my mind for a day or two
towards the prisoners in the jail at Bristol,
on returning from this meeting I gave a hint of it to James Thornton,
and he was willing to join me.
So taking John Lury, we went into the jail, and had the women felons first,
being seventeen, and generally young,
some to appearance about fourteen and sixteen years of age.
But it was sorrowful to find, that although the gospel spring was experienced,
and they were closely spoken to, it had little effect upon some;
others however were more affected.
We then had the men felons, about twenty, and these also mostly young,
some to appearance not more than fifteen or sixteen years of age, all in irons.
It was a very affecting sight.
Counsel, through the efficacy of Divine love, flowed towards these,
and some were affected and tendered.
The opportunity was satisfactory.`"
After visiting Bath and some other places, he says, "`We went to Marlborough,
and had a meeting, which was open,
though the professors here are very wide from the path of self-denial.

"`Sixth-day, had an open favoured meeting at Newberry,
many of the town`'s people coming in.
There are but two families in this large place who go under our name,
and but one person of these two families was at the meeting.
Formerly there were many Friends here, and two meeting houses;
but they became divided in early time by Story and Wilkinson,
and a spirit opposed to discipline getting up, a blast ensued;
and there is now scarcely one in the place worthy of the name.
First-day, attended two meetings at Reading, and the next day reached London.

"`First month 6th, 1789;
Attended the quarterly meeting for ministers and elders at Aylesbury.
It was small, and no women Friends were there,
none of that sex being under the nomination of elders in this quarter.
Friends were stirred up in regard to it,
and advised to appoint women Friends to this service.
Next day was the quarterly meeting for business, opened by a meeting for worship.
The nature and advantage of humble inward retirement and waiting upon Almighty God,
were pointed out.
The business was as well conducted as could be expected, considering their weak state,
and the replies to the queries were solidly considered.
In the evening we had a public meeting for the inhabitants, which was pretty open,
large and satisfactory.

"`Fifth-day,
feeling my mind drawn towards the prisoners confined in the jail at Aylesbury,
I communicated it to some Friends, and my companion J. Row, and myself,
with three other Friends, went thither, and had an opportunity first with the felons,
about sixteen men, mostly young; then with the debtors, nine in number;
and lastly with those in the house of correction; forty-eight in all, in this jail;
it was very affecting to behold so many brought into difficulty and disgrace,
for want of attention to the Divine fear.
I thought they took the visit kindly,
and some seemed tendered by the counsel delivered and
the concern manifested towards them.`"

John Pemberton spent several weeks in London and the places adjacent,
attending meetings chiefly as they came in course,
and occasionally in company with his dear friend Jarnes Thornton.
On the 3rd of second month he writes thus,
in reference to some places visited in the country:
"`I have been this autumn and winter at some very weak meetings.
The discipline in many places is chiefly attended to by
such as are brought in by convincement and conversion;
many have departed from the profession by being laden with wealth,
gotten through the eager pursuit of it by their parents;
yet there is a hopeful appearance of youth,
and a choice body of Friends when collected at the yearly meeting from the various parts.

"`Second month 28th;
Having been thoughtful respecting the prisoners in the jail at Chelmsford,
I set out this morning, accompanied by Dr. Sims, and had ready admittance.
There were eight cells with one person in each, called penitential cells;
the ceilings high, and conveniences for washing, lodging, etc., in each;
a method I much approve, as it seems most likely to produce reflection.
It is certain there is opportunity for it.
Several men and women were under sentence of transportation.

In one apartment there appeared to be about fifty felons, mostly young men,
and divers under age; with whom I had eleven opportunities.
My mind was much affected,
and it was no agreeable task to be among such a company of depraved spirits.

"`I left London with James Thornton on the 11th ultimo, on a visit to the county of Essex.
We have attended three monthly and most of the particular meetings,
some of which I had not been at since being in Europe this time.
James is favoured with strength to labour fervently; the effect must be left.`"

He continued for a considerable part of the spring of this year in Essex,
Suffolk and Norfolk, attending various meetings without much occurring worthy of remark.
On the 25th of third month he attended the quarterly meeting for Norfolk and Norwich;
"`in which,`" he says, "`James Thornton had close labour;
and though the meeting for discipline was an instructive opportunity,
yet it was a season of close exercise, and held until late in the evening.
I have been silent at, I think, eleven meetings following each other.`"

On the 2nd of fourth month he returned to London,
and next day attended the meeting for sufferings.
Between this and the time of the yearly meeting,
he was occupied in the neighbourhood of London,
and at some meetings in the midland counties, occasionally accompanied by James Thornton.
"`The yearly meeting,`" he remarks, "`was large and solid;
and although there were in some of the sittings too many speakers,
and some particular matters took up much time, yet the cause and testimony gain ground;
a concern is increasing for the support of our Christian discipline;
and those who were opposers through earthly wisdom, are fewer.
Dear George Dillwyn is preserved in faith and patience,
and very lively in his religious labours.
He, like myself, has had to live as from day to day.
Our dear friend, James Thornton,
informed Friends that he felt the same draught to attend his mind,
to return to his family, as he felt to leave them, and a certificate was signed.
Unexpectedly to myself, I found, as I apprehended,
a liberty to inform Friends that I had a hope of being set at liberty during the summer,
to return home.
The meeting was solid, and an endorsement was made on a certificate formerly granted.`"

He concluded to take passage for his native country in
company with his beloved fellow-labourer,
James Thornton;
and on the 23rd of the seventh month they sailed from Gravesend in the ship Apollo,
after a solemn parting opportunity with about fifty Friends,
who came from London and Rochester to take leave of them.

The following remarks occur respecting his homeward journey.

"`Eighth month 2nd,
we were alarmed three several days by the discontent among the seamen;
they apprehending that they were not treated kindly by the captain.
He was young,
and it must be acknowledged that he did not act
with all the prudence which could be wished.
The men seemed determined to stand by each other; but being reasoned with,
on the last day of the three, they softened and returned to their work,
and the captain again permitted them their allowance of meat.

"`21st; A contest occurred this morning between two persons,
and they were going to fight; but I stepped in and prevented it.
The great dissipation,
wantonness and folly that have prevailed among our passengers have been grievous to me.
God does not appear to be in their thoughts, but eating, drinking,
and rising up to play are too prevalent among them.

"`Ninth month 6th, 1789; This is my birthday, being sixty-two years of age,
and having attained to more years than I or my friends had any expectation of,
having been of a weakly frame, and often very ill.
May the Lord`'s mercy and gracious visitation continue to me, a poor unworthy creature.
I acknowledge that it is of his mercy I am not consumed,
my omissions and failings having been many.
But great is the long suffering of a gracious God.
If my time is lengthened out,
may it be spent more attentively and obediently to the Divine counsel,
that after the many trials, temptations and difficulties of life, I may,
through his mercy, and not through any merit of my own,
be received into the Divine favour.
In reviewing my past life, I have many things to be grieved for,
but nothing to boast of or glory in; and if at any time I have been rendered of any use,
it is through the Lord`'s help, and to him be the glory and praise.

"`8th; In the evening a fresh affray occurred between the captain and two of the men.
He seemed very rash, but was prevented from doing any considerable harm,
only bruising the speaking trumpet, which he had made use of to beat the man at the helm.
The light, airy, vain and unprofitable conversation,
and frequent quarrels of many on board, have made it a time of trial to me.

"`9th; the captain supposes we are about seven miles to the south,
and about six hundred and sixty miles to the eastward of Cape Henlopen.
The wind continues favourable, though light.

"`22nd; About three o`'clock P. M, we sounded, and found bottom at about thirty fathoms;
and the next day we saw the False Cape in the morning,
and afterwards sailed between the two capes and came to anchor to wait for the tide.

"`Seventh-day, the 26th,
about two o`'clock J. Gulson and myself went ashore at Wilmington,
and John Dickinson sent his carriage with us to Chester.
The next-day, I reached Philadelphia, and found my dear wife pretty well,
and many rejoiced at my return in safety.
I attended the meeting for ministers and elders, which was large;
and the following week the yearly meeting, which was large and favoured.`"
